---
title:  
    "Fixation rate models for EXPIII"
date: 
    "August 6th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---

```{r loading libraries, echo=FALSE}

# loading libraries


library(ggplot2)
library(plotly)
library(MASS)
library(fitdistrplus)


```


```{r generate fixation rate numbers for a neutral variant driven only by genetic drift}


set.seed(7)

#MODEL PARAMETERS

pop_size <- 2000
btk_size <- 20
r0 <- 10
mut_rate <- (3*10^(-4) + 3*10^(-5))/2
# genome_length <- 9300


pop <- rep ("A", pop_size)



fix_passage <- c()
j <- 1
while (j<= 1000){
    print(paste0("!!!!! ", j, " !!!!!"))
    transfer <- sample(pop, btk_size)
    i <- 1
    while (sum(transfer=="B") != btk_size){


        mut_prob <- mut_rate*length(transfer)

        mut <- sample(c(1, 0), size = 1, prob = c(mut_prob, 1-mut_prob))

        if (mut>0){
            if (transfer[sample(1:length(transfer),mut)] == "A"){
                transfer[sample(1:length(transfer),mut)] <- "B"
            } else if (transfer[sample(1:length(transfer),mut)] == "B"){
                transfer[sample(1:length(transfer),mut)] <- "A"
            }
        }

        round1 <- rep(transfer, each = r0)

        mut_prob <- mut_rate*length(round1)

        mut <- sample(c(1, 0), size = 1, prob = c(mut_prob, 1-mut_prob))

        if (mut>0){
            if (round1[sample(1:length(round1),mut)] == "A"){
                round1[sample(1:length(round1),mut)] <- "B"
            } else if (round1[sample(1:length(round1),mut)] == "B"){
                round1[sample(1:length(round1),mut)] <- "A"
            }
        }



        round2 <- rep(round1, each = r0)

        mut_prob <- mut_rate*length(round2)

        mut <- sample(c(1, 0), size = 1, prob = c(mut_prob, 1-mut_prob))

        if (mut>0){
            if (round2[sample(1:length(round2),mut)] == "A"){
                round2[sample(1:length(round2),mut)] <- "B"
            } else if (round2[sample(1:length(round2),mut)] == "B"){
                round2[sample(1:length(round2),mut)] <- "A"
            }
        }
        round3 <- rep(round2, each = r0)
        transfer <- sample(round3, btk_size)
        i <- i + 1
    }
    fix_passage <- append(fix_passage,i)
    j <- j +1
}


data <- data.frame(value = fix_passage)

write.table(data, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/fixation_rate_neutral.tsv", sep = "\t", quote = F)


```



```{r visualization inspection of simulated data}

data <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/fixation_rate_neutral.tsv", sep = "\t", head = T)

# Summary statistics and distributions 

mean(data$value)

# boxplot
dd <- ggplot(data, aes(y = value)) +
  geom_boxplot()

ggplotly(dd)


# distribution plot
d <- ggplot(data, aes(x = value)) +
  geom_density() +
  #stat_function(fun = dpois, args = list(lambda = lambda), color = "red", linewidth = 1) +
  labs(title = "Density Plot", x = "Value", y = "Density") 
  

ggplotly(d)


```

```{r distribution model inspection}



## model testing based on ChatGPT suggestion
fit_pois <- fitdist(data$value, "pois")

fit_norm <- fitdist(data$value/10, "norm")

fit_exp <- fitdist(data$value/10, "exp")

fit_gamma <- fitdist(data$value/10, "gamma")


# visualize
plot(fit_pois)
plot(fit_norm)
plot(fit_exp)
plot(fit_gamma)


# evaluate goodness of fit measures and statistics
gofstat(fit_pois)
gofstat(fit_norm)
gofstat(fit_exp)
gofstat(fit_gamma)



# KS test to get P.values and for the D parameters reported above

# Perform the Kolmogorov-Smirnov test
ks_test_result <- ks.test(data$value/10, "pexp", rate = 0.008527097)

# Print the test result
print(ks_test_result)

# Perform the Kolmogorov-Smirnov test
ks_test_result <- ks.test(data$value/10, "pgamma", shape = 1.21582003, rate = 0.01036809)

# Print the test result
print(ks_test_result)


```


Fixation time of (almost) neutral mutations, i.e., mutations with fitness effect of close to zero, 
only driven by genetic drift seems to follow a gamma distribution in our experimental design.


```{r}


pgamma(2000/10, shape = 1.126612817, rate = 0.005348949)


```





```{r simulation of time to fixation based on Kimura's calculations (chatGPT suggestion)}


set.seed(123)  # for reproducibility

# Function to simulate time to fixation
simulate_fixation_time <- function(Ne) {
  # Initialize variables
  allele_freq <- 1 / (2 * Ne)  # Initial frequency of the neutral mutation (1 copy in the population)
  generation <- 0
  
  # Run simulation until fixation (allele frequency = 1)
  while (allele_freq < 1) {
    # Simulate genetic drift in a Wright-Fisher model
    num_copies <- rbinom(1, 2 * Ne, allele_freq)  # Randomly choose new number of copies
    allele_freq <- num_copies / (2 * Ne)  # Update allele frequency
    generation <- generation + 1
    if (allele_freq ==0) {
        allele_freq <- 1 / (2 * Ne)
        generation <- 0
    }
  } 
  
  return(generation)
}

# Parameters
Ne <- 1000  # Effective population size (you can change this)
num_simulations <- 1000  # Number of simulations to average over

# Run the simulations
fixation_times <- replicate(num_simulations, simulate_fixation_time(Ne))

# Average time to fixation
average_fixation_time <- mean(fixation_times)
theoretical_fixation_time <- 4 * Ne  # Kimura's prediction

# Display results
cat("Simulated average time to fixation:", average_fixation_time, "generations\n")
cat("Theoretical time to fixation:", theoretical_fixation_time, "generations\n")

# Plot histogram of fixation times
hist(fixation_times, breaks = 30, col = "lightblue", main = "Distribution of Time to Fixation",
     xlab = "Generations to Fixation", border = "black")

library(fitdistrplus)


fit_normal <- fitdist(fixation_times, "norm")

# Fit a gamma distribution
fit_pois <- fitdist(fixation_times, "pois")

# Fit an exponential distribution
fit_gamma <- fitdist(fixation_times/10, "gamma")

# Summary of fits
summary(fit_normal)
summary(fit_pois)
summary(fit_gamma)

library(goftest)
ks.test(fixation_times, "pgamma", 0.9351768, 1)



```

