---
title:  
    "Fixed Mutation Accumulation"
date: 
    "Jul 15th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---



```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("dplyr")
library("zoo") # estimate na's if any 
library("tidyr")
library("stringr")
library("magrittr")


```


```{r set paths and load data}

# set working directory
if (file.exists("/home/amovas/")) {
    # running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load project-specific functions and data readers
source(paste0(wd, "src/analysis/strict-btk/readin_data.R"))
source(paste0(wd, "src/analysis/strict-btk/plot_custom.R"))


```

```{r category thresholds}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```


```{r category thresholds}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}


```



```{r process observed data and merge with simulated data}


# prepare data for visualization
counts <- variants_2exp %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate_at(1, as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)

# 1. Replace 0 with NA (indicating missing samples)
counts <- counts %>%
    mutate(mut_count = ifelse(mut_count == 0, NA, mut_count))

# 2. Interpolate missing values (mut_count) within each exp_line
counts <- counts %>%
    group_by(exp_line) %>%
    arrange(passage, .by_group = TRUE) %>%
    mutate(mut_count = na.approx(mut_count, x = passage, na.rm = FALSE)) %>%
    ungroup()



```



```{r visualization1: fixed accumulation + regression + simulated data}

# visualize

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= paste0(category, " mutation count\n"), color = "Population", title = "")+
        scale_y_continuous(limits = c(0,max(counts$mut_count, na.rm = TRUE)+20),breaks = seq(0,max(counts$mut_count, na.rm = TRUE)+20,20)) +
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0(category, "_accumulation.pdf"), height = 14, width = 14)


```



```{r in-text variables}

# total number of unique fixed mutations per lineage at the end of experiment
variants_2exp %>% 
    filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
    filter(passage == end_psg) %>%
    group_by(exp_line, exp_dataset) %>%
    summarise(count = n()) %>%
    ungroup() %>%
    group_by(exp_dataset) %>%
    summarise(overall = mean(count))



# total number of unique fixed mutations at the end of experiment
variants_2exp %>% 
    filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
    filter(passage == end_psg) %>%
    select(mut_info) %>%
    distinct() %>%
    nrow()

# total number of fixed mutation instances at the end of experiment
variants_2exp %>% 
    filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
    filter(passage == end_psg) %>%
    select(mut_info) %>%
    nrow()




```


```{r visualization2: fixed accumulation per coding and non-coding regions normalized for length}


# prepare data for visualization
counts <- variants_2exp %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            mutate(effect_simplified2 = ifelse(effect_simplified %in% c("S","N"), "Coding", "Non-coding")) %>%
            mutate(effect_simplified2 = factor(effect_simplified2, levels = c("Coding", "Non-coding"))) %>%
            group_by(exp_line, passage, effect_simplified2, .drop = FALSE) %>%
            summarise(count = n()) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate(density = ifelse(effect_simplified2 == "Coding", count*100/(9407-790),count*100/(9626-9076+789-454)))


# 1. Replace 0 with NA (indicating missing samples)
counts <- counts %>%
    mutate(count = ifelse(count == 0, NA, count),
        density = ifelse(density == 0, NA, density))

# 2. Interpolate missing values (mut_count) within each exp_line
counts <- counts %>%
    group_by(exp_line, effect_simplified2) %>%
    arrange(passage, .by_group = TRUE) %>%
    mutate(count = na.approx(count, x = passage, na.rm = FALSE),
        density = na.approx(density, x = passage, na.rm = FALSE)) %>%
    ungroup()



counts %<>% mutate(exp_dataset = ifelse(exp_line %in% c("MT-2_1", "MT-2_2"), "RB", "SB")) %>%
            mutate(exp_dataset = factor(exp_dataset, levels = exp_factor))

# visualize
fig <- counts %>%  ggplot(aes(x=passage, y = density, color = exp_line, linetype = effect_simplified2)) +
        geom_line(linewidth=1) +
        facet_wrap(~exp_dataset) +
        labs(title = paste0("Normalized ",category, " Mutation Accumulation \n (Coding vs Non-Coding)"),
        x="\nTransfer", y=paste0("Normalized ", tolower(category), " variant count (%)\n"), color = "Population", linetype = "Region")+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$density, na.rm = TRUE)+1),breaks = seq(0,max(counts$density, na.rm = TRUE)+1,0.5)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0(tolower(category), "_accumulation_coding_vs_noncoding.pdf"), height = 14, width = 14)

```

```{r visualization3: fixed accumulation per syn and non-syn normalized for sites}

# In dn_ds.Rmd 

```
