---
title:  
    "Diversity measures"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(magrittr)
library(ggplot2)
library(tidyr)
library(stringr)
library(plotly)


```


```{r set paths and load data}

# set working directory
if (file.exists("/home/amovas/")) {
    # running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load project-specific functions and data readers
source(paste0(wd, "src/analysis/strict-btk/readin_data.R"))
source(paste0(wd, "src/analysis/strict-btk/plot_custom.R"))


```



```{r read in diversity data}


lines <- c(13:14, 17:20)

diversity_df <- data.frame()


for (line in lines){
    if (line %in% 13:14){
        exp <- "iii"
    } else {
        exp <- "iv"
    }
    diversity_df <- rbind(diversity_df, read.table(file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/diversity/", exp, "/", line, "_diversity_measures.tsv"), sep = "\t", header = T)) #"_shannon_entropy"
}

# set the correct viral line names and  add host info
diversity_df %<>% mutate(exp_dataset = ifelse(exp_line %in% c("13", "14"), "RB", "SB")) %>% # add a field containing pos, ref, and alt info of muts
                mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==17 ~ "MT-2_i", exp_line==18 ~ "MT-2_ii", exp_line==19 ~ "MT-2_iii", exp_line==20 ~ "MT-2_iv")) %>%
                filter(passage <= end_psg)


```


```{r mean shannon entropy per sample}


shannon_measure <- diversity_df %>% group_by(exp_dataset,exp_line,passage) %>%
    summarise (sum_ent = sum(shannon_entropy, na.rm = T), 
        mean_ent = mean(shannon_entropy, na.rm = T), 
        .groups = 'drop') %>%
    mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))



# visualize 
fig <- ggplot(shannon_measure, aes(x = passage, y = mean_ent, color = exp_line)) +
    geom_line(linewidth=2) + 
    labs(x="Transfer", y= "Mean entropy", color = "Population", title = paste0("Mean of Entropy per Sample")) +
    scale_color_manual(values = line_col_palette) +
    scale_x_continuous(breaks = seq(0,end_psg+10,50)) +
    custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, "shannon_per_sample_mean.pdf", height = 14, width = 14)

```