---
title:  
    "Fixation dynamics of EXPIII"
date: 
    "Dec 19th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("gtools")
library("effsize")


```




```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT-2", "MT-4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 


# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))

# Visualization settings

exp_line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50



```


```{r max-fold-increase processing _ Bertels' replicate}


# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()

# exp_line <- "MT-2_2"
# mut <- "6807_C_A"
# which(fixed_muts == mut)
# i <- 169
# j <- 2

for (exp_line in exp_line_factor){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.5])
    print(length(fixed_muts))

    for (i in 1:length(fixed_muts)){
        print(i)
        appearance_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i]]))) #  & variants_expiii_sub$allele_freq >= 0.01
        fixation_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0.5])))
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == fixed_muts[i]]))
        
        psgs <- seq(appearance_psg, fixation_psg, by = 10)
        recordings <- data.frame()
        
        for (j in 1:(length(psgs)-1)){
            prev_freq <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == psgs[j]]
            current_freq <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == psgs[j+1]]
            if (length(c(prev_freq,current_freq)) == 2){
                recordings <- rbind(recordings, c(psgs[j], psgs[j+1], current_freq/prev_freq))
            }
        }
        
        if (nrow(recordings) != 0){
            df <- rbind(df, c(exp_line, fixed_muts[i], translational_impact, appearance_psg, fixation_psg, fixation_psg-appearance_psg,as.numeric(recordings[which.max(recordings[,3]),])))
        } else {
            df <- rbind(df, c(exp_line, fixed_muts[i], translational_impact, appearance_psg, fixation_psg, fixation_psg-appearance_psg,rep(NA,3)))
        }
    }
}


# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation", "max_psg_lower", "max_psg_upper", "max_fold_change")) %>% 
        mutate_at(4:6, as.integer) %>%
        filter(!is.na(max_fold_change)) %>%
        mutate(max_psg_range = paste(max_psg_lower, max_psg_upper, sep = "_")) %>%
        mutate(max_psg_range = factor(max_psg_range),
        exp_line = factor(exp_line, levels = exp_line_factor),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))



df %<>% mutate(max_fold_change = as.numeric(max_fold_change))
df %<>% mutate(max_psg_range = factor(max_psg_range, levels = mixedsort(c(unique(levels(max_psg_range),"370_380", "380_390", "390_400","420_430", "430_440", "440_450", "450_460", "460_470", "470_480", "480_490", "490_500")))))





saveRDS(df, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/max_fold_inc_bertels.rds")


```

```{r max-fold-increase figure _ Bertels' replicate}


max_fold <- readRDS(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/max_fold_inc_bertels.rds")


max_fold %<>% mutate(host_line = ifelse(exp_line %in% c("MT-2_1", "MT-2_2"), "MT-2", "MT-4")) %>% 
            mutate(host_line = factor(host_line, levels = host_factor))

# axis text label data frame
breaks <- seq(10,80,10)
x_axis_labels <- paste0(breaks, "_", breaks+10)


fig <- max_fold[max_fold$fixation <= 90,] %>% 
    ggplot(aes(x = as.numeric(max_psg_lower), y = log10(max_fold_change), group = host_line, color = host_line, shape = effect_simplified)) +
    # facet_wrap(~exp_line) +
    geom_point(size = 10) +
    geom_smooth(method = "lm", se = FALSE) +  # Add regression line without confidence interval
    scale_color_manual(labels = host_factor, values = c("#ff8000", "#00bbff")) +
    scale_shape_manual(values = c("U", "S", "N")) +
    scale_x_continuous(limits = c(0,90), breaks = breaks, labels = x_axis_labels) +
    labs(title = "Maximum Fold Increase Trend over Time \n (Bertels' replicate)", x = "\n Transfer", y = "Log10(Max. Fold Inc.) \n",
    color = "Virus Line") +
    theme_bw() +
    theme(plot.title = element_text(size = 40, face = "bold", hjust = 0.5),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        axis.text.x = element_text(size = 15, color = "black", angle = 90),
        axis.text.y = element_text(size = 15, color = "black"))




```

```{r lm models}

modell <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$fixation <= 90 & max_fold$host_line == "MT-2",])
summary(modell)

```
