


include: "modules/0_config.smk"
include: "modules/1_sequence_qc.smk"
include: "modules/2_read_trimming.smk"
include: "modules/3_mapping.smk"
include: "modules/4_mapping_qc.smk"
include: "modules/5_mutation_calling.smk"
include: "modules/6_vcf_generation.smk"
include: "modules/7_variant_table_prep.smk"
include: "modules/8_consensus_seq.smk"
include: "modules/9_phylo_tree_inference.smk"
include: "modules/10_diversity_calc.smk"



# define the master rule
rule all:
    input:
       expand(f"{wd}/results/tables/pipeline-outputs/{{experiment}}/{{experiment}}_annotated_variants.tsv.gz", experiment=set(EXP)),
       f"{wd}/results/tables/pipeline-outputs/qc/all_quals.tsv.gz",
       expand(f"{wd}/results/tables/pipeline-outputs/qc/{{experiment}}_{{line}}_multiqc_report.html", zip, experiment=EXP, line=LINES),
       expand(f"{wd_shared}/data/processed-data/mappings/pipeline-outputs/{{experiment}}/{{line}}/{{sample}}_sorted_stats/qualimapReport.html", zip,experiment=EXP, line=LINES, sample=SAMPLES),
       f"{wd}/data/processed-data/consensus/pipeline-outputs/full/tree/all_consensus_full_msa2.fasta.iqtree",
       expand(f"{wd}/results/tables/diversity/{{experiment}}/{{line}}_diversity_measures.tsv", zip, experiment=EXP, line=LINES)
