

```{r parallel boxplots}


plt <- ggplot(data = as.data.frame(shared_df), aes(x=line1, y=line2, fill=val)) + 
  geom_tile() +
  geom_text(aes(line1, line2, label = val), color = "black", size = 15) +
  labs(x = "\nViral Lines", y = "Viral Lines\n", title = paste0("Majority Mutation Parallelism at Passage #", end_passage, "\n")) +
  scale_fill_gradient2(low = "white", high = "red", 
  midpoint = 1, limit = c(0,100), space = "Lab", 
  name="Shared %") +
  theme(plot.title = element_text(size = 50, hjust = 0.5),
          axis.title = element_blank(),
          axis.text.x = element_text(size = 40, angle = 90),
          axis.text.y = element_text(size = 40),
          legend.title = element_text(size=35),
          legend.text = element_text(size = 25))




png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/parallel_evo_boxplot.png")
    , width = 1500, height = 1500)
plt
dev.off()


# SIMULATED 
head(permuted_df_all)
str(permuted_df_all)
permuted_df_all[,2]
permuted_df_all[permuted_df_all]
plt <- ggplot(data = as.data.frame(permuted_df_all), aes(x=line1, y=line2, fill= round(permute_ave,1))) + 
        geom_tile() +
        geom_text(aes(line1, line2, label = round(permute_ave,1)), color = "black", size = 15) +
        labs(title = paste0("Simulated Majority Mutation Parallelism until Passage #", end_passage, "\n(",permutation_nr," Permutation)\n")) +
        scale_fill_gradient2(low = "white", high = "red", 
        midpoint = 1, limit = c(0,100), space = "Lab", 
        name="Shared %") +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
          axis.title = element_blank(),
          axis.text.x = element_text(size = 40, angle = 90),
          axis.text.y = element_text(size = 40),
          legend.title = element_text(size=35),
          legend.text = element_text(size = 25))

ggplotly(plt)

png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/parallel_evo_sim_boxplot2.png")
    , width = 1500, height = 1500)
plt
dev.off()


```




```{r parallel venn diagrams}



# visualization
plt <- ggvenn(muts_list, text_size = 15, set_name_size = 20) +
        labs(title = paste0(category, " Mutations at passage #", end_passage, "\n"))+
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        plot.margin = unit(c(1,1,1,1), "cm"))



png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/parallel_evo_venn_", experiment, ".png")
    , width = 1800, height = 1800)
plt
dev.off()
```






```{r G>A in their context}

threshold <- 0.01
experiment <- "EXPIII"


mapping_vec <- c(A = "T", T = "A", C = "G", G = "C")

variants_sub <- variants %>%
                    filter(allele_freq >= threshold) %>%
                    filter(exp == experiment)


for (i in 1:nrow(variants_sub)){
    if (variants_sub$ref_allele[i] %in% c("G", "A")){
        context <- variants_sub$mut_context[i]
        rev_context <- paste0(as.character(mapping_vec[str_sub(context,3,3)]),
                                        as.character(mapping_vec[str_sub(context,2,2)]), 
                                        as.character(mapping_vec[str_sub(context,1,1)]))
        variants_sub$mut_context_6[i] <- rev_context
    } else {
        variants_sub$mut_context_6[i] <- variants_sub$mut_context[i]
    }
}
head(variants_sub)

variants_sub2 <- variants_sub %>%
                    filter((ref_allele == "G" & alt_allele == "A") | (ref_allele == "C" & alt_allele == "T")) %>% 
                    select(genomic_pos, exp_line, exp, mut_context_6) %>%
                    distinct() %>%
                    group_by(exp_line) %>%
                    count(mut_context_6) %>%
                    dplyr::rename(count = n) %>%
                    mutate(perc = count/sum(count))



variants_sub2 %>% ggplot(aes(x = mut_context_6, y = perc)) +
        geom_bar(stat = "identity") +
        facet_wrap(~exp_line)


variants_sub3 <- variants_sub %>%
                    filter((ref_allele == "G" & alt_allele == "A")) %>% 
                    select(genomic_pos, exp_line, exp, mut_3_context) %>%
                    distinct() %>%
                    group_by(exp_line) %>%
                    count(mut_3_context) %>%
                    dplyr::rename(count = n) %>%
                    mutate(perc = count/sum(count))

variants_sub3 %>% ggplot(aes(x = mut_3_context, y = perc)) +
        geom_bar(stat = "identity") +
        facet_wrap(~exp_line)

```



```{r}

threshold <- 0.99
category <- "Fixated"

`%notin%` <- Negate(`%in%`)

# prepare data for visualization
counts <- variants %>%
              filter(allele_freq >= threshold) %>%
              filter(exp_line %notin% c("MT-4_1", "MT-4_2")) %>%
              group_by(exp_line, passage) %>%
              count() %>%
              dplyr::rename(mut_count = n) %>%
              mutate(host_line = ifelse(exp_line %in% c("MT2_1","MT2_2"), "MT2", "MT4")) %>%
              mutate_at(c(1,4), as.factor) %>%
              mutate_at(2:3, as.numeric)


line_palette <- c("#ff00ff", "#ff2400", "#66ff66", "#009900", "#00cc99", "#558000")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
counts[counts$passage == 430 & counts$exp_line == "MT-2_iii","mut_count"] <- round(mean(as.numeric(counts[counts$passage == 420 & counts$exp_line == "MT-2_iii","mut_count"]),as.numeric(counts[counts$passage == 440 & counts$exp_line == "MT-2_iii","mut_count"])))

head(counts)
fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(size=2) +
        labs(x="\nPassage", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(breaks = seq(0,400,breaks_step)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 30))

png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/",category,"_accumulation.png")
    , width = 1400, height = 1600)
fig
dev.off()




```



```{r}

exp <- "EXPIII"

if (exp == "EXPIII"){
    line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
    breaks_step <- 50
    line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")
} else{
    line_palette <- c("#66ff66", "#009900", "#00cc99", "#558000")
    breaks_step <- 5
    line_labels <- c("MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
}

counts[counts$passage == 430 & counts$exp_line == "MT2_3","mut_count"] <- round(mean(as.numeric(counts[counts$passage == 420 & counts$exp_line == "MT2_3","mut_count"]),as.numeric(counts[counts$passage == 440 & counts$exp_line == "MT2_3","mut_count"])))

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(size=2) +
        labs(x="\nPassage", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation in ", exp, "\n"))+
        scale_x_continuous(breaks = seq(0,510,50)) +
        scale_y_continuous(limits = c(0,250),breaks = seq(0,250,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 30))


png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/majority_accumulation_", exp, ".png")
    , width = 1400, height = 1600)
fig
dev.off()


```




```{r}


gene <- "nef"


syn_pos <- gene_summary$synonymous_count[gene_summary$gene == gene]
nonsyn_pos <- gene_summary$nonsynonymous_count[gene_summary$gene == gene]

experiment <- "EXPIV"
head(variants)

counts <- variants %>%
            mutate(mut_cat = factor(mut_cat, levels = mut_cat_factor)) %>%
            filter(exp == experiment) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            filter(feature == gene) %>%
            filter(allele_freq >= 0.5) %>%
            mutate(mut_cat = "Majority") %>%
            mutate(effect_simplified = factor(effect_simplified, levels = c("N", "S"))) %>%
            group_by(exp_line, passage, mut_cat, effect_simplified, .drop=F) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-4_1","MT-4_2"), "MT4", "MT2")) %>%
            mutate(exp_line = factor(exp_line, levels = exp_line_factor)) %>%
            mutate(effect_simplified = factor(effect_simplified, levels = c("N", "S"))) %>%
            mutate(host_line = factor(host_line, levels = c("MT2", "MT4")))

counts_plt <- 
    counts %>%
    spread(key = effect_simplified, mut_count) %>%
    mutate(S = case_when(S == 0 ~ S+0.01 , S !=0 ~ S)) %>%
    mutate(`dN/dS` = log((N/nonsyn_pos)/(S/syn_pos))) 

counts_plt$`dN/dS`[is.infinite(counts_plt$`dN/dS`) | is.nan(counts_plt$`dN/dS`)] <- 0

counts_plt$mut_cat <- factor(counts_plt$mut_cat, levels = "Majority")
str(counts_plt)
plt_type <- "ggplot"

fig <- counts_plt %>%  
    ggplot(aes(x=passage, y = `dN/dS`, color = exp_line)) +
    geom_line(size=1) +
    labs(x="\nPassage", y= "Log2(dN/dS)\n", color = "Virus Line", title = paste0("dN/dS Over Time\n in ", experiment, " for ", gene, "\n"))+
    scale_color_manual(values = gg_var_list[[experiment]][["line_palette"]]) +
    scale_y_continuous(limits= c(-4,6)) +
    geom_hline(yintercept = 0, color = "black", size = 2) +
    theme_bw() +
    theme(plot.title = element_text(size = gg_size_list[[plt_type]][["title.size"]], hjust = 0.5),
    axis.title = element_text(size = gg_size_list[[plt_type]][["axis.title.size"]]),
    axis.text.x = element_text(size = gg_size_list[[plt_type]][["axis.text.size"]], angle = 90),
    axis.text.y = element_text(size = gg_size_list[[plt_type]][["axis.text.size"]]),
    legend.title = element_text(size=gg_size_list[[plt_type]][["legend.title.size"]]),
    legend.text = element_text(size = gg_size_list[[plt_type]][["legend.text.size"]]))


fig
# save pdfs

png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/dn_ds_", experiment, "_", gene, ".png")
, width = 1000, height = 1500)
print(fig)
dev.off()

```



```{r}

experiment <- "EXPIV"
syn_pos <- as.numeric(sum(gene_summary[,3]))
nonsyn_pos <- as.numeric(sum(gene_summary[,4]))

counts <- variants %>%
    mutate(mut_cat = factor(mut_cat, levels = mut_cat_factor)) %>%
    filter(exp == experiment) %>%
    mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
    mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
    filter(effect_simplified != "U") %>%
    filter(allele_freq >= 0.5) %>%
    mutate(mut_cat = "Majority") %>%
    mutate(effect_simplified = factor(effect_simplified, levels = c("N", "S"))) %>%
    group_by(exp_line, passage, mut_cat, effect_simplified, .drop=F) %>%
    count() %>%
    dplyr::rename(mut_count = n) %>%
    mutate(host_line = ifelse(exp_line %in% c("MT-4_1","MT-4_2"), "MT4", "MT2")) %>%
    mutate(exp_line = factor(exp_line, levels = exp_line_factor)) %>%
    mutate(effect_simplified = factor(effect_simplified, levels = c("N", "S"))) %>%
    mutate(host_line = factor(host_line, levels = c("MT2", "MT4")))

counts_plt <- 
    counts %>%
    spread(key = effect_simplified, mut_count) %>%
    mutate(S = case_when(S == 0 ~ S+0.01 , S !=0 ~ S)) %>%
    mutate(`dN/dS` = log((N/nonsyn_pos)/(S/syn_pos))) 

counts_plt$`dN/dS`[is.infinite(counts_plt$`dN/dS`) | is.nan(counts_plt$`dN/dS`)] <- 0

counts_plt$mut_cat <- factor(counts_plt$mut_cat, levels = "Majority")

fig <- counts_plt %>%  
    ggplot(aes(x=passage, y = `dN/dS`, color = exp_line)) +
    geom_line(size=1) +
    labs(x="\nPassage", y= "Log2(dN/dS)\n", color = "Virus Line", title = paste0("dN/dS Over Time\n in ", experiment, " for the Whole Genome", "\n"))+
    scale_color_manual(values = gg_var_list[[experiment]][["line_palette"]]) +
    scale_y_continuous(limits = c(-2,2)) +
    geom_hline(yintercept = 0, color = "black", size = 2) +
    theme_bw() +
    theme(plot.title = element_text(size = gg_size_list[[plt_type]][["title.size"]], hjust = 0.5),
    axis.title = element_text(size = gg_size_list[[plt_type]][["axis.title.size"]]),
    axis.text.x = element_text(size = gg_size_list[[plt_type]][["axis.text.size"]], angle = 90),
    axis.text.y = element_text(size = gg_size_list[[plt_type]][["axis.text.size"]]),
    legend.title = element_text(size=gg_size_list[[plt_type]][["legend.title.size"]]),
    legend.text = element_text(size = gg_size_list[[plt_type]][["legend.text.size"]]))



png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/301123/dn_ds_", experiment, "_whole_genome", ".png")
, width = 1000, height = 1500)
print(fig)
dev.off()



```