---
title:  
    "Initial Relative Fitness from 10.1038/nature12344"
date: 
    "August 7th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("gtools")
library("effsize")
library(purrr)


```



```{r read-in variant data}

if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}


# load data
source(paste0(wd, "src/analysis/adaptive-deceleration/readin_data.R"))

```

```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/adaptive-deceleration/plot_custom.R"))


```


```{r}

initial_rel_fitness <- function(t1, af1, t2, af2) {
    rel_fit <- (1/(3*(t2-t1)))*(log(af2/(1-af2))-log(af1/(1-af1)))
    return(rel_fit)
}

# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()


for (exp_line in exp_line_factor){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.1])
    print(length(fixed_muts))

    for (i in 1:length(fixed_muts)){
        print(i)
        appearance_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0]))) #  & variants_expiii_sub$allele_freq >= 0.01
        freq_appearance <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == appearance_psg]
        ten_percent_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0.1])))
        freq_ten_percent <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == ten_percent_psg]
        


        init_rel_fit <- initial_rel_fitness(appearance_psg, freq_appearance, ten_percent_psg, freq_ten_percent)

        
        df <- rbind(df, c(exp_line, fixed_muts[i], appearance_psg, freq_appearance, ten_percent_psg, freq_ten_percent, init_rel_fit))
        
    }
}


# set column names and right data types
df2 <- df %>% set_colnames(c("exp_line", "mut_info", "appearance_psg", "freq_appearance", "ten_percent_psg", "freq_ten_percent", "init_rel_fit")) %>% 
        mutate_at(3:7, as.numeric) %>%
        filter(!is.nan(init_rel_fit))




saveRDS(df2, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/init_rel_fitness.rds")





```






```{r initila relative fitness per relative order}


df <- readRDS("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/init_rel_fitness.rds")

# df from ## Method 2 in time_to_fixation.Rmd
merged <- merge(t_2_f, df[,c("exp_line", "mut_info", "init_rel_fit")], by = c("exp_line", "mut_info"), all.y = TRUE)


df1 <- merged[merged$Occurrence %in% c("Triple", "Quadruple"),]


for (i in 1:nrow(df1)) {
    df1$relative_order[i] <- nrow(df1[df1$exp_line == df1$exp_line[i] & df1$fixation < df1$fixation[i],])
}


# saveRDS(df1, file = "/Users/alimos313/Documents/studies/phd/hpc-research/lte-viz/data/initial_relative_fitness_triple_quadruple.rds")

df1$line_label <- df1$exp_line  # or paste shape/linetype if different

head(df1)
fig <- df1 %>%
    ggplot(aes(x = relative_order, y = log2(init_rel_fit), color = exp_line)) +
    geom_point(aes(), size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(title = "", y = "log2 (initial relative fitness)", x = "\nRelative order of fixation", color = "Line", linetype = "Line") +
    scale_color_manual(values = line_col_palette) +
    scale_x_continuous(breaks = seq(0,13, 1))+
    custom_plot_theme(application = "publication") +
    theme(axis.text.x = element_text(angle = 0))

# save figure
custom_plot_save(fig, "triple_quadruple_init_rel_fitness_vs_relative_order.pdf", height = 14, width = 14)





# Fit a linear model for each experimental line
models <- df1 %>%
    group_by(exp_line) %>%
    do(tidy(lm(init_rel_fit ~ relative_order, data = .)))

# View the p-values
models %>%
    filter(term == "relative_order") %>%
    select(exp_line, estimate, std.error, statistic, p.value) %>%
    ungroup() %>% 
    mutate(p.adjusted = p.adjust(p.value, method = "BH"))

```


```{r probability of fixation}


merged %<>% mutate(fixed = ifelse(is.na(fixation), FALSE, TRUE))





model <- glm(fixed ~ init_rel_fit, data = merged, family = binomial)

merged$predicted_prob <- predict(model, type = "response")


ggplot(merged, aes(x = init_rel_fit, y = predicted_prob)) +
    geom_line(color = "blue") +
    labs(title = "Probability of Binary = 1 vs. Continuous Variable",
        x = "Continuous Variable",
        y = "Predicted Probability (Binary = 1)") +
    theme_minimal()

```

```{r probability of fixation per line}

library(pscl)
library(pROC)


# Fit model per exp_line
models_df <- merged[merged$Occurrence %in% c("Triple", "Quadruple", "NA")] %>%
    group_by(exp_line) %>%
    nest() %>%
    mutate(
        model = map(data, ~ glm(fixed ~ init_rel_fit, data = ., family = binomial)),
        preds = map2(data, model, ~ mutate(.x, predicted_prob = predict(.y, newdata = .x, type = "response")))
    ) %>%
    unnest(preds)


fig <- ggplot(models_df, aes(x = init_rel_fit, y = predicted_prob, color = exp_line)) +
    geom_line(linewidth = 2) +
    geom_point(
        aes(y = as.numeric(fixed) + (as.numeric(factor(exp_line)) - 2.5) * 0.01),
        size = 3, alpha = 0.6
    ) +  # shift each lineage slightly in y
    labs(
        title = "",
        x = "\nInitial relative fitness",
        y = "Probability of fixation",
        color = "Line"
    ) +
    custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, "probability_of_fixation.pdf", height = 14, width = 14)


### model assessment


models_df <- merged %>%
    group_by(exp_line) %>%
    nest() %>%
    mutate(
        model = map(data, ~ glm(fixed ~ init_rel_fit, data = ., family = binomial)),
        preds = map2(data, model, ~ mutate(.x, predicted_prob = predict(.y, newdata = .x, type = "response"))),
        # goodness-of-fit
        logLik = map_dbl(model, logLik),
        AIC = map_dbl(model, AIC),
        pseudoR2 = map(model, ~ pscl::pR2(.x)),
        auc = map2_dbl(data, model, ~ {
        roc_obj <- pROC::roc(.x$fixed, predict(.y, newdata = .x, type = "response"))
        pROC::auc(roc_obj)
        })
    )

models_df %>%
    mutate(pseudoR2 = map(pseudoR2, tibble::as_tibble_row)) %>%
    unnest(pseudoR2)


```


```{r}

df2 <- merged[merged$Occurrence %in% c("Single"),]


for (i in 1:nrow(df2)) {
    df2$relative_order[i] <- nrow(df2[df2$exp_line == df2$exp_line[i] & df2$fixation < df2$fixation[i],])
}

fig <- df2 %>%
    ggplot(aes(x = relative_order, y = log2(init_rel_fit), color = exp_line)) +
    geom_point(, size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(title = "", y = "log2(initial relative fitness)\n", x = "Relative order \n (single-occurrence)", color = "Lineage", linetype = "Lineage") +
    scale_color_manual(values = line_col_palette) +
    scale_linetype_manual(values = c(1,2,3,4)) +
    scale_x_continuous(breaks = seq(0,90, 15))+
    custom_plot_theme(application = "publication") 


# save figure
custom_plot_save(fig, "single_max_fold_inc_vs_relative_order.pdf", height = 14, width = 14)

# Fit a linear model for each experimental line
models <- df2 %>%
    group_by(exp_line) %>%
    do(tidy(lm(log2(init_rel_fit) ~ relative_order, data = .)))

# View the p-values
models %>%
    filter(term == "relative_order") %>%
    select(exp_line, estimate, std.error, statistic, p.value)



```

```{r}

mean(df2$init_rel_fit)
mean(df1$init_rel_fit)
mean(merged$init_rel_fit[merged$fixed == FALSE])

wilcox.test(df1$init_rel_fit[df1$exp_line == "MT-2_1"], df2$init_rel_fit[df2$exp_line == "MT-2_1"])
```