---
title:  
    "Parallel evolution _ neutral randomization + Translational impact"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("effsize")
library("coda")


```


```{r read-in variant data}

# determine the server path
if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/adaptive-deceleration/readin_data.R"))

```


```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/adaptive-deceleration/plot_custom.R"))


```



```{r category thresholds}

# set parameters
category <- "Minority"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```


```{r parallelism neutral randomization + heatmap}


effect_list <- list(Syn = "S", Non_Syn = "N", Untranslated = "U", All = c("S", "N", "U"))
regions <- list(Syn = 790:9407, Non_Syn = 790:9407, Untranslated = c(454:789,9076:9625), All = 454:9625)
possible_muts <- c(0.22, 0.78, 1, 1)



overall_df <- data.frame()

for (k in 1:4){
    effect <- effect_list[k]
    effect_factor <- possible_muts[k]
    print(effect)



    # Nr of unique mutations with af >= 0.05
    variants_expiii$passage <- as.integer(as.character(variants_expiii$passage))
    variants_expiii$effect_simplified <- as.character(variants_expiii$effect_simplified)

    
    df <- data.frame()

    for (line1 in exp_line_factor){
        for (line2 in exp_line_factor){
            if (str_detect(line1, "MT-2")){
                offset1 <- 140 # median(df$time_to_fixation[df$exp_line %in% c("MT-2_1","MT-2_2")])
            } else {
                offset1 <- 185 # median(df$time_to_fixation[df$exp_line %in% c("MT-4_1","MT-4_2")])
            }

            if (str_detect(line2, "MT-2")){
                offset2 <- 140
            } else {
                offset2 <- 185
            }

            exp_all <- data.frame()
            for (base in c("A", "C", "G", "T")){
                variants_expiii_sub <- variants_expiii[variants_expiii$ref_allele == base & variants_expiii$genomic_pos %in% regions[[k]] & variants_expiii$mut_type == "P",]
                minority1 <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.05 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage <= end_psg-offset1]))
                minority2 <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.05 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage <= end_psg-offset2]))
                shared_minority <- length(intersect(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.05 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage <= end_psg-offset1],variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.05 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage <= end_psg-offset2]))

                variants_expiii_sub2 <- variants_expiii[variants_expiii$ref_allele == base & variants_expiii$effect_simplified %in% effect[[1]] & variants_expiii$mut_type == "P",]
                fixed1 <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage == end_psg]))
                fixed2 <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage == end_psg]))
                
                
                i <- 0
                
                exp_base <- integer()
                while (i <= 1000){
                    i <- i + 1
                    j <- sample(1:round(minority1*effect_factor), size = fixed1, replace = F)
                    z <- sample(1:round(minority2*effect_factor), size = fixed2, replace = F)
                    exp_base <- c(exp_base,sum(intersect(j,z)<=shared_minority))
                }

                exp_all <- rbind(exp_all, exp_base)
            }

            
            exp_shared <- colSums(exp_all)
            variants_expiii_sub <- variants_expiii[variants_expiii$effect_simplified %in% effect[[1]] & variants_expiii$mut_type == "P",]
            obs_all <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1,line2) & variants_expiii_sub$passage == end_psg]))
            obs_shared <- length(intersect(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage == end_psg],variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage == end_psg]))
            
            # Calculate mean and standard deviation
            mean_data <- mean(exp_shared)
            sd_data <- sd(exp_shared)
            # Calculate the z-score
            z_score <- (obs_shared - mean_data) / sd_data
            # Calculate the p-value
            if (obs_shared > mean_data){
                p_value <- 2 * (1 - pnorm(z_score))
            } else {
                1
            }
            df <- rbind(df,c(line1,line2,obs_all,obs_shared,obs_shared/obs_all,mean_data/obs_all,p_value))
        }
    }

    df %<>% set_colnames(c("Var1", "Var2", "total_unique", "shared", "%shared", "expected_%shared", "p.val"))

    #######################
    
    # uniqueness of fixed variants observed at the end of experiment
    variants_expiii_sub <- variants_expiii[variants_expiii$effect_simplified %in% effect[[1]] & variants_expiii$mut_type == "P",]
    end_fixed <- variants_expiii_sub %>%
                            filter(allele_freq >= min_threshold, allele_freq < max_threshold, passage == end_psg) %>%
                            select(c(exp_line,mut_info)) %>%
                            distinct()




    # create a named vector from the df
    muts <- end_fixed$mut_info
    names(muts) <- end_fixed$exp_line

    # convert named vector to list
    muts_list <- lapply(split(muts, names(muts)), unname)


    shared_percent <- c()


    for (i in 1:4){
            dd <- muts_list[[i]]
            for (j in 1:4){
                if (i<=j){
                    shared_percent <- append(shared_percent,100*(sum(dd %in% muts_list[[j]])/(length(muts_list[[i]])+length(muts_list[[j]])-sum(dd %in% muts_list[[j]]))))
                } else {shared_percent <- append(shared_percent,NA)}
            }
            
    }


    shared_mat <- matrix(shared_percent, ncol = 4)
    row.names(shared_mat) <- exp_line_factor
    colnames(shared_mat) <- exp_line_factor

    shared_df <- as.data.frame(shared_mat) %>% 
                            `colnames<-`(names(muts_list)) %>%
                            mutate(line1 = names(muts_list)) %>%
                            mutate(line1 = factor(line1, levels = exp_line_factor)) %>%
                            gather(key = "line2", value = "val", 1:4) %>%
                            mutate(line2 = factor(line2, levels = exp_line_factor)) %>%
                            mutate(val = round(val, 2))



    melted_cormat <- melt(shared_mat, na.rm = TRUE)

    melted_cormat$value <- round(melted_cormat$value, digits = 1)

    # merge simulation data


    melted_cormat <- merge(melted_cormat, df[,c(1,2,6,7)], by = c("Var1", "Var2"))
    melted_cormat <- melted_cormat %>%
        mutate(p.val = as.numeric(p.val)) %>%
        mutate(p_value_category = case_when(
            p.val >= 0.05 ~ "n.s.",
            p.val >= 0.01 & p.val < 0.05 ~ "*",
            p.val >= 0.001 & p.val < 0.01 ~ "**",
            p.val < 0.001 ~ "***"
        ))

    melted_cormat$`expected_%shared` <- round(as.numeric(melted_cormat$`expected_%shared`)*100, digits = 1)
    melted_cormat$`expected_%shared`[melted_cormat$val == 100] <- 100
    melted_cormat$p_value_category[melted_cormat$val == 100] <- ""

    fig <- ggplot(data = as.data.frame(melted_cormat), aes(x=Var1, y=Var2, fill=value)) + 
            geom_tile(color = "white") +
            geom_text(aes(Var1, Var2, label = paste0(value, "(", `expected_%shared`,")\n", p_value_category)), color = "black", size = 13) +
            labs(title = paste0("Pairwise Overlap Among ", category, " Variants \nat Passage #", end_psg)) +
            scale_fill_gradient2(low = "white", high = "red", 
            midpoint = 1, limit = c(0,100), space = "Lab", 
            name="Shared(%)") +
            custom_plot_theme() +
            theme(axis.title = element_blank())+
            coord_fixed()



    # save figure
    custom_plot_save(fig, paste0("parallel_heatmap_", names(effect),".pdf"), height = 14, width = 14)
    
    #######################

    obs <- melted_cormat$value[melted_cormat$value != 100]
    mean_obs <- mean(obs)
    se_obs <- sd(obs)/sqrt(length(obs))
    exp <- melted_cormat$`expected_%shared`[melted_cormat$value != 100]
    mean_exp <- mean(exp)
    se_exp <- sd(exp)/sqrt(length(exp))

    test_res <- t.test(obs, exp)


    cohen_d <- cohen.d(obs, exp, paired=TRUE)
    ratio <- mean(obs)/ mean(exp)


    p_val <- test_res$p.value

    overall_df <- rbind(overall_df, c(names(effect), "Observed", mean_obs, se_obs, p_val, cohen_d$estimate, ratio))
    overall_df <- rbind(overall_df, c(names(effect), "Simulated", mean_exp, se_exp, p_val, cohen_d$estimate, ratio))

}

```




```{r parallel translational impact barplot summary}

colnames(overall_df) <- c("Translation_impact", "group", "mean", "se", "p.val", "cohen_d", "ratio")


overall_df %<>% mutate_at(1, as.factor)
overall_df$group <- factor(overall_df$group, levels = c("Observed", "Simulated"))
overall_df %<>% mutate_at(3:7, as.numeric)


fig <- ggplot(overall_df, aes(x = Translation_impact, y = mean, fill = group)) +
    geom_col(position = "dodge") +
    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.9),width = 0.2) +
    labs(title = paste0("Summary of Parallelism at Tranfer #", end_psg), y = "Shared(%)\n", x = "\nTranslational impact") +
    scale_fill_manual(name = "Dataset",  # Change the legend title here
        values = c("#038331", "#ffdf50"),
        labels = c("Observed", "Randomized"))+
    custom_plot_theme()

# save figure
custom_plot_save(fig, "parallel_summary_barplot_translational_impact.pdf", height = 14, width = 14)


```

