---
title:  
    "Parallel evolution"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("effsize")
library("coda")


```


```{r read-in variant data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data

source(paste0(wd, "src/analysis/adaptive-deceleration/readin_data.R"))

```

```{r load visualization settings}
# Visual settings

source(paste0(wd, "src/analysis/adaptive-deceleration/plot_custom.R"))


```


```{r category thresholds}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```


```{r visualization1: venn diagram at end passage}


end_fixed <- 
        variants_expiii %>%
        filter(allele_freq >= min_threshold, allele_freq < max_threshold, passage == end_psg) %>%
        select(c(exp_line,mut_info)) %>%
        distinct()



# create a named vector from the df
muts <- end_fixed$mut_info
names(muts) <- end_fixed$exp_line

# convert named vector to list
muts_list <- lapply(split(muts, names(muts)), unname)


# visualization
fig <- ggvenn(muts_list, text_size = 9, fill_color = c("#ff00ff", "#ff2400", "#6600cc", "#0000ff"), set_name_size = 11) +
        # labs(title = paste0(category, " Mutations at Transfer #", end_psg, "\n"))+
        scale_fill_manual(labels = exp_line_factor, values = unname(line_col_palette))


# save figure
custom_plot_save(fig, paste0("parallel_venn_end_passage.pdf"), height = 14, width = 14)

```

```{r in-text numbers}


# percentage of line specific mutations
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 1)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 2)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 3)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 4)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))


```

```{r visualization11: throughout venn diagram}

# # prepare data for visualization
# throughout <- 
#         variants_expiii %>%
#         filter(allele_freq >= min_threshold, allele_freq < max_threshold) %>%
#         select(c(exp_line,mut_info)) %>%
#         distinct()



# # create a named vector from the df
# muts <- throughout$mut_info
# names(muts) <- throughout$exp_line

# # convert named vector to list
# muts_list <- lapply(split(muts, names(muts)), unname)


# # visualization
# fig <- ggvenn(muts_list) +
#         # labs(title = paste0(category, " Mutations Occurrence Venn Diagram"))+
#         scale_fill_manual(labels = exp_line_factor, values = unname(line_col_palette)) +
#         theme(plot.title = element_text(size = 40, hjust = 0.5))


# # save figure
# custom_plot_save(fig, paste0("parallel_venn_throughout.pdf"), height = 14, width = 14)


```

