---
title:  
    "Parallel evolution _ neutral randomization + Translational impact"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("effsize")
library("coda")


```


```{r read-in variant data for exp 2e and sb}

# determine the server path
if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}



# load exp-2e data
variants_ann_expiii <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/iii/iii_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)



# correct for the switched experimental lines
variants_ann_expiii$exp_line[variants_ann_expiii$exp_line == 13 & variants_ann_expiii$passage == 700] <- "A"
variants_ann_expiii$exp_line[variants_ann_expiii$exp_line == 15 & variants_ann_expiii$passage == 700] <- "B"

variants_ann_expiii$exp_line[variants_ann_expiii$exp_line == "A"] <- "15"
variants_ann_expiii$exp_line[variants_ann_expiii$exp_line == "B"] <- "13"

# load exp-btk data
variants_ann_expiv <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/iv/iv_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann_expiv$exp_line[variants_ann_expiv$exp_line == 18 & variants_ann_expiv$passage > 350] <- "A"
variants_ann_expiv$exp_line[variants_ann_expiv$exp_line == 19 & variants_ann_expiv$passage > 350] <- "B"

variants_ann_expiv$exp_line[variants_ann_expiv$exp_line == "A"] <- "19"
variants_ann_expiv$exp_line[variants_ann_expiv$exp_line == "B"] <- "18"

variants_ann_expiv <- variants_ann_expiv[!(variants_ann_expiv$exp_line == 20 & variants_ann_expiv$passage == 680),] # remove the 680th passage for the line 20, as it is low quality data


variants_ann_2exp <- rbind(variants_ann_expiii, variants_ann_expiv)

# determine what data to be included

end_psg <- 500

variants_ann_2exp <- variants_ann_2exp %>% filter(passage <= end_psg) %>%
        mutate(feature = ifelse(feature == "envelope", "env", feature)) # correct the feature name




# facors
exp_factor <- c("2E", "BTK")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2", "MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "env", "nef")
feature_factor <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "env", "tat2", "rev2", "nef", "3UTR", "3R")
feature_start <- c(454,551,635,790,2085,5041,5559,5830,5969,6061,6221,8369,8369,8787,9408,9529)
feature_end <- c(550,634,789,2292,5096,5619,5849,6044,6044,6306,8785,8414,8643,9407,9528,9625)

feature_df <- data.frame(feature = feature_factor,
                            start = feature_start,
                            end = feature_end,
                            length = feature_end - feature_start + 1)

feature_df <- rbind(feature_df, c("tat", sum(feature_df$length[feature_df$feature %in% c("tat1", "tat2")])))
feature_df$length <- as.numeric(feature_df$length)
feature_df <- rbind(feature_df, c("rev", sum(feature_df$length[feature_df$feature %in% c("rev1", "rev2")])))
feature_df$length <- as.numeric(feature_df$length)

feature_df <- feature_df[feature_df$feature %notin% c("tat1", "tat2", "rev1", "rev2"),]
feature_df$feature <- factor(feature_df$feature, levels = c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "env", "nef", "3UTR", "3R"))



# format the dataframe
variants_ann_2exp <- variants_ann_2exp %>%
                            filter(exp_line %in% c(13:16,17:20) & allele_freq >= 0.01) %>%
                            mutate(exp_dataset = ifelse(exp_line %in% c("13", "14", "15", "16"), "2E", "BTK"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2", exp_line==17 ~ "MT-2_i", exp_line==18 ~ "MT-2_ii", exp_line==19 ~ "MT-2_iii", exp_line==20 ~ "MT-2_iv"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(exp_dataset = factor(exp_dataset, levels = exp_factor),
                              passage = as.factor(passage),
                              exp_line = factor(exp_line, levels = exp_line_factor),
                              effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_2exp <- variants_ann_2exp %>% filter(!duplicated(variant_id))


line_col_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff", "#66ff66", "#00cc99", "#009900", "#558000")
names(line_col_palette) <- exp_line_factor

```


```{r in text numbers}

variants_2exp[variants_2exp$passage == 500 & variants_2exp$mut_info == "2058_G_A",]


variants_2exp[variants_2exp$passage == 500 & variants_2exp$exp_line == "MT-2_i" & variants_2exp$allele_freq >= 0.99,]


head(t_2_f)

for (mut in unique(t_2_f$mut_info[t_2_f$Occurrence %in% "Triple"])){
    print(mut)
    print(variants_2exp[variants_2exp$passage == 500 & variants_2exp$exp_dataset == "BTK" & variants_2exp$mut_info == mut,])
}

for (mut in unique(t_2_f$mut_info[t_2_f$Occurrence %in% "Quadruple"])){
    print(mut)
    print(variants_2exp[variants_2exp$passage == 500 & variants_2exp$exp_dataset == "BTK" & variants_2exp$mut_info == mut,])
}

```


```{r fixed accumulation}


# prepare data for visualization
counts <- variants_2exp %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate_at(1, as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)

# 1. Replace 0 with NA (indicating missing samples)
counts <- counts %>%
    mutate(mut_count = ifelse(mut_count == 0, NA, mut_count))

# 2. Interpolate missing values (mut_count) within each exp_line
counts <- counts %>%
    group_by(exp_line) %>%
    arrange(passage, .by_group = TRUE) %>%
    mutate(mut_count = na.approx(mut_count, x = passage, na.rm = FALSE)) %>%
    ungroup()


# visualize

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= paste0(category, " mutation count\n"), color = "Line", title = "")+
        scale_y_continuous(limits = c(0,max(counts$mut_count, na.rm = TRUE)+20),breaks = seq(0,max(counts$mut_count, na.rm = TRUE)+20,20)) +
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0(category, "_accumulation_2e_vs_sb.pdf"), height = 14, width = 14)


```


```{r read in diversity data}


lines <- c(13:20)

diversity_df <- data.frame()


for (line in lines){
    if (line %in% c(13:16)){
        exp <- "iii"
    } else {
        exp <- "iv"
    }
  diversity_df <- rbind(diversity_df, read.table(file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/diversity/", exp, "/", line, "_diversity_measures.tsv"), sep = "\t", header = T)) #"_shannon_entropy"
}

# set the correct viral line names and  add host info
diversity_df %<>% mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2",
                        exp_line==17 ~ "MT-2_i", exp_line==18 ~ "MT-2_ii", exp_line==19 ~ "MT-2_iii", exp_line==20 ~ "MT-2_iv")) %>%
                filter(passage <= end_psg)

```

```{r visualization1: mean shannon entropy per sample}

head(diversity_df)
shannon_measure <- diversity_df %>% group_by(exp_line,passage) %>%
  summarise (sum_ent = sum(shannon_entropy, na.rm = T), 
    mean_ent = mean(shannon_entropy, na.rm = T), 
    .groups = 'drop') %>%
  mutate(exp_line = factor(exp_line, levels = exp_line_factor))



# visualize 
fig <- ggplot(shannon_measure, aes(x = passage, y = mean_ent, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Mean entropy", color = "Line", title = paste0("Mean of Entropy per Sample")) +
  scale_color_manual(values = line_col_palette) +
  scale_x_continuous(breaks = seq(0,end_psg+10,50)) +
  custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, "shannon_per_sample_mean_2e_vs_sb.pdf", height = 14, width = 14)

```


```{r parallelism neutral randomization + heatmap}


effect_list <- list(Syn = "S", Non_Syn = "N", Untranslated = "U", All = c("S", "N", "U"))
regions <- list(Syn = 790:9407, Non_Syn = 790:9407, Untranslated = c(454:789,9076:9625), All = 454:9625)
possible_muts <- c(0.22, 0.78, 1, 1)



overall_df <- data.frame()

for (k in 4){
    effect <- effect_list[k]
    effect_factor <- possible_muts[k]
    print(effect)



    # Nr of unique mutations with af >= 0.05
    variants_2exp$passage <- as.integer(as.character(variants_2exp$passage))
    variants_2exp$effect_simplified <- as.character(variants_2exp$effect_simplified)

    
    df <- data.frame()

    for (line1 in exp_line_factor){
        for (line2 in exp_line_factor){
            if (str_detect(line1, "MT-2")){
                offset1 <- 140 # median(df$time_to_fixation[df$exp_line %in% c("MT-2_1","MT-2_2")])
            } else {
                offset1 <- 185 # median(df$time_to_fixation[df$exp_line %in% c("MT-4_1","MT-4_2")])
            }

            if (str_detect(line2, "MT-2")){
                offset2 <- 140
            } else {
                offset2 <- 185
            }

            exp_all <- data.frame()
            for (base in c("A", "C", "G", "T")){
                variants_2exp_sub <- variants_2exp[variants_2exp$ref_allele == base & variants_2exp$genomic_pos %in% regions[[k]] & variants_2exp$mut_type == "P",]
                minority1 <- length(unique(variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.05 & variants_2exp_sub$exp_line %in% c(line1) & variants_2exp_sub$passage <= end_psg-offset1]))
                minority2 <- length(unique(variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.05 & variants_2exp_sub$exp_line %in% c(line2) & variants_2exp_sub$passage <= end_psg-offset2]))
                shared_minority <- length(intersect(variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.05 & variants_2exp_sub$exp_line %in% c(line1) & variants_2exp_sub$passage <= end_psg-offset1],variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.05 & variants_2exp_sub$exp_line %in% c(line2) & variants_2exp_sub$passage <= end_psg-offset2]))

                variants_2exp_sub2 <- variants_2exp[variants_2exp$ref_allele == base & variants_2exp$effect_simplified %in% effect[[1]] & variants_2exp$mut_type == "P",]
                fixed1 <- length(unique(variants_2exp_sub2$mut_info[variants_2exp_sub2$allele_freq >= 0.99 & variants_2exp_sub2$exp_line %in% c(line1) & variants_2exp_sub2$passage == end_psg]))
                fixed2 <- length(unique(variants_2exp_sub2$mut_info[variants_2exp_sub2$allele_freq >= 0.99 & variants_2exp_sub2$exp_line %in% c(line2) & variants_2exp_sub2$passage == end_psg]))
                
                
                i <- 0
                
                exp_base <- integer()
                while (i <= 1000){
                    i <- i + 1
                    j <- sample(1:round(minority1*effect_factor), size = fixed1, replace = F)
                    z <- sample(1:round(minority2*effect_factor), size = fixed2, replace = F)
                    exp_base <- c(exp_base,sum(intersect(j,z)<=shared_minority))
                }

                exp_all <- rbind(exp_all, exp_base)
            }

            
            exp_shared <- colSums(exp_all)
            variants_2exp_sub <- variants_2exp[variants_2exp$effect_simplified %in% effect[[1]] & variants_2exp$mut_type == "P",]
            obs_all <- length(unique(variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.99 & variants_2exp_sub$exp_line %in% c(line1,line2) & variants_2exp_sub$passage == end_psg]))
            obs_shared <- length(intersect(variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.99 & variants_2exp_sub$exp_line %in% c(line1) & variants_2exp_sub$passage == end_psg],variants_2exp_sub$mut_info[variants_2exp_sub$allele_freq >= 0.99 & variants_2exp_sub$exp_line %in% c(line2) & variants_2exp_sub$passage == end_psg]))
            
            # Calculate mean and standard deviation
            mean_data <- mean(exp_shared)
            sd_data <- sd(exp_shared)
            # Calculate the z-score
            z_score <- (obs_shared - mean_data) / sd_data
            # Calculate the p-value
            if (obs_shared > mean_data){
                p_value <- 2 * (1 - pnorm(z_score))
            } else {
                1
            }
            df <- rbind(df,c(line1,line2,obs_all,obs_shared,obs_shared/obs_all,mean_data/obs_all,p_value))
        }
    }
    print("df is done!")

    df %<>% set_colnames(c("Var1", "Var2", "total_unique", "shared", "%shared", "expected_%shared", "p.val"))

    #######################
    
    # uniqueness of fixed variants observed at the end of experiment
    variants_2exp_sub <- variants_2exp[variants_2exp$effect_simplified %in% effect[[1]] & variants_2exp$mut_type == "P",]
    end_fixed <- variants_2exp_sub %>%
                            filter(allele_freq >= min_threshold, allele_freq < max_threshold, passage == end_psg) %>%
                            select(c(exp_line,mut_info)) %>%
                            distinct()




    # create a named vector from the df
    muts <- end_fixed$mut_info
    names(muts) <- end_fixed$exp_line

    # convert named vector to list
    muts_list <- lapply(split(muts, names(muts)), unname)
    muts_list <- muts_list[exp_line_factor]

    shared_percent <- c()


    for (i in 1:8){
            dd <- muts_list[[i]]
            for (j in 1:8){
                if (i<=j){
                    shared_percent <- append(shared_percent,100*(sum(dd %in% muts_list[[j]])/(length(muts_list[[i]])+length(muts_list[[j]])-sum(dd %in% muts_list[[j]]))))
                } else {shared_percent <- append(shared_percent,NA)}
            }
            
    }


    shared_mat <- matrix(shared_percent, ncol = 8)
    row.names(shared_mat) <- exp_line_factor
    colnames(shared_mat) <- exp_line_factor

    shared_df <- as.data.frame(shared_mat) %>% 
                            `colnames<-`(names(muts_list)) %>%
                            mutate(line1 = names(muts_list)) %>%
                            mutate(line1 = factor(line1, levels = exp_line_factor)) %>%
                            gather(key = "line2", value = "val", 1:4) %>%
                            mutate(line2 = factor(line2, levels = exp_line_factor)) %>%
                            mutate(val = round(val, 2))



    melted_cormat <- melt(shared_mat, na.rm = TRUE)

    melted_cormat$value <- round(melted_cormat$value, digits = 1)

    # merge simulation data


    melted_cormat <- merge(melted_cormat, df[,c(1,2,6,7)], by = c("Var1", "Var2"))
    melted_cormat <- melted_cormat %>%
        mutate(p.val = as.numeric(p.val)) %>%
        mutate(p_value_category = case_when(
            p.val >= 0.05 ~ "n.s.",
            p.val >= 0.01 & p.val < 0.05 ~ "*",
            p.val >= 0.001 & p.val < 0.01 ~ "**",
            p.val < 0.001 ~ "***"
        ))

    melted_cormat$`expected_%shared` <- round(as.numeric(melted_cormat$`expected_%shared`)*100, digits = 1)
    melted_cormat$`expected_%shared`[melted_cormat$val == 100] <- 100
    melted_cormat$p_value_category[melted_cormat$val == 100] <- ""

    fig <- ggplot(data = as.data.frame(melted_cormat), aes(x=Var1, y=Var2, fill=value)) + 
            geom_tile(color = "white") +
            geom_text(aes(Var1, Var2, label = paste0(value, "(", `expected_%shared`,")\n", p_value_category)), color = "black", size = 7) +
            labs(title = paste0("Pairwise Overlap Among ", category, " Variants \nat Passage #", end_psg)) +
            scale_fill_gradient2(low = "white", high = "red", 
            midpoint = 1, limit = c(0,100), space = "Lab", 
            name="Parallel (%)\n") +
            custom_plot_theme() +
            theme(axis.title = element_blank())+
            coord_fixed()



    # save figure
    custom_plot_save(fig, paste0("parallel_heatmap_", names(effect),"_2e_vs_sb.pdf"), height = 14, width = 14)
    
    #######################

    obs <- melted_cormat$value[melted_cormat$value != 100]
    mean_obs <- mean(obs)
    se_obs <- sd(obs)/sqrt(length(obs))
    exp <- melted_cormat$`expected_%shared`[melted_cormat$value != 100]
    mean_exp <- mean(exp)
    se_exp <- sd(exp)/sqrt(length(exp))

    test_res <- t.test(obs, exp)


    cohen_d <- cohen.d(obs, exp)
    ratio <- mean(obs)/ mean(exp)


    p_val <- test_res$p.value

    overall_df <- rbind(overall_df, c(names(effect), "Observed", mean_obs, se_obs, p_val, cohen_d$estimate, ratio))
    overall_df <- rbind(overall_df, c(names(effect), "Simulated", mean_exp, se_exp, p_val, cohen_d$estimate, ratio))

}

```