---
title:  
    "variant freq. dynamics"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```


```{r read-in variant data}

# determine the server path
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/adaptive-deceleration/readin_data.R"))

```


```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/adaptive-deceleration/plot_custom.R"))


```



```{r category thresholds}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```

```{r trajectories of fixed variants}

fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])



variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])
variants_expiii_subset <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,]

for (i in 1:nrow(variants_expiii_subset)){
    matching_index <- which(sapply(fix_count_table_list, function(x) variants_expiii_subset$mut_info[i] %in% names(x)))
    if (length(matching_index) == 0) {
        variants_expiii_subset$rep[i] <- 1
    } else {
        variants_expiii_subset$rep[i] <- names(fix_count_table_list)[matching_index]
    }
    
}



blues_colors <- c("#A4DDED", "#A3C1AD", "#CCCCFF", "#00CCFF", "#15f4ee", 
"#0071c5", "#5A4FCF", "#004687", "#0000CD", "#191970")

triples <- blues_colors
names(triples) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"])[order(unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"]))]

reds_colors <- brewer.pal(5, "Reds")[3:5]
quad <- reds_colors
names(quad) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "4"])



variants_expiii_subset %<>%
    mutate(mut_info2 = case_when(rep == 1 ~ "Single-occurrence",
                                rep == 2 ~ "Double-occurrence",
                                rep == 3 ~ mut_info,
                                rep == 4 ~ mut_info)) %>%
    mutate(mut_info2 = factor(mut_info2, levels = c("Single-occurrence", "Double-occurrence", names(triples), names(quad))))



custom_colors <- c(
    "Single-occurrence" = alpha("grey", 0.3),
    "Double-occurrence" = alpha("green", 0.6)
)
custom_colors <- c(custom_colors, triples, quad)


variants_expiii_subset$linewidth[variants_expiii_subset$rep %in% 3:4] <- 3
variants_expiii_subset$linewidth[is.na(variants_expiii_subset$linewidth)] <- 2
head(variants_expiii_subset)


fig <- variants_expiii_subset %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = mut_info2, linewidth = linewidth)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 2) +
    labs(title = "Variant Frequency Trajectories \n", y = "Frequency", x = "\n Transfer", color = "Fixed mutation") +
    scale_color_manual(values = custom_colors) +
    scale_x_continuous(breaks = seq(0,500, 50))+
    scale_linewidth(range = c(2, 3)) +
    custom_plot_theme(application = "publication", scale = 1.5) +
        guides(linewidth = "none",
        color = guide_legend(override.aes = list(linewidth = 8)))


# save figure
custom_plot_save(fig, paste0("frequency_dynamics_per_repeated_", category, ".pdf"), height = 21, width = 42)

```