---
title:  
    "Divergence per genomic regions"
date: 
    "Jan 21, 2026"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(ggpubr)
library(plotly)
library(hrbrthemes)
library(irr)
library(dplyr)
library(tidyr)
library(Biostrings)
library(stringr)
library(magrittr)
library(rstatix)
library(RColorBrewer)
library(vegan)


```



```{r read-in variant data}

# set working directory
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/reductive-evolution/readin_data.R"))

```

```{r load visualization settings}

# load visual settings
source(paste0(wd, "src/analysis/reductive-evolution/plot_custom.R"))


```



```{r text numbers}

# set parameters
category <- "Fixed" 

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

```



```{r plot normalized mut counts per feature, results=TRUE}


# based on feature range
feature_length <- data.frame(feature = c("5R","5UTR","5LTRLS","gag","pol","vif","vpr","tat","rev","vpu","env","nef","3UTR","3R"),
                            feature_length = c(97,84,155,1503,3012,579,291,261,351,246,2565,621,453,97))



# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(feature %notin% c("5R", "U5", "GLS", "U3", "3R")) %>%
            filter(allele_freq >= min_threshold) %>%
            filter(passage == end_psg) %>%
            group_by(exp_line, feature, effect_simplified) %>%
            summarise(count = n()) %>%
            mutate_at(c(1,2,3), as.factor) %>%
            left_join(feature_df_p[,c(1,4)], by = join_by(feature == feature)) %>%
            mutate(normalized_count = count*100/length) %>%
            mutate(feature = factor(feature, levels = c("gag", "pol", "vif","vpr", "tat","rev","vpu","env","nef")))


# make the visualization
fig <- ggplot(counts) +
    geom_bar(aes(x = effect_simplified, y = normalized_count, fill = exp_line),
        position = "stack",
        stat = "identity") +
    labs(x = "Gene", y = "Fixed mutation density (per nucleotide)", fill = "Population")+
    scale_fill_manual(values = line_col_palette) +
    facet_grid(~ feature, switch = "x") +
    custom_plot_theme(application = "publication") +
    theme(
        axis.text.x = element_text(angle = 0))

fig

### save figure
custom_plot_save(fig, paste0("fixed_mutation_density_per_gene_per_translation.pdf"), height = 14, width = 28)
```
