
---
title:  
    "Divergence rate over genome"
date: 
    "Jan 23, 2026"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(ggpubr)
library(plotly)
library(hrbrthemes)
library(irr)
library(dplyr)
library(tidyr)
library(Biostrings)
library(stringr)
library(magrittr)
library(rstatix)
library(RColorBrewer)
library(vegan)


```



```{r read-in variant data}

# set working directory
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/reductive-evolution/readin_data.R"))

```

```{r load visualization settings}

# load visual settings
source(paste0(wd, "src/analysis/reductive-evolution/plot_custom.R"))


```




```{r compute divergence rate for sliding windows}

# parameters for sliding window analysis
window_size  <- 300
genome_start <- 525
genome_end   <- 9554

# # define sliding windows (step = 1 bp)
# windows <- tibble(
#     window_start = seq(genome_start,
#                         genome_end - window_size + 1,
#                         by = 1)
#     ) %>%
#     mutate(
#         window_end = window_start + window_size,
#         mid_window = (window_start + window_end) / 2
#     )



# # compute divergence rate per exp_line per window
# divergence_rates <- variants_expiii %>%
#     filter(allele_freq >= 0.01) %>%
#     group_by(exp_line, passage) %>%
#     group_modify(~{
#         pos_vec <- .x$genomic_pos
#         af_vec  <- .x$allele_freq
        
#         div <- sapply(windows$window_start, function(ws){
#         we <- ws + window_size
#         sum(af_vec[pos_vec >= ws & pos_vec <= we]) / (window_size+1)
#         })
        
#         windows %>% mutate(divergence_rate = div)
#     }) %>%
#     ungroup()

# # add mean line
# mean_line <- divergence_rates %>%
#     group_by(mid_window, passage) %>%
#     summarise(
#         divergence_rate = mean(divergence_rate, na.rm = TRUE),
#         window_start = dplyr::first(window_start),
#         window_end   = dplyr::first(window_end),
#         .groups = "drop"
#     ) %>%
#     mutate(exp_line = "Average")

# # combine and set factor levels
# divergence_rates <- bind_rows(divergence_rates, mean_line) %>% mutate(exp_line = factor(exp_line, levels = c(exp_line_factor, "Average")))

# # calculate divergence rate per unit time (per year)
# divergence_rates %<>% mutate(divergence_rate_per_year = divergence_rate / ((passage / 2)/52)) 

# # save results
# saveRDS(divergence_rates, file = paste0(wd, "results/tables/divergence_rate_sliding_window_", window_size,".rds"))

# load pre-computed results
divergence_rates <- readRDS(file = paste0(wd, "results/tables/divergence_rate_sliding_window_", window_size,".rds"))

divergence_rates[divergence_rates$window_start == 526,]
# plot divergence rates over genome

fig <- divergence_rates[divergence_rates$passage == end_psg & divergence_rates$window_start >= 551 & divergence_rates$window_end <= 9529,] %>%
    ggplot(aes(x = mid_window, y = log10(divergence_rate_per_year), color = exp_line)) +
    geom_line(aes(alpha = exp_line, linewidth = exp_line)) +
    labs(x = "Genomic position", y = "Divergence rate [1/site/year]", color = "Population")+
    scale_x_continuous(breaks = c(454, min(divergence_rates$mid_window), seq(0, 9000, by = 1000), max(divergence_rates$mid_window), 9625), limits = c(min(divergence_rates$mid_window), max(divergence_rates$mid_window))) +
    scale_y_continuous(
        labels = function(x) parse(text = paste0("10^", x))) +
    scale_color_manual(values = c(line_col_palette, "Average" = "#000000")) +
    scale_linewidth_manual(values = c(rep(1, length(exp_line_factor)), 2)) +
    scale_alpha_manual(values = c(rep(0.5, length(exp_line_factor)), 1)) +
    guides(alpha = "none", linewidth = "none") +
    coord_cartesian(ylim = c(-3, -1.5)) +
    custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, paste0("divergence_rate_over_genome.pdf"), height = 14, width = 28)



```

```{r genome-wide average divergence rate over time}

# calculate genome-wide average divergence rate per passage
divergence_rates %<>%
    filter(window_start >= 551 & window_end <= 9529) %>%
    group_by(exp_line, passage) %>%
    summarise(
        genome_divergence_rate_per_year = sum(divergence_rate_per_year, na.rm = TRUE),
        .groups = "drop"
    ) %>%
    mutate(exp_line = factor(exp_line, levels = c(exp_line_factor, "Average")))

# plot genome-wide average divergence rate over time
fig <- divergence_rates %>% ggplot(aes(x = passage, y = genome_divergence_rate_per_year, color = exp_line)) +
    geom_line(aes(alpha = exp_line, linewidth = exp_line)) +
    labs(x = "Transfer", y = "Divergence rate [1/genome/year]", color = "Population")+
    scale_x_continuous(breaks = seq(0, end_psg, by = 50)) +
    scale_color_manual(values = c(line_col_palette, "Average" = "#000000")) +
    scale_linewidth_manual(values = c(rep(1, length(exp_line_factor)), 2)) +
    scale_alpha_manual(values = c(rep(0.5, length(exp_line_factor)), 1)) +
    guides(alpha = "none", linewidth = "none") +
    custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0("divergence_rate_per_genome_over_time.pdf"), height = 14, width = 14)


```

```{r average div per gene}

divergence_rates %>% filter(passage == end_psg)
min(divergence_rates$mid_window)
ave_divergence_rates <- data.frame()
region <- "U5"
for (region in feature_df$feature[feature_df$feature %notin% c("tat2", "rev2")]) {
    print(region)

    if (region %in% c("tat1", "rev1")){
        divergence_rates_sub <- divergence_rates %>% filter(passage == end_psg & 
                                                    ((mid_window >= feature_df$start[feature_df$feature == region] & 
                                                    mid_window <= feature_df$end[feature_df$feature == region]) |
                                                    (mid_window >= feature_df$start[feature_df$feature == paste0(substr(region, 1, 3),"2")] & 
                                                    mid_window <= feature_df$end[feature_df$feature == paste0(substr(region, 1, 3),"2")])))
        region2 <- substr(region,1,3)
    } else {
        divergence_rates_sub <- divergence_rates %>% filter(passage == end_psg &
                                                    mid_window >= feature_df$start[feature_df$feature == region] &
                                                    mid_window <= feature_df$end[feature_df$feature == region])
        region2 <- region
    }
    
    ave_divergence_rates_sub <- divergence_rates_sub %>% group_by(exp_line) %>% summarise(ave = mean(divergence_rate_per_year, na.rm = T))
    ave_divergence_rates_sub$feature <- region2
    ave_divergence_rates <- rbind(ave_divergence_rates, ave_divergence_rates_sub)
    
}

order_feature <- unique(ave_divergence_rates$feature)[order(ave_divergence_rates$ave[ave_divergence_rates$exp_line == "Average"])]

ave_divergence_rates$feature <- factor(ave_divergence_rates$feature, levels = order_feature)

fig <- ggplot(ave_divergence_rates, aes(x = feature, y = ave, fill = exp_line)) +
    geom_col(position = "dodge") +
    labs(x = "Region", y = "Average divergence rate [1/site/year]", fill = "Population") +
    scale_fill_manual(values = c(line_col_palette, "Average" = "#000000")) +
    custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0("divergence_rate_per_region.pdf"), height = 14, width = 14)

View(ave_divergence_rates)
```