---
title:  
    "computing g score per gene"
date: 
    "Feb 25, 2026"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
library(ggpattern)
library(plotly)
library(hrbrthemes)
library(irr)
library(dplyr)
library(zoo) # estimate na's if any 
library(tidyr)
library(Biostrings)
library(stringr)
library(magrittr)
library(rstatix)
library(RColorBrewer)
library(vegan)
library(reshape2)
library(effsize)
library(boot)
library(gt)
library(webshot2)



```



```{r read-in variant data}

# set working directory
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/reductive-evolution/readin_data.R"))

# further script-specific processing
variants_ann_expiii %<>% filter(feature %notin% c("5R", "3R"))
feature_df %<>% filter(feature %notin% c("5R", "3R"))
```

```{r load visualization settings}

# load visual settings
source(paste0(wd, "src/analysis/reductive-evolution/plot_custom.R"))


```



```{r text numbers}

# set parameters
category <- "Fixed" 

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

```


```{r}


filtered_data <- variants_ann_expiii %>%
    filter(feature %notin% c("3R", "5R"),
            effect_simplified %in% c("U", "N"),
            allele_freq >= min_threshold) %>%
    filter(!(genomic_pos <= 9407 & genomic_pos > 8787 & effect_simplified == "U")) %>%
    select(exp_line, feature, mut_info) %>%
    distinct()



mutation_classification <- filtered_data %>%
    group_by(feature, mut_info) %>%
    summarise(
        n_exp_lines = n_distinct(exp_line),
        .groups = "drop"
    ) %>%
    mutate(
        mutation_type = if_else(n_exp_lines == 1, 
                                "unique", 
                                "shared")
    )

result <- mutation_classification %>%
    mutate(
        unique_count = if_else(n_exp_lines == 1, 1L, 0L),
        shared_count = if_else(n_exp_lines > 1, n_exp_lines, 0L)
    ) %>%
    group_by(feature) %>%
    summarise(
        unique = sum(unique_count),
        shared = sum(shared_count),
        .groups = "drop"
    ) %>% mutate(parallel_prop = shared / (shared + unique) %>% round(3))


result_wide <- result %>% mutate(total = unique + shared) %>%
    mutate(total_prop = total / sum(total) %>% round(3))


result_wide <- merge(result_wide, feature_df_p[,c("feature", "length")], by = "feature") %>% mutate(length_prop = length / sum(length) %>% round(3))

result_wide %<>% mutate(g_score = total_prop / length_prop)

result_wide %<>% arrange(desc(parallel_prop))


# Pipe data to kable
# Convert data frame to gt table
table <- result_wide %>%
    select(c(feature, length, unique, shared, total, parallel_prop)) %>%
    gt() %>%
    tab_header(title = "Overview of fixed mutation counts per region") %>%
    fmt_number(columns = c("parallel_prop"), decimals = 3) %>%
    cols_label(
        feature = "Feature",
        unique = "Unique",
        shared = "Parallel",
        total = "Total",
        parallel_prop = "Parallel Proportion",
        length = "Length"
    )
    
# Save as PDF
gtsave(table, "/Users/alimos313/Documents/studies/phd/research/manuscripts/reductive-evolution/figures/fixed_mut_table.pdf")



```



```{r parallelism neutral randomization + heatmap}




# Bootstrap function for mean
boot_mean <- function(data, indices) {
    mean(data[indices])
}

k <- 14
line1 <- "MT-4_1"
line2 <- "MT-4_1"
base1 <- "A"
base2 <- "G"

overall_df <- data.frame()

for (k in 1:nrow(feature_df)){
    if (feature_df$feature[k] %in% c("tat1", "tat2")){
        if (feature_df$feature[k] == "tat2") {
            next
        }
        feature <- "tat"
        range_of_feature <- c(feature_df$start[feature_df$feature == "tat1"]:feature_df$end[feature_df$feature == "tat1"], 
                            feature_df$start[feature_df$feature == "tat2"]:feature_df$end[feature_df$feature == "tat2"])
    } else if (feature_df$feature[k] %in% c("rev1", "rev2")){
        if (feature_df$feature[k] == "rev2") {
            next
        }
        feature <- "rev"
        range_of_feature <- c(feature_df$start[feature_df$feature == "rev1"]:feature_df$end[feature_df$feature == "rev1"], 
                            feature_df$start[feature_df$feature == "rev2"]:feature_df$end[feature_df$feature == "rev2"])
    } else {
        feature <- as.character(feature_df$feature[k])
        range_of_feature <- feature_df$start[k]:feature_df$end[k]
    }
    print(feature)



    # update data types
    variants_ann_expiii$passage <- as.integer(as.character(variants_ann_expiii$passage))
    variants_ann_expiii$feature <- as.character(variants_ann_expiii$feature)

    # initialize an empty data frame to store results
    df <- data.frame()

    # loop through all pairs of experimental lines
    for (line1 in exp_line_factor){
        for (line2 in exp_line_factor){
            if (str_detect(line1, "MT-2")){
                offset1 <- 140 # median(df$time_to_fixation[df$exp_line %in% c("MT-2_1","MT-2_2")])
            } else {
                offset1 <- 185 # median(df$time_to_fixation[df$exp_line %in% c("MT-4_1","MT-4_2")])
            }

            if (str_detect(line2, "MT-2")){
                offset2 <- 140
            } else {
                offset2 <- 185
            }

            exp_all <- data.frame()
            for (base1 in c("A", "C", "G", "T")){
                for (base2 in setdiff(c("A", "C", "G", "T"), base1)){
                    variants_expiii_sub <- variants_ann_expiii[variants_ann_expiii$ref_allele == base1 & variants_ann_expiii$alt_allele == base2 & variants_ann_expiii$feature %in% feature & variants_ann_expiii$genomic_pos %in% range_of_feature & variants_ann_expiii$mut_type == "P",]
                    minority1 <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.01 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage <= end_psg-offset1]))
                    minority2 <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.01 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage <= end_psg-offset2]))
                    shared_minority <- length(intersect(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.01 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage <= end_psg-offset1],variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.01 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage <= end_psg-offset2]))

                    variants_expiii_sub2 <- variants_ann_expiii[variants_ann_expiii$ref_allele == base1 & variants_ann_expiii$alt_allele == base2 & variants_ann_expiii$feature %in% feature & variants_ann_expiii$genomic_pos %in% range_of_feature & variants_ann_expiii$mut_type == "P",]
                    fixed1 <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage == end_psg]))
                    fixed2 <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage == end_psg]))
                    
                    
                    counter <- 0
                    
                    exp_base <- integer()
                    while (counter <= 1000){
                        counter <- counter + 1
                        j <- sample(1:round(minority1), size = fixed1, replace = F)
                        z <- sample(1:round(minority2), size = fixed2, replace = F)
                        exp_base <- c(exp_base,sum(intersect(j,z)<=shared_minority))
                    }

                    exp_all <- rbind(exp_all, exp_base)
                }
            }
            
            
            exp_shared <- colSums(exp_all)
            variants_expiii_sub <- variants_ann_expiii[variants_ann_expiii$feature %in% feature & variants_ann_expiii$genomic_pos %in% range_of_feature & variants_ann_expiii$mut_type == "P",]
            obs_all <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1,line2) & variants_expiii_sub$passage == end_psg]))
            obs_shared <- length(intersect(
                                    variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage == end_psg],
                                    variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage == end_psg]))
            
            # Calculate mean and standard deviation
            mean_data <- mean(exp_shared)
            sd_data <- sd(exp_shared)
            # Calculate the z-score
            z_score <- (obs_shared - mean_data) / sd_data
            # Calculate the p-value
            if (obs_shared > mean_data){
                p_value <- 2 * (1 - pnorm(z_score))
            } else {
                p_value <- 1
            }

            if (obs_all  != 0){
                df <- rbind(df,c(line1,line2,obs_all,obs_shared,obs_shared/obs_all,mean_data/obs_all,p_value))
            } else {
                df <- rbind(df,c(line1,line2,obs_all,obs_shared,0,0,p_value))
            }
            
        }
    }

    df %<>% set_colnames(c("Var1", "Var2", "total_unique", "shared", "%shared", "expected_%shared", "p.val"))

    #######################
    
    # preparing the data for heatmap
    melted_cormat <- df[,c(1:2, 5:7)]
    melted_cormat$`%shared` <- round(as.numeric(melted_cormat$`%shared`)*100, digits = 1)
    
    # remove redundant comparisons
    melted_cormat <- melted_cormat[-c(2:4,7,8,12),]
    
    melted_cormat <- melted_cormat %>%
        mutate(p.val = as.numeric(p.val)) %>%
        mutate(p.adj = p.adjust(p.val, method = "BH")) %>%
        mutate(p_value_category = case_when(
            p.adj >= 0.05 ~ "n.s.",
            p.adj >= 0.01 & p.adj < 0.05 ~ "*",
            p.adj >= 0.001 & p.adj < 0.01 ~ "**",
            p.adj < 0.001 ~ "***"
        ))

    melted_cormat$`expected_%shared` <- round(as.numeric(melted_cormat$`expected_%shared`)*100, digits = 1)
    melted_cormat$`expected_%shared`[melted_cormat$val == 100] <- 100
    melted_cormat$p_value_category[melted_cormat$val == 100] <- ""

    # generate heatmap
    fig <- ggplot(data = as.data.frame(melted_cormat), aes(x=Var1, y=Var2, fill=`%shared`)) + 
            geom_tile(color = "white") +
            geom_text(aes(Var1, Var2, label = paste0(`%shared`, "(", `expected_%shared`,")\n", p_value_category)), color = "black", size = 13) +
            labs(title = paste0("Pairwise Overlap Among ", category, " Variants \nat Passage #", end_psg)) +
            scale_fill_gradient2(low = "white", high = "red", 
            midpoint = 1, limit = c(0,100), space = "Lab", 
            name="Parallel (%)") +
            custom_plot_theme() +
            theme(axis.title.x = element_blank(),
                    axis.title.y = element_blank())+
            coord_fixed()


    # save figure
    custom_plot_save(fig, paste0("parallel_heatmap_", feature,".pdf"), height = 14, width = 14)
    
    #######################

    obs <- melted_cormat$`%shared`[melted_cormat$`%shared` != 100]
    mean_obs <- mean(obs)
    se_obs <- sd(obs)/sqrt(length(obs))
    exp <- melted_cormat$`expected_%shared`[melted_cormat$`%shared` != 100]
    mean_exp <- mean(exp)
    se_exp <- sd(exp)/sqrt(length(exp))

    # 1000 bootstrap replicates (matches your perms)
    boot_obs <- boot(obs, boot_mean, R = 1000)
    boot_exp <- boot(exp, boot_mean, R = 1000)

    # 95% percentile CI (two-sided, bias-corrected optional)
    ci_obs <- boot.ci(boot_obs, type = "perc")$percent[4:5]
    ci_exp <- boot.ci(boot_exp, type = "perc")$percent[4:5]


    wilcox_res <- t.test(obs, exp, paired = TRUE)


    cohen_d <- cohen.d(obs, exp)
    ratio <- mean(obs)/ mean(exp)


    p_val <- wilcox_res$p.value

    overall_df <- rbind(overall_df, c(feature, "Observed", mean_obs, se_obs, ci_obs[1], ci_obs[2], p_val, cohen_d$estimate, ratio))
    overall_df <- rbind(overall_df, c(feature, "Simulated", mean_exp, se_exp, ci_exp[1], ci_exp[2],p_val, cohen_d$estimate, ratio))

}

colnames(overall_df) <- c("feature", "group", "mean", "se", "ci_lower", "ci_upper", "p.val", "cohen_d", "ratio")



overall_df %<>% mutate_at(1, as.factor)
overall_df$group <- factor(overall_df$group, levels = c("Observed", "Simulated"))
overall_df %<>% mutate_at(3:9, as.numeric)

# Keep one p-value per Translation_impact
unique_tests <- overall_df[!duplicated(overall_df$feature), ]

# Apply BH
unique_tests$adj.p.val <- p.adjust(unique_tests$p.val, method = "BH")

# Merge back if needed
overall_df <- merge(
    overall_df[, !colnames(overall_df) %in% "adj.p.val"],
    unique_tests[, c("feature", "adj.p.val")],
    by = "feature"
)


saveRDS(overall_df, file = paste0(wd, "results/tables/parallel_randomized_per_genomic_region.rds"))

overall_df <- readRDS(file = paste0(wd, "results/tables/parallel_randomized_per_genomic_region.rds"))

overall_df2 <- overall_df

```



```{r parallel translational impact barplot summary}



overall_df_sub <- overall_df %>%
    group_by(feature) %>%
    mutate(
        ratio = mean[group == "Observed"] /
                mean[group == "Simulated"]
    ) %>%
    ungroup() %>%
    arrange(desc(cohen_d)) %>%
    mutate(feature = factor(feature, levels = unique(feature)))


# generate barplot
fig <- ggplot(overall_df_sub, 
            aes(x = feature, y = mean, pattern = group)) +
    geom_col_pattern(
        position = position_dodge(width = 0.9),
        color = "black",
        fill = "white",
        pattern_fill = "black",
        pattern_density = 0.3,
        pattern_spacing = 0.03,
        pattern_key_scale_factor = 0.6,
        width = 0.8
    ) +
    geom_errorbar(aes(ymin = mean-se, ymax = mean+se),
        position = position_dodge(width = 0.9),
        width = 0.3, color = "black", size = 1.5) +
    labs(
        title = paste0("Summary of Parallelism at Transfer #", end_psg),
        y = "Parallel (%)",
        x = "\nTranslational impact"
    ) +
    scale_x_discrete(
        labels = c("All" = "All", "Syn" = "Synonymous", "Non_Syn" = "Nonsynonymous")
    ) +
    scale_y_continuous(breaks = seq(0, 50, by = 5)) +
    scale_pattern_manual(
        name = "Dataset",
        values = c("Observed" = "stripe", "Randomized" = "circle"),
        labels = c("Observed", "Randomized")
    ) +
    scale_pattern_fill_manual(
        values = c("Observed" = "black", "Randomized" = "black"),
        guide = "none"
    ) +
    guides(
        fill = "none",
        pattern = guide_legend(
        override.aes = list(
            pattern_fill = "black",
            fill = "white",
            color = "black"
        )
        )
    ) +
    geom_text(
        data = overall_df_sub %>% filter(group == "Observed"),
        aes(y= mean + se + 2, label = ifelse(p.val < 0.001, "***", ifelse(p.val < 0.01, "**", ifelse(p.val < 0.05, "*", "n.s.")))),
        position = position_dodge(width = 0.9),
        size = 10
    ) +
    custom_plot_theme(application = "publication") +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()
    )

# save figure
custom_plot_save(fig, "parallel_summary_barplot_translational_impact.pdf", height = 14, width = 14)
```





```{r measuring number of expected parallel mutations}

# # pre-filter data
# filtered_data <- variants_ann_expiii %>%
#         filter(effect_simplified %in% c("U", "N"),
#         mut_type == "P") %>%
#         filter(!(genomic_pos <= 9407 & genomic_pos > 8787 & effect_simplified == "U")) %>%
#         distinct()

# df <- data.frame()
# k <- 14
# base1 <- "A"
# base2 <- "G"
# for (k in 1:nrow(feature_df)){
#     if (feature_df$feature[k] %in% c("tat1", "tat2")){
#         if (feature_df$feature[k] == "tat2") {
#             next
#         }
#         feature <- "tat"
#         range_of_feature <- c(feature_df$start[feature_df$feature == "tat1"]:feature_df$end[feature_df$feature == "tat1"], 
#                             feature_df$start[feature_df$feature == "tat2"]:feature_df$end[feature_df$feature == "tat2"])
#     } else if (feature_df$feature[k] %in% c("rev1", "rev2")){
#         if (feature_df$feature[k] == "rev2") {
#             next
#         }
#         feature <- "rev"
#         range_of_feature <- c(feature_df$start[feature_df$feature == "rev1"]:feature_df$end[feature_df$feature == "rev1"], 
#                             feature_df$start[feature_df$feature == "rev2"]:feature_df$end[feature_df$feature == "rev2"])
#     } else {
#         feature <- as.character(feature_df$feature[k])
#         range_of_feature <- feature_df$start[k]:feature_df$end[k]
#     }
#     print(feature)


#     filtered_data_sub <- filtered_data[filtered_data$feature %in% feature & filtered_data$genomic_pos %in% range_of_feature,]

#     exp_all <- data.frame()
#     for (base1 in c("A", "C", "G", "T")){
#         for (base2 in setdiff(c("A", "C", "G", "T"), base1)){
#             filtered_data_sub2 <- filtered_data_sub[filtered_data_sub$ref_allele == base1 & filtered_data_sub$alt_allele == base2,]
#             minority1 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.05 & filtered_data_sub2$exp_line %in% exp_line_factor[1] & filtered_data_sub2$passage <= end_psg])
#             minority2 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.05 & filtered_data_sub2$exp_line %in% exp_line_factor[2] & filtered_data_sub2$passage <= end_psg])
#             minority3 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.05 & filtered_data_sub2$exp_line %in% exp_line_factor[3] & filtered_data_sub2$passage <= end_psg])
#             minority4 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.05 & filtered_data_sub2$exp_line %in% exp_line_factor[4] & filtered_data_sub2$passage <= end_psg])

#             fixed1 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.99 & filtered_data_sub2$exp_line %in% exp_line_factor[1] & filtered_data_sub2$passage <= end_psg])
#             fixed2 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.99 & filtered_data_sub2$exp_line %in% exp_line_factor[2] & filtered_data_sub2$passage <= end_psg])
#             fixed3 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.99 & filtered_data_sub2$exp_line %in% exp_line_factor[3] & filtered_data_sub2$passage <= end_psg])
#             fixed4 <- unique(filtered_data_sub2$mut_info[filtered_data_sub2$allele_freq >= 0.99 & filtered_data_sub2$exp_line %in% exp_line_factor[4] & filtered_data_sub2$passage <= end_psg])
    
            
            
#             counter <- 0
            
#             exp_base <- integer()
#             while (counter <= 1000){
#                 counter <- counter + 1
#                 line1 <- sample(minority1, size = length(fixed1), replace = F)
#                 line2 <- sample(minority2, size = length(fixed2), replace = F)
#                 line3 <- sample(minority3, size = length(fixed3), replace = F)
#                 line4 <- sample(minority4, size = length(fixed4), replace = F)
#                 random_fixed <- c(line1, line2, line3, line4)
#                 random_fixed_shared <- random_fixed[duplicated(random_fixed)]
#                 exp_base <- c(exp_base,length(random_fixed_shared))
#             }
            
#             exp_all <- rbind(exp_all, exp_base)
#         }
#     }
    
    
#     exp_shared <- colSums(exp_all)
    
#     # Calculate mean and standard deviation
    
#     test_res <- t.test(exp_shared, mu = result_wide$shared[result_wide$feature %in% feature], alternative = c("less"))

#     if (obs_all  != 0){
#         df <- rbind(df,c(feature,mean(exp_shared),sd(exp_shared),test_res$p.value))
#     } else {
#         df <- rbind(df,c(feature,mean(exp_shared),sd(exp_shared),test_res$p.value))
#     }

    

    
# }


# df %<>% set_colnames(c("feature", "mean_exp", "sd_exp", "p.val"))


```