---
title:  
    "Evolutionary pressure per gene"
date: 
    "Jan 16, 2026"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(ggpubr)
library(plotly)
library(hrbrthemes)
library(irr)
library(dplyr)
library(zoo) # estimate na's if any 
library(tidyr)
library(Biostrings)
library(stringr)
library(magrittr)
library(rstatix)
library(RColorBrewer)
library(vegan)


```



```{r read-in variant data}

# set working directory
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/reductive-evolution/readin_data.R"))

```

```{r load visualization settings}

# load visual settings
source(paste0(wd, "src/analysis/reductive-evolution/plot_custom.R"))


```



```{r text numbers}

# set parameters
category <- "Minority" 

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

```


```{r corrlation between dn_ds and diversity}

# prepare variant data for visualization
counts <- variants_ann_expiii %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            filter(passage <= end_psg & allele_freq >= min_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            filter(effect_simplified != "U") %>%
            mutate(feature = factor(feature, levels = gene_factor),
            effect_simplified = factor(effect_simplified, levels = c("N", "S"))) %>%
            select(exp_line, feature, effect_simplified, mut_info) %>%
            distinct() %>%
            group_by(exp_line, effect_simplified, feature, .drop = FALSE) %>%
            summarise(count = n()) %>%
            pivot_wider(names_from = effect_simplified, values_from = count)


# read in the gene summary data
gene_summary <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/gene_summary_table.tsv", sep = "\t", header = T)
gene_summary %<>% mutate(gene = ifelse(gene == "envelope", "env", gene))


# prepare dn/ds data for visualization (combine tat and rev genes)
## tat gene
gene_summary <- rbind(gene_summary, c("tat",
                            gene_summary$gene_length[gene_summary$gene == "tat1"]+gene_summary$gene_length[gene_summary$gene == "tat2"],
                            gene_summary$synonymous_count[gene_summary$gene == "tat1"]+gene_summary$synonymous_count[gene_summary$gene == "tat2"],
                            NA,
                            gene_summary$nonsynonymous_count[gene_summary$gene == "tat1"]+gene_summary$nonsynonymous_count[gene_summary$gene == "tat2"],
                            NA,
                            gene_summary$all_count[gene_summary$gene == "tat1"]+gene_summary$all_count[gene_summary$gene == "tat2"]))

gene_summary %<>% mutate_at(2:7, as.numeric)

gene_summary$synonymous_percentage[gene_summary$gene == "tat"] <- gene_summary$synonymous_count[gene_summary$gene == "tat"]/gene_summary$all_count[gene_summary$gene == "tat"]
gene_summary$nonsynonymous_percentage[gene_summary$gene == "tat"] <- gene_summary$nonsynonymous_count[gene_summary$gene == "tat"]/gene_summary$all_count[gene_summary$gene == "tat"]

## rev gene
gene_summary <- rbind(gene_summary, c("rev",
                            gene_summary$gene_length[gene_summary$gene == "rev1"]+gene_summary$gene_length[gene_summary$gene == "rev2"],
                            gene_summary$synonymous_count[gene_summary$gene == "rev1"]+gene_summary$synonymous_count[gene_summary$gene == "rev2"],
                            NA,
                            gene_summary$nonsynonymous_count[gene_summary$gene == "rev1"]+gene_summary$nonsynonymous_count[gene_summary$gene == "rev2"],
                            NA,
                            gene_summary$all_count[gene_summary$gene == "rev1"]+gene_summary$all_count[gene_summary$gene == "rev2"]))

gene_summary %<>% mutate_at(2:7, as.numeric)

gene_summary$synonymous_percentage[gene_summary$gene == "rev"] <- as.numeric(gene_summary$synonymous_count[gene_summary$gene == "rev"])/as.numeric(gene_summary$all_count[gene_summary$gene == "rev"])
gene_summary$nonsynonymous_percentage[gene_summary$gene == "rev"] <- as.numeric(gene_summary$nonsynonymous_count[gene_summary$gene == "rev"])/as.numeric(gene_summary$all_count[gene_summary$gene == "rev"])


gene_summary %<>% filter(gene %notin% c("tat1", "tat2", "rev1", "rev2"))


# merge the two datasets
merged_df <- merge(counts, gene_summary[,c("gene", "gene_length", "nonsynonymous_count", "synonymous_count")], by.x = "feature", by.y = "gene")

merged_df %<>% mutate(S = ifelse(S == 0, 1, S)) %>%
            mutate(dnds = (N/nonsynonymous_count)/(S/synonymous_count),
            mut_count_normalized = (N+S)/(gene_length))

merged_df$bind <- paste0(counts$exp_line, counts$feature)


# get pearson r measure for the correlation
pearson_cor <- cor(merged_df$dnds,merged_df$mut_count, method = "pearson")




# visualization
fig <- merged_df %>% ggplot(aes(x = mut_count_normalized, y = dnds, color = feature, shape = exp_line, group = 1)) +
            geom_point(size = 8) +
            geom_smooth(method = "lm", se = T)+
            scale_shape_manual(values = c(15, 16,17,18)) +
            scale_x_continuous(limits = c(0.2,1), breaks = seq(0,1,0.2)) +
            scale_y_continuous(limits = c(0,1.2), breaks = seq(0,1.2,0.2)) +
            geom_text(label = paste0("Pearson's r: ", round(pearson_cor,2)), x= 0.4, y = 1.15, color = "black", size = 9) +
            labs(x="Fraction polymorphic site", y= "dN/dS",  color = "Gene", shape = "Population",
            title = "")+
            scale_color_manual(values = set1) +
            custom_plot_theme(application = "publication")




# save figure
custom_plot_save(fig, "dnds_diversity_cor_scatter_regression.pdf", height = 14, width = 14)


```

```{r compute icc for each variable separately}

# Make a wide matrix: rows = genes, columns = replicates

df_wide <- merged_df %>%
    select(feature, exp_line, dnds) %>%
    pivot_wider(names_from = exp_line, values_from = dnds)

# Remove gene names column for ICC calculation
dnds_matrix <- as.matrix(df_wide[,-1])

# Compute ICC (one-way random)
icc_result <- icc(dnds_matrix, model="oneway", type="consistency", unit="single")

print(icc_result)

# ========

# Pivot data to wide format: rows = genes, columns = replicates
div_wide <- merged_df %>%
    select(feature, exp_line, mut_count_normalized) %>%
    pivot_wider(names_from = exp_line, values_from = mut_count_normalized)

# Convert to matrix (remove 'feature' column)
div_matrix <- as.matrix(div_wide[,-1])

# Compute ICC (one-way random, single measurement)
icc_div <- icc(div_matrix, model = "oneway", type = "consistency", unit = "single")

print(icc_div)


```


```{r}

# Prepare data
# Response variables: dnds and mut_count_normalized
response_matrix <- merged_df %>%
    select(dnds, mut_count_normalized) %>%
    as.matrix()

# Grouping factor
gene_group <- merged_df$feature

# PERMANOVA
permanova_res <- adonis2(response_matrix ~ gene_group, method = "euclidean", permutations = 999)

print(permanova_res)

```

```{r ellipses for replicates}



fig <- ggplot(merged_df, aes(x = mut_count_normalized, y = dnds, color = feature,shape = exp_line, group = feature)) +
    geom_point(size = 8) +
    stat_ellipse(level = 0.95, linewidth = 1.5) +  # 95% confidence ellipse per gene
    scale_shape_manual(values = c(15, 16,17,18)) +
    scale_x_continuous(limits = c(0.05,1.3), breaks = seq(0.2,1,0.2)) +
    scale_y_continuous(limits = c(0,1.6), breaks = seq(0,1.6,0.2)) +
    labs(x="Fraction polymorphic site", y= "dN/dS",  color = "Gene", shape = "Population",
    title = "")+
    scale_color_manual(values = set1) +
    custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, "dnds_diversity_cor_scatter_ellipses.pdf", height = 14, width = 14)

```


```{r corrlation between dn_ds and diversity over time}


category <- "Minority"

cor_df <- data.frame()


for (psg in seq(10,end_psg,10)){
    cor_vec <- c()
    # prepare variant data for visualization
    counts <- variants_ann_expiii %>%
                mutate(passage = as.numeric(as.character(passage))) %>%
                filter(allele_freq >= min_threshold & passage <= psg) %>%
                mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                filter(effect_simplified != "U") %>%
                mutate(feature = factor(feature, levels = gene_factor),
                effect_simplified = factor(effect_simplified, levels = c("N", "S"))) %>%
                select(exp_line, feature, effect_simplified, mut_info) %>%
                distinct() %>%
                group_by(exp_line, effect_simplified, feature, .drop = FALSE) %>%
                summarise(count = n()) %>%
                pivot_wider(names_from = effect_simplified, values_from = count)

    # read in the gene summary data
    gene_summary <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/gene_summary_table.tsv", sep = "\t", header = T)
    gene_summary %<>% mutate(gene = ifelse(gene == "envelope", "env", gene))


    # prepare dn/ds data for visualization (combine tat and rev genes)
    ## tat gene
    gene_summary <- rbind(gene_summary, c("tat",
                                gene_summary$gene_length[gene_summary$gene == "tat1"]+gene_summary$gene_length[gene_summary$gene == "tat2"],
                                gene_summary$synonymous_count[gene_summary$gene == "tat1"]+gene_summary$synonymous_count[gene_summary$gene == "tat2"],
                                NA,
                                gene_summary$nonsynonymous_count[gene_summary$gene == "tat1"]+gene_summary$nonsynonymous_count[gene_summary$gene == "tat2"],
                                NA,
                                gene_summary$all_count[gene_summary$gene == "tat1"]+gene_summary$all_count[gene_summary$gene == "tat2"]))

    gene_summary %<>% mutate_at(2:7, as.numeric)

    gene_summary$synonymous_percentage[gene_summary$gene == "tat"] <- gene_summary$synonymous_count[gene_summary$gene == "tat"]/gene_summary$all_count[gene_summary$gene == "tat"]
    gene_summary$nonsynonymous_percentage[gene_summary$gene == "tat"] <- gene_summary$nonsynonymous_count[gene_summary$gene == "tat"]/gene_summary$all_count[gene_summary$gene == "tat"]

    ## rev gene
    gene_summary <- rbind(gene_summary, c("rev",
                                gene_summary$gene_length[gene_summary$gene == "rev1"]+gene_summary$gene_length[gene_summary$gene == "rev2"],
                                gene_summary$synonymous_count[gene_summary$gene == "rev1"]+gene_summary$synonymous_count[gene_summary$gene == "rev2"],
                                NA,
                                gene_summary$nonsynonymous_count[gene_summary$gene == "rev1"]+gene_summary$nonsynonymous_count[gene_summary$gene == "rev2"],
                                NA,
                                gene_summary$all_count[gene_summary$gene == "rev1"]+gene_summary$all_count[gene_summary$gene == "rev2"]))

    gene_summary %<>% mutate_at(2:7, as.numeric)

    gene_summary$synonymous_percentage[gene_summary$gene == "rev"] <- as.numeric(gene_summary$synonymous_count[gene_summary$gene == "rev"])/as.numeric(gene_summary$all_count[gene_summary$gene == "rev"])
    gene_summary$nonsynonymous_percentage[gene_summary$gene == "rev"] <- as.numeric(gene_summary$nonsynonymous_count[gene_summary$gene == "rev"])/as.numeric(gene_summary$all_count[gene_summary$gene == "rev"])


    gene_summary %<>% filter(gene %notin% c("tat1", "tat2", "rev1", "rev2"))


    # merge the two datasets
    merged_df <- merge(counts, gene_summary[,c("gene", "gene_length", "nonsynonymous_count", "synonymous_count")], by.x = "feature", by.y = "gene")


    merged_df %<>% filter(N != 0 & S != 0)
    if (nrow(merged_df) < 3){
        cor_df <- rbind(cor_df, c(psg, rep(NA, 5)))
        next
    }

    merged_df %<>% mutate(dnds = (N/nonsynonymous_count)/(S/synonymous_count),
                mut_count_normalized = (N+S)/(gene_length*3))

    merged_df$bind <- paste0(merged_df$exp_line, merged_df$feature)


    # get pearson r measure for the correlation
    pearson_cor <- cor(merged_df$dnds,merged_df$mut_count, method = "pearson")
    cor_vec <- c(cor_vec, pearson_cor)
    for (exp_line in exp_line_factor){
        pearson_cor <- cor(merged_df$dnds[merged_df$exp_line == exp_line],merged_df$mut_count[merged_df$exp_line == exp_line], method = "pearson")
        cor_vec <- c(cor_vec, pearson_cor)
    }
    cor_df <- rbind(cor_df, c(psg, cor_vec))
}

colnames(cor_df) <- c("passage", "All", exp_line_factor)

cor_df_long <- cor_df %>% tidyr::pivot_longer(cols = -passage, names_to = "exp_line", values_to = "pearson_r") %>%
            mutate(exp_line = factor(exp_line, levels = c("All", exp_line_factor)))


saveRDS(cor_df_long, paste0(wd, "results/tables/dnds_diversity_cor_over_time_", category,".rds"))


cor_df_long <- readRDS(paste0(wd, "results/tables/dnds_diversity_cor_over_time_", category,".rds"))


fig <- cor_df_long[!is.na(cor_df_long$pearson_r),] %>% ggplot(aes(x=passage, y=pearson_r, color=exp_line, linewidth = exp_line == "All", alpha = exp_line == "All")) +
    geom_line() +
    geom_point(size=5) +
    labs(x="Transfer", y= "Pearson's r", color = "Population",
    title = "") +
    scale_x_continuous(breaks = c(seq(0, end_psg, 50), end_psg)) +
    scale_y_continuous(limits = c(min(0, round(min(cor_df_long$pearson_r, na.rm = TRUE), digits = 0.1)),round(max(cor_df_long$pearson_r, na.rm = TRUE))),
        breaks = seq(min(0, round(min(cor_df_long$pearson_r, na.rm = TRUE), digits = 0.1)), round(max(cor_df_long$pearson_r, na.rm = TRUE)), 0.1)) +
    scale_color_manual(values = c("All"= "black", line_col_palette)) +
    scale_linewidth_manual(values = c(`TRUE` = 2, `FALSE` = 0.8), guide = "none") +
    scale_alpha_manual(values = c(`TRUE` = 1, `FALSE` = 0.5), guide = "none") +
    custom_plot_theme(application = "publication")



# save figure
custom_plot_save(fig, paste0("dnds_diversity_cor_over_time_", category,".pdf"), height = 14, width = 14)

```