---
title:  
    "Fixed Mutation Accumulation"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(magrittr)
library(tidyr)
library(stringr)
library(ggplot2)
library(purrr)
library(ggrepel)



```




```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}


# load data
source(paste0(wd, "src/analysis/reductive-evolution/readin_data.R"))

```

```{r load visualization settings}

# load visual settings
source(paste0(wd, "src/analysis/reductive-evolution/plot_custom.R"))


```



```{r category thresholds}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}


```



```{r process observed data and merge with simulated data}


# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)

counts <- counts[,-4]
counts$group <- "Observed"

# simulated data (own simulation)
bottleneck_freq <- 3
sim_data <- readRDS(paste0(wd, "results/tables/neutral-seq-sim/", bottleneck_freq, "_sim_count_all.rds"))

# Convert to data frame
sim_data_long_df <- purrr::imap_dfr(sim_data, ~ {
    tibble(
        exp_line = .y,
        passage = seq_along(.x) * 10,     # multiply by 10 as per your example
        mut_count = .x,
        group = "Simulated"
    )
})

counts_all <- rbind(counts, sim_data_long_df)
counts_all$group <- factor(counts_all$group, levels = c("Observed", "Simulated"))

```



```{r fixed mutation linear regression}

# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)


# linear regression

counts2 <- counts %>% select(passage,mut_count,host_line) %>% group_by(passage,host_line) %>% summarize(ave_count = mean(mut_count))



#### 
lm_mt2 <- lm(ave_count ~ passage, data = counts2[counts2$host_line == "MT2",])

df_lm_mt2 <- data.frame(passage = as.numeric(seq(10,end_psg,10)))
df_lm_mt2$predicted <- predict(lm_mt2, newdata = df_lm_mt2)
df_lm_mt2$group <- "Observed"

#### 
lm_mt4 <- lm(ave_count ~ passage, data = counts2[counts2$host_line == "MT4",])

df_lm_mt4 <- data.frame(passage = as.numeric(seq(10,end_psg,10)))
df_lm_mt4$predicted <- predict(lm_mt4, newdata = df_lm_mt4)
df_lm_mt4$group <- "Observed"


```

```{r visualization1: fixed accumulation + regression + simulated data}

# visualize
fig <- counts_all[counts_all$group == "Observed",] %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        geom_line(data = df_lm_mt4, aes(x = passage, y = predicted), color = "#00c8ff", size = 2)+
        geom_line(data = df_lm_mt2, aes(x = passage, y = predicted), color = "#ff8b08", size = 2)+
        labs(x="Transfer", y= paste0(category, " mutation count"), color = "Population", title = "")+
        scale_x_continuous(breaks = c(seq(0,end_psg,50), 630)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+2),breaks = seq(0,max(counts$mut_count)+20,20)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication") +
        guides(
            color = guide_legend(order = 1),     # Line legend first
            linetype = guide_legend(order = 2)   # Dataset legend second
        )

# save figure
custom_plot_save(fig, paste0(category, "_accumulation_regression_whole.pdf"), height = 14, width = 14)


```



```{r in-text variables}

# get numbers for in-text reporting
variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & allele_freq < max_threshold) #& mut_type == "P"



# in-text numbers
overall_fixed <- length(unique(paste0(variants_expiii_subset$exp_line,variants_expiii_subset$mut_info)))
unique_fixed <- length(unique(variants_expiii_subset$mut_info))


```


```{r visualization2: fixed accumulation per coding and non-coding regions normalized for length}


# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            mutate(effect_simplified2 = ifelse(effect_simplified %in% c("S","N"), "Coding", "Non-coding")) %>%
            group_by(exp_line, passage, effect_simplified2) %>%
            summarise(count = n()) %>%
            mutate_at(4, as.numeric) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(density = ifelse(effect_simplified2 == "Coding", count*100/(9407-790),count*100/(9626-9076+789-454)))

counts$effect_simplified2 <- factor(
    counts$effect_simplified2,
    levels = c("Non-coding", "Coding")  # desired order
)


# visualize
fig <- counts %>%  ggplot(aes(x=passage, y = density, color = exp_line, linetype = effect_simplified2)) +
        geom_line(linewidth=1) +
        labs(title = paste0("Normalized ",category, " Mutation Accumulation \n (Coding vs Non-Coding)"),
        x="Transfer", y=paste0("Sites with fixed mutation (%)"), color = "Population", linetype = "Region")+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$density)+1),breaks = seq(0,max(counts$density)+1,1)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0(tolower(category), "_mut_accumulation_coding_vs_noncoding.pdf"), height = 14, width = 14)

```

```{r visualization3: fixed accumulation per syn and non-syn normalized for sites}

# In dn_ds.Rmd 

```

```{r visualization4: gif of mutated sites over time per min_threshold}


# df <- data.frame()
# variants_expiii_subset <- variants_expiii %>% mutate(passage = as.numeric(as.character(passage)))

# for (exp_line in exp_line_factor){
#     for (min_threshold in seq(0.01,0.99, by=0.01)){
#         for (passage in seq(10,end_psg, 10)){
#             print(passage)
#             count <- length(unique(variants_expiii_subset$genomic_pos[variants_expiii_subset$allele_freq >= min_threshold & variants_expiii_subset$passage == passage & variants_expiii_subset$exp_line == exp_line & variants_expiii_subset$mut_type == "P"]))
#             df <- rbind(df, c(exp_line, min_threshold, passage, count))
#         }
#     }
# }

# df %<>% set_colnames(c("exp_line", "min_threshold", "passage", "count")) %>%
#             mutate_at(2:4, as.numeric)

# saveRDS(df, file = paste0(wd, "results/tables/misc/mutated_sites_over_time_per_min-threshold.rds"))

df <- readRDS(file = paste0(wd, "results/tables/misc/mutated_sites_over_time_per_min-threshold.rds"))

gg_fig <- ggplot(df, aes(x=passage, y = count)) + 
    geom_line(aes(color=exp_line), linewidth=1) +
    scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
    transition_states(min_threshold, transition_length = 100, state_length = 1, wrap = TRUE) + # to create animation 
    view_follow(fixed_y = FALSE) +
    labs(title = "min_threshold = {closest_state}", x = "Passage", y = "Count") +
    theme_bw() +
    theme(
    plot.title = element_text(size = 25, hjust = 0.5),
    axis.title = element_text(size = 20),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    strip.text.x = element_text(size = 25),
    legend.title = element_text(size=15),
    legend.text = element_text(size = 10),
    plot.margin = unit(c(1,1,1,1), "cm"))



# save for lteeviz
fig_dir <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/gif/"
anim_save(gg_fig, file = paste0(fig_dir, "mutated_sites_over_time_per_min-threshold.gif"))


```
```