---
title:  
    "variant freq. trajectories of certain cases of EXPIII"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```


```{r read-in variant data}

# determine the server path
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/reductive-evolution/readin_data.R"))

```


```{r load visualization settings}

# source visual settings
source(paste0(wd, "src/analysis/reductive-evolution/plot_custom.R"))


```



```{r arbitrary cases}

cases <- c("5611_G_A", "5671_G_A", "5672_G_A", "5725_GA_G", "5784_TGTCGACATAGCA_T")
case <- cases[2]


fig <- variants_expiii[variants_expiii$mut_info %in% case,] %>% ggplot(aes(x = passage, y = log10(allele_freq), group = mut_info)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_alpha_manual(values = c(0.1,1)) +
    scale_y_continuous(breaks = c(0, -1, -2, -3), labels = c("1", "0.1", "0.01", "0.001")) +
    labs(title = paste0(case, "\n"), y = "Frequency \n", x = "\n Transfer") +
    # scale_color_manual(values = my_col_pal) +
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")

fig

```



```{r high-impact cases}

variants_expiii_subset <- variants_ann_expiii %>%
                                filter(nchar(ref_allele) < 20 & nchar(alt_allele) < 20) %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))


gene_of_interest <- c("nef")



cases_10 <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$feature %in% gene_of_interest & 
    variants_expiii_subset$impact == "HIGH" & 
    variants_expiii_subset$allele_freq >= 0.1])

cases_50 <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$feature %in% gene_of_interest & 
    variants_expiii_subset$impact == "HIGH" & 
    variants_expiii_subset$allele_freq >= 0.5])


variants_expiii_subset <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% cases_10,]

variants_expiii_subset <- variants_expiii_subset %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info))


color_code_cases_50 <- unique(sapply(str_split(cases_50, "_"), "[[", 3))



set.seed(4)

color = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
if (gene_of_interest == "vpr"){
    sample_color_vpr <- sample(color, length(color_code_cases_50))
    # Assign colors
    variants_expiii_subset <- variants_expiii_subset %>%
        mutate(
            legend_label = ifelse(mut_info %in% color_code_cases_50, mut_info, "Other")
    )
    legend_colors <- c(
        setNames(sample_color_vpr, color_code_cases_50),
        Other = "gray70"
    )
} else {
    sample_color_vpr <- sample(color, 5)
    color <- setdiff(color, sample_color_vpr)
    sample_color_nef <- sample(color, length(color_code_cases_50))
    # Assign colors
    variants_expiii_subset <- variants_expiii_subset %>%
        mutate(
            legend_label = ifelse(mut_info %in% color_code_cases_50, mut_info, "Other")
    )
    legend_colors <- c(
        setNames(sample_color_nef, color_code_cases_50),
        Other = "gray70"
    )
}


ordered_major_cases <- variants_expiii_subset %>%
    filter(mut_info %in% color_code_cases_50) %>%
    distinct(mut_info, genomic_pos) %>%
    arrange(genomic_pos) %>%
    pull(mut_info)

legend_levels <- c(ordered_major_cases, "Other")


variants_expiii_subset <- variants_expiii_subset %>%
    mutate(
        legend_label = factor(legend_label, levels = legend_levels)
    )


fig <- variants_expiii_subset %>%
    ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = legend_label)) +
    geom_line(size = 2) +
    facet_grid(rows = vars(exp_line), switch = "y") +
    labs(title = "", y = "Frequency", x = "Transfer") +
    scale_color_manual(values = legend_colors, name = paste0("LOF Mutations (", gene_of_interest, ")")) +
    scale_x_continuous(breaks = c(seq(0, end_psg, by = 50), end_psg)) +
    custom_plot_theme(application = "publication") + 
    theme(strip.text.y = element_text(size = 35, angle=0),
        legend.position = "right")



# save figure
custom_plot_save(fig,  paste0("frequency_", gene_of_interest, "_stop_gained.pdf"), height = 14, width = 21)
```



