

# Introduction



This R Markdown document is to be used as scrap for quick calculations, functionality testing, etc..

By this line I want to check if the spell-checking functionality of VS Code is working or not. Apparently not!

But then I opened up the configuration of the extension and by checking the box to include Rmd files it is working just fine now.


```{r}
exp <- "EXPIV"

if (exp == "EXPIII"){
    line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
    breaks_step <- 50
    line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")
} else{
    line_palette <- c("#66ff66", "#009900", "#00cc99", "#558000")
    breaks_step <- 5
    line_labels <- c("MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
}

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(size=2) +
        labs(x="\nPassage", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation in ", exp, "\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(breaks = seq(0,400,breaks_step)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 30))


png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/131123/minority_accumulation_", exp, ".png")
    , width = 1400, height = 1600)
fig
dev.off()


```


```{r}

counts %<>% mutate_at(1, as.factor)


if (exp == "EXPIII"){
    levels(counts$exp_line) <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")
} else{
    levels(counts$exp_line) <- c("MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
}





fig <- as.data.frame(counts) %>% ggplot(aes(x=passage, y = pct, fill = mut_subtype)) +
                                geom_bar(position="stack", stat="identity") + 
                                facet_wrap(~exp_line) +
                                labs(x="\nPassage", y= "Percentage\n", fill = "Base Substitution")+
                                theme_bw() +
                                theme(strip.text.x = element_text(size = 35),
                                axis.title = element_text(size = 45),
                                axis.text.x = element_blank(),
                                axis.text.y = element_text(size = 40),
                                legend.title = element_text(size=35),
                                legend.text = element_text(size = 30))




png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/131123/spectrum_",exp,".png")
    , width = 1600, height = 1200)
fig
dev.off()



```

```{r}

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(size=2) +
        labs(x="\nPassage", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation in ", exp, "\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(breaks = seq(0,250,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 30))


png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/131123/majority_accumulation_", exp, ".png")
    , width = 1400, height = 1600)
fig
dev.off()


```

```{r}
head(counts)

fig <- counts %>%  ggplot(aes(x=passage, y = nr_majority_density, color = exp_line, linetype=effect_simplified2)) +
        geom_line(size=2) +
        labs(x="\nPassage", y= "Normalized Count\n", color = "Virus Line", linetype = "Translation Effect", title = paste0(category, " Mutation Accumulation Based on Translational Effect \n in ", exp, "\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        #scale_y_continuous(breaks = seq(0,250,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 30))


png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/131123/density_", exp,".png")
    , width = 1600, height = 1600)
fig
dev.off()


```


```{r}



# make the visualization
fig <- ggplot(counts) +
    geom_bar(aes(x = mut_type, y = normalized_count, fill = exp_line),
        position = "stack",
        stat = "identity") +
    labs(x = "\nGenomic Features", y = "Normalized Count\n", fill = "Virus Line")+
    scale_fill_manual(labels = line_labels, values = line_palette) +
    facet_grid(~ feature, switch = "x") +
    theme_bw()+
    theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, color = "white"),
        panel.spacing = unit(0.2,"cm"))+
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 40),
        strip.text.x = element_text(size = 35, angle=90),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 30))


png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/131123/feature_count_", exp, ".png")
    , width = 1600, height = 1400)
fig
dev.off()
```


```{r}


# prepare data for visualization
mut_profile_maj_unique <- variants_expiii_sub %>% filter(allele_freq >= threshold) %>%
                            select(mut_info, mut_type_sub, host_line) %>%
                            distinct() %>%
                            group_by(mut_type_sub, host_line) %>%
                            summarise(count = n())


mut_profile_maj_unique_mt2 <- mut_profile_maj_unique[mut_profile_maj_unique$host_line == "MT2",]
mut_profile_maj_unique_mt4 <- mut_profile_maj_unique[mut_profile_maj_unique$host_line == "MT4",]

fig <- plot_ly()
fig <- fig %>% add_pie(data = mut_profile_maj_unique_mt2, labels = ~mut_type_sub, values = ~count, title = paste0("All Mutations", " (", sum(mut_profile_maj_unique_mt2$count),")"),
                       name = "Cut", domain = list(x = c(0, 0.4), y = c(0.4, 1)))
fig <- fig %>% add_pie(data = mut_profile_maj_unique_mt4, labels = ~mut_type_sub, values = ~count, title = paste0("Unique Mutations", " (", sum(mut_profile_maj_unique_mt4$count),")"),
                       name = "Color", domain = list(x = c(0.6, 1), y = c(0.4, 1))) %>%
                       layout(title=paste0('Mutation Sub-Types _ ', subset_name))
fig

png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/131123/mut_subtype_", exp, ".png")
    , width = 1600, height = 1400)
fig
dev.off()

```



```{r}

# uniqueness of majority mutations present at the end passage
end_maj <- variants_expiii %>%
                        filter(passage == end_passage) %>%
                        select(c(exp_line,mut_info)) %>%
                        distinct()



#table(as.numeric(table(par$mut_info)))


# create a named vector from the df
muts <- end_maj$mut_info
names(muts) <- end_maj$exp_line

# convert named vector to list
muts_list <- lapply(split(muts, names(muts)), unname)
names(muts_list) <- line_labels

# visualization
ggvenn(muts_list) +
        labs(title = paste0(category, " Mutations at passage #", end_passage))+
        theme(plot.title = element_text(size = 20, hjust = 0.5),
        plot.margin = unit(c(1,1,1,1), "cm"))

```


```{r}



# uniqueness of majority mutations present at the end passage
end_maj <- variants_expiv %>%
                        filter(passage == end_passage) %>%
                        select(c(exp_line,mut_info)) %>%
                        distinct()



#table(as.numeric(table(par$mut_info)))


# create a named vector from the df
muts <- end_maj$mut_info
names(muts) <- end_maj$exp_line

# convert named vector to list
muts_list <- lapply(split(muts, names(muts)), unname)
names(muts_list) <- line_labels

# visualization
ggvenn(muts_list) +
        labs(title = paste0(category, " Mutations at passage #", end_passage))+
        theme(plot.title = element_text(size = 20, hjust = 0.5),
        plot.margin = unit(c(1,1,1,1), "cm"))



```

```{r}



variants_ann_all <- variants_ann %>%
                            mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2",
                            exp_line==17 ~ "MT-2_i", exp_line==18 ~ "MT-2_ii", exp_line==19 ~ "MT-2_iii", exp_line==20 ~ "MT-2_iv"))


head(shared_df)

shared_df$line1 <- factor(shared_df$line1, levels = c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2","MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv"))
shared_df$line2 <- factor(shared_df$line2, levels = c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2","MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv"))


shared_df <- shared_df[c(1:2, 7:8,3:6),]
```
