---
title:  
    "Mutable position"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```


```{r read-in variant data}


if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data

source(paste0(wd, "src/analysis/1st-man/readin_data.R"))

```

```{r load visualization settings}
# Visual settings

source(paste0(wd, "src/analysis/1st-man/plot_custom.R"))


```


# Accumulation

```{r text numbers}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```



```{r}

# plot number of unique positions that have been mutated (minority) 


variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & mut_type == "P")


# prepare dataset

variants_expiii_subset$passage <- as.integer(as.character(variants_expiii_subset$passage))


counts <- data.frame()
for (psg in seq(10,end_psg,10)){
    d <- variants_expiii_subset[variants_expiii_subset$passage <= psg,]
    dd <- d %>% dplyr::select(genomic_pos, exp_line) %>% distinct() %>% group_by(exp_line) %>% summarise(count = n())
    dd$passage <- psg
    counts <- rbind(counts, dd)
}


# counts <- counts[counts$exp_line != "All",]

fig <- counts %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutable position pool\n", color = "Lineage", title = paste0("Cumulative Number of Uniquely Mutated Positions (", category,")"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$count)+20),breaks = seq(0,max(counts$count)+20,100)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, paste0(category, "_cumulative_mutated_pos.pdf"), height = 14, width = 14)



```



```{r random sampling from pool of possible mutations modelling per host}

counts_sub <- counts[str_detect(counts$exp_line, pattern = "MT-2"),]

counts_sub %<>% group_by(passage) %>%
        summarize(average = mean(count))


# Fit a negative exponential model
model_exp <- nls(average ~ L * (1 - exp(-K * passage)),
                data = counts_sub,
                start = list(L = 5000, K = 0.01),
                control = nls.control(maxiter = 1000))

summary(model_exp)

df <- data.frame(passage = seq(10,2000,10))

df_prediction <- data.frame(passage = seq(10,2000,10))
df_prediction$predicted_mt_2 <- predict(model_exp, newdata = df)
df_prediction$predicted_mt_4 <- predict(model_exp, newdata = df)
df_prediction$predicted_all <- predict(model_exp, newdata = df)

counts_addon <- data.frame(exp_line = rep(levels(counts$exp_line), each = 150), count = NA, passage = rep(seq(510,2000,10), 4))
counts <- rbind(counts, counts_addon)



fig <- counts[!str_detect(counts$exp_line, pattern = "All"),] %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
        geom_line(linewidth=2) +
        geom_line(data = df_prediction, aes(y = predicted_mt_2), color = "grey", size = 2, linetype = "dashed") +
        geom_line(data = df_prediction, aes(y = predicted_mt_4), color = "grey", size = 2, linetype = "dashed") +
        # geom_line(data = df_prediction, aes(y = predicted_all), color = "grey", size = 2, linetype = "dashed") +
        labs(x="\nTransfer", y= "Position Count\n", color = "Virus Line", title = paste0("Modelling of Uniquely Mutated Positions (", category,")"))+
        scale_x_continuous(breaks = seq(0,2000,100)) +
        scale_y_continuous(limits = c(0,max(df_prediction$predicted_mt_2+100, na.rm=T)+20),breaks = seq(0,max(df_prediction$predicted_mt_2+100, na.rm=T)+20,100)) +
        scale_color_manual(labels = c(exp_line), values = c(line_col_palette)) +
        custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0(category, "_cumulative_mutated_pos_models.pdf"), height = 14, width = 14)

```