

```{r load libraries}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")



```



```{r read in data}


# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
variants_ann_expiii <- variants_ann[variants_ann$exp_line %in% 13:16,]


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# last passage 

end_passage <- 560


# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")



```




```{r section one}



# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}



## Figure 1



# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)



# visualize 

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line\n", title = paste0(category, " Mutation Accumulation"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20),breaks = seq(0,max(counts$mut_count)+20,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90, color = "black"),
        axis.text.y = element_text(size = 20, color = "black"),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


ggplotly(fig)

png(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/mim-retreat-poster/fixed_accumulation.png", height = 1000, width = 1000)
fig
dev.off()


## fig2


variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info)) %>%
                                mutate(passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])

tot_fixed_4lines <- length(fixed_muts)

gray_shades <- gray(seq(0, 0.75, length.out = 503))
gray_shades <- sample(gray_shades)

fig <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,] %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = mut_info_line)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_colour_manual(values = gray_shades) +
    scale_x_continuous(breaks = seq(0,570,50)) +
    labs(title = "Variant Frequency Trajectories", y = "Frequency \n", x = "\n Passage") +
    theme_bw() +
    theme(plot.title = element_text(size = 30, hjust = 0.5),
    axis.title = element_text(size = 25),
    axis.text.x = element_text(size = 20, angle = 90, color = "black"),
    axis.text.y = element_text(size = 20, color = "black"),
    strip.text.x = element_text(size = 25),
    legend.position="none")

fig

png(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/mim-retreat-poster/fixed_freq_dynamics.png", height = 1000, width = 1000)
fig
dev.off()



## fig3


# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()

for (exp_line in line_labels){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.05])))
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}

# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        mut_info = paste(exp_line, mut_info, sep = "_"),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))



# perform pairwise t-test between translation impact groups per exp line
pwc <- df %>%
    group_by(exp_line) %>%
    pairwise_t_test(time_to_fixation ~ effect_simplified, p.adjust.method = "BH",pool.sd=T, detailed = T)




# Visualization: box plots with p-values

low<-findInterval(max(df$time_to_fixation),c(5,10,20,50,100))
step <- c(5,10,20,50,100)[low]

#Add x position
pwc <- pwc %>% add_xy_position(x = "effect_simplified", step.increase = 1)
# assign new y.positions 
pwc$y.position <- sample(seq(580,700,10), replace = F, size = 12)
# make the plot
fig <- ggboxplot(df, x = "effect_simplified", y = "time_to_fixation", color = "exp_line") +
    facet_wrap(~exp_line, ncol = 2) +
    labs(x="\nTranslational Impact", y= "Transfer Time\n", title = "Time to Fixation per Translational Impact")+
    scale_color_manual(values = line_palette) +
    scale_y_continuous(breaks = seq(0,max(df$time_to_fixation)+step,step)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE) +
    theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, color = "black"),
        axis.text.y = element_text(size = 20, color = "black"),
        strip.text = element_text(size = 25),
        legend.position = "none")

png(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/mim-retreat-poster/time_to_fixation_per_translational_impact.png", height = 1000, width = 1000)
fig
dev.off()








```


```{r section two}
line_col_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
names(line_col_palette) <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

d <- shannon_df %>% group_by(host_line,exp_line,passage) %>% summarise (sum_ent = sum(shannon_entropy, na.rm = T), mean_ent = mean(shannon_entropy, na.rm = T), .groups = 'drop')

d %<>% mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))

# sum of entropy per sample 

fig <- ggplot(d, aes(x = passage, y = mean_ent, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Mean\n", color = "Virus Line\n", title = paste0("Mean of Entropy per Sample")) +
  scale_color_manual(values = line_col_palette) +
  scale_x_continuous(breaks = seq(0,570,50)) +
  theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90, color = "black"),
        axis.text.y = element_text(size = 20, color = "black"),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


png(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/mim-retreat-poster/diversity_entropy.png", height = 1000, width = 1000)
fig
dev.off()

```


```{r section three}

# set variables

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")

feature_factor <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "env", "tat2", "rev2", "nef_only", "nef_3UTR", "3UTR", "3R")
feature_start <- c(454,551,635,790,2085,5041,5559,5830,5969,6061,6221,8369,8369,8787,9076,9408,9529)
feature_end <- c(550,634,789,2292,5096,5619,5849,6044,6044,6306,8785,8414,8643,9075,9407,9528,9625)

feature_df <- data.frame(feature = feature_factor,
                            start = feature_start,
                            end = feature_end,
                            length = feature_end - feature_start + 1)

feature_df <- rbind(feature_df, c("tat", sum(feature_df$length[feature_df$feature %in% c("tat1", "tat2")])))
feature_df$length <- as.numeric(feature_df$length)
feature_df <- rbind(feature_df, c("rev", sum(feature_df$length[feature_df$feature %in% c("rev1", "rev2")])))
feature_df$length <- as.numeric(feature_df$length)

feature_df <- feature_df[feature_df$feature %notin% c("tat1", "tat2", "rev1", "rev2"),]

feature_factor_new <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "env", "nef_only", "nef_3UTR", "3UTR", "3R")


## fig1

end_passage <- 560

variants_ann_expiii$feature[variants_ann_expiii$feature == "envelope"] <- "env"
variants_ann_expiii$feature[variants_ann_expiii$genomic_pos >= 9076 & variants_ann_expiii$genomic_pos <= 9407] <- "nef_3UTR"
variants_ann_expiii$feature[variants_ann_expiii$genomic_pos >= 8787 & variants_ann_expiii$genomic_pos <= 9075] <- "nef_only"
# prepare data for visualization

counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            filter(passage == end_passage) %>%
            group_by(exp_line, feature, effect_simplified) %>%
            summarise(count = n()) %>%
            mutate_at(c(1,2,3), as.factor) %>%
            left_join(feature_df[,c("feature", "length")], by = join_by(feature == feature)) %>%
            mutate(feature = factor(feature, levels = feature_factor_new)) %>%
            mutate(normalized_count = count*100/length)


# make the visualization
fig <- ggplot(counts) +
    geom_bar(aes(x = effect_simplified, y = normalized_count, fill = exp_line),
            position = "stack",
            stat = "identity") +
    scale_fill_manual(labels = line_labels, values = line_palette) +
    labs(x = "Genomic Features", y = "Normalized Count", fill = "Virus Line\n", title = paste0(category, " Mutation Distribution at #", end_passage))+
    facet_grid(~ feature, switch = "x") +
    theme_bw()+
    theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, color = "white"),
        panel.spacing = unit(0.2,"cm"))+
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, face="bold"),
        axis.text.y = element_text(size = 20),
        strip.text.x = element_text(size = 25, angle=90),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))

fig

png(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/mim-retreat-poster/mutation_distribution_per_category.png", height = 1000, width = 1000)
fig
dev.off()

```