---
title:  
    "Phylogenetics analysis for EXPIII"
date: 
    "Jan 23rd, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---

```{css, echo=F}

#TOC {
  position: fixed;
  left: 0;
  top: 0;
  width: 250px;
  height: 100%;
  overflow:auto;
}

body, td {
  font-family: sans-serif;
  background-color: white;
  font-size: 16px;
}


h1, .h1, h2, .h2, h3, .h3 {
    margin-top: 30px;
}


p.caption {
  font-size: 0.9em;
  font-style: italic;
  color: grey;
  margin-right: 10%;
  margin-left: 10%;  
  text-align: justify;
}


/* scrollable code chunks, limit code chunk window height */

pre {
  max-height: 600px;
  overflow-y: auto;
}

pre[class] {
  max-height: 300px;
}


/* scrollable output of code chunks */
/* add class.output="scroll-100" to code chunks */

.scroll-100 {
  max-height: 300px;
  overflow-y: auto;
  background-color: inherit;
}
```



```{r setting global code chunk parameters, include=FALSE}

# options for code chunk and output inclusion 
knitr::opts_chunk$set(
  message = FALSE, echo = TRUE, warning=FALSE, results = "hide"
)

# options for figures
knitr::opts_chunk$set(
  fig.width = 8, fig.height = 8, fig.align = "center"
)


# options(scipen=999)

# margin of plotly
m <- list(
  l = 150,
  r = 150,
  b = 100,
  t = 100,
  pad = 4
)


```




# Introduction




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("ape")


```




```{r read-in the data}

# read in the data
variants_ann <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/2-p/all_annotated_variants.tsv.gz", 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)

str(variants_ann)

# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data

variants_ann_expiii <- variants_ann[variants_ann$exp_line %in% 13:16,]


# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                              mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                                exp_line = case_when(exp_line==13 ~ "MT2_1", exp_line==14 ~ "MT2_2", exp_line==15 ~ "MT4_1", exp_line==16 ~ "MT4_2"), # update exp line labels
                                mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) # add a field containing pos, ref, and alt info of muts

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# last passage 

end_passage <- 560

```



# Overview {.tabset .tabset-pills}


```{r}

phymltest(seqfile = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/src/r-processing-scripts/phylogenetics/test1/test1.txt", execname = "/Users/alimos313/miniconda3/envs/ha_proj/bin/phyml")

```



```{r}

# APE relevant methods and functions for performing phylogenetic analyses

## loading package example datasets

### DNAbin object
data(woodmouse)
class(woodmouse)
str(woodmouse)
as.character(woodmouse[1:3,10:20])

### phylo object
data(bird.orders) 
class(bird.orders)
print(bird.orders)
plot(bird.orders)

## plotting phylo object

### useful parameters (page 206 for full list of parameters)

#### label.offset: distance between tip label and external nodes
#### type: format of the phylogenetic tree, for example type = "c", FALSE, would be a triangle format


## function: add.scale.bar
## adds scale bar to the phylogeny tree

add.scale.bar()

## function: axisPhylo
## adds time axis to the phylogeny tree

axisPhylo()


## assign color to different lineages
col_def <- def(phylo_obj_rooted$tip.label, "b" = "red", regexp = TRUE)
plot(phylo_obj_rooted, tip.col = col_def)

## ladderize
##This function reorganizes the internal structure of the tree to get the ladderized effect when plotted.

## reorder.phylo function (232 page)




## function: ace
## function: tiplabels
## function: nodelabels
## estimates internal nodes character state

### example for discrete data: 
### also an example of how to assign colors (groups) to tips using tiplabels function

x <- factor(c(rep(0, 5), rep(1, 18)))
ans <- ace(x, bird.orders, type = "d", CI = T)



plot(bird.orders, type = "c", FALSE, label.offset = 1)
co <- c("blue", "yellow")
tiplabels(pch = 22, bg = co[as.numeric(x)], cex = 2, adj = 1)
nodelabels(thermo = ans$lik.anc, piecol = co, cex = 0.75)


## tree estimation methods
### function nj
### function bionj (mvr)
### function fastme.ole # this method relies on minimum evolution methods which are also distance-based
### function hclust(dist_mat, method = "average")
fun <- function(x) as.phylo(hclust(dist.dna(x), "average")) # same as upgma
tree <- fun(woodmouse)

## CADM.global function
## use if you want to compare between the distance matrices that will be derived from using different regions of the genome
## a similar function would be mantel.test


##checkAlignment function
## produces plot for: 1. MSA 2. shannon index per position

## compute.brlen 
## can be used to tweak the branch length of the phylo

## dnds function
## try it for different genes after msa=

## function makeLabel to manage labels?
## function updateLabel

## skyline to get an estimate on effective population size?

## function cophenetic to compute the pairwise distance of all pairs of tips using the branch length

pdf("/Users/alimos313/Desktop/phylo_tree.pdf", height = 21)
plot(as)
dev.off()




```



```{r test run for p17}

## set path to fasta file containing consensus seq
cons_path <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/processed-data/consensus/pipeline-outputs/all_consensus_p17.fasta"
## read in the data
otherthing <- read.dna(file = cons_path, format = "fasta")
### to get lengths of sequences
lens <- lengths(as.character(otherthing))
table(lens)
## perform multiple sequence alignment
## you can change the penalties for gaps, check out the function vignette
msa <- muscle5(otherthing, mc.cores = 8)
msa <- read.dna(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/processed-data/consensus/pipeline-outputs/all_consensus_p17_msa.fasta", format = "fasta")
### first save the MSA to a file on disk
ape::write.dna(msa, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/processed-data/consensus/pipeline-outputs/all_consensus_p17_msa.fasta")
### run phyml.test which will save results on disk and return it in Ras well
X <- phymltest("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/processed-data/consensus/pipeline-outputs/all_consensus_p17_msa.fasta", execname = "phyml")

class(msa)
head(msa)
msa2 <- as.matrix(msa)
cd as.character(msa[1:3,1:10])
```

```{r}

otherthing <- woodmouse
otherthing <- as.list(woodmouse)

# workflow

## set path to fasta file containing consensus seq
cons_path <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/processed-data/consensus/pipeline-outputs/some.fasta"
## read in the data
otherthing <- read.dna(file = cons_path, format = "fasta")
### to get lengths of sequences
lens <- lengths(as.character(otherthing))
## perform multiple sequence alignment
## you can change the penalties for gaps, check out the function vignette
msa <- muscle5(otherthing) # muscle5 clustalomega function
### view MSA
as.character(msa)
j <- c(1,5,10)
msa_subset <- msa[,j]
alview(msa_subset, showpos = j)
### generate pixelized representation of MSA
image.DNAbin(msa) 
### another way to generate an image of the alignment and shannon index per position
checkAlignment(msa)

## find most-fitted DNA evolutionary model for the data
### first save the MSA to a file on disk
ape::write.dna(msa, file = "/Users/alimos313/Desktop/dummy.txt")
### run phyml.test which will save results on disk and return it in Ras well
X <- phymltest("/Users/alimos313/Desktop/dummy.txt", execname = "phyml")
### inspect result
### the lower the AIC and the higher the log likelihood value the better the model fits the data
X
summary(X)
plot(X)
dev.off()


## obtain pairwise distance matrix
dist_mat <- dist.dna(msa, model = "TN93") # you can choose different other models, the best to be determined by running phyml.test function with lowest log likelihood and highest AIC
## obtain phylogeny
phylo_obj <- bionj(dist_mat) # nj, bionj, fastme.ols, hclust(method = "average") = UPGMA
## inspect phylogeny
plot(ladderize(phylo_obj)) # laddersize function re-orders the branchs and clades with respect to pairwise genetic distances (highest distance to the right if the plot were to be plotted upward)
add.scale.bar()
print(phylo_obj_roo)
## calculate pairwise genetic distance
cophenetic(phylo_obj)
cophenetic(phylo_obj)["seq_a", "seq_e"]

## generate delta plot
## https://doi.org/10.1093/oxfordjournals.molbev.a004030
## the assessment of treelikeness of phylogenetic distance data before tree estimation
delta.plot(dist_mat)
## root the tree using an outgroup
phylo_obj_rooted <- root(phylo_obj, outgroup = "seq_a", resolve.root = T) # No306
is.rooted(phylo_obj_rooted)
## check
phylo_obj_rooted$edge.length
is.ultrametric(phylo_obj_rooted) # TRUE if UPGMA used
checkValidPhylo(phylo_obj)

## bootstrapping (confidence in tree)
fun <- function(xx) bionj(dist.dna(xx, model = "TN93"))
set.seed(2)
bstrees <- boot.phylo(phylo_obj_rooted, msa, FUN = fun, B = 5, block = 1, rooted = is.rooted(phylo_obj_rooted), trees = T)$trees
## add confidence values to the plot
clad_boot <- prop.clades(phylo_obj_rooted, bstrees, rooted = is.rooted(phylo_obj_rooted))

plot(phylo_obj_rooted, type = "c", main = "Bipartition vs. Clade Support Values")
#drawSupportOnEdges(clad)
nodelabels(clad_boot)
dev.off()

legend("bottomleft", legend = c("Bipartitions", "Clades"), pch = 22,
      pt.bg = c("green", "lightblue"), pt.cex = 2.5)

# bootstrapping value interpretations:
# >90% strongly supported, 70-90% well supported, 50-70% weakly supported, <50% not supported

## CADM.global function to evaluate concordance between matrices derived from different regions of the genome
## comparePhylo is a function to compare two trees
comparePhylo(phylo_obj,phylo_obj_rooted)

## assign color to different lineages
col_def <- def(phylo_obj_rooted$tip.label, "b" = "red", regexp = TRUE)
plot(phylo_obj_rooted, tip.col = col_def)


## check if a list of tip labels are monophyletic or not
is.monophyletic(phy, tips, reroot = !is.rooted(phy), plot = FALSE, ...)

## check number of lineages through time 

ltt.plot(bird.families)
ltt.plot(bird.families, log = "y")













nodelabels()

tr <- rcoal(5)
    (x <- evonet(tr, 6:7, 8:9))
    plot(x)
    ## simple example of extended Newick format:
    (enet <- read.evonet(text = "((a:2,(b:1)#H1:1):1,(#H1,c:1):2);"))
    plot(enet, arrows=1)
    ## from Fig. 2 in Cardona et al. 2008:
    z <- read.evonet(text =
    "((1,((2,(3,(4)Y#H1)g)e,(((Y#H1, 5)h,6)f)X#H2)c)a,((X#H2,7)d,8)b)r;")
    z
    plot(z)
    ## Not run:
    if (require(igraph)) {
        plot(as.igraph(z))
    }
    ## End(Not run)

data(woodmouse)
    trw <- fastme.bal(dist.dna(woodmouse))
    plot(trw)

2*(1 - pnorm(abs(gammaStat(trw))))

ss <- fastme.ols(dist.dna(g, model = "TN93"))
plot(ss)

data(hivtree.newick)
data(hivtree.table)
class(hiv)
howmanytrees(5, rooted = F)

class(hivtree.newick)

as.phylo(hivtree.newick)

x <- rep("a", 3)
    makeLabel(x)
    make.unique(x) # <- from R's base
    x <- rep("aaaaa", 2)
    makeLabel(x, len = 3) # made unique and of length 3
    makeLabel(x, len = 3, make.unique = FALSE)


sa <- rDNAbin(ncol = 1000, nrow = 5, base.freq = rep(0.25, 4), prefix = "Ind_")

sa
as.character(sa[,1:10])

phymltest(p17_cons_path)

setwd("/Users/alimos313/Desktop")

phymltest(p17_cons_path, execname = "phyml", format = "sequential")

getwd()




```

```{r}

ss <- ape::read.tree(file = "/Users/alimos313/Desktop/alaki/dummy.txt.treefile")
phylo_obj


cophenetic(phylo_obj)
cophenetic(ss)

fun <- function(xx) bionj(dist.dna(xx))
set.seed(2)

bstrees <- boot.phylo(ss, msa, FUN = fun, B = 100, block = 1, rooted = is.rooted(ss), trees = T)$trees
## add confidence values to the plot
clad_boot <- prop.clades(ss, bstrees, rooted = is.rooted(ss))

plot(ss, main = "Bipartition vs. Clade Support Values")
#drawSupportOnEdges(clad)
nodelabels(clad_boot)

is.binary(ss)
is.rooted(ss)
is.ultrametric(ss)

plot(ss)
print(ss)
plot(X)

class(dist_mat)
dist_mat



```
