---
title:  
    "Mutational signatures of EXPIII"
date: 
    "Sept. 17th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---



```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("RColorBrewer")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
variants_ann_expiii <- variants_ann[variants_ann$exp_line %in% 13:16,]


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# last passage 

end_passage <- 560


# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```



```{r}

## Majority stats
min_threshold <- 0.01
max_threshold <- 1.01


passages <- seq(10,570, 10)
diff_df <- data.frame()



for (i in 1:56){
    for (exp_line in c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")){
        prev_in <- passages[i]
        pres_in <- passages[i+1]

        prev <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == prev_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line", "mut_context")]

        pres <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == pres_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line", "mut_context")]

        addition <- dplyr::setdiff(pres, prev)
        nrow(prev)

        diff_df <- rbind(diff_df, cbind(addition, passage = passages[i+1]))

    }
    
}


```



```{r}



reverse_complement <- function(sequences) {

    # Define the complement base pairs
    complement <- c(A = "T", T = "A", C = "G", G = "C")

    # Function to reverse complement a single sequence
    reverse_complement_single <- function(sequence) {
        sequence_split <- unlist(strsplit(sequence, ""))
        complement_sequence <- complement[sequence_split]
        reverse_complement_sequence <- rev(complement_sequence)
        return(paste(reverse_complement_sequence, collapse = ""))
    }

    # Apply the reverse_complement_single function to each sequence in the vector
    return(as.character(sapply(sequences, reverse_complement_single)))
}

context_formatter <- function(alt_allele, three_n_context) {
    return(paste0(substr(three_n_context,1,1), "[", substr(three_n_context,2,2), ">", alt_allele, "]", substr(three_n_context,3,3)))
}



context_fac <- c()
for (alt in c("A","C", "G", "T")){
    for (pos1 in c("A","C", "G", "T")){
        for (pos2 in c("C", "T")){
            for (pos3 in c("A","C", "G", "T")){
                if (alt != pos2){
                    context_fac <- append(context_fac,context_formatter(alt, paste0(pos1,pos2,pos3)))
                }
            }
        }
    }
}




```


```{r}



ss <- diff_df %>%
    filter(mut_type == "P") %>%
    mutate(mut_context_96 = ifelse(substr(mut_context, 2, 2) %in% c("C", "T"), context_formatter(alt_allele, mut_context), context_formatter(reverse_complement(alt_allele),reverse_complement(mut_context)))) %>%
    mutate(mut_context_96 = factor(mut_context_96, levels = context_fac))



aa <- ss %>% 
        group_by(passage, exp_line, mut_context_96) %>%
        summarise(counts = n(), .groups = "drop") %>%
        complete(passage, exp_line, mut_context_96, fill = list(counts = 0))


aa %<>% pivot_wider(names_from = mut_context_96, values_from = counts) 

aa <- as.data.frame(aa)
row.names(aa) <- paste0(aa$passage, ".", aa$exp_line)

aa <- aa[,-c(1:2)]

aa1 <- aa

aa1 <- t(aa[str_detect(row.names(aa), "MT-2|MT-4"),])

# remove 0 counts in the count matrix
aa1 <- aa1 + 0.0001

View(aa1)



```



```{r}

library(devtools)
devtools::load_all("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/src/analysis/mut_sig/MutationalPatterns/R")
library(NMF)


# to decide on how many signatures to be extracted de novo
est <- nmf(aa1, rank = 2:7, method = "brunet", 
                nrun = 10, seed = 123456, .opt = "v-p")

# visualize
plot(est)


library("ccfindR")
set.seed(4)
sc <- scNMFSet(count = aa1)

estimate_bayes <- vb_factorize(sc, ranks = 2:8, nrun = 1, 
                            progress.bar = FALSE, verbose = 0)


plot(estimate_bayes)


```


```{r}



# extract signatures
nmf_res <- extract_signatures(aa1, rank = 3, nrun = 10, single_core = TRUE)


# You can provide the extracted signatures with custom names:
colnames(nmf_res$signatures) <- c("Signature A", "Signature B", "Signature C")
rownames(nmf_res$contribution) <- c("Signature A", "Signature B", "Signature C")

# already existing signatures. Here we will use signatures from COSMIC (v3.2) (Alexandrov et al. 2020).
signatures = get_known_signatures()

# In this example the name of a signature is changed if it has a cosine similarity of more than 0.85 with an existing COSMIC signature.
nmf_res <- rename_nmf_signatures(nmf_res, signatures, cutoff = 0.65)


# You can plot the 96-profile of the signatures (When looking at SNVs):
plot_96_profile(nmf_res$signatures, condensed = TRUE)

# You can visualize the contribution of the signatures in a barplot:
plot_contribution(nmf_res$contribution, nmf_res$signature,
    mode = "relative"
)


# Plot signature contribution as a heatmap with sample and signature clustering dendrograms
plot_contribution_heatmap(nmf_res$contribution, 
                          cluster_samples = TRUE, 
                          cluster_sigs = TRUE)

pdf("/Users/alimos313/Desktop/ss.pdf", height = 21, width = 14)
dev.off()

# We can compare the reconstructed mutational profile with the original mutational profile for a single sample like this
plot_compare_profiles(aa1[, 1],
  nmf_res$reconstructed[, 1],
  profile_names = c("Original", "Reconstructed"),
  condensed = TRUE
)


# We can also plot the cosine similarity between the original and reconstructed matrix for 
#all the samples. When a reconstructed profile has a cosine similarity of more than 0.95 with 
#the original, the reconstructed profile is considered very good.

plot_original_vs_reconstructed(aa1, nmf_res$reconstructed, 
                               y_intercept = 0.95)


# explore similarity of extracted signatures and

cosine_similarity_matrix <- cos_sim_matrix(nmf_res$signatures, signatures)

cosine_similarity_matrix <- cos_sim_matrix(nmf_res$signatures, nmf_res$signatures)

cosine_similarity_matrix <- cos_sim_matrix(signatures, signatures)
cosine_similarity_matrix > 0.7


```





```{r}


sig_cont <- as.data.frame(nmf_res$contribution) %>%
                mutate(Signature=row.names(as.data.frame(nmf_res$contribution))) %>%
                pivot_longer(cols = -Signature, names_to = "Sample", values_to = "Contribution") %>%
                mutate(Line = str_extract(Sample, "(?<=\\.).*"),
                Host = ifelse(str_detect(Line, "MT-2"), "MT2", "MT4")) 


sig_cont %>% ggplot(aes(x = Signature, y = Contribution, fill = Host))+
                geom_boxplot() +
                stat_compare_means(aes(group = Host), method = "t.test", label = "p.signif")





mt2_a <- nmf_res$contribution["Signature A",str_detect(colnames(nmf_res$contribution), "MT-2")]
mt4_a <- nmf_res$contribution["Signature A",str_detect(colnames(nmf_res$contribution), "MT-4")]

mean(mt4_a)/mean(mt2_a)

t.test(mt2_a, mt4_a)

colSums(nmf_res$contribution)


```



```{r}


#############
# signature refitting

# Fit mutation matrix to the COSMIC mutational signatures:

fit_res <- fit_to_signatures(aa1, signatures)


# show the contribution of signatures as a barplot.
plot_contribution(fit_res$contribution,
  coord_flip = FALSE,
  mode = "absolute"
)


plot_original_vs_reconstructed(aa1, fit_res$reconstructed, 
                               y_intercept = 0.95)



```