---
title:  
    "Diversity measures"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(magrittr)
library(ggplot2)
library(tidyr)
library(stringr)
library(plotly)


```


```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```



```{r read in diversity data}


lines <- c(13:16)

diversity_df <- data.frame()


for (line in lines){
  diversity_df <- rbind(diversity_df, read.table(file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/diversity/iii/", line, "_diversity_measures.tsv"), sep = "\t", header = T)) #"_shannon_entropy"
}

# set the correct viral line names and  add host info
diversity_df %<>% mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4")) %>% # add a field containing pos, ref, and alt info of muts
                mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2")) %>%
                filter(passage <= end_psg)

```


```{r mean shannon entropy per sample}


shannon_measure <- diversity_df %>% group_by(host_line,exp_line,passage) %>%
  summarise (sum_ent = sum(shannon_entropy, na.rm = T), 
    mean_ent = mean(shannon_entropy, na.rm = T), 
    .groups = 'drop') %>%
  mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))



# visualize 
fig <- ggplot(shannon_measure, aes(x = passage, y = mean_ent, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="Transfer", y= "Mean entropy (H)", color = "Population", title = paste0("Mean of Entropy per Sample")) +
  scale_color_manual(values = line_col_palette) +
  scale_x_continuous(breaks = seq(0,end_psg+10,50)) +
  custom_plot_theme(application = "publication")


# save figure
# custom_plot_save(fig, "shannon_per_sample_mean.pdf", height = 14, width = 14)

```



```{r read in simulated diversity}


# read in simulated diversity data
bottleneck_freq <- 3
sim_diversity_df <- readRDS(file = paste0(wd, "results/tables/neutral-seq-sim/", bottleneck_freq, "_sim_diversity_all_runs.rds"))
sim_diversity_df %<>% mutate_at(c(1,3:5), as.numeric)


# create full grid to include all positions including zeros (i.e., positions with no variants)
all_positions <- expand.grid(
  run_nr = 1:max(sim_diversity_df$run_nr),
  exp_line = exp_line_factor,
  passage = seq(10, 500, 10),
  genomic_position = 454:9625,
  stringsAsFactors = FALSE
)

# merge to have full dataset
sim_diversity_df <- all_positions %>%
  left_join(sim_diversity_df, by = c("run_nr", "exp_line", "passage", "genomic_position")) %>%
  mutate(shannon_entropy = replace_na(shannon_entropy, 0))


# summarize shannon measures per sample
shannon_measure_sim <- sim_diversity_df %>% group_by(exp_line,passage) %>%
  summarise (sum_ent = sum(shannon_entropy, na.rm = T), 
    n = n(),
    mean_ent = mean(shannon_entropy),
    sd_ent = sd(shannon_entropy),
    se = sd_ent / sqrt(n),
    t_crit = qt(0.975, df = n - 1),
    lower_95 = mean_ent - t_crit * se,
    upper_95 = mean_ent + t_crit * se,
    .groups = "drop") %>%
  mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))


```


```{r merge observed and simulated data}

# combine observed and simulated data
shannon_measure$lower_95 <- NA
shannon_measure$upper_95 <- NA
shannon_measure$group <- "Observed"
shannon_measure <- shannon_measure[,-1]
shannon_measure_sim$group <- "Simulated"

shannon_measure_all <- rbind(shannon_measure, shannon_measure_sim[,c(1:3,5,9:11)])

# Calibrate

cols <- c("mean_ent", "lower_95", "upper_95")
obs <- mean(shannon_measure_all$mean_ent[shannon_measure_all$group == "Observed" & shannon_measure_all$passage == 10])
sim <- mean(shannon_measure_all$mean_ent[
  shannon_measure_all$group == "Simulated" & shannon_measure_all$passage == 10])

shannon_measure_all[
  shannon_measure_all$group == "Simulated",
  cols
] <- shannon_measure_all[
  shannon_measure_all$group == "Simulated",
  cols
] * (obs/sim)


# visualize
fig <- ggplot(shannon_measure_all, aes(x = passage, y = mean_ent, color = exp_line, linetype = group)) +
  geom_line(linewidth=2) + 
  geom_ribbon(
    data = shannon_measure_all %>% dplyr::filter(group == "Simulated"),
    aes(
        x = passage,
        ymin = lower_95,
        ymax = upper_95,
        fill = exp_line,
        group = interaction(exp_line)
    ),
    alpha = 0.2,
    inherit.aes = FALSE,
    show.legend = FALSE
  )+
  labs(x="Transfer", y= "Mean entropy (H)", color = "Population", linetype = "Dataset", title = "") +
  scale_color_manual(values = line_col_palette) +
  scale_fill_manual(labels = exp_line_factor, values = line_col_palette) +
  scale_y_continuous(limits = c(0,max(shannon_measure_all$mean_ent)+0.001),breaks = seq(0,max(shannon_measure_all$mean_ent)+0.001,0.005)) +
  scale_x_continuous(breaks = seq(0,end_psg+10,50)) +
  custom_plot_theme(application = "publication") +
  guides(
    color = guide_legend(order = 1),     # Line legend first
    linetype = guide_legend(order = 2)   # Dataset legend second
  )


# save figure
custom_plot_save(fig, "shannon_per_sample_mean_plus_simulated.pdf", height = 14, width = 14)

```

