---
title:  
    "dn/ds"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(ggpubr)
library(plotly)
library(ggvenn)
library(hrbrthemes)
library(DT)
library(dplyr)
library(tidyr)
library(Biostrings)
library(stringr)
library(magrittr)
library(rstatix)


```

```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```


```{r text numbers}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

```


```{r syn and non-syn accumulation over time}

# read in the gene summary data
gene_summary <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/gene_summary_table.tsv", sep = "\t", header = T)


N_site <- sum(gene_summary$nonsynonymous_count)
S_site <- sum(gene_summary$synonymous_count)
U_site <- 336*3 + 217*3

S_site_perc <- S_site/((N_site+S_site+U_site))

N_site <- mean(gene_summary$nonsynonymous_percentage)*100
S_site <- mean(gene_summary$synonymous_percentage)*100

# prepare data for visualization
counts <- variants_ann_expiii%>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "syn", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "non-syn")) %>%
            filter(effect_simplified != "U") %>%
            mutate(effect_simplified = factor(effect_simplified, levels = c("non-syn", "syn"))) %>%
            group_by(exp_line, passage, effect_simplified,.drop = FALSE) %>%
            summarise(count = n()) %>%
            mutate_at(4, as.numeric) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(normalized_rate = ifelse(effect_simplified == "syn", (count*100)/((S_site/100)*(9407-790)*3),(count*100)/((N_site/100)*(9407-790)*3)))

counts$effect_simplified <- factor(
    counts$effect_simplified,
    levels = c("syn", "non-syn")  # desired order
)

# visualize
fig <- counts %>%  ggplot(aes(x=passage, y = normalized_rate, color = exp_line, linetype = effect_simplified)) +
        geom_line(linewidth=1) +
        labs(x="Transfer", y= "Sites with fixed mutation (%)",  color = "Population", linetype = "Sites",
        title = paste0(category, " Mutation Accumulation \n (Syn vs Non-Syn)"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$normalized_rate)+0.1),breaks = seq(0,max(counts$normalized_rate)+0.1,0.1)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        scale_linetype_manual(
            values = c("syn" = "solid", "non-syn" = "dashed"),
            labels = c("syn" = "Synonymous", "non-syn" = "Nonsynonymous")
        ) +
        guides(color = guide_legend(order = 1), linetype = guide_legend(order = 2)) +
        custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, paste0(category, "_mut_accumulation_ds_vs_dn.pdf"), height = 14, width = 14)
```

```{r in-text numbers}
## compute effect sizes
# Filter data for each condition
ds_data <- counts$normalized_rate[counts$exp_line %in% c("MT-2_1","MT-2_2") & counts$effect_simplified == "dS"]
dn_data <- counts$normalized_rate[counts$exp_line %in% c("MT-2_1","MT-2_2") & counts$effect_simplified == "dN"]

# Perform the paired t-test
t_test_result <- t.test(ds_data, dn_data, paired = TRUE)

# Calculate the differences
differences <- ds_data - dn_data

# Compute Cohen's d
mean_diff <- mean(differences)
sd_diff <- sd(differences)
cohen_d <- mean_diff / sd_diff


```

```{r dn/ds over time}


# prepare data for visualization
counts <- variants_ann_expiii%>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "dS", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "dN")) %>%
            filter(effect_simplified != "U") %>%
            mutate(effect_simplified = factor(effect_simplified, levels = c("dN", "dS"))) %>%
            group_by(exp_line, passage, effect_simplified,.drop = FALSE) %>%
            summarise(count = n()) %>%
            mutate_at(4, as.numeric) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(normalized_rate = ifelse(effect_simplified == "dS", count/S_site,count/N_site))




counts_wide <- counts %>% select(exp_line, passage, effect_simplified, normalized_rate) %>% pivot_wider(names_from = effect_simplified, values_from = c(normalized_rate))
counts_wide$dS[counts_wide$dS == 0] <- counts_wide$dN[counts_wide$dS == 0]/4


counts_wide$dnds <- counts_wide$dN/counts_wide$dS


# visualize
fig <- counts_wide %>%  ggplot(aes(x=passage, y = dnds, color = exp_line)) +
        # geom_line(linewidth=1) +
        geom_smooth(method = "gam", se = FALSE) +
        labs(x="Transfer", y= "dN/dS",  color = "Population",
        title = paste0(category, " dN/dS over Time"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts_wide$dnds, na.rm = T)+0.1),breaks = seq(0,max(counts_wide$dnds, na.rm = T)+0.1,0.25)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")



# save figure
custom_plot_save(fig, paste0(category, "_dn_ds_ratio_over_time.pdf"), height = 14, width = 14)

```

```{r dn/ds over time in-text numbers}

max(counts_wide$passage[counts_wide$dnds > 2 & counts_wide$exp_line == "MT-2_1"], na.rm = T)
max(counts_wide$passage[counts_wide$dnds > 2 & counts_wide$exp_line == "MT-2_2"], na.rm = T)
max(counts_wide$passage[counts_wide$dnds > 2 & counts_wide$exp_line == "MT-4_1"], na.rm = T)
max(counts_wide$passage[counts_wide$dnds > 2 & counts_wide$exp_line == "MT-4_2"], na.rm = T)


```