---
title:  
    "Effective population size of EXPIII"
date: 
    "Dec 18th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```





## Effective population size

```{r measure variance ne}

## estimating the effective population size (Variance Effective Size) by this formula: Ne ≈ p(1−p)/Var(Δp)
## if there are more than one generation between the time points: 1/(2*(1-(1-(var(delta_afs)/(af_ave*(1-af_ave))))^(1/20)))

df <- data.frame()


# exp_line <- "MT-4_1"
# pres_psg <- 130
# trans_effect <- "S"

# 8787 9408
for (exp_line in names(line_col_palette)){
    
    print(exp_line)
    
    for (trans_effect in c("S", "ALL")) {
        if (trans_effect == "ALL"){
            variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9408,]
        } else {
            variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$effect_simplified == trans_effect,]
        }
        
        # set generation number between time points
        gen_nr <- 30

        for (pres_psg in seq(20,570,10)){
            print(pres_psg)
            prev_psg <- pres_psg - 10
            
            pres_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$passage == pres_psg & variants_expiii_sub$allele_freq >= 0.01])
            prev_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$passage == prev_psg & variants_expiii_sub$allele_freq >= 0.01])
            union_muts <- union(pres_muts, prev_muts)
            intersect_muts <- intersect(pres_muts, prev_muts)
            
            delta_afs <- c()
            for (mut in intersect_muts){
                if (mut %in% pres_muts){
                    pres_mut_af <- variants_expiii_sub$allele_freq[variants_expiii_sub$passage == pres_psg & variants_expiii_sub$mut_info == mut]
                } else {pre_mut_af <- 0}
                if (mut %in% prev_muts){
                    prev_mut_af <- variants_expiii_sub$allele_freq[variants_expiii_sub$passage == prev_psg & variants_expiii_sub$mut_info == mut]
                } else {prev_mut_af <- 0}
                
                delta_af <- pres_mut_af - prev_mut_af
                delta_afs <- append(delta_afs, delta_af)
            }
            
            af_pres <- sum(variants_expiii_sub$allele_freq[variants_expiii_sub$passage == pres_psg & variants_expiii_sub$allele_freq >= 0.01])
            af_prev <- sum(variants_expiii_sub$allele_freq[variants_expiii_sub$passage == prev_psg & variants_expiii_sub$allele_freq >= 0.01])
            af_ave <- af_pres/length(pres_muts)
            
            Ne <- tryCatch({1/(2*(1-(1-(var(delta_afs)/(af_ave*(1-af_ave))))^(1/gen_nr)))}, error = function(e){NA})
            
            df <- rbind(df, c(exp_line, trans_effect, pres_psg, length(union_muts), length(intersect_muts), af_ave, tryCatch({var(delta_afs)}, error = function(e){NA}), Ne))
        }
    }
    
}



df %<>% set_colnames(c("exp_line", "effect_simplified", "psg", "union_count", "intersect_count", "average_allele_freq", "var_freq_change", "Ne")) %>%
        mutate(
            psg = as.numeric(psg),
            var_freq_change = as.numeric(var_freq_change),
            union_count = as.integer(union_count),
            intersect_count = as.integer(intersect_count),
            Ne = as.numeric(Ne))



# save data on disk
save(df, file = paste0(wd,"results/tables/misc/variance_effective_size_nef.RData"))

```


```{r visualize variance ne}

load(paste0(wd,"results/tables/misc/variance_effective_size_nef.RData")) # or all of genome: variance_effective_size.RData



df_subset <- df[df$effect_simplified == "S",]
# plot Ne
fig <- df_subset %>% ggplot(aes(x = psg, y = log10(Ne), col = exp_line)) +
        # facet_wrap(~ exp_line) +
        geom_line() +
        geom_hline(yintercept = log10(mean(df_subset$Ne[df_subset$exp_line %in% c("MT-2_1","MT-2_2")], na.rm = TRUE)), linetype = "dashed", linewidth = 2, color = "#ff8b08") +
        geom_hline(yintercept = log10(mean(df_subset$Ne[df_subset$exp_line %in% c("MT-4_1","MT-4_2")], na.rm = TRUE)), linetype = "dashed", linewidth = 2, color = "#00bbff") +
        scale_y_continuous(breaks = seq(1.5,4,0.5),limits = c(1.5,4))+
        scale_x_continuous(breaks = seq(0,500,50),limits = c(0,500))+
        scale_color_manual(values = line_col_palette) +
        geom_smooth(method = "loess", se = FALSE) +
        labs(x= "Transfer", y = "Log10(Ne)", title = "Variance Effective Population Size (nef Variants) \n", color = "Population") + # Label for the legend
        custom_plot_theme(application = "publication")




# save figure

custom_plot_save(fig, "variance_ne_syn.pdf", height = 14, width = 14)

log10(mean(df_subset$Ne[df_subset$exp_line %in% c("MT-2_1","MT-2_2")], na.rm = TRUE))
log10(mean(df_subset$Ne[df_subset$exp_line %in% c("MT-4_1","MT-4_2")], na.rm = TRUE))
```



```{r in-line numbers}

# ave Ne per line
head(df)
df %>%
    mutate(host = ifelse(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4")) %>%
    filter(effect_simplified == "ALL" & psg >= 300) %>%
    group_by(host) %>%
    summarise(mean = mean(Ne, na.rm = T), iqr_upper = quantile(Ne, 0.75, na.rm = T), iqr_lower = quantile(Ne, 0.25, na.rm = T), n = n())

4394/634
6.9/4.8
# plot variance in allele freq change
df[df$effect_simplified != "ALL",] %>% ggplot(aes(x = psg, y = log2(var_freq_change), color = effect_simplified)) +
        facet_wrap(~ exp_line) +
        geom_line() +
        geom_smooth(method = "loess", se = FALSE)

# plot proportion of mutation retention
df[df$effect_simplified != "ALL",] %>% ggplot(aes(x = psg, y = intersect_count/union_count, color = effect_simplified)) +
        facet_wrap(~ exp_line) +
        geom_line() +
        geom_smooth(method = "loess", se = FALSE)


df[df$psg == 130 & df$effect_simplified == "S",]



```


## Effective population size by BEAST

```{r}

# read-in data
skyline_data <- data.frame()
line_labels
for (line in line_labels){
    data <- read.table(file = paste0("/Applications/BEAST_2.7.6/ltee/ne-estimate/gag/",line,"/",line,"_skyline_data.txt"), sep = "\t", header = T, skip = 1)
    data$exp_line <- line
    skyline_data <- rbind(skyline_data, data)
}

skyline_data %<>% mutate(lower = (lower+mean)/2, upper = (upper+mean)/2)


ne__fig <- skyline_data %>% 
    ggplot(aes(x = time, y = mean, color = exp_line)) +
    geom_line() +
    geom_ribbon(aes(ymin = lower, ymax = upper, fill = exp_line), alpha = 0.1, linetype = 0) +
    labs(title = "Bayesian Skyline Ne Estimates \n", x= "\n Days", y= "Baysian Ne Estimate \n", color = "Virus Line") +
    scale_color_manual(values = line_col_palette) +
    scale_fill_manual(values = line_col_palette) +
    guides(fill = "none") +
    theme_bw() +
    theme(
        plot.title = element_text(size = 40, face = "bold", hjust = 0.5),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        axis.text = element_text(size = 15))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "bayesina_ne_estimates.pdf"), height = 14, width = 21)
ne__fig
dev.off()
```