---
title:  
    "Fixation timeline of fixed variants"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(magrittr)
library(tidyr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
library(ggrepel)


```


```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```



```{r set paramters}

# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
} else if (category == "All"){
    min_threshold <- 0.01
    max_threshold <- 1.01
}

```

```{r}

# set seed for reproducibility
set.seed(2)

# obtain fixation parameters
df <- data.frame()
for (exp_line in exp_line_factor){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$passage == end_psg])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.01])))
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}

# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = rev(exp_line_factor)),
        mut_info_line = paste(exp_line, mut_info, sep = "_"),
        host_line = if_else(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4"),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))


df %<>% group_by(mut_info) %>% 
    mutate(Occurrence = n()) %>%
    mutate(Occurrence = factor(Occurrence, levels = c("1","2","3","4"))) %>%
    mutate(exp_line_number = case_when(exp_line == "MT-2_1" ~ 4,
                                        exp_line == "MT-2_2" ~ 3,
                                        exp_line == "MT-4_1" ~ 2,
                                        exp_line == "MT-4_2" ~ 1)) %>%
    ungroup()


# add jitter to y values for better visualization
df_jittered <- df %>%
    mutate(y_jittered = exp_line_number + runif(n(), min = -0.1, max = 0.1))  # Add jitter to y values




# define colors for mutations based on occurrence
blues_colors <- c("#A4DDED", "#A3C1AD", "#CCCCFF", "#00CCFF", "#15f4ee", 
"#0071c5", "#5A4FCF", "#004687", "#0000CD", "#191970")
triples <- blues_colors
names(triples) <- unique(df_jittered$mut_info[df_jittered$Occurrence == "3"])[order(unique(df_jittered$mut_info[df_jittered$Occurrence == "3"]))]

reds_colors <- brewer.pal(5, "Reds")[3:5]
quad <- reds_colors
names(quad) <- unique(df_jittered$mut_info[df_jittered$Occurrence == "4"])



df_jittered %<>%
    mutate(mut_info2 = case_when(Occurrence == 1 ~ "Single-occurrence",
                                Occurrence == 2 ~ "Double-occurrence",
                                Occurrence == 3 ~ mut_info,
                                Occurrence == 4 ~ mut_info)) %>%
    mutate(mut_info2 = factor(mut_info2, levels = c("Single-occurrence", "Double-occurrence", names(triples), names(quad))))



custom_colors <- c(
    "Single-occurrence" = "grey",
    "Double-occurrence" = "green"
)
custom_colors <- c(custom_colors, triples, quad)

# update mut_info so that double-occurrence cases are not connected by lines
df_jittered$mut_info3[df_jittered$mut_info2 == "Double-occurrence"] <- paste0(df_jittered$mut_info[df_jittered$mut_info2 == "Double-occurrence"], rnorm(sum(df_jittered$mut_info2 == "Double-occurrence")))
df_jittered$mut_info3[df_jittered$mut_info2 != "Double-occurrence"] <- df_jittered$mut_info[df_jittered$mut_info2 != "Double-occurrence"]


fig <- ggplot(df_jittered, aes(x = fixation, y = exp_line, group = mut_info3, color = mut_info2)) +
    # Thicker lines for Occurrence 3 and 4
    geom_line(aes(y = y_jittered, size = Occurrence), alpha = 1) +
    geom_point(aes(y = y_jittered), size = 4) +
    scale_y_continuous(breaks = 1:4, labels = rev(exp_line_factor)) +
    scale_x_continuous(breaks = seq(0, 500, by = 50)) +
    scale_color_manual(values = custom_colors) +
    scale_size_manual(values = c("1" = 0.5, "2" = 1, "3" = 3, "4" = 3)) +  # Adjust line thickness here
    labs(title = "Mutation Fixation Timeline",
        x = "Transfer of fixation", y = "Line", color = "Fixed mutation") +
    custom_plot_theme(application = "publication", scale = 1.8) +
    guides(
        color = guide_legend(override.aes = list(size = 8)),  # change legend point size
        size = "none"  # hide the size legend if you don't want it
    )

# save figure
custom_plot_save(fig, "fixation_timeline.pdf", height = 21, width = 42)

```

####!!!!
Extra analysis
####!!!!

```{r case by case mutation order}


df_jittered[df_jittered$mut_info == "9412_G_A",]
df_jittered[df_jittered$mut_info == "9416_T_C",]

variants_expiii[variants_expiii$exp_line == "MT-4_2" & variants_expiii$mut_info == "9412_G_A" & variants_expiii$passage == 70,]
variants_expiii[variants_expiii$exp_line == "MT-4_2" & variants_expiii$mut_info == "9416_T_C" & variants_expiii$passage == 70,]


df_jittered[df_jittered$mut_info == "2058_G_A",]

bam <- c()
i <- 0
for (mut in unique(df_jittered$mut_info[df_jittered$Occurrence %in% 3])){
    i <- i + 1
    print(paste(as.character(df_jittered$exp_line[df_jittered$mut_info == mut]), collapse = ", "))
    bam <- append(bam, mut)
    names(bam)[i] <- paste(as.character(df_jittered$exp_line[df_jittered$mut_info == mut]), collapse = ", ")
}


table(names(bam))
View(df_jittered[df_jittered$mut_info %in% as.vector(bam[names(bam) == "MT-2_2, MT-4_1, MT-4_2"]),])

```