```{r}


aa <- c("Ala", "Arg", "Asn", "Asp", "Cys", "Gln", "Glu", "Gly", "His", "Ile",
        "Leu", "Lys", "Met", "Phe", "Pro", "Ser", "Thr", "Trp", "Tyr", "Val")

grantham_matrix_3letter <- matrix(c(
    0,112,111,126,195, 91,107,102,124, 60, 27, 99,106, 96, 34, 97,112, 84, 61, 96,
  112,  0, 86, 96,180, 26, 29, 96, 97,102,103, 96,142,121,110, 43, 97, 26, 97, 97,
  111, 86,  0, 65,160, 36, 23, 80, 85, 95, 98, 91,130,108, 91, 24, 77, 42, 84, 84,
  126, 96, 65,  0,160, 61, 61, 56, 71,101,102, 54,126,103,101, 42, 65, 61, 96, 96,
  195,180,160,160,  0,154,170,152,177,135,131,169,205,194,158,147,180,154,149,139,
    91, 26, 36, 61,154,  0, 24, 87, 94, 98, 99, 84,127,106, 93, 29, 89, 38, 96, 96,
  107, 29, 23, 61,170, 24,  0, 80, 89, 96, 98, 87,135,112, 94, 20, 77, 42, 91, 91,
  102, 96, 80, 56,152, 87, 80,  0, 37,127,128, 32, 98, 87,130, 80, 61, 78, 84, 84,
  124, 97, 85, 71,177, 94, 89, 37,  0,134,135, 21,100, 85,135, 92, 61, 85, 84, 84,
    60,102, 95,101,135, 98, 96,127,134,  0, 36,135,149,142, 61,109,121, 96, 71, 71,
    27,103, 98,102,131, 99, 98,128,135, 36,  0,136,153,144, 56,116,130,107, 74, 74,
    99, 96, 91, 54,169, 84, 87, 32, 21,135,136,  0, 95, 74,134, 78, 48, 61, 91, 91,
  106,142,130,126,205,127,135, 98,100,149,153, 95,  0, 29,177,132,155,127, 88, 88,
    96,121,108,103,194,106,112, 87, 85,142,144, 74, 29,  0,164,110,134,109, 77, 77,
    34,110, 91,101,158, 93, 94,130,135, 61, 56,134,177,164,  0,103,121, 98, 55, 55,
    97, 43, 24, 42,147, 29, 20, 80, 92,109,116, 78,132,110,103,  0, 68, 45, 96, 96,
  112, 97, 77, 65,180, 89, 77, 61, 61,121,130, 48,155,134,121, 68,  0, 65,100,100,
    84, 26, 42, 61,154, 38, 42, 78, 85, 96,107, 61,127,109, 98, 45, 65,  0, 97, 97,
    61, 97, 84, 96,149, 96, 91, 84, 84, 71, 74, 91, 88, 77, 55, 96,100, 97,  0, 37,
    96, 97, 84, 96,139, 96, 91, 84, 84, 71, 74, 91, 88, 77, 55, 96,100, 97, 37,  0
  ), nrow = 20, byrow = TRUE)

rownames(grantham_matrix_3letter) <- colnames(grantham_matrix_3letter) <- aa

convert_aa <- function(code) {
  aa_1_to_3 <- c(
    A = "Ala", R = "Arg", N = "Asn", D = "Asp", C = "Cys",
    Q = "Gln", E = "Glu", G = "Gly", H = "His", I = "Ile",
    L = "Leu", K = "Lys", M = "Met", F = "Phe", P = "Pro",
    S = "Ser", T = "Thr", W = "Trp", Y = "Tyr", V = "Val"
  )
  
  aa_3_to_1 <- setNames(names(aa_1_to_3), aa_1_to_3)

  if (all(nchar(code) == 1)) {
    return(unname(aa_1_to_3[code]))
  } else if (all(nchar(code) == 3)) {
    return(unname(aa_3_to_1[code]))
  } else {
    stop("Input must be all 1-letter or all 3-letter codes.")
  }
}

grantham_score <- function(from, to, mat = grantham_matrix_3letter) {
  if (from %in% rownames(mat) && to %in% colnames(mat)) {
    return(mat[from, to])
  } else {
    stop("Invalid amino acid abbreviation.")
  }
}




```

```{r}


pattern <- "^p\\.([A-Z][a-z]{2})([0-9]+)([A-Z][a-z]{2})$"
variants_expiiifiltered <- variants_expiii[grepl(pattern, variants_expiii$aa_change), ]

# Extract components: first AA, position, second AA
matches <- str_match(variants_expiiifiltered$aa_change, pattern)

# Add new columns
variants_expiiifiltered$aa_from <- matches[, 2]
variants_expiiifiltered$aa_to <- matches[, 4]

variants_expiiifiltered <- variants_expiiifiltered[variants_expiiifiltered$aa_from != "Ter",]


# Apply grantham_score to each row
variants_expiiifiltered$grantham_score <- mapply(grantham_score, variants_expiiifiltered$aa_from, variants_expiiifiltered$aa_to)

head(variants_expiiifiltered)

variants_expiiifiltered[] <- variants_expiiifiltered[variants_expiiifiltered$grantham_score != 0,]

variants_expiiifiltered %>% filter(allele_freq >= 0.99 & passage == 500) %>% group_by(feature) %>%
  summarise(mean_grantham = mean(grantham_score), sd_grantham = sd(grantham_score), n = n()) %>%
  arrange(desc(mean_grantham))

fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])


variants_expiiifiltered$Occurrence <- NA
variants_expiiifiltered$Occurrence[variants_expiiifiltered$mut_info %in% names(fix_count_table_list[["1"]])] <- "One"
variants_expiiifiltered$Occurrence[variants_expiiifiltered$mut_info %in% names(fix_count_table_list[["2"]])] <- "Two"
variants_expiiifiltered$Occurrence[variants_expiiifiltered$mut_info %in% names(fix_count_table_list[["3"]])] <- "Three"
variants_expiiifiltered$Occurrence[variants_expiiifiltered$mut_info %in% names(fix_count_table_list[["4"]])] <- "Four"
variants_expiiifiltered <- variants_expiiifiltered[!is.na(variants_expiiifiltered$Occurrence),]
variants_expiiifiltered$Occurrence <- factor(variants_expiiifiltered$Occurrence, levels = c("One", "Two", "Three", "Four"))


variants_expiiifiltered %>% filter(allele_freq >= 0.99 & passage == 500) %>% group_by(Occurrence) %>%
  summarise(mean_grantham = mean(grantham_score), sd_grantham = sd(grantham_score), n = n()) %>%
  arrange(desc(mean_grantham))

variants_expiiifiltered %>% filter(allele_freq >= 0.99 & passage == 500 & Occurrence == "Four") %>%
  distinct()



```