---
title:  
    "Initial Relative Fitness for all fixed mutations"
date: 
    "May 7th, 2026"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(magrittr)
library(tidyr)
library(stringr)
library(ggplot2)
library(purrr)
library(broom)
library(pscl)
library(pROC)
library(scales)
```


```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```
```{r initila relative fitness per relative order}

# read in data
df <- readRDS("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/init_rel_fitness.rds")
t_2_f <- readRDS(paste0(wd, "results/tables/time_to_fixation.Rds"))

# df from ## Method 2 in time_to_fixation.Rmd
merged <- merge(t_2_f, df[,c("exp_line", "mut_info", "init_rel_fit")], by = c("exp_line", "mut_info"), all.y = TRUE)



# get relative order of fixation per experimental line
line_specific_df <- merged %>%
    filter(Occurrence %in% c("1 out of 4")) %>%
    group_by(exp_line) %>%
    arrange(fixation, appearance, .by_group = TRUE) %>%
    mutate(relative_order = row_number()) %>%
    ungroup()


max(line_specific_df$relative_order)

fig <- line_specific_df %>%
    ggplot(aes(x = relative_order, y = init_rel_fit, color = exp_line)) +
    geom_point(size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(
        title = "",
        y = "Initial relative fitness",
        x = "Relative order of fixation",
        color = "Population"
    ) +
    scale_color_manual(values = line_col_palette) +
    scale_x_continuous(breaks = seq(0, 90, 5)) +
    scale_y_continuous(trans = log10_trans(),
    breaks = c(3*10^-1, 10^-1, 5*10^-2, 10^-2, 5*10^-3),
    labels = scales::label_number(accuracy = 0.001)) +
    custom_plot_theme(application = "publication") +
    theme(axis.text.x = element_text(angle = 90)) +
    annotation_logticks(sides = "l", 
        outside = TRUE, 
        short = unit(.6,"mm"), 
        mid = unit(1.2,"mm"), 
        long = unit(2.4,"mm"),
        linewidth = 1) +
    theme(
        axis.text.y = element_text(margin = margin(r = 8))
    ) +
    coord_cartesian(ylim = c(4*10^-3, 3*10^-1), 
        clip = "off")


# save figure
custom_plot_save(fig, "init_rel_fitness_vs_relative_order_line_specific.pdf", height = 14, width = 14)

```

```{r linear model specifics}

# Fit a linear model for each experimental line
models <- line_specific_df %>%
    group_by(exp_line) %>%
    do(tidy(lm(log10(init_rel_fit) ~ relative_order, data = .)))

# View the p-values
models %>%
    filter(term == "relative_order") %>%
    select(exp_line, estimate, std.error, statistic, p.value) %>%
    ungroup() %>% 
    mutate(p.adjusted = p.adjust(p.value, method = "BH"))



```
