---
title:  
    "Initial Relative Fitness from 10.1038/nature12344"
date: 
    "August 7th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(magrittr)
library(tidyr)
library(stringr)
library(ggplot2)
library(purrr)
library(broom)
library(pscl)
library(pROC)
library(scales)
```


```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```

```{r obtain fixation dynamics parameters}

# initial_rel_fitness <- function(t1, af1, t2, af2) {
#     rel_fit <- (1/(3*(t2-t1)))*(log(af2/(1-af2))-log(af1/(1-af1)))
#     return(rel_fit)
# }

# # record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
# df <- data.frame()


# for (exp_line in exp_line_factor){
#     variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
#     fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.1])
#     print(length(fixed_muts))

#     for (i in 1:length(fixed_muts)){
#         print(i)
#         appearance_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0]))) #  & variants_expiii_sub$allele_freq >= 0.01
#         freq_appearance <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == appearance_psg]
#         ten_percent_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0.1])))
#         freq_ten_percent <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == ten_percent_psg]
        


#         init_rel_fit <- initial_rel_fitness(appearance_psg, freq_appearance, ten_percent_psg, freq_ten_percent)

        
#         df <- rbind(df, c(exp_line, fixed_muts[i], appearance_psg, freq_appearance, ten_percent_psg, freq_ten_percent, init_rel_fit))
        
#     }
# }


# # set column names and right data types
# df2 <- df %>% set_colnames(c("exp_line", "mut_info", "appearance_psg", "freq_appearance", "ten_percent_psg", "freq_ten_percent", "init_rel_fit")) %>% 
#         mutate_at(3:7, as.numeric) %>%
#         filter(!is.nan(init_rel_fit))




# saveRDS(df2, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/init_rel_fitness.rds")





```



```{r initila relative fitness per relative order}

# read in data
df <- readRDS("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/init_rel_fitness.rds")
t_2_f <- readRDS(paste0(wd, "results/tables/time_to_fixation.Rds"))

# df from ## Method 2 in time_to_fixation.Rmd
merged <- merge(t_2_f, df[,c("exp_line", "mut_info", "init_rel_fit")], by = c("exp_line", "mut_info"), all.y = TRUE)



# get relative order of fixation per experimental line
adaptive_df <- merged %>%
    filter(Occurrence %in% c("3 out of 4", "4 out of 4")) %>%
    group_by(exp_line) %>%
    arrange(fixation, appearance, .by_group = TRUE) %>%
    mutate(relative_order = row_number()) %>%
    ungroup()




fig <- adaptive_df %>%
    ggplot(aes(x = relative_order, y = init_rel_fit, color = exp_line)) +
    geom_point(size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(
        title = "",
        y = "Initial relative fitness",
        x = "Relative order of fixation",
        color = "Population"
    ) +
    scale_color_manual(values = line_col_palette) +
    scale_x_continuous(breaks = seq(0, 13, 1)) +
    scale_y_continuous(trans = log10_trans(),
    breaks = c(3*10^-1, 10^-1, 5*10^-2, 10^-2, 5*10^-3),
    labels = scales::label_number(accuracy = 0.001)) +
    custom_plot_theme(application = "publication") +
    theme(axis.text.x = element_text(angle = 0)) +
    annotation_logticks(sides = "l", 
        outside = TRUE, 
        short = unit(.6,"mm"), 
        mid = unit(1.2,"mm"), 
        long = unit(2.4,"mm"),
        linewidth = 1) +
    theme(
        axis.text.y = element_text(margin = margin(r = 8))
    ) +
    coord_cartesian(clip = "off")


# save figure
custom_plot_save(fig, "init_rel_fitness_vs_relative_order.pdf", height = 14, width = 14)

```

```{r cumulative fitness gain per relative order}


for (exp_line in names(line_col_palette)){
    for (rel_order in sort(unique(adaptive_df$relative_order[adaptive_df$exp_line == exp_line]))){
        print(rel_order)
        if (rel_order == 1){
            adaptive_df$cum_fit_gain[adaptive_df$exp_line == exp_line & adaptive_df$relative_order == rel_order] <- 1 + adaptive_df$init_rel_fit[adaptive_df$exp_line == exp_line & adaptive_df$relative_order == rel_order]
        } else {
            adaptive_df$cum_fit_gain[adaptive_df$exp_line == exp_line & adaptive_df$relative_order == rel_order] <- adaptive_df$cum_fit_gain[adaptive_df$exp_line == exp_line & adaptive_df$relative_order == rel_order -1] + adaptive_df$init_rel_fit[adaptive_df$exp_line == exp_line & adaptive_df$relative_order == rel_order]
        }
        
    }
}

# adaptive_df$cum_fit_gain[adaptive_df$host_line == "MT-4"] <- adaptive_df$cum_fit_gain[adaptive_df$host_line == "MT-4"] * log(3600)/log(600)

adaptive_df <- rbind(adaptive_df, c("MT-2_1", NA, NA, NA, NA, NA, NA, NA, NA, 0, 0, 1),
                    c("MT-2_2", NA, NA, NA, NA, NA, NA, NA, NA, 0, 0, 1),
                    c("MT-4_1", NA, NA, NA, NA, NA, NA, NA, NA, 0, 0, 1),
                    c("MT-4_2", NA, NA, NA, NA, NA, NA, NA, NA, 0, 0, 1))

adaptive_df %<>% mutate_at(c("relative_order", "cum_fit_gain"), as.numeric)

midpoints <- adaptive_df %>%
    group_by(exp_line) %>%
    summarise(
        max_y = max(cum_fit_gain),
        y_mid = 1 + (max_y - 1) * 0.9,
        x_mid = approx(x = cum_fit_gain,
                    y = relative_order,
                    xout = y_mid)$y,
        # Get the curve's y value at that x_mid (interpolated)
        curve_y = approx(x = relative_order,
                        y = cum_fit_gain,
                        xout = x_mid)$y
    )

fig <- ggplot(adaptive_df, aes(x = relative_order,
                                y = cum_fit_gain,
                                color = exp_line)) +
    geom_point(size = 3) +
    geom_line(aes(group = exp_line), size = 1) +
    # Horizontal dashed line up to x_mid
    geom_segment(
        data = midpoints,
        aes(x = -Inf, xend = x_mid,
            y = y_mid, yend = y_mid,
            color = exp_line),
        linetype = "dashed",
        linewidth = 1.4,
        inherit.aes = FALSE
    ) +
    # Vertical connecting line from curve to horizontal line
    geom_segment(
        data = midpoints,
        aes(x = x_mid, xend = x_mid,
            y = 1, yend = y_mid,
            color = exp_line),
        linetype = "dashed",
        linewidth = 1.4,
        inherit.aes = FALSE
    ) +

    scale_color_manual(values = line_col_palette) +
    scale_x_continuous(breaks = seq(0, 13, 1)) +
    labs(
        y = "Fitness",
        x = "Relative order of fixation",
        color = "Population"
    ) +
    custom_plot_theme(application = "publication") +
    theme(axis.text.x = element_text(angle = 0))


# save figure
custom_plot_save(fig, "cumulative_fitness.pdf", height = 14, width = 14)

# in-text numbers
adaptive_df[adaptive_df$exp_line == "MT-2_1" & adaptive_df$relative_order == 6, ]
adaptive_df[adaptive_df$exp_line == "MT-2_2" & adaptive_df$relative_order == 7, ]
adaptive_df[adaptive_df$exp_line == "MT-4_1" & adaptive_df$relative_order == 9, ]
adaptive_df[adaptive_df$exp_line == "MT-4_2" & adaptive_df$relative_order == 7, ]

```

```{r linear model specifics}

# Fit a linear model for each experimental line
models <- df1 %>%
    group_by(exp_line) %>%
    do(tidy(lm(log10(init_rel_fit) ~ relative_order, data = .)))

# View the p-values
models %>%
    filter(term == "relative_order") %>%
    select(exp_line, estimate, std.error, statistic, p.value) %>%
    ungroup() %>% 
    mutate(p.adjusted = p.adjust(p.value, method = "BH"))


1 - 10^mean(c(-0.140, -0.133))
1 - 10^mean(c(-0.0866, -0.0729))

```


```{r probability of fixation}

# add a binary variable indicating whether the mutation fixed or not
merged %<>% mutate(fixed = ifelse(is.na(fixation), FALSE, TRUE))



model <- glm(fixed ~ init_rel_fit, data = merged, family = binomial)

merged$predicted_prob <- predict(model, type = "response")


ggplot(merged, aes(x = init_rel_fit, y = predicted_prob)) +
    geom_line(color = "blue") +
    labs(title = "Probability of Binary = 1 vs. Continuous Variable",
        x = "Continuous Variable",
        y = "Predicted Probability (Binary = 1)") +
    theme_minimal()

```

```{r probability of fixation per host line}


# fit model per exp_line
models_df <- merged %>%
    group_by(exp_line) %>%
    nest() %>%
    mutate(
        model = map(data, ~ glm(fixed ~ init_rel_fit, data = ., family = binomial)),
        preds = map2(data, model, ~ mutate(.x, predicted_prob = predict(.y, newdata = .x, type = "response")))
    ) %>%
    unnest(preds)


fig <- ggplot(models_df, aes(x = init_rel_fit, y = predicted_prob, color = exp_line)) +
    geom_line(linewidth = 2) +
    geom_point(
        aes(y = as.numeric(fixed) + (as.numeric(factor(exp_line)) - 2.5) * 0.01),
        size = 3, alpha = 0.6
    ) +  # shift each lineage slightly in y
    labs(
        title = "",
        x = "Initial relative fitness",
        y = "Probability of fixation",
        color = "Population"
    ) +
    custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, "probability_of_fixation.pdf", height = 14, width = 14)

```

```{r logistic regression model assessment}

### model assessment
models_df <- merged %>%
    group_by(exp_line) %>%
    nest() %>%
    mutate(
        model = map(data, ~ glm(fixed ~ init_rel_fit, data = ., family = binomial)),
        preds = map2(data, model, ~ mutate(.x, predicted_prob = predict(.y, newdata = .x, type = "response"))),
        # goodness-of-fit
        logLik = map_dbl(model, logLik),
        AIC = map_dbl(model, AIC),
        pseudoR2 = map(model, ~ pscl::pR2(.x)),
        auc = map2_dbl(data, model, ~ {
        roc_obj <- pROC::roc(.x$fixed, predict(.y, newdata = .x, type = "response"))
        pROC::auc(roc_obj)
        })
    )

models_df %>%
    mutate(pseudoR2 = map(pseudoR2, tibble::as_tibble_row)) %>%
    unnest(pseudoR2)


```

```{r init_rel_fitness_ratio_same_adaptive_mutation}


for (i in 1:nrow(df1)) {
    df1$relative_order[i] <- nrow(df1[df1$exp_line == df1$exp_line[i] & df1$fixation < df1$fixation[i],])
}


dff <- data.frame()
for (host in c("MT-2", "MT-4")){
    df1_subset <- df1[df1$host == host,]
    for (mut_info in unique(df1_subset$mut_info)) {
        if (nrow(df1_subset[df1_subset$mut_info == mut_info,]) == 1) {
            df1_subset <- df1_subset[df1_subset$mut_info != mut_info,]
            print(mut_info)
        }
    }
    for (mut_info in unique(df1_subset$mut_info)) {
        early_line1 <- as.character(df1_subset$exp_line[df1_subset$mut_info == mut_info][which.min(df1_subset$fixation[df1_subset$mut_info == mut_info])])
        late_line1 <- as.character(df1_subset$exp_line[df1_subset$mut_info == mut_info][which.max(df1_subset$fixation[df1_subset$mut_info == mut_info])])
        delta_time <- abs(diff(df1_subset$fixation[df1_subset$mut_info == mut_info]))
        initial_rel_ratio1 <- df1_subset$init_rel_fit[df1_subset$mut_info == mut_info & df1_subset$exp_line == early_line1] / df1_subset$init_rel_fit[df1_subset$mut_info == mut_info & df1_subset$exp_line == late_line1]
        time_to_fixation1 <- df1_subset$time_to_fixation[df1_subset$mut_info == mut_info & df1_subset$exp_line == late_line1] - df1_subset$time_to_fixation[df1_subset$mut_info == mut_info & df1_subset$exp_line == early_line1]
        early_line2 <- as.character(df1_subset$exp_line[df1_subset$mut_info == mut_info][which.min(df1_subset$relative_order[df1_subset$mut_info == mut_info])])
        late_line2 <- as.character(df1_subset$exp_line[df1_subset$mut_info == mut_info][which.max(df1_subset$relative_order[df1_subset$mut_info == mut_info])])
        delta_order <- abs(diff(df1_subset$relative_order[df1_subset$mut_info == mut_info]))
        initial_rel_ratio2 <- df1_subset$init_rel_fit[df1_subset$mut_info == mut_info & df1_subset$exp_line == early_line2] / df1_subset$init_rel_fit[df1_subset$mut_info == mut_info & df1_subset$exp_line == late_line2]
        time_to_fixation2 <- df1_subset$time_to_fixation[df1_subset$mut_info == mut_info & df1_subset$exp_line == late_line2] - df1_subset$time_to_fixation[df1_subset$mut_info == mut_info & df1_subset$exp_line == early_line2]
        dff <- rbind(dff, c(host, mut_info, delta_time, initial_rel_ratio1, time_to_fixation1, delta_order, initial_rel_ratio2, time_to_fixation2))
    }
}

colnames(dff) <- c("host", "mut_info", "delta_f", "initial_rel_ratio_f", "time_to_fixation_f", "delta_o", "initial_rel_ratio_o", "time_to_fixation_o")
dff %<>% mutate_at(c("delta_f", "initial_rel_ratio_f", "time_to_fixation_f", "delta_o", "initial_rel_ratio_o", "time_to_fixation_o"), as.numeric)

# from vf_trajectories_fixed.Rmd script
all <- c(triples, quad)

dff$mut_info <- factor(dff$mut_info, levels = names(all))
dff$color <- all[as.character(dff$mut_info)]


fig <- dff %>% ggplot(aes(x = "", y = log2(initial_rel_ratio_o))) +
    geom_boxplot(outliers = FALSE, linewidth = 2) +
    geom_jitter(aes(color = mut_info, shape = host), width = 0.2, size = 5) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
    scale_color_manual(values = all) +
    labs(
        title = "",
        x = "",
        y = "log2 (initial relative fitness ratio\nfor early vs late replicate)",
        color = "Adaptive mutation",
        shape = "Host"
    ) +
    custom_plot_theme(application = "publication")


# save figure
custom_plot_save(fig, "init_rel_fitness_ratio_same_adaptive_mutation.pdf", height = 14, width = 14)

# in-text statistics
wilcox.test(log2(dff$initial_rel_ratio_o), mu = 0)
median_ratio <- median(dff$initial_rel_ratio_o)



```


####!!!!
Extra analysis
####!!!!

```{r fixation probability for mutations fixed only in one line}

df2 <- merged[merged$Occurrence %in% c("1 out of 4"),]


for (i in 1:nrow(df2)) {
    df2$relative_order[i] <- nrow(df2[df2$exp_line == df2$exp_line[i] & df2$fixation < df2$fixation[i],])
}

fig <- df2 %>%
    ggplot(aes(x = relative_order, y = log2(init_rel_fit), color = exp_line)) +
    geom_point(, size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(title = "", y = "log2(initial relative fitness)\n", x = "Relative order \n (single-occurrence)", color = "Lineage", linetype = "Lineage") +
    scale_color_manual(values = line_col_palette) +
    scale_linetype_manual(values = c(1,2,3,4)) +
    scale_x_continuous(breaks = seq(0,90, 15))+
    custom_plot_theme(application = "publication") 


# save figure
custom_plot_save(fig, "single_max_fold_inc_vs_relative_order.pdf", height = 14, width = 14)

# Fit a linear model for each experimental line
models <- df2 %>%
    group_by(exp_line) %>%
    do(tidy(lm(log2(init_rel_fit) ~ relative_order, data = .)))

# View the p-values
models %>%
    filter(term == "relative_order") %>%
    select(exp_line, estimate, std.error, statistic, p.value)



```

```{r}

mean(df2$init_rel_fit)
mean(df1$init_rel_fit)
mean(merged$init_rel_fit[merged$fixed == FALSE])

wilcox.test(df1$init_rel_fit[df1$exp_line == "MT-2_1"], df2$init_rel_fit[df2$exp_line == "MT-2_1"])
```