---
title:  
    "McDonald-Kreitman neutrality test"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---

```{r}

# set the wd paths
if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}


# loading libraries
# library("ggplot2")
# library("ggpubr")
# library("plotly")
# library("ggvenn")
# library("hrbrthemes")
# library("DT")
library("dplyr")
library("tidyr")
# library("Biostrings")
library("stringr")
library("magrittr")
# library("rstatix")

```

```{r read-in variant data}

# load data
source(paste0(wd, "src/analysis/decelerating-adaptation/readin_data.R"))

```

```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```




```{r McDonald-Kreitman test}



df <- data.frame()
genes <- c("gag", "pol","env", "nef")

psg <- 130
expline <- ""
for (expline in exp_line_factor){
    print(expline)
    for (psg in seq(10,700,10)){
        print(psg)
        
        variants_expiii_subset <- variants_expiii %>% 
            mutate(passage = as.numeric(as.character(passage))) %>%
            filter(exp_line == expline & passage == psg & feature %in% genes)


        P_S <- nrow(variants_expiii_subset %>% filter(effect_simplified == "S" & allele_freq >= 0.05 & allele_freq < 0.99) %>% distinct(mut_info))
        D_S <- nrow(variants_expiii_subset %>% filter(effect_simplified == "S" & allele_freq >= 0.99) %>% distinct(mut_info))

        P_N <- nrow(variants_expiii_subset %>% filter(effect_simplified == "N" & allele_freq >= 0.05 & allele_freq < 0.99) %>% distinct(mut_info))
        D_N <- nrow(variants_expiii_subset %>% filter(effect_simplified == "N" & allele_freq >= 0.99) %>% distinct(mut_info))

        # Calculate Neutrality Index
        NI <- (P_N / P_S) / (D_N / D_S)

        # Create a contingency table
        MK_table <- matrix(c(D_N, D_S, P_N, P_S), nrow = 2, byrow = TRUE,
                        dimnames = list(c("Fixed", "Polymorphic"),
                                        c("Nonsynonymous", "Synonymous")))

        # Perform Fisher's Exact Test
        MK_result <- fisher.test(MK_table)
        MK_result$p.value
        df <- rbind(df, c(expline, psg, P_S, D_S, P_N, D_N, NI, MK_result$p.value))
    
        
    }
}

colnames(df) <- c("exp_line", "passage", "P_S", "D_S", "P_N", "D_N", "NI", "p_value")
df %<>% mutate_at(2:8, as.numeric)
df$NI <- as.numeric(as.character(df$NI))
df$passage <- as.integer(as.character(df$passage))
str(df)

ggplot(df, aes(x=passage, y=(D_N/D_S)/(P_N/P_S), color=exp_line)) +
    geom_line() +
    geom_point() +
    scale_y_log10() +
    labs(title="McDonald-Kreitman Neutrality Index over Passages",
         x="Passage",
         y="Neutrality Index (NI)") +
    theme_minimal() +
    theme(legend.title=element_blank())

df[df$passage == 690,]

```