---
title:  
    "Mutable position"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(magrittr)



```


```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```


# Accumulation

```{r category thresholds}

# set parameters
category <- "Minority"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```

```{r in-text numbers}

# get numbers for in-text reporting
variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & allele_freq < max_threshold) #& mut_type == "P"




variants_expiii_subset_mt2 <- variants_expiii_subset[variants_expiii_subset$host_line == "MT2",]
variants_expiii_subset_mt4 <- variants_expiii_subset[variants_expiii_subset$host_line == "MT4",]
b_mt2 <- length(unique(variants_expiii_subset_mt2$mut_info))
b_mt4 <- length(unique(variants_expiii_subset_mt4$mut_info))
b_mt2/b_mt4



```


```{r with all group}


# # all group
# variants_expiii_subset2 <- variants_expiii_subset
# variants_expiii_subset2$exp_line <- "All"

# variants_expiii_subset_pooled <- rbind(variants_expiii_subset, variants_expiii_subset2)


# variants_expiii_subset_pooled$passage <- as.integer(as.character(variants_expiii_subset_pooled$passage))


# counts <- data.frame()
# for (psg in seq(10,end_psg,10)){
#     d <- variants_expiii_subset_pooled[variants_expiii_subset_pooled$passage <= psg,]
#     dd <- d %>% dplyr::select(genomic_pos, exp_line) %>% distinct() %>% group_by(exp_line) %>% summarise(count = n())
#     dd$passage <- psg
#     counts <- rbind(counts, dd)
# }

# fig <- counts %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
#         geom_line(linewidth=2) +
#         labs(x="\nTransfer", y= "Position count\n", color = "Lineage", title = paste0("Cumulative Number of Uniquely Mutated Positions (", category,")"))+
#         scale_x_continuous(breaks = seq(0,end_psg,50)) +
#         scale_y_continuous(limits = c(0,max(counts$count)+20),breaks = seq(0,max(counts$count)+20,200)) +
#         scale_color_manual(labels = c(exp_line_factor, "All"), values = c(line_col_palette, All = "black")) +
#         custom_plot_theme(application = "publication")


```




```{r visualization1: cumulative plot of unique mutations}



df <- data.frame()
variants_expiii_subset <- variants_expiii %>% mutate(passage = as.numeric(as.character(passage)))

for (exp_line in exp_line_factor){
    for (passage in seq(10,end_psg, 10)){
        count <- length(unique(variants_expiii_subset$genomic_pos[variants_expiii_subset$allele_freq >= 0.05 & variants_expiii_subset$passage <= passage & variants_expiii_subset$exp_line == exp_line & variants_expiii_subset$mut_type == "P"]))
        df <- rbind(df, c(exp_line, passage, count))
    }
}

df %<>% set_colnames(c("exp_line", "passage", "count")) %>%
            mutate_at(2:3, as.numeric)

# visualize 

fig <- df %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="Transfer", y= "Cumulative number of mutated positions (> 0.05)", color = "Population", title = paste0("Number of unique point mutations (",category,")"))+
        geom_hline(yintercept = mean(df$count[df$passage == 500 & df$exp_line %in% c("MT-2_1","MT-2_2")], na.rm = TRUE), linetype = "dashed", linewidth = 2, color = "#ff8b08") +
        geom_hline(yintercept = mean(df$count[df$passage == 500 & df$exp_line %in% c("MT-4_1","MT-4_2")], na.rm = TRUE), linetype = "dashed", linewidth = 2, color = "#00bbff") +
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(df$count)+20),breaks = seq(0,max(df$count)+20,100)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0(tolower(category), "_cumulative_unique_mutations.pdf"), height = 14, width = 14)

```


```{r visualization2: Unique mutation appearance plot}

# prepare data for visualization
variants_expiii_subset <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold)



for (line in exp_line_factor){
    variants_expiii_subset2 <- variants_expiii_subset[variants_expiii_subset$exp_line == line,]
    for (mut in unique(variants_expiii_subset2$mut_info)){
        variants_expiii_subset$appearance[variants_expiii_subset$mut_info == mut & variants_expiii_subset$exp_line == line] <- min(as.numeric(as.character(variants_expiii_subset2$passage[variants_expiii_subset2$mut_info == mut])))
    }
}

variants_expiii_subset$appearance <- factor(variants_expiii_subset$appearance, levels = seq(10,end_psg,10))

variants_expiii_subset2 <- variants_expiii_subset
variants_expiii_subset2$exp_line <- "All"
variants_expiii_subset <- rbind(variants_expiii_subset, variants_expiii_subset2)

# prepare data for visualization
counts <- variants_expiii_subset %>%
            select(exp_line, appearance, mut_info) %>%
            distinct() %>%
            group_by(exp_line, appearance, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(appearance = as.numeric(as.character(appearance))) %>%
            mutate_at(3, as.numeric)


# visualize 

low<-findInterval(max(counts$mut_count),c(5,10,20,50,100))
step <- c(5,10,20,50,100)[low - 1]

fig <- counts %>%  ggplot(aes(x=appearance, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="Transfer", y= "Mutation Count", color = "Population", title = paste0("Appearance of Unique ", category, " Mutations"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+step),breaks = seq(0,max(counts$mut_count)+step,step)) +
        scale_color_manual(labels = c(exp_line_factor, "All"), values = c(line_col_palette, "black")) +
        custom_plot_theme()





# save figure
custom_plot_save(fig, paste0(tolower(category), "_appearance.pdf"), height = 14, width = 14)


```


```{r visualization3: disappearance}


passages <- seq(10,500, 10)
diff_df <- data.frame()



for (i in 1:49){
    for (exp_line in exp_line_factor){
        prev_in <- passages[i]
        pres_in <- passages[i+1]

        prev <- variants_expiii$mut_info[variants_expiii$exp_line == exp_line & variants_expiii$passage == prev_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold]

        pres <- variants_expiii$mut_info[variants_expiii$exp_line == exp_line & variants_expiii$passage == pres_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold]

        addition <- length(setdiff(pres, prev))
        removal <- length(setdiff(prev,pres))

        diff_df <- rbind(diff_df, c(exp_line, passages[i+1], addition, removal))

    }
    
}

diff_df %<>% set_colnames(c("exp_line", "passage", "addition", "removal")) %>%
            arrange(exp_line) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1", "MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,5), as.factor) %>%
            mutate_at(2:4, as.numeric)

# prepare the data for statistical test
counts <- diff_df %>%
            group_by(passage, host_line) %>%
            summarize(addition_mean = mean(addition),
                    removal_mean = mean(removal), .groups = 'drop')


# store the statistical test result
t_test_result_removal <- t.test(counts$removal_mean[counts$host_line == "MT2"], counts$removal_mean[counts$host_line == "MT4"], paired = TRUE, alternative = "two.sided")

# visualize using plotly
fig <- diff_df %>%  ggplot(aes(x=passage, y = removal, color = exp_line)) +
        geom_line(linewidth=1, alpha = 0.5) +
        geom_smooth(se = F) +
        labs(x="Transfer", y= "Minority mutation disappearance", color = "Population", title = paste0(category, " Mutations Disappearance"))+
        scale_x_continuous(breaks = seq(0,500,50)) +
        scale_y_continuous(limits = c(max(0,min(diff_df$removal)-21),max(diff_df$removal)+16),breaks = seq(max(0,min(diff_df$removal)-21),max(diff_df$removal)+16,20)) +
        scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
        custom_plot_theme(application = "publication")




# save figure
custom_plot_save(fig, paste0(tolower(category),"_disappearance.pdf"), height = 14, width = 14)
```



