---
title:  
    "Fixation dynamics"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(magrittr)
library(rstatix)
library(effsize)
library(purrr)
library(ggpubr)


```


```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```



# Accumulation

```{r category thresholds}

# set parameters
category <- "Fixed"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```




```{r calculate time to fixation}

# # record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
# t_2_f <- data.frame()


# for (exp_line in exp_line_factor){
#     variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
#     fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$passage == end_psg])
#     for (mut in fixed_muts){
#         variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$mut_info == mut,]
#         fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
#         appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(variants_expiii_sub2$passage[(variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.01)]))))) + 10
#         disappearance_vec <- as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq < 0.5]))
#         disappearance <- ifelse(length(disappearance_vec[disappearance_vec > fixation]) == 0, NA, min(disappearance_vec[disappearance_vec > fixation]))
#         translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
#         t_2_f <- rbind(t_2_f, c(exp_line, mut, translational_impact, appearance, fixation, disappearance, fixation-appearance))
#     }
# }


# # set column names and right data types
# t_2_f %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "disappearance","time_to_fixation")) %>% 
#         mutate_at(c(4,5,7), as.integer) %>%
#         mutate(exp_line = factor(exp_line, levels = exp_line_factor),
#         host_line = if_else(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4"),
#         effect_simplified = factor(effect_simplified, levels = translational_impacts))

# t_2_f[!is.na(t_2_f$disappearance),]
# aa <- t_2_f$mut_info[!is.na(t_2_f$disappearance)]

# # average time to fixation for fixated mutations based on how many times they are repeated

# fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])



# fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
#     "3" = fix_count_table[fix_count_table==3],
#     "2" = fix_count_table[fix_count_table==2],
#     "1" = fix_count_table[fix_count_table==1])

# sum(fix_count_table_list[[4]]) + sum(fix_count_table_list[[3]]) + sum(fix_count_table_list[[2]]) + sum(fix_count_table_list[[1]])




# t_2_f$Occurrence <- NA
# t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["1"]])] <- "1 out of 4"
# t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["2"]])] <- "2 out of 4"
# t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["3"]])] <- "3 out of 4"
# t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["4"]])] <- "4 out of 4"
# t_2_f <- t_2_f[!is.na(t_2_f$Occurrence),]
# t_2_f$Occurrence <- factor(t_2_f$Occurrence, levels = c("1 out of 4", "2 out of 4", "3 out of 4", "4 out of 4"))

# saveRDS(t_2_f, paste0(wd, "results/tables/time_to_fixation.Rds"))

t_2_f <- readRDS(paste0(wd, "results/tables/time_to_fixation.Rds"))

```


```{r visualization1: time-to-fixation}
# density of time_to_fixation distributions
fig <- t_2_f %>% ggplot(aes(x = time_to_fixation, color = exp_line)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = exp_line_factor, values = line_col_palette)

fig



# perform pairwise wilcox-test between translation impact groups per exp line

pwc <- t_2_f %>%
    group_by(exp_line) %>%
    pairwise_wilcox_test(
        time_to_fixation ~ effect_simplified,
        p.adjust.method = "none",
        detailed = TRUE
    )


# Visualization: box plots with p-values

low<-findInterval(max(t_2_f$time_to_fixation),c(5,10,20,50,100))
step <- c(5,10,20,50,100)[low - 1]

#Add x position
pwc <- pwc %>% add_xy_position(x = "effect_simplified", step.increase = 1)
# assign new y.positions 
set.seed(1)
pwc$y.position <- sample(seq(500,590,7), replace = F, size = 12)
# make the plot
fig2 <- ggboxplot(t_2_f, x = "effect_simplified", y = "time_to_fixation", color = "exp_line") +
    geom_jitter(aes(color = exp_line), width = 0.2, size = 2, alpha = 0.9) +
    facet_wrap(~exp_line, ncol = 2) +
    labs(x = "Translational Impact", y = "Time to Fixation", color = "Virus Line")+
    scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
    scale_y_continuous(breaks = seq(0,max(t_2_f$time_to_fixation)+step,step), limit = c(0,600)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj", size = 8) +
    custom_plot_theme(application = "publication") +
    theme(axis.text.x = element_text(angle = 0), legend.position = "none")


fig2

# save figure
custom_plot_save(fig2, "time_to_fixation_significance_boxplot_per_line.pdf", height = 14, width = 14)


# # perform pairwise wilcox-test between exp line groups per translation impact
# pwc <- t_2_f %>%
#     group_by(effect_simplified) %>%
#     pairwise_wilcox_test(time_to_fixation ~ exp_line, p.adjust.method = "BH",pool.sd=FALSE, detailed = T)

# #Add x position
# pwc <- pwc %>% add_xy_position(x = "exp_line", step.increase = 1)
# # assign new y.positions 
# pwc$y.position <- sample(seq(500,750,10), replace = F, size = 18)
# # make the plot
# fig3 <- ggboxplot(t_2_f, x = "exp_line", y = "time_to_fixation", color = "exp_line") +
#     facet_wrap(~effect_simplified, ncol = 3) +
#     labs(x = "Virus Line", y = "Time to Fixation", color = "Virus Line")+
#     scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
#     scale_y_continuous(breaks = seq(0,max(t_2_f$time_to_fixation)+step,step)) +
#     stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj") 

# fig4

# perform pairwise wilcox-test between host line groups per translation impact
pwc <- t_2_f %>%
    # filter(mut_info %in% shared) %>%
    # filter(fixation >= 300) %>%
    group_by(effect_simplified) %>%
    pairwise_wilcox_test(time_to_fixation ~ host_line, p.adjust.method = "BH",pool.sd=FALSE, detailed = T)

#Add x position
pwc <- pwc %>% add_xy_position(x = "host_line", step.increase = 1)
# assign new y.positions 
pwc$y.position <- sample(seq(500,650,10), replace = F, size = 3)

# make the plot
fig4 <- ggboxplot(t_2_f, x = "host_line", y = "time_to_fixation", color = "host_line", outliers = FALSE ) +
    geom_jitter(aes(color = host_line), width = 0.2, size = 2, alpha = 0.9) +
    facet_wrap(~effect_simplified, ncol = 3) +
    labs(x = "Host", y = "Time to fixation", color = "Population")+
    scale_color_manual(labels = c("MT-2", "MT-4"), values = c("#ff8b08", "#00bbff")) +
    scale_y_continuous(breaks = seq(0,max(t_2_f$time_to_fixation)+step,step), limit = c(0,600)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj", size = 8) +
    custom_plot_theme(application = "publication") +
    theme(legend.position = "none")

fig4


# save figure
custom_plot_save(fig4, "time_to_fixation_per_translation_impact.pdf", height = 14, width = 14)

# get inline variables
df %>% group_by(host_line) %>% summarize(Mean = mean(time_to_fixation, na.rm=TRUE), n = n())

wilcox.test(df$time_to_fixation[df$host_line == "MT-2"], df$time_to_fixation[df$host_line == "MT-4"])

```




```{r calculate fixation time based on number of recurrence}

comparisons <- list(
  c("4 out of 4", "3 out of 4"),
  c("4 out of 4", "2 out of 4"),
  c("4 out of 4", "1 out of 4"),
  c("3 out of 4", "2 out of 4"),
  c("3 out of 4", "1 out of 4"),
  c("2 out of 4", "1 out of 4")
)


my_col_pal <- c(alpha("grey"), "green", "blue", "red")

```

```{r average time to fixation of neutral sequence simulations}
bottleneck_freq <- 2
sim_data <- readRDS(paste0(wd, "results/tables/neutral-seq-sim/", bottleneck_freq, "_sim_freq_all.Rds"))

sim_data$mut_info <- paste0(sim_data$pos, "_", sim_data$base_allele, "_", sim_data$alt_allele)

## Method 2
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
t_2_f_sim <- data.frame()


for (exp_line in exp_line_factor){
    sim_data_sub <- sim_data[sim_data$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(sim_data_sub$mut_info[sim_data_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        sim_data_sub2 <- sim_data_sub[sim_data_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(sim_data_sub$passage[sim_data_sub$mut_info == mut & sim_data_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(sim_data_sub2$passage[(sim_data_sub2$mut_info == mut & sim_data_sub2$allele_freq >= 0.01)]))))) + 10
        t_2_f_sim <- rbind(t_2_f_sim, c(exp_line, mut, appearance, fixation, fixation-appearance))
    }
}


# set column names and right data types
t_2_f_sim %<>% set_colnames(c("exp_line", "mut_info", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(3:5, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor))

median(t_2_f_sim$time_to_fixation)

```

```{r visualization of time to fixation based on number of occurrence}

# Create the plot
fig <- ggplot(t_2_f, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7, outliers = FALSE) +
    geom_jitter(aes(color = Occurrence), width = 0.2, size = 2, alpha = 0.9) +
    geom_hline(yintercept = median(t_2_f_sim$time_to_fixation), linetype = "dashed", color = "black", size = 1) +
    geom_hline(yintercept = median(t_2_f$time_to_fixation), linetype = "solid", color = "black", size = 1) +
    stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj", size = 12) +
    scale_y_continuous(limits = c(0, 800), breaks = seq(0, 500, by = 50)) +
    scale_fill_manual(values = my_col_pal) +
    scale_color_manual(values = my_col_pal) +
    labs(fill = "Fixed in", x= "Occurrence", y = "Time to fixation", title = "") + # Label for the legend
    custom_plot_theme() +
    theme(axis.title.x = element_blank(), axis.text.x = element_blank()) +
    guides(color = "none")


# save figure
custom_plot_save(fig, "time-to-fixation-based-on-recurrence.pdf", height = 14, width = 14)

```

####!!!!




####!!!!
Extra analysis
####!!!!

```{r distribution of rapidly fixating mutations over time}



t_2_f <- t_2_f %>%
    group_by(exp_line) %>%
    mutate(p10 = quantile(time_to_fixation, 0.10)) %>%
    mutate(p90 = quantile(time_to_fixation, 0.90)) %>%
    ungroup()

labels_with_p10 <- with(t_2_f, setNames(
    paste0(exp_line, "(", round(p10, 1), ")"),
    exp_line
))

t_2_f %<>% mutate(labels = labels_with_p10)


bins <- seq(0,400, 100)

t_2_f_summary <- t_2_f[t_2_f$time_to_fixation < t_2_f$p10,] %>%
        mutate(bin = cut(fixation, breaks = bins, right = FALSE)) %>%
        group_by(exp_line,labels, effect_simplified) %>%
        count(bin, .drop = FALSE)

t_2_f_summary <- t_2_f_summary[!is.na(t_2_f_summary$bin),]



fig <- ggplot(t_2_f_summary, aes(x = effect_simplified, y = n, fill = bin)) +
    facet_wrap(~labels, ncol = 2, strip.position = "top") +
    geom_bar(stat = "identity", position = "dodge") +
    scale_y_continuous(limits = c(0, 8), breaks = seq(0, 12, by = 2)) +
    labs(title = "", x = "\nTranslational impact", y = "Count of rapidly-fixing variants \n", fill = "Fixation period") +
    custom_plot_theme() +
    theme(axis.text.x = element_text(angle = 0))

fig

# save figure
custom_plot_save(fig, "rapidly_fixating_variants_over_time.pdf", height = 14, width = 14)
```

