---
title:  
    "variant freq. trajectories of certain cases of EXPIII"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# loading libraries
library(dplyr)
library(ggplot2)
library(magrittr)
library(stringr)
library(RColorBrewer)
library(ggrepel)


```



```{r set paths and load data}

# Set working directory
if (file.exists("/home/amovas/")) {
    # Running on HPC
    message("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    # Running locally
    message("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# Load project-specific functions and data readers
source(file.path(wd, "src/analysis/decelerating-adaptation/readin_data.R"))
source(file.path(wd, "src/analysis/decelerating-adaptation/plot_custom.R"))

```




```{r arbitrary cases}

cases <- c("G5671A", "T9528G", "G618A", "TGTTTAATAGTACTTG7383T")
case <- cases[4]


fig <- variants_expiii[variants_expiii$mut_info %in% case,] %>% ggplot(aes(x = passage, y = log10(allele_freq), group = mut_info)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_alpha_manual(values = c(0.1,1)) +
    scale_y_continuous(breaks = c(0, -1, -2, -3), labels = c("1", "0.1", "0.01", "0.001")) +
    labs(title = paste0(case, "\n"), y = "Frequency \n", x = "\n Transfer") +
    # scale_color_manual(values = my_col_pal) +
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")

fig

```



```{r linkage case}

variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])
variants_expiii_subset <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,]


variants_expiii_subset_mt21 <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts & variants_expiii_subset$exp_line == "MT-2_1",]



intersect(variants_expiii_subset_mt21$variant_info[variants_expiii_subset_mt21$passage == 270 & variants_expiii_subset_mt21$allele_freq >= 0.125],
variants_expiii_subset_mt21$variant_info[variants_expiii_subset_mt21$passage == 280 & variants_expiii_subset_mt21$allele_freq <= 0.14 ])


case <- c("G972A" , "G973A" , "G974C")

variants_expiii_subset_mt21$tracking_group <- "No"
variants_expiii_subset_mt21$tracking_group[variants_expiii_subset_mt21$mut_info %in% case] <- "Yes"

variants_expiii_subset_mt21[variants_expiii_subset_mt21$tracking_group == "Yes",]

variants_expiii_subset_mt21 <- variants_expiii_subset_mt21 %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info))



variants_expiii_subset_mt21$passage <- as.numeric(as.character(variants_expiii_subset_mt21$passage))


s <- variants_expiii_subset %>% filter(mut_info_line %in% fixed_muts) %>% dplyr::select(exp_line, mut_info) %>% distinct()




variants_expiii_subset_mt21$color <- "grey"# line_col_palette[1]
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[1]] <- "#7C8F00"
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[2]] <- "#00588F"
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[3]] <- "#8F0002"

color_mapping <- setNames(variants_expiii_subset_mt21$color, variants_expiii_subset_mt21$mut_info)



fig <- variants_expiii_subset_mt21[variants_expiii_subset_mt21$mut_info_line %in% fixed_muts,] %>%
    ggplot(aes(x = passage, y = allele_freq, group = mut_info, color = mut_info, alpha = tracking_group, size = tracking_group)) +
    geom_line() +
    facet_grid(rows = vars(exp_line), switch = "y") +
    scale_x_continuous(breaks = seq(0, 500, by = 50)) +
    scale_alpha_manual(values = c(0.2,1)) +
    scale_size_manual(values = c(1,1.5)) +
    labs(title = "Linked variants", y = "Frequency", x = "Transfer") +
    scale_color_manual(values = color_mapping, name = "Variant") +
    custom_plot_theme(application = "publication") + 
    theme(strip.text.y = element_text(size = 35, angle=0),
        legend.position = "none")


fig <- fig + geom_text_repel(
    data = . %>% filter(tracking_group == "Yes" & passage == 180),
    aes(label = mut_info, y = c(0.08, 0.06, 0.17), x = c(330, 330, 180)), # Adjust y position to avoid overlap
    size = 10,       # Adjust label text size
    color = c("#7C8F00", "#00588F", "#8F0002") # Optional: set label color
)



# save figure
custom_plot_save(fig, "frequency_dynamics_linkage_cases.pdf", height = 14, width = 14)
```



```{r clonal interference case, results=TRUE}


# 566_G_A  678_G_A 7854_A_G 
case <- c("G566A")

variants_expiii$tracking_group <- "No"
variants_expiii$tracking_group[variants_expiii$mut_info %in% case] <- "Yes"
variants_expiii$linewidth[variants_expiii$tracking_group == "Yes"] <- 3
variants_expiii$linewidth[variants_expiii$tracking_group == "No"] <- 1
variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))

variants_expiii_subset$color_group <- as.character(variants_expiii_subset$exp_line)
variants_expiii_subset$color_group[variants_expiii_subset$mut_info == case[1]] <- "special_case_1"

color_palette <- c(
  "MT-2_1" = "grey", # unname(line_col_palette[1]),
  "MT-2_2" = "grey", # unname(line_col_palette[2]),
  "MT-4_1" = "grey", # unname(line_col_palette[3]),
  "MT-4_2" = "grey", # unname(line_col_palette[4]),
  "special_case_1" = brewer.pal(5, "Reds")[3]
)



fig <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,] %>% 
    ggplot(aes(x = passage, y = allele_freq, group = mut_info, color = color_group, alpha = tracking_group, linewidth = linewidth)) +
    geom_line() +
    facet_grid(rows = vars(exp_line), switch = "y") +
    scale_x_continuous(breaks = seq(0, 500, by = 50)) +
    scale_alpha_manual(values = c(0.1,1)) +
    labs(title = paste0(case, " variant"), y = "Frequency", x = "Transfer") + #title = paste0(case, "\n")
    scale_color_manual(values = color_palette) +
    scale_linewidth(range = c(1, 3)) +
    custom_plot_theme(application = "publication") +
    theme(strip.text.y = element_text(size = 35, angle=0),
        legend.position="none")

fig


# save figure
custom_plot_save(fig, paste0("frequency_dynamics_",case, ".pdf"), height = 14, width = 14)

# average time to fixation
mean(t_2_f$time_to_fixation)
mean(t_2_f$time_to_fixation[t_2_f$mut_info == case])
t.test(t_2_f$time_to_fixation[t_2_f$mut_info != case], t_2_f$time_to_fixation[t_2_f$mut_info == case])

```


```{r draft cases}


variants_expiii_subset <- variants_expiii %>%
                                filter(exp_line == "MT-2_1" & allele_freq >= 0.01) %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))

muts <- unique(variants_expiii_subset$mut_info)
doubled <- c()
for (mut in muts){
    freq1 <- variants_expiii_subset$allele_freq[variants_expiii_subset$mut_info == mut & variants_expiii_subset$passage == 270]
    freq2 <- variants_expiii_subset$allele_freq[variants_expiii_subset$mut_info == mut & variants_expiii_subset$passage == 310]
    # skip if missing or empty
    if (length(freq1) == 0 || length(freq2) == 0) next
    if (is.na(freq1) || is.na(freq2)) next
    
    if (freq2 >= 2 * freq1) {
        doubled <- append(doubled, mut)
    }
}

length(doubled)
fixed_muts <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$allele_freq >= 0.99 & variants_expiii_subset$passage == 500])
sum(doubled %in% fixed_muts)
doubled_fixed <- doubled[doubled %in% fixed_muts]

View(variants_expiii_subset[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 270,])

table(variants_expiii_subset$effect_simplified[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500])

doubled_fixed_syn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "S"]
doubled_fixed_nonsyn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "N"]
doubled_fixed_un <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "U"]

fix_count_table[names(fix_count_table) %in% doubled_fixed_syn]
fix_count_table[names(fix_count_table) %in% doubled_fixed_nonsyn]
fix_count_table[names(fix_count_table) %in% doubled_fixed_un]

fixed_syn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% fixed_muts & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "S"]
fixed_nonsyn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% fixed_muts & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "N"]
fixed_un <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% fixed_muts & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "U"]

table(fix_count_table[names(fix_count_table) %in% fixed_syn])
table(fix_count_table[names(fix_count_table) %in% fixed_nonsyn])
table(fix_count_table[names(fix_count_table) %in% fixed_un])
fisher.test(matrix(c(5, 2, 29, 7), byrow = TRUE, nrow = 2))
fisher.test(matrix(c(52, 18, 11, 4), byrow = TRUE, nrow = 2))

```


```{r draft cases mt-2_2}




variants_expiii_subset <- variants_expiii %>%
                                filter(exp_line == "MT-2_2" & allele_freq >= 0.01) %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))

muts <- unique(variants_expiii_subset$mut_info)
doubled <- c()
for (mut in muts){
    freq1 <- variants_expiii_subset$allele_freq[variants_expiii_subset$mut_info == mut & variants_expiii_subset$passage == 160]
    freq2 <- variants_expiii_subset$allele_freq[variants_expiii_subset$mut_info == mut & variants_expiii_subset$passage == 200]
    # skip if missing or empty
    if (length(freq1) == 0 || length(freq2) == 0) next
    if (is.na(freq1) || is.na(freq2)) next
    
    if (freq2 >= 2 * freq1) {
        doubled <- append(doubled, mut)
    }
}

length(doubled)
fixed_muts <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$allele_freq >= 0.99 & variants_expiii_subset$passage == 300])
sum(doubled %in% fixed_muts)
doubled_fixed <- doubled[doubled %in% fixed_muts]

View(variants_expiii_subset[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 270,])

table(variants_expiii_subset$effect_simplified[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500])

doubled_fixed_syn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "S"]
doubled_fixed_nonsyn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "N"]
doubled_fixed_un <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% doubled_fixed & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "U"]

fix_count_table[names(fix_count_table) %in% doubled_fixed_syn]
fix_count_table[names(fix_count_table) %in% doubled_fixed_nonsyn]
fix_count_table[names(fix_count_table) %in% doubled_fixed_un]

fixed_syn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% fixed_muts & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "S"]
fixed_nonsyn <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% fixed_muts & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "N"]
fixed_un <- variants_expiii_subset$mut_info[variants_expiii_subset$mut_info %in% fixed_muts & variants_expiii_subset$passage == 500 & variants_expiii_subset$effect_simplified == "U"]

table(fix_count_table[names(fix_count_table) %in% fixed_syn])
table(fix_count_table[names(fix_count_table) %in% fixed_nonsyn])
table(fix_count_table[names(fix_count_table) %in% fixed_un])
fisher.test(matrix(c(5, 2, 29, 7), byrow = TRUE, nrow = 2))
fisher.test(matrix(c(52, 18, 11, 4), byrow = TRUE, nrow = 2))

```