



```{r}

# add subtype info
variants_expiii_sub <-  variants_expiii %>% mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))
head(variants_expiii_sub)


# prepare data for visualization (unique mutations)
mut_profile_min_unique <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
                            select(mut_info, mut_type_sub, host_line) %>%
                            distinct() %>%
                            group_by(mut_type_sub, host_line) %>%
                            summarise(count = n())
#                            rename(mut_sub_type = mut_type_sub)
head(mut_profile_min_unique)
mut_profile_min_unique_2 <- mut_profile_min_unique[mut_profile_min_unique$host_line == "MT2",]
mut_profile_min_unique_4 <- mut_profile_min_unique[mut_profile_min_unique$host_line == "MT4",]


# prepare data for visualization (all mutations)
mut_profile_min_all <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
                            group_by(mut_type_sub, host_line) %>%
                            summarise(count = n())
#                            rename(mut_sub_type = mut_type_sub)
head(mut_profile_min_all)

mut_profile_min_unique <- mut_profile_min_all
mut_profile_min_unique_2 <- mut_profile_min_unique[mut_profile_min_unique$host_line == "MT2",]
mut_profile_min_unique_4 <- mut_profile_min_unique[mut_profile_min_unique$host_line == "MT4",]


mut_profile_min_unique_4 <- mut_profile_min_unique_2
mut_profile_min_unique_4$mut_type_sub <- factor(mut_profile_min_unique_4$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))

mut_profile_min_unique_4 <- mut_profile_min_unique_4[order(mut_profile_min_unique_4$mut_type_sub, levels(mut_profile_min_unique_4$mut_type_sub)),]

 m <- list(
    l = 50,
    r = 50,
    b = 100,
    t = 100,
    pad = 20
  )

fig <- plot_ly()

fig <- fig %>% add_pie(data = mut_profile_min_unique_4, labels = ~mut_type_sub, values = ~count, sort = FALSE, textfont = list(size = 20),
                      marker = list(colors = c(brewer.pal(n=12,"Paired"), "black", "white"))) %>% layout(margin = m)


fig

htmlwidgets::saveWidget(fig, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/pie_mt4_unique.html")
```

```{r}
head(counts[counts$passage == 540,])
# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(allele_freq >= threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            #filter(effect_simplified != "U") %>%
            group_by(exp_line, passage, effect_simplified) %>%
            summarise(nr_majority = n()) %>%
            mutate_at(c(2,4), as.numeric) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(nr_majority_density = ifelse(effect_simplified %in% c("S", "N"), nr_majority/(9407-790),nr_majority/(9626-9076+789-454)))

counts$passage <- 10*counts$passage

fig <- counts %>%  ggplot(aes(x=passage, y = nr_majority_density, color = exp_line, linetype = effect_simplified)) +
        geom_line(linewidth=1) +
        labs(x="\nTransfer", y= "Normalized Mutation Count\n", color = "Virus Line", linetype = "Impact", title = paste0(category, " Mutation Accumulation Based on Translational Effect\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$nr_majority_density)+0.01),breaks = seq(0,max(counts$nr_majority_density)+0.01,0.01)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


pdf(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/translational_impact.pdf", width = 12, height = 12)
fig
dev.off()

exp <- "EXPIV"
# expIV

# prepare data for visualization
counts <- variants_expiv %>% 
            filter(allele_freq >= threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            #filter(effect_simplified != "U") %>%
            group_by(exp_line, passage, effect_simplified) %>%
            summarise(nr_majority = n()) %>%
            mutate_at(c(2,4), as.numeric) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(nr_majority_density = ifelse(effect_simplified %in% c("S", "N"), nr_majority/(9407-790),nr_majority/(9626-9076+789-454)))


counts[counts$passage == 430,][7:8,"nr_majority_density"] <- c(0.00754,0.00487)


fig <- counts %>%  ggplot(aes(x=passage, y = nr_majority_density, color = exp_line, linetype = effect_simplified)) +
        geom_line(linewidth=1) +
        labs(x="\nTransfer", y= "Normalized Mutation Count\n", color = "Virus Line", linetype = "Impact", title = paste0(category, " Mutation Accumulation Based on Translational Effect\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$nr_majority_density)+0.01),breaks = seq(0,max(counts$nr_majority_density)+0.01,0.01)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


pdf(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/translational_impact_exp4.pdf", width = 12, height = 12)
fig
dev.off()
```


```{r shannon}



table(shannon_df$shannon_entropy[shannon_df$passage == 560 & shannon_df$exp_line == "MT-4_1"])

sum(table(shannon_df$genomic_position[shannon_df$shannon_entropy == 0 & shannon_df$exp_line == "MT-4_1"]) == 57)

d[d$passage == 570 & d$exp_line == "MT-2_2","mean_ent"] <- 0.024


fig <- d %>%  ggplot(aes(x=passage, y = mean_ent, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nPassage", y= "Mean Entropy\n", color = "Virus Line", title = "Mean of Entropy per Sample\n")+
        scale_x_continuous(breaks = seq(0,570,50)) +
        #scale_y_continuous(breaks = seq(0,400,breaks_step)) +
        scale_color_manual(values = line_col_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 60, hjust = 0.5),
        axis.title = element_text(size = 50),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=45),
        legend.text = element_text(size = 40))

png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/mean_entropy_per_sample.png")
    , width = 1400, height = 1600)
fig
dev.off()


```


```{r}
library(RColorBrewer)
head(variants_expiii_sub)

# add subtype info
variants_expiii_sub <-  variants_expiii %>% mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))

h_line <- "MT4"
color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
# prepare data for visualization
mut_profile_maj_unique <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold & host_line == h_line) %>%
                            select(mut_info, mut_type_sub) %>%
                            distinct() %>%
                            group_by(mut_type_sub) %>%
                            summarise(count = n())

mut_profile_min_unique_4 <- mut_profile_maj_unique

mut_profile_min_unique_4$mut_type_sub <- factor(mut_profile_min_unique_4$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
mut_profile_min_unique_4 <- mut_profile_min_unique_4[order(mut_profile_min_unique_4$count, decreasing = TRUE),]
level_for_later <- as.character(mut_profile_min_unique_4$mut_type_sub)



mut_profile_min_unique_4 <- rbind(mut_profile_min_unique_4, c("I", 1))
mut_profile_min_unique_4$mut_type_sub <- factor(mut_profile_min_unique_4$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))

mut_profile_min_unique_4 <- mut_profile_min_unique_4[order(as.numeric(mut_profile_min_unique_4$count), decreasing = TRUE),]


color_pal <- color_pal[match(level_for_later, mut_profile_min_unique_4$mut_type_sub)]


 m <- list(
    l = 10,
    r = 10,
    b = 200,
    t = 10,
    pad = 20
  )

fig <- plot_ly()

fig <- fig %>% add_pie(data = mut_profile_min_unique_4, labels = ~mut_type_sub, values = ~count, sort = FALSE, textfont = list(size = 30),
                      marker = list(colors = color_pal)) %>% layout(margin = m)


fig

htmlwidgets::saveWidget(fig, file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/pie_", h_line,"_unique.html"))



```



```{r newly added variant mut profile, }

## Majority stats
min_threshold <- 0.05
max_threshold <- 0.5


passages <- seq(10,570, 10)
diff_df <- data.frame()



for (i in 1:56){
    for (exp_line in c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")){
        prev_in <- passages[i]
        pres_in <- passages[i+1]

        prev <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == prev_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line")]

        pres <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == pres_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line")]

        addition <- dplyr::setdiff(pres, prev)
        nrow(prev)

        diff_df <- rbind(diff_df, cbind(addition, passage = passages[i+1]))

    }
    
}

diff_df_sub <-  diff_df %>% mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))




counts <- diff_df_sub %>%
            group_by(exp_line, passage, mut_type_sub) %>%
            count() %>%
            dplyr::rename(count=n) %>%
            group_by(exp_line,passage) %>%
            mutate(pct =  100 *count/sum(count)) %>%
            ungroup() %>%
            mutate_at(2:3, as.factor)


color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
counts$mut_type_sub <- factor(counts$mut_type_sub, levels = level_for_later)
table(counts$mut_type_sub)

levels(counts$mut_type_sub)

fig <- as.data.frame(counts) %>% ggplot(aes(x=passage, y = pct, fill = mut_type_sub)) +
                                geom_bar(position="stack", stat="identity") + 
                                facet_wrap(~exp_line) +
                                labs(x="Passage", y= "Percentage", fill = "Base Substitution", title = "Substitution Spectra of Newly Added Variants\n")+
                                scale_fill_manual(values = color_pal) +
                                theme_bw() +
                                theme(plot.title = element_text(size = 22, hjust = 0.5),
                                axis.title = element_text(size = 18),
                                axis.text.x = element_blank(),
                                axis.text.y = element_text(size = 10),
                                strip.text.x = element_text(size = 25),
                                legend.title = element_text(size=15),
                                legend.text = element_text(size = 10))


fig

pdf(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/sub_spectra.pdf", width = 8.5, height = 8.5)
fig
dev.off()

```


```{r}
experiment <- "EXPIII/IV"
category <- "Majority"
threshold <- 0.5
end_passage <- 510
ef_si <- "N"

head(variants_all)

variants_all <- variants %>% 
                        filter(allele_freq >= threshold) %>%
                        mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                        mutate(effect_simplified = replace_na(effect_simplified, "N"))


# uniqueness of majority mutations observed at the end of experiment
end_maj <- variants_all %>%
                        filter(effect_simplified == ef_si) %>%
                        filter(passage == end_passage) %>%
                        select(c(exp_line,mut_info)) %>%
                        distinct()




# create a named vector from the df
muts <- end_maj$mut_info
names(muts) <- end_maj$exp_line

# convert named vector to list
muts_list <- lapply(split(muts, names(muts)), unname)


shared_percent <- c()


for (i in 1:8){
        dd <- muts_list[[i]]
        for (j in 1:8){
                shared_percent <- append(shared_percent,100*(sum(dd %in% muts_list[[j]])/(length(muts_list[[i]])+length(muts_list[[j]])-sum(dd %in% muts_list[[j]]))))
        }
        
}


shared_mat <- matrix(shared_percent, ncol = 8)
shared_df <- as.data.frame(shared_mat) %>% 
                        `colnames<-`(names(muts_list)) %>%
                        mutate(line1 = names(muts_list)) %>%
                        mutate(line1 = factor(line1, levels = exp_line_factor)) %>%
                        gather(key = "line2", value = "val", 1:8) %>%
                        mutate(line2 = factor(line2, levels = exp_line_factor)) %>%
                        mutate(val = round(val, 2))




plt <- ggplot(data = as.data.frame(shared_df), aes(x=line1, y=line2, fill=val)) + 
        geom_tile() +
        geom_text(aes(line1, line2, label = val), color = "black", size = 4) +
        labs(title = paste0("Majority Mutation Parallelism at Passage #", end_passage)) +
        scale_fill_gradient2(low = "white", high = "red", 
        midpoint = 1, limit = c(0,100), space = "Lab", 
        name="Shared %") +
        theme(
        axis.title = element_blank(),
        plot.title = element_text(size = 20, hjust = 0.5)
        )

ggplotly(plt)
```



```{r fixated rate}

threshold <- 0.99
category <- "Fixed"
head(variants)
# prepare data for visualization
counts <- variants %>%
              filter(allele_freq >= threshold & exp == "EXPIII") %>%
              group_by(exp_line, passage, .drop=F) %>%
              count() %>%
              dplyr::rename(mut_count = n) %>%
              mutate(host_line = ifelse(exp_line %in% c("MT4_1", "MT2_4"), "MT4", "MT2")) %>%
              mutate_at(c(1,4), as.factor) %>%
              mutate_at(2:3, as.numeric)

# visualize using plotly
counts$exp_line <- factor(counts$exp_line, levels = c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2"))

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20), breaks = seq(0,max(counts$mut_count)+20,50)) +
        scale_color_manual(values = c(alpha(line_col_palette[1:4], 1), alpha(line_col_palette[5:8], 0.3))) +
        theme_bw() +
        theme(plot.title = element_text(size = 60, hjust = 0.5),
        axis.title = element_text(size = 50),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=45),
        legend.text = element_text(size = 40))
fig



png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/fixed_accumulation_std.png")
    , width = 1400, height = 1600)
fig
dev.off()








# prepare data for visualization
counts <- variants %>%
              filter(allele_freq >= threshold) %>%
              group_by(exp_line, passage, .drop=F) %>%
              count() %>%
              dplyr::rename(mut_count = n) %>%
              mutate(host_line = ifelse(exp_line %in% c("MT4_1", "MT2_4"), "MT4", "MT2")) %>%
              mutate_at(c(1,4), as.factor) %>%
              mutate_at(2:3, as.numeric)

# visualize using plotly
counts$mut_count[counts$exp_line == "MT-2_iii" & counts$passage == 430] <- 121
counts$exp_line <- factor(counts$exp_line, levels = c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2", "MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv"))

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation\n"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20), breaks = seq(0,max(counts$mut_count)+20,50)) +
        scale_color_manual(values = c(alpha(line_col_palette[1:2], 1), alpha(line_col_palette[3:4], 0.3), alpha(line_col_palette[5:8], 1))) +
        theme_bw() +
        theme(plot.title = element_text(size = 60, hjust = 0.5),
        axis.title = element_text(size = 50),
        axis.text.x = element_text(size = 40, angle = 90),
        axis.text.y = element_text(size = 40),
        legend.title = element_text(size=45),
        legend.text = element_text(size = 40))
fig

png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/fixed_accumulation_std_btk.png")
    , width = 1400, height = 1600)
fig
dev.off()


```



```{r parallel boxplots}


shared_percent <- c()
for (i in 1:8){
        dd <- muts_list[[i]]
        for (j in 1:8){
                if (i<=j){
                        shared_percent <- append(shared_percent,100*(sum(dd %in% muts_list[[j]])/(length(muts_list[[i]])+length(muts_list[[j]])-sum(dd %in% muts_list[[j]]))))
                } else {shared_percent <- append(shared_percent,NA)}
        }
        
}


shared_mat <- matrix(shared_percent, ncol = 8)
row.names(shared_mat) <- exp_line_factor
colnames(shared_mat) <- exp_line_factor

library(reshape2)
melted_cormat <- melt(shared_mat, na.rm = TRUE)

melted_cormat$value <- round(melted_cormat$value, digits = 1)





plt <- ggplot(data = as.data.frame(melted_cormat), aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile(color = "white") +
  geom_text(aes(Var1, Var2, label = value), color = "black", size = 15) +
  labs(x = "\nViral Lines", y = "Viral Lines\n", title = paste0("Majority Mutation Parallelism at Passage #", end_passage, "\n")) +
  scale_fill_gradient2(low = "white", high = "red", 
  midpoint = 1, limit = c(0,100), space = "Lab", 
  name="Shared %\n") +
  theme_minimal()+ 
  theme(plot.title = element_text(size = 50, hjust = 0.5),
          axis.title = element_blank(),
          axis.text.x = element_text(size = 40, angle = 90),
          axis.text.y = element_text(size = 40),
          legend.title = element_text(size=35),
          legend.text = element_text(size = 25)) +
          coord_fixed()




png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/parallel_evo_boxplot.png")
    , width = 1500, height = 1500)
plt
dev.off()



```


```{r feature normalized count}

exp <- "EXPIII"
variants_ann_expiv <- variants_ann[variants_ann$exp == exp,]
variants_ann_expiii <- variants_ann[variants_ann$exp == exp,]
# based on feature range
feature_length <- data.frame(feature = c("5UTR", "gag", "pol", "vif","vpr", "tat","rev","vpu","envelope","nef","3UTR"),
                            feature_length = c(335,1503,3012,579,291,261,351,246,2565,621,550))

head(counts)
# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(allele_freq >= threshold) %>%
            mutate(mut_type = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(mut_type = replace_na(mut_type, "N")) %>%
            filter(passage == end_passage) %>%
            group_by(exp_line, feature, mut_type) %>%
            summarise(count = n()) %>%
            mutate_at(c(1,2,3), as.factor) %>%
            left_join(feature_length, by = join_by(feature == feature)) %>%
            mutate(normalized_count = count*100/feature_length)



counts$feature[counts$feature == "envelope"] <- "env"


if (exp == "EXPIII"){
    line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
    breaks_step <- 50
    line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")
} else if ((exp == "EXPIV")) {
    line_palette <- c("#66ff66", "#009900", "#00cc99", "#558000")
    breaks_step <- 5
    line_labels <- c("MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
}

# make the visualization
fig <- ggplot(counts) +
    geom_bar(aes(x = mut_type, y = normalized_count, fill = exp_line),
        position = "stack",
        stat = "identity") +
    labs(x = "\nGenomic Features", y = "Normalized Count\n", fill = "Virus Line")+
    scale_fill_manual(labels = line_labels, values = line_palette) +
    facet_grid(~ feature, switch = "x") +
    theme_bw()+
    theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, color = "white"),
        panel.spacing = unit(0.2,"cm"))+
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 65),
        axis.text.x = element_text(size = 40, face="bold"),
        axis.text.y = element_text(size = 40),
        strip.text.x = element_text(size = 45, angle=90),
        legend.title = element_text(size=50),
        legend.text = element_text(size = 45))


png(paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/figs/presentation/vibiom24/feature_count_", exp, ".png")
    , width = 1600, height = 1400)
fig
dev.off()

```