---
title:  
    "Reproduce Bertel Figure 7"
date: 
    "Dec 30th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```



```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")

gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")

feature_factor <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "env", "tat2", "rev2", "nef", "3UTR", "3R")
feature_start <- c(454,551,635,790,2085,5041,5559,5830,5969,6061,6221,8369,8369,8787,9076,9529)
feature_end <- c(550,634,789,2292,5096,5619,5849,6044,6044,6306,8785,8414,8643,9407,9528,9625)


feature_df <- data.frame(feature = feature_factor,
                            start = feature_start,
                            end = feature_end,
                            length = feature_end - feature_start + 1)

feature_df <- rbind(feature_df, c("tat", sum(feature_df$length[feature_df$feature %in% c("tat1", "tat2")])))
feature_df$length <- as.numeric(feature_df$length)
feature_df <- rbind(feature_df, c("rev", sum(feature_df$length[feature_df$feature %in% c("rev1", "rev2")])))
feature_df$length <- as.numeric(feature_df$length)

feature_df <- feature_df[feature_df$feature %notin% c("tat1", "tat2", "rev1", "rev2"),]

feature_factor_new <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "env", "nef", "3UTR", "3R")



# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))




# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```






# Accumulation

```{r text numbers}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```

```{r}
# count parallel fix mut per gene



fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg], variants_expiii$feature[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

rows_above_1_per_column <- apply(fix_count_table, 2, function(x) sum(x > 1))



```


```{r}
# parallel fix mutation per site


ss <- rows_above_1_per_column / feature_df$length[order(feature_df$feature, names(rows_above_1_per_column))]

ss <- ss[ss != 0]
names(ss)[which(names(ss) == "envelope")] <- "env"

```


```{r}

possible_muts <- c(0.22*3, 0.78*3, 1*3)
names(possible_muts) <- c("S", "N", "U")
variants_ann_expiii$possible_muts <- possible_muts[as.character(variants_ann_expiii$effect_simplified)]

# diversity per genomic feature per passage
variants_ann_expiii$feature[variants_ann_expiii$feature == "envelope"] <- "env"
table(variants_ann_expiii$feature)[!names(table(variants_ann_expiii$feature)) %in% feature_df$feature]



counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            select(exp_line, passage, mut_info, feature, effect_simplified, possible_muts) %>%
            distinct() %>%
            group_by(exp_line, passage, feature, possible_muts) %>%
            summarise(count = n()) %>%
            mutate_at(c(1,3), as.factor) %>%
            left_join(feature_df[,c("feature", "length")], by = join_by(feature == feature)) %>%
            mutate(feature = factor(feature, levels = feature_factor_new)) %>%
            mutate(normalized_min_count = (count*100)/round(length*possible_muts))


counts$passage <- as.numeric(as.character(counts$passage))
counts %<>% filter(feature %in% names(ss))

```

```{r}
ss <- as.data.frame(ss)
ss$feature <- row.names(ss)
colnames(ss)[1] <- "parallel_fix"
counts_all <- merge(counts, ss, by = "feature")
counts_all %<>% group_by(feature, exp_line, passage) %>% mutate(mean = mean(normalized_min_count)) %>% select(feature, exp_line, passage, parallel_fix, mean)



model <- lm(counts_all$parallel_fix[counts_all$exp_line == "MT-2_1" & counts_all$passage == 10] ~ counts_all$normalized_min_count[counts_all$exp_line == "MT-2_1" & counts_all$passage == 10])
model_sum <- summary(model)
model_sum$adj.r.squared

df <- data.frame()
options(scipen = 999)
for (psg in seq(10,500, 10)){
    for (exp_line in exp_line_factor){
        model <- lm(counts_all$parallel_fix[counts_all$exp_line == exp_line & counts_all$passage == psg] ~ counts_all$mean[counts_all$exp_line == exp_line & counts_all$passage == psg])
        model_sum <- summary(model)
        model_sum$adj.r.squared
        df <- rbind(df, data.frame(passage = psg, exp_line = exp_line, r2 = model_sum$r.squared))
    }
}

fig <- df %>% ggplot(aes(x = passage, y = r2, color = exp_line)) + 
    geom_line() + 
    geom_point() +
    scale_color_manual(values = line_palette, name = "Virus Line") + 
    labs(title = paste0("Fixed Parallelism Association with Diversity per Gene"), y = "R-squared\n", x = "\nTransfer") +
    theme_bw() +
    theme(plot.title = element_text(size = 40, hjust = 0.5),
        axis.title = element_text(size = 30),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=35),
        legend.text = element_text(size = 25))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "diversity_parallel_association",".pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/diversity_parallel_association.pdf"), height = 14, width = 14)
fig
dev.off()



# Subset the data for clarity
subset_data <- counts_all[counts_all$exp_line == "MT-4_2" & counts_all$passage == 40, ]



fig <- ggplot(subset_data, aes(x = mean, y = 100*parallel_fix)) +
    geom_point(color = "blue", size = 3) +  # Plot points
    geom_smooth(method = "lm", color = "black", se = TRUE) + 
    geom_text(aes(label = feature), hjust = -0.2, color = "darkred", size = 5) +  # Add annotations
    labs(title = paste0("MT-4_2 Passage #40 Diversity vs\n passage #500 Parallism"), y = "Fixed Parallelism (%)\n", x = "\n Normalized Minority Count (%)") +
    theme_bw()+ 
    theme(plot.title = element_text(size = 40, hjust = 0.5),
            axis.title = element_text(size = 30),
            axis.text.x = element_text(size = 20, angle = 90),
            axis.text.y = element_text(size = 20),
            legend.title = element_text(size=35),
            legend.text = element_text(size = 25))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "diversity_parallel_association_mt-2_1_30.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/diversity_parallel_association_mt-4_2_40.pdf"), height = 14, width = 14)
fig
dev.off()


model <- lm(parallel_fix ~ mean, data = subset_data)
model_sum <- summary(model)

model_sum$r.squared

```