---
title:  
    "Diversity of EXPIII"
date: 
    "June 30th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly") 
library("patchwork")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# determine what data to be included

exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# Visual settings

line_col_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
names(line_col_palette) <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```



```{r read in the data}


lines <- c(13:16)

shannon_df <- data.frame()

for (line in lines){
    shannon_df <- rbind(shannon_df, read.table(file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/", line, "_diversity_measures.tsv"), sep = "\t", header = T)) #"_shannon_entropy"
}

# set the correct viral line names and  add host info

shannon_df %<>% mutate(host_line = ifelse(exp_line %in% c("13", "14","17", "18", "19", "20"), "MT2", "MT4")) %>% # add a field containing pos, ref, and alt info of muts
                mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2")) %>%
                filter(passage <= end_psg)

```


> First let's take a look at total and mean entropy per sample. 

```{r entropy per sample, results=TRUE}


d <- shannon_df %>% group_by(host_line,exp_line,passage) %>% summarise (sum_ent = sum(shannon_entropy, na.rm = T), mean_ent = mean(shannon_entropy, na.rm = T), .groups = 'drop')

d %<>% mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))

# sum of entropy per sample 

fig <- ggplot(d, aes(x = passage, y = sum_ent, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Total Entropy\n", color = "Virus Line", title = paste0("Sum of Entropy per Sample\n")) +
  scale_color_manual(values = line_col_palette) +
  theme_bw() +
  theme(plot.title = element_text(size = 30, hjust = 0.5),
    axis.title = element_text(size = 25),
    axis.text.x = element_text(size = 20, angle = 90),
    axis.text.y = element_text(size = 20),
    legend.title = element_text(size=20),
    legend.text = element_text(size = 15))

ggplotly(fig)

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_sample_sum.pdf"), height = 14, width = 14)
fig
dev.off()



# mean of entropy per sample 

fig <- ggplot(d, aes(x = passage, y = mean_ent, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Mean Entropy\n", color = "Virus Line", title = paste0("Mean of Entropy per Sample")) +
  scale_color_manual(values = line_col_palette) +
  theme_bw() +
  theme(plot.title = element_text(size = 30, hjust = 0.5),
    axis.title = element_text(size = 25),
    axis.text.x = element_text(size = 20, angle = 90),
    axis.text.y = element_text(size = 20),
    legend.title = element_text(size=20),
    legend.text = element_text(size = 15),
    strip.text = element_text(size = 25))

ggplotly(fig)

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_sample_mean.pdf"), height = 14, width = 14)
fig
dev.off()

```

> Let's take a look at total and mean heterozygosity per sample. 

```{r heterozygosity per sample, results=TRUE}


d <- shannon_df %>% group_by(host_line,exp_line,passage) %>% summarise (sum_het = sum(heterozygosity, na.rm = T), mean_het = mean(heterozygosity, na.rm = T), .groups = 'drop')

d %<>% mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))

# sum of heterozygosity per sample 

fig <- ggplot(d, aes(x = passage, y = sum_het, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Total Heterozygosity\n", color = "Virus Line", title = paste0("Sum of Heterozygosity per Sample\n")) +
  scale_color_manual(values = line_col_palette) +
  theme_bw() +
  theme(plot.title = element_text(size = 30, hjust = 0.5),
    axis.title = element_text(size = 25),
    axis.text.x = element_text(size = 20, angle = 90),
    axis.text.y = element_text(size = 20),
    legend.title = element_text(size=20),
    legend.text = element_text(size = 15))

ggplotly(fig)

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "heterozygosity_per_sample_sum.pdf"), height = 14, width = 14)
fig
dev.off()



# mean of heterozygosity per sample 

fig <- ggplot(d, aes(x = passage, y = mean_het, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Mean Heterozygosity\n", color = "Virus Line", title = paste0("Mean of Heterozygosity per Sample \n")) +
  scale_color_manual(values = line_col_palette) +
  theme_bw() +
  theme(plot.title = element_text(size = 30, hjust = 0.5),
    axis.title = element_text(size = 25),
    axis.text.x = element_text(size = 20, angle = 90),
    axis.text.y = element_text(size = 20),
    legend.title = element_text(size=20),
    legend.text = element_text(size = 15),
    strip.text = element_text(size = 25))

ggplotly(fig)

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "heterozygosity_per_sample_mean.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r entropy per position, results=TRUE}

dd <- shannon_df %>% group_by(host_line,exp_line,genomic_position) %>% summarise (sum_ent = sum(shannon_entropy, na.rm = T), mean_ent = mean(shannon_entropy, na.rm = T), var_ent = var(shannon_entropy, na.rm = T),.groups = 'drop')



fig <- ggplot(dd[dd$mean_ent !=0,], aes(x=exp_line, y = mean_ent)) +
    geom_boxplot() +
    labs(x="\nPosition", y= "Entropy Mean \n", title = paste0("Mean of Entropy per Genomic Position")) +
    theme_bw() +
        theme(plot.title = element_text(size = 20, hjust = 0.5),
        axis.title = element_text(size = 15),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10))



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_position_mean.pdf"), height = 14, width = 14)
fig
dev.off()


```

```{r}

t.test(dd$mean_ent[dd$exp_line == "MT-4_2"], dd$mean_ent[dd$exp_line == "MT-4_1"], paired = T)
t.test(dd$mean_ent[dd$exp_line == "MT-2_2"], dd$mean_ent[dd$exp_line == "MT-2_1"], paired = T)

```


```{r entropy change per position, results=TRUE}


dd <- shannon_df %>% group_by(host_line,exp_line,genomic_position) %>% summarise (sum_ent = sum(shannon_entropy, na.rm = T), mean_ent = mean(abs(diff(shannon_entropy)), na.rm = T), var_ent = var(abs(diff(shannon_entropy)), na.rm = T),.groups = 'drop')

dd %<>% mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))



fig <- ggplot(dd, aes(x=genomic_position, y = mean_ent)) + facet_wrap(~exp_line, ncol=4) +
    geom_point() +
    labs(x="\nPosition", y= "Mean of Entropy Difference\n", title = paste0("Mean of Entropy Difference per Genomic Position")) +
    theme_bw() +
        theme(plot.title = element_text(size = 25, hjust = 0.5),
        axis.title = element_text(size = 20),
        axis.text.x = element_text(size = 15, angle = 90),
        axis.text.y = element_text(size = 15),
        strip.text = element_text(size = 20))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_position_change_mean.pdf"), height = 14, width = 14)
fig
dev.off()


fig <- ggplot(dd, aes(x=genomic_position, y = var_ent)) + facet_wrap(~exp_line, ncol=4) +
    geom_point() +
    labs(x="\nPosition", y= "Variance of Entropy Difference\n", title = paste0("Variance of Entropy Difference per Genomic Position")) +
    theme_bw() +
        theme(plot.title = element_text(size = 20, hjust = 0.5),
        axis.title = element_text(size = 15),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_position_change_variance.pdf"), height = 14, width = 14)
fig
dev.off()



```

What can be observed from these data is that overall the rate of entropy change for 3 and 5 prime untranslated regions is higher.

```{r distribution of mean entropy difference, results=TRUE}


fig <- dd %>% ggplot(aes(x=mean_ent)) +
        facet_wrap(~exp_line) +
        geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth=0.01) +
        scale_y_continuous(labels = scales::percent) +
        labs(x="\nMean Entropy Difference", y= "Percentage\n", title = "Distribution of Mean Entropy Difference for MT-2_1") +
        theme_bw() +
                theme(plot.title = element_text(size = 20, hjust = 0.5),
                axis.title = element_text(size = 15),
                axis.text.x = element_text(size = 10, angle = 90),
                axis.text.y = element_text(size = 10))


ggplotly(fig)

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_position_distribution.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r}




cor_coefs <- data.frame()
for (i in levels(dd$exp_line)){
  for (j in levels(dd$exp_line)[levels(dd$exp_line) != i]){
    cor_res <- cor.test(dd$var_ent[dd$exp_line == i], dd$var_ent[dd$exp_line == j], method = 'spearman', exact = FALSE)
    cor_coefs <- rbind(cor_coefs, c(i , j, cor_res$estimate))
    print(paste0("Spearman's Rho between ", i, " and ", j, " is ", cor_res$estimate, " and p.value is ", cor_res$p.value))
  }
}


cor_coefs <- as.data.frame(cor_coefs) %>% 
                        `colnames<-`(c("line1", "line2", "Rho")) %>%
                        mutate(line1 = factor(line1, levels = names(line_col_palette))) %>%
                        mutate(line2 = factor(line2, levels = names(line_col_palette))) %>%
                        mutate(Rho = round(as.numeric(Rho), 2))




fig <- ggplot(data = as.data.frame(cor_coefs), aes(x=line1, y=line2, fill=Rho)) + 
        geom_tile() +
        geom_text(aes(line1, line2, label = Rho), color = "black", size = 4) +
        labs(title = "Correlation for Variance of Change of Positional Entropy") +
        scale_fill_gradient2(low = "blue", high = "red", 
        midpoint = 0, limit = c(-1,1), space = "Lab", 
        name="Spearman's Rho") +
        theme(
        axis.title = element_blank(),
        plot.title = element_text(size = 20, hjust = 0.5)
        )

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shannon_per_position_correlation_coefficient.pdf"), height = 14, width = 14)
fig
dev.off()

```



```{r}

### calculate number of polymorphic sites
### definition of polymorphic sites: any position where the allele frequency of none of the bases is above a certain cutoff, in our case: 99%



d <- shannon_df %>% group_by(host_line,exp_line,passage) %>% summarise (polymorphic_count = sum(polymorphic, na.rm = T), .groups = 'drop')

d %<>% mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))



# nr of polymorphic sites per sample

fig <- ggplot(d, aes(x = passage, y = polymorphic_count, color = exp_line)) +
  geom_line(linewidth=2) + 
  labs(x="\nTransfer", y= "Nr. Polymorphic Site\n", color = "Virus Line", title = paste0("Polymorphism")) +
  scale_color_manual(values = line_col_palette) +
  theme_bw() +
        theme(plot.title = element_text(size = 25, hjust = 0.5),
        axis.title = element_text(size = 20),
        axis.text.x = element_text(size = 15, angle = 90),
        axis.text.y = element_text(size = 15))

ggplotly(fig)

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "polymorphic_site_per_sample.pdf"), height = 14, width = 14)
fig
dev.off()



```




```{r combine mean ent and polymorphic site count}



d <- shannon_df %>% group_by(host_line,exp_line,passage) %>% summarise (sum_ent = sum(shannon_entropy, na.rm = T), mean_ent = mean(shannon_entropy, na.rm = T), polymorphic_count = sum(polymorphic, na.rm = T), .groups = 'drop')

d %<>% mutate(exp_line = factor(exp_line, levels = names(line_col_palette)))



# mean entropy and nr of polymorphic sites per sample

figs <- ggplot(d, aes(x = passage, color = exp_line)) +
  geom_line(aes(y = mean_ent), linewidth=2) + 
  geom_line(aes(y = polymorphic_count/30000), linewidth=2, linetype = "dashed") +
  facet_wrap(~exp_line, ncol = 2) +
  scale_y_continuous(name = "Mean Entropy \n",
    sec.axis = sec_axis(~.*30000, name="Nr. Polymorphic Site \n")) +
  labs(x="\nTransfer", color = "Virus Line", title = paste0("Polymorphism")) +
  scale_color_manual(values = line_col_palette) +
  theme_bw() +
        theme(plot.title = element_text(size = 25, hjust = 0.5),
        axis.title = element_text(size = 20),
        axis.text.x = element_text(size = 15, angle = 90),
        axis.text.y = element_text(size = 15))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "mean_entropy_and_polymorphic_site_per_sample.pdf"), height = 14, width = 14)
figs
dev.off()

```