---
title:  
    "Reproduce predictive power of diversity for parallelism"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggrepel")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```


```{r read-in variant data}


if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data

source(paste0(wd, "src/analysis/1st-man/readin_data.R"))

```

```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/1st-man/plot_custom.R"))


```


```{r compute gene-level diversity _ shannon}


lines <- c(13:16)

diversity_df <- data.frame()


for (line in lines){
    diversity_df <- rbind(diversity_df, read.table(file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/diversity/iii/", line, "_diversity_measures.tsv"), sep = "\t", header = T)) #"_shannon_entropy"
}

# set the correct viral line names and  add host info
diversity_df %<>% mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4")) %>% # add a field containing pos, ref, and alt info of muts
                mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2")) %>%
                filter(passage <= end_psg)

colnames(diversity_df)[3] <- "genomic_pos"

# add coverage data to remove deleted regions from mean calculation of diversity
diversity_dff <- merge(diversity_df, variants_expiii[,c("exp_line", "genomic_pos", "coverage")], by = c("exp_line", "genomic_pos"), all.x = T)


shannon_measure_all <- data.frame()
for (feature in feature_df$feature){
    print(feature)
    shannon_measure <- 
        diversity_dff %>% 
        filter(genomic_pos >= as.numeric(feature_df$start[feature_df$feature == feature]) & 
            genomic_pos <= as.numeric(feature_df$end[feature_df$feature == feature]) &
            coverage >= 500) %>% 
        group_by(host_line,exp_line,passage) %>%
        summarise (sum_ent = sum(shannon_entropy, na.rm = T), 
            mean_ent = mean(shannon_entropy, na.rm = T), 
            .groups = 'drop') %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
            feature = feature)
    
    shannon_measure_all <- rbind(shannon_measure_all, shannon_measure)
}



```



```{r count parallel majority variants at end passage}


# count parallel mut per gene 

threshold <- 0.5
psg_of_interest <- 500


variants_expiii %<>% mutate(passage = as.numeric(as.character(passage)))

fix_count_table <- as.data.frame(table(variants_expiii$mut_info[variants_expiii$allele_freq >= threshold & variants_expiii$passage == psg_of_interest], 
        variants_expiii$feature[variants_expiii$allele_freq >= threshold & variants_expiii$passage == psg_of_interest], 
        variants_expiii$exp_line[variants_expiii$allele_freq >= threshold & variants_expiii$passage == psg_of_interest]))



colnames(fix_count_table) <- c("mut_info", "feature", "exp_line", "occurrence")
fix_count_table %<>% filter(occurrence %notin% c(0))




counts <- table(fix_count_table$mut_info)
fix_count_table$occurrence <- unname(counts[fix_count_table$mut_info])
parallel <- fix_count_table %>% 
    filter(occurrence != 1) %>%
    count(feature, name = "count")



## normalize by length

feature_parallel <- merge(parallel, feature_df[,c("feature", "length")], by = "feature")

feature_parallel$normalized_parallel_count <- feature_parallel$count / feature_parallel$length

# ## normalize by total number of variants (parallel ratio)

# fix_counts_per_element <- as.data.frame(table(variants_expiii %>% filter(allele_freq >= 0.5 & passage == end_psg) %>% 
#                     select(mut_info, feature, exp_line) %>%
#                     distinct() %>%
#                     select(feature)))

# feature_parallel <- merge(parallel, fix_counts_per_element, by = "feature")

# feature_parallel$normalized_parallel_count <- feature_parallel$count / feature_parallel$Freq


```




```{r compute r-squared between diversity and parallel at each time point}


diversity_parallel <- merge(shannon_measure_all, feature_parallel[,c("feature", "normalized_parallel_count")], by = c("feature"))
diversity_parallel %<>% select(feature, exp_line, passage, mean_ent, normalized_parallel_count)
diversity_parallel[diversity_parallel$feature == "env" & diversity_parallel$exp_line == "MT-4_2" & diversity_parallel$passage == 500,]



diversity_parallel %<>%distinct() %>% filter(feature %notin% c("3R", "5R"))
diversity_parallel %<>%distinct() %>% filter(feature %notin% c("nef", "vpr"))

df <- data.frame()
options(scipen = 999)
for (psg in seq(10,500, 10)){
    for (exp_line in exp_line_factor){
        model <- lm(diversity_parallel$normalized_parallel_count[diversity_parallel$exp_line == exp_line & diversity_parallel$passage == psg] ~ diversity_parallel$mean_ent[diversity_parallel$exp_line == exp_line & diversity_parallel$passage == psg])
        model_sum <- summary(model)
        model_sum$adj.r.squared
        df <- rbind(df, data.frame(passage = psg, exp_line = exp_line, r2 = model_sum$r.squared))
    }
}

```

```{r visualization1 summary plot}

fig <- df %>% ggplot(aes(x = passage, y = r2, color = exp_line)) + 
    geom_line() + 
    geom_point() +
    scale_color_manual(values = line_col_palette, name = "Lineage") + 
    labs(title = "", y = "R-squared\n", x = "\nTransfer") +
    custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0("diversity_parallel_association.pdf"), height = 14, width = 14)


```

```{r visualization2 example plot}

psg <- 30
exp_line <- "MT-2_1"

# Subset the data for clarity
subset_data <- diversity_parallel[diversity_parallel$exp_line == exp_line & diversity_parallel$passage == psg, ]



model <- lm(subset_data$normalized_parallel_count ~ subset_data$mean_ent)
model_sum <- summary(model)
model_sum$adj.r.squared


fig <- ggplot(subset_data, aes(x = mean_ent, y = normalized_parallel_count)) +
    geom_point(color = "blue", size = 3) +  # Plot points
    geom_smooth(method = "lm", color = "black", se = TRUE) + 
    geom_text_repel(aes(label = feature), color = "darkred", size = 8) +  # Repel instead of plain text
    labs(title = "", y = "Parallel majority variant per site \n", x = "\n Diversity (mean Shannon entropy)") +
    # scale_x_continuous(breaks = seq(0, 0.01, by = 0.005), labels = seq(0, 0.01, by = 0.005), limit = c(0,0.02)) +
    custom_plot_theme(application = "publication")

# save figure
custom_plot_save(fig, paste0("diversity_parallel_association_mt-2_1_30.pdf"), height = 14, width = 14)



```

```{r visualization3 diversity per gene over time}



fig <- shannon_measure_all %>% 
    ggplot(aes(x = passage, y = mean_ent, color = exp_line)) + 
    geom_line() + 
    geom_point() +
    facet_wrap(~ feature, scales = "free_y") +
    scale_color_manual(values = line_col_palette, name = "Lineage") + 
    labs(title = "", y = "Diversity (mean Shannon entropy)\n", x = "\nTransfer") +
    custom_plot_theme(application = "publication")

custom_plot_save(fig, paste0("diversity_per_gene_over_time.pdf"), height = 28, width = 28)

```