---
title:  
    "Fixation timeline of Variants in EXPIII"
date: 
    "Feb 7th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"

# determine what data to be included

exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))

# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```

```{r set paramters}

# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
} else if (category == "All"){
    min_threshold <- 0.01
    max_threshold <- 1.01
}

```

```{r}


df <- data.frame()

for (exp_line in line_labels){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$passage == end_psg])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.01])))
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}

# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        mut_info_line = paste(exp_line, mut_info, sep = "_"),
        host_line = if_else(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4"),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))


df %<>% group_by(mut_info) %>% 
    mutate(Occurrence = n()) %>%
    mutate(Occurrence = factor(Occurrence, levels = c("1","2","3","4"))) %>%
    mutate(exp_line_number = case_when(exp_line == "MT-2_1" ~ 1,
                                        exp_line == "MT-2_2" ~ 2,
                                        exp_line == "MT-4_1" ~ 3,
                                        exp_line == "MT-4_2" ~ 4)) %>%
    ungroup()


df_jittered <- df %>%
    mutate(y_jittered = exp_line_number + runif(n(), min = -0.1, max = 0.1))  # Add jitter to y values


library(RColorBrewer)


blues_colors <- c("#A4DDED", "#A3C1AD", "#CCCCFF", "#00CCFF", "#15f4ee", 
"#0071c5", "#5A4FCF", "#004687", "#0000CD", "#191970")
triples <- blues_colors
names(triples) <- unique(df_jittered$mut_info[df_jittered$Occurrence == "3"])[order(unique(df_jittered$mut_info[df_jittered$Occurrence == "3"]))]

reds_colors <- brewer.pal(5, "Reds")[3:5]
quad <- reds_colors
names(quad) <- unique(df_jittered$mut_info[df_jittered$Occurrence == "4"])



df_jittered %<>%
    mutate(mut_info2 = case_when(Occurrence == 1 ~ "Single Occurrence",
                                Occurrence == 2 ~ "Double Occurrence",
                                Occurrence == 3 ~ mut_info,
                                Occurrence == 4 ~ mut_info)) %>%
    mutate(mut_info2 = factor(mut_info2, levels = c("Single Occurrence", "Double Occurrence", names(triples), names(quad))))



custom_colors <- c(
    "Single Occurrence" = "grey",
    "Double Occurrence" = "green"
)
custom_colors <- c(custom_colors, triples, quad)

fig <- ggplot(df_jittered, aes(x = fixation, y = exp_line, group = mut_info, color = mut_info2)) +
    # Add lines connecting identical mutations within the same group
    geom_line(aes(y = y_jittered),
                alpha = 0.5, 
                size = 1) +
    # Add points for mutations
    geom_point(aes(y = y_jittered), size = 3) +
    scale_y_continuous(breaks = 1:4, labels = line_labels) +
    scale_color_manual(values = custom_colors) +
    labs(title = "Mutation Fixation Timeline",
        x = "Transfer", y = "Virus Line") +
    xlim(0, 500) +
    theme_minimal() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
            axis.title = element_text(size = 45),
            axis.text.x = element_text(size = 20, face="bold"),
            axis.text.y = element_text(size = 30),
            strip.text.x = element_text(size = 35),
            legend.title = element_text(size=40),
            legend.text = element_text(size = 35))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "fixation_timeline.pdf"), height = 14, width = 28)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/fixation_timeline.pdf"), height = 14, width = 28)
fig
dev.off()


```