---
title:  
    "Fixation dynamics of EXPIII"
date: 
    "June 30th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("RColorBrewer")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("gtools")
library("effsize")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 


# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))

# Visualization settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```



# Accumulation

```{r set paramters}

# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

```





```{r calculate time to fixation}

## Method 1
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()

for (exp_line in line_labels){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.01])))
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}

## Method 2
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()


for (exp_line in line_labels){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(variants_expiii_sub2$passage[(variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.01)]))))) + 10
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}



# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        mut_info = paste(exp_line, mut_info, sep = "_"),
        host_line = if_else(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4"),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))

```


```{r visualization1: time-to-fixation}
# density of time_to_fixation distributions
fig <- df %>% ggplot(aes(x = time_to_fixation, color = exp_line)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = line_labels, values = line_palette)

fig



# perform pairwise wilcox-test between translation impact groups per exp line

pwc <- df %>%
    group_by(exp_line) %>%
    pairwise_wilcox_test(
        time_to_fixation ~ effect_simplified,
        p.adjust.method = "none",
        detailed = TRUE
    )

# Visualization: box plots with p-values

low<-findInterval(max(df$time_to_fixation),c(5,10,20,50,100))
step <- c(5,10,20,50,100)[low - 1]

#Add x position
pwc <- pwc %>% add_xy_position(x = "effect_simplified", step.increase = 1)
# assign new y.positions 
pwc$y.position <- sample(seq(500,700,10), replace = F, size = 12)
# make the plot
fig2 <- ggboxplot(df, x = "effect_simplified", y = "time_to_fixation", color = "exp_line") +
    facet_wrap(~exp_line, ncol = 2) +
    labs(x = "Translational Impact", y = "Time to Fixation", color = "Virus Line")+
    scale_color_manual(labels = line_labels, values = line_palette) +
    scale_y_continuous(breaks = seq(0,max(df$time_to_fixation)+step,step)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj") 


fig2

# perform pairwise wilcox-test between exp line groups per translation impact
pwc <- df %>%
    group_by(effect_simplified) %>%
    pairwise_wilcox_test(time_to_fixation ~ exp_line, p.adjust.method = "BH",pool.sd=FALSE, detailed = T)

#Add x position
pwc <- pwc %>% add_xy_position(x = "exp_line", step.increase = 1)
# assign new y.positions 
pwc$y.position <- sample(seq(500,750,10), replace = F, size = 18)
# make the plot
fig3 <- ggboxplot(df, x = "exp_line", y = "time_to_fixation", color = "exp_line") +
    facet_wrap(~effect_simplified, ncol = 3) +
    labs(x = "Virus Line", y = "Time to Fixation", color = "Virus Line")+
    scale_color_manual(labels = line_labels, values = line_palette) +
    scale_y_continuous(breaks = seq(0,max(df$time_to_fixation)+step,step)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj") 

fig3

# perform pairwise wilcox-test between host line groups per translation impact
pwc <- df %>%
    # filter(mut_info %in% shared) %>%
    # filter(fixation >= 300) %>%
    group_by(effect_simplified) %>%
    pairwise_wilcox_test(time_to_fixation ~ host_line, p.adjust.method = "BH",pool.sd=FALSE, detailed = T)

#Add x position
pwc <- pwc %>% add_xy_position(x = "host_line", step.increase = 1)
# assign new y.positions 
pwc$y.position <- sample(seq(500,750,10), replace = F, size = 3)

# make the plot
fig4 <- ggboxplot(df, x = "host_line", y = "time_to_fixation", color = "host_line") +
    facet_wrap(~effect_simplified, ncol = 3) +
    labs(x = "\nVirus Line", y = "Time to Fixation\n", color = "Virus Line")+
    scale_color_manual(labels = c("MT-2", "MT-4"), values = c("red", "blue")) +
    scale_y_continuous(breaks = seq(0,max(df$time_to_fixation)+step,step), limit = c(0,800)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj", size = 8) +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
            axis.title = element_text(size = 45),
            axis.text.x = element_text(size = 20, face="bold"),
            axis.text.y = element_text(size = 30),
            strip.text.x = element_text(size = 35),
            legend.title = element_text(size=40),
            legend.text = element_text(size = 35))

fig4


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "time_to_fixation_per_density.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0(fig_dir, "time_to_fixation_significance_boxplot_per_line.pdf"), height = 14, width = 14)
fig2
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/time_to_fixation_significance_boxplot_per_line.pdf"), height = 14, width = 14)
fig2
dev.off()
pdf(file = paste0(fig_dir, "time_to_fixation_significance_boxplot_per_translation_group.pdf"), height = 14, width = 14)
fig3
dev.off()
pdf(file = paste0(fig_dir, "time_to_fixation_significance_boxplot_per_translation_group_host_line.pdf"), height = 14, width = 14)
fig4
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/time_to_fixation_significance_boxplot_per_translation_group_host_line.pdf"), height = 14, width = 14)
fig4
dev.off()


# get inline variables
df %>% group_by(host_line) %>% summarize(Mean = mean(time_to_fixation, na.rm=TRUE), n = n())

wilcox.test(df$time_to_fixation[df$host_line == "MT-2"], df$time_to_fixation[df$host_line == "MT-4"])

```


```{r visualization11: time-to-fixation over time}

# time_to_fixation distributions per function of appearance time

fig <- df %>% ggplot(aes(x = appearance, y = time_to_fixation, color = exp_line, shape = effect_simplified)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_point() +
                    geom_hline(yintercept = 100) +
                    scale_color_manual(labels = line_labels, values = line_palette)

fig

```

```{r distribution of rapidly fixating mutations over time}

quantile(df$time_to_fixation[df$exp_line == "MT-4_2"], probs = c(0.25, 0.5, 0.75))

df <- df %>%
  group_by(exp_line) %>%
  mutate(p10 = quantile(time_to_fixation, 0.10)) %>%
  mutate(p90 = quantile(time_to_fixation, 0.90)) %>%
  ungroup()

labels_with_p10 <- with(df, setNames(
  paste0(exp_line, "\n(", round(p10, 1), ")"),
  exp_line
))

df %<>% mutate(labels = labels_with_p10)


bins <- seq(0,400, 100)

df_summary <- df[df$time_to_fixation < df$p10,] %>%
        mutate(bin = cut(fixation, breaks = bins, right = FALSE)) %>%
        group_by(exp_line,labels, effect_simplified) %>%
        count(bin, .drop = FALSE)

df_summary <- df_summary[!is.na(df_summary$bin),]



fig <- ggplot(df_summary, aes(x = effect_simplified, y = n, fill = bin)) +
    facet_wrap(~labels, ncol = 2) +
    geom_bar(stat = "identity", position = "dodge") +
    scale_color_manual(labels = line_labels, values = line_palette) +
    scale_y_continuous(limits = c(0, 10), breaks = seq(0, 12, by = 2)) +
    labs(title = "Frequency of Rapidly Fixating Mutations over Time", x = "Translational Impact", y = "Count of Rapidly Fixing Variants \n (10th Percentile Time to Fixation)", fill = "Fixation Period") +
    theme_bw() +
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 40),
        axis.text.x = element_text(size = 30, face="bold", angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 40, angle=90),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 30))

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "Rapidly_Fixating_Mutations_over_Time.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/Rapidly_Fixating_Mutations_over_Time.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r}

# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))



dff <- df %>% group_by(mut_info) %>%
    summarize(Mean = mean(time_to_fixation, na.rm=TRUE),
            n = n())

dff[dff$mut_info == "7854_A_G",]
dff[dff$Mean == max(dff$Mean[dff$n == 4]),]


# view the frequency dynamics of one fixed mutation
df[df$mut_info == "MT-2_1_566_G_A",]

fig <- variants_expiii[variants_expiii$mut_info %in% "566_G_A",] %>% ggplot(aes(x = passage, y = allele_freq, color = exp_line)) +
    geom_line(aes(group = exp_line)) +
    scale_color_manual(labels = line_labels, values = line_palette) +
    geom_hline(yintercept = 0.01, lty = "dashed")+
    theme(legend.position="none") 

fig

pdf(file = paste0(fig_dir, "time_to_fixation_case.pdf"), height = 14, width = 14)
fig
dev.off()


```





```{r time-to-fixation over time}

# # record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
# df <- data.frame()

# for (exp_line in line_labels){
#     variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
#     fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.5])
#     for (mut in fixed_muts){
#         appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.05])))
#         af_fold_change <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == mut & variants_expiii_sub$passage == appearance + 20]/variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == mut & variants_expiii_sub$passage == appearance]
#         if (length(af_fold_change) == 0){af_fold_change <- 0}
#         translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
#         df <- rbind(df, c(exp_line, mut, translational_impact, appearance, af_fold_change))
#     }
# }

# # set column names and right data types
# df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "af_fold_change")) %>% 
#         mutate_at(4:5, as.numeric) %>%
#         mutate(exp_line = factor(exp_line, levels = exp_line_factor),
#         mut_info = paste(exp_line, mut_info, sep = "_"),
#         effect_simplified = factor(effect_simplified, levels = translational_impacts))

# # summarize time to fixation per passage of appearance
# df_summary <- df %>% group_by(exp_line, appearance, effect_simplified) %>%
#                     summarize(Mean = median(af_fold_change, na.rm=TRUE),
#                     n = n())

# line <- "MT-2_2"
# lm(df_summary$Mean[df_summary$effect_simplified == "U" & df_summary$exp_line == line] ~ df_summary$appearance[df_summary$effect_simplified == "U" & df_summary$exp_line == line])

# # visualize time to fixation summary
# fig <- df_summary[df_summary$effect_simplified == "S",] %>% ggplot(aes(x = appearance, y = Mean, group = exp_line, color = exp_line)) +
#     geom_line() +
#     geom_point(aes(size = n)) +
#     facet_wrap(~exp_line, ncol = 1) +
#     scale_color_manual(labels = line_labels, values = line_palette) +
#     theme_bw() +
#     theme(plot.title = element_text(size = 30, hjust = 0.5),
#     axis.title = element_text(size = 25),
#     axis.text.x = element_text(size = 20, angle = 90),
#     axis.text.y = element_text(size = 20),
#     legend.title = element_text(size=20),
#     legend.text = element_text(size = 15))
# fig


# # save figure
# date <- str_split(Sys.time(), pattern = " ")[[1]][1]
# fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
# ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
# pdf(file = paste0(fig_dir, "time_to_fixation_per_passage.pdf"), height = 14, width = 14)
# fig
# dev.off()


```



```{r time-to-fixation over time2}

# # record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
# df <- data.frame()

# for (exp_line in line_labels){
#     variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
#     fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
#     for (mut in fixed_muts){
#         appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.01])))
#         fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
#         translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
#         df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
#     }
# }

# # set column names and right data types
# df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
#         mutate_at(4:6, as.integer) %>%
#         mutate(exp_line = factor(exp_line, levels = exp_line_factor),
#         effect_simplified = factor(effect_simplified, levels = translational_impacts))



# # summarize time to fixation per passage of appearance
# df_summary <- df %>% group_by(exp_line, appearance) %>%
#                     summarize(Med = median(time_to_fixation, na.rm=TRUE),
#                     n = n())

# # visualize time to fixation summary
# fig <- df_summary %>% ggplot(aes(x = appearance, y = Med, group = exp_line, color = exp_line)) +
#     geom_line() +
#     geom_point(aes(size = n)) +
#     facet_wrap(~exp_line, ncol = 1) +
#     scale_color_manual(labels = line_labels, values = line_palette) +
#     theme_bw() +
#     theme(plot.title = element_text(size = 30, hjust = 0.5),
#     axis.title = element_text(size = 25),
#     axis.text.x = element_text(size = 20, angle = 90),
#     axis.text.y = element_text(size = 20),
#     legend.title = element_text(size=20),
#     legend.text = element_text(size = 15))
# fig


# # save figure
# date <- str_split(Sys.time(), pattern = " ")[[1]][1]
# fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
# ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
# pdf(file = paste0(fig_dir, "time_to_fixation_per_passage.pdf"), height = 14, width = 14)
# fig
# dev.off()


```



```{r fixation time based on number of recurrence}

## Method 2
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()


for (exp_line in line_labels){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(variants_expiii_sub2$passage[(variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.01)]))))) + 10
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}


# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))


# average time to fixation for fixated mutations based on how many times they are repeated

fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])




df$Occurrence <- NA
df$Occurrence[df$mut_info %in% names(fix_count_table_list[["1"]])] <- "One"
df$Occurrence[df$mut_info %in% names(fix_count_table_list[["2"]])] <- "Two"
df$Occurrence[df$mut_info %in% names(fix_count_table_list[["3"]])] <- "Three"
df$Occurrence[df$mut_info %in% names(fix_count_table_list[["4"]])] <- "Four"
df <- df[!is.na(df$Occurrence),]
df$Occurrence <- factor(df$Occurrence, levels = c("One", "Two", "Three", "Four"))


comparisons <- list(
  c("Four", "Three"),
  c("Four", "Two"),
  c("Four", "One"),
  c("Three", "Two"),
  c("Three", "One"),
  c("Two", "One")
)


my_col_pal <- c(alpha("grey"), "green", "blue", "red")
# Create the plot
fig <- ggplot(df, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj", size = 12) +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + # Label for the legend
    theme_minimal() + # Optional: use a minimal theme
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 40),
        axis.text.x = element_text(size = 35, angle = 90, color = "black"),
        axis.text.y = element_text(size = 35, color = "black"),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 35)) 


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "fixation-based-on-recurrence.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/time-to-fixation-based-on-recurrence.pdf"), height = 14, width = 14)
fig
dev.off()

mean(df$time_to_fixation[df$mut_info %in% names(fix_count_table_list[["1"]])])


t.test(df$time_to_fixation[df$mut_info %in% names(fix_count_table_list[["3"]])],df$time_to_fixation[df$mut_info %in% names(fix_count_table_list[["1"]])])


```

```{r regression model of time to fixation for number of occurrence}

# density of time_to_fixation distributions
fig <- df %>% ggplot(aes(x = time_to_fixation, color = exp_line)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = line_labels, values = line_palette)

fig

fig <- df %>% ggplot(aes(x = time_to_fixation, color = Occurrence)) +
                    facet_wrap(~Occurrence, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = c("One", "Two", "Three", "Four"), values = c(alpha("grey"), "green", "blue", "red"))

fig



# Shapiro-Wilk test
shapiro.test(df[df$Occurrence == "One",]$time_to_fixation)
shapiro.test(df[df$exp_line == "MT-2_1",]$time_to_fixation)

# pairwise wilcox-test between Occurrence groups

fig <- ggplot(df, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj") +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + # Label for the legend
    theme_minimal() + # Optional: use a minimal theme
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15)) 

fig

# ordinary linear model
# problem 1 - the occurrence variable is not continuous. Can I treat an ordinal categorical variable as continuous?
# problem 2 - each group has a different variance (non-homoscedasticity)

dff <- df
dff %<>% mutate(Occurrence = as.numeric(Occurrence))

# Fit an ordinary linear model
model_lm <- lm(time_to_fixation ~ Occurrence, data = dff)

# Diagnostic plots
par(mfrow = c(2, 2))
plot(model_lm)

# Extract model summary
model_lm_summary <- summary(model_lm)
lm_effects <- model_lm_summary$coefficients

# Create a data frame for the fixed effects
lm_effects_df <- data.frame(
  Term = rownames(lm_effects),
  Estimate = lm_effects[, 1],
  StdError = lm_effects[, 2],
  tValue = lm_effects[, 3],
  pValue = 2 * (1 - pnorm(abs(lm_effects[, 3])))
)

# Prepare the fixed effects text for annotation
lm_effects_text <- paste0(
  "Intercept: ", round(lm_effects_df$Estimate[lm_effects_df$Term == "(Intercept)"], 2), "\n",
  "Occurrence effect: ", round(lm_effects_df$Estimate[lm_effects_df$Term == "Occurrence"], 2), "\n",
  "p-value: ", format.pval(lm_effects_df$pValue[lm_effects_df$Term == "Occurrence"], digits = 3)
)

# Plot with ggplot
fig <- ggplot(df, aes(x = Occurrence, y = time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + 
    theme_minimal() + 
    theme(plot.title = element_text(size = 30, hjust = 0.5),
          axis.title = element_text(size = 25),
          axis.text.x = element_text(size = 20, angle = 90),
          axis.text.y = element_text(size = 20),
          legend.title = element_text(size=20),
          legend.text = element_text(size = 15)) +
    annotate(
        "text", x = 1.5, y = max(dff$time_to_fixation), label = lm_effects_text, 
        size = 6, hjust = -1, color = "orange"
    )

# Add regression line to the plot
fig <- fig +
    geom_smooth(data = dff, aes(x = Occurrence, y = time_to_fixation), method = "lm", se = FALSE, color = "orange")

# Print the final plot
fig



# mixed effect linear model with random effect the exp line
# problem 3 - there is subgrouping in the data that needs to be accounted for, so regard exp_line as a random effect in a mixed effect model




library(lme4)
model_lme <- lmer(time_to_fixation ~ Occurrence + (1|exp_line), data = dff)

par(mfrow = c(2, 2))
plot(model_lme)
model_lme_summary <- summary(model_lme)
fixed_effects <- model_lme_summary$coefficients

fixed_effects_df <- data.frame(
  Term = rownames(fixed_effects),
  Estimate = fixed_effects[, 1],
  StdError = fixed_effects[, 2],
  tValue = fixed_effects[, 3],
  pValue = 2 * (1 - pnorm(abs(fixed_effects[, 3])))
)

fixed_effects_text <- paste0(
  "Intercept: ", round(fixed_effects_df$Estimate[fixed_effects_df$Term == "(Intercept)"], 2), "\n",
  "Occurrence effect: ", round(fixed_effects_df$Estimate[fixed_effects_df$Term == "Occurrence"], 2), "\n",
  "p-value: ", format.pval(fixed_effects_df$pValue[fixed_effects_df$Term == "Occurrence"], digits = 3)
)

fig <- ggplot(df, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    # stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj") +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + # Label for the legend
    theme_minimal() + # Optional: use a minimal theme
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15)) +
    annotate(
        "text", x = 1.5, y = max(df$time_to_fixation), label = fixed_effects_text, 
        size = 6, hjust = -1, color = "orange"
    )

fig <- fig +
    geom_smooth(data = dff, aes(x = Occurrence, y = time_to_fixation), method = "lm", se = FALSE, color = "orange")



```


```{r distribution of rapidly fixating variants shared}

quantile(df$time_to_fixation, probs = c(0.25, 0.5, 0.75))

bins <- seq(0,400, 100)

df_summary <- df[df$time_to_fixation <= 100,] %>%
        mutate(bin = cut(appearance, breaks = bins, right = FALSE)) %>%
        group_by(exp_line,effect_simplified,Occurrence) %>%
        count(bin, .drop = FALSE)

df_summary <- df_summary[!is.na(df_summary$bin),]
my_col_pal <- c(alpha("grey"), "green", "blue", "red")

fig <- ggplot(df_summary, aes(x = bin, y = n, fill = Occurrence)) +
  facet_wrap(~exp_line, ncol = 2) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(labels = c("1", "2", "3", "4"), values = my_col_pal) +
  labs(title = "Frequency of Rapidly Fixating Mutations over Time\n", x = "\nTime Bin", y = "Nr. of Fixed Variants \n with TF <= 100\n", fill = "Occurrence\n") +
  theme_bw() +
  theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 20),
        axis.text.x = element_text(size = 15, face="bold"),
        axis.text.y = element_text(size = 15),
        strip.text.x = element_text(size = 20, angle=90),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "Rapidly_Fixating_Shared_Variants_over_Time.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/Rapidly_Fixating_Shared_Variants_over_Time.pdf"), height = 14, width = 14)
fig
dev.off()

```




```{r misc}

df <- data.frame()

for (exp_line in line_labels){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.01])))
        af_fold_change <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == mut & variants_expiii_sub$passage == appearance + 10]/variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == mut & variants_expiii_sub$passage == appearance]
        if (length(af_fold_change) == 0){af_fold_change <- 0}
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance, af_fold_change))
    }
}

# set column names and right data types
df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "af_fold_change")) %>% 
        mutate_at(4:5, as.numeric) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))

dff<- data.frame()
for (mut in unique(df$mut_info)){
    if (all(any(str_detect(df$exp_line[df$mut_info == mut], pattern = "MT-2")),any(str_detect(df$exp_line[df$mut_info == mut], pattern = "MT-4")))){
        MT2 <- mean(df$af_fold_change[df$mut_info == mut & str_detect(df$exp_line,pattern = "MT-2")])
        MT4 <- mean(df$af_fold_change[df$mut_info == mut & str_detect(df$exp_line,pattern = "MT-4")])
        translational_impact <- unique(as.character(df$effect_simplified[df$mut_info == mut]))
        dff <- rbind(dff, c(mut,translational_impact,MT2,MT4))
    }
}




dff %<>% set_colnames(c("mut_info", "translational_impact","mt2", "mt4"))

plot(dff$mt2[dff$translational_impact == "N"], dff$mt4[dff$translational_impact == "N"])

cor.test(as.numeric(dff$mt2[dff$translational_impact == "S"]), as.numeric(dff$mt4[dff$translational_impact == "S"]), method = "spearman")



```
