---
title:  
    "Fixed Mutation Accumulation of EXPIII"
date: 
    "June 18th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"

# determine what data to be included

exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))

# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```



# Accumulation

```{r text numbers}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

# get numbers for in-text reporting
variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & allele_freq < max_threshold) #& mut_type == "P"



# in-text numbers
bb <- length(unique(paste0(variants_expiii_subset$exp_line,variants_expiii_subset$mut_info)))
b <- length(unique(variants_expiii_subset$mut_info))

# numbers per translational impact groups
variants_expiii_subset_unique <- variants_expiii_subset %>% select(mut_info, effect_simplified) %>% distinct()
prop.table(table(variants_expiii_subset_unique$effect_simplified))


variants_expiii_subset_mt2 <- variants_expiii_subset[variants_expiii_subset$host_line == "MT2",]
variants_expiii_subset_mt4 <- variants_expiii_subset[variants_expiii_subset$host_line == "MT4",]
bb_mt2 <- length(unique(paste0(variants_expiii_subset_mt2$exp_line,variants_expiii_subset_mt2$mut_info)))
bb_mt4 <- length(unique(paste0(variants_expiii_subset_mt4$exp_line,variants_expiii_subset_mt4$mut_info)))
bb_mt2/bb_mt4
b_mt2 <- length(unique(variants_expiii_subset_mt2$mut_info))
b_mt4 <- length(unique(variants_expiii_subset_mt4$mut_info))
b_mt2/b_mt4


c <- length(setdiff(unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT4"]),unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT2"])))
d <- length(setdiff(unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT2"]),unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT4"])))
e <- length(intersect(unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT2"]),unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT4"])))


```

```{r visualization1: Accumulation plot}



# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)


# visualize 

# estimate na's if any 
library(zoo) 
counts$mut_count[counts$passage > 600 & counts$mut_count == 0] <- NA
counts %<>% group_by(exp_line) %>% mutate(mut_count = na.approx(mut_count, rule = 2))


fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line, alpha = exp_line)) +
        geom_line(linewidth=2) +
        # geom_smooth(aes(group = host_line, color = host_line), method = "lm", se = FALSE, linetype = "dashed", linewidth = 1) + # Regression by host_factor
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation"))+
        scale_x_continuous(breaks = seq(0,end_psg+10,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count, na.rm = T)+20),breaks = seq(0,max(counts$mut_count, na.rm = T)+20,20)) +
        scale_color_manual(labels = c(line_labels, "MT-2 Regression", "MT-4 Regression"), values = c(line_palette,"#ff8000", "#00bbff")) +
        # scale_alpha_manual(values = c("MT-2_1" = 0.1, "MT-2_2" = 0.1, "MT-4_1" = 1, "MT-4_2" = 0.1)) +  # Adjust for your line names
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 40),
        axis.text.x = element_text(size = 40, angle = 90, color = "black"),
        axis.text.y = element_text(size = 40, color = "black"),
        legend.title = element_text(size=50),
        legend.text = element_text(size = 40))


ggplotly(fig)



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_accumulation.pdf"), height = 14, width = 14)
fig
dev.off()

```



```{r visualization1: Accumulation plot with simulation data}


# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)

counts <- counts[,-4]
counts$group <- "Observed"

counts_all <- rbind(counts, fixed_count_df_long)
counts_all$group <- factor(counts_all$group, levels = c("Observed", "Simulation"))


# visualize 

fig <- counts_all %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line, linetype = group)) +
        geom_line(linewidth=2) +
        # geom_smooth(aes(group = host_line, color = host_line), method = "lm", se = FALSE, linetype = "dashed", linewidth = 1) + # Regression by host_factor
        labs(x="\nTransfer", y= "Mutation Count\n", linetype = "Group", color = "Virus Line", title = paste0(category, " Mutation Accumulation"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts_all$mut_count)+20),breaks = seq(0,max(counts_all$mut_count)+20,50)) +
        scale_color_manual(labels = c(line_labels, "MT-2 Regression", "MT-4 Regression"), values = c(line_palette,"#ff8000", "#00bbff")) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))






# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_accumulation.pdf"), height = 14, width = 14)
fig
dev.off()

```



```{r fixed mutation linear regression}

# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)


# linear regression

counts2 <- counts %>% select(passage,mut_count,host_line) %>% group_by(passage,host_line) %>% summarize(ave_count = mean(mut_count))

lm_mt2 <- lm(ave_count ~ passage, data = counts2[counts2$host_line == "MT2",])
summary(lm_mt2)
lm_mt2_200 <- lm(ave_count ~ passage, data = counts2[counts2$passage <= 200 & counts2$host_line == "MT2",])
summary(lm_mt2_200)
lm_mt2_500 <- lm(ave_count ~ passage, data = counts2[counts2$passage > 200 & counts2$host_line == "MT2",])
summary(lm_mt2_500)
(0.977 + 0.9891)/2
lm_mt4 <- lm(ave_count ~ passage, data = counts2[counts2$host_line == "MT4",])
summary(lm_mt4)
lm_mt4_200 <- lm(ave_count ~ passage, data = counts2[counts2$passage <= 200 & counts2$host_line == "MT4",])
summary(lm_mt4_200)
lm_mt4_500 <- lm(ave_count ~ passage, data = counts2[counts2$passage > 200 & counts2$host_line == "MT4",])
summary(lm_mt4_500)


#### 

df_lm_mt4 <- data.frame(passage = as.numeric(seq(10,500,10)))
df_lm_mt4$predicted <- predict(lm_mt4, newdata = df_lm_mt4)
df_lm_mt4$group <- "Observed"

#### 

df_lm_mt2 <- data.frame(passage = as.numeric(seq(10,500,10)))
df_lm_mt2$predicted <- predict(lm_mt2, newdata = df_lm_mt2)
df_lm_mt2$group <- "Observed"


#### 
df_lm_mt2_200_1 <- data.frame(passage = as.numeric(seq(10,200,10)))
df_lm_mt2_200_1$predicted <- predict(lm_mt2_200, newdata = df_lm_mt2_200_1)
df_lm_mt2_200_1$line_type <- "solid"

df_lm_mt2_200_2 <- data.frame(passage = as.numeric(seq(210,500,10)))
df_lm_mt2_200_2$predicted <- predict(lm_mt2_200, newdata = df_lm_mt2_200_2)
df_lm_mt2_200_2$line_type <- "dashed"

df_lm_mt2_200 <- rbind(df_lm_mt2_200_1,df_lm_mt2_200_2)
df_lm_mt2_200 %<>% mutate(line_type = factor(line_type, levels = c("solid", "dashed")))
str(df_lm_mt2_200)

#### 
df_lm_mt2_500_1 <- data.frame(passage = as.numeric(seq(10,200,10)))
df_lm_mt2_500_1$predicted <- predict(lm_mt2_500, newdata = df_lm_mt2_500_1)
df_lm_mt2_500_1$line_type <- "dashed"

df_lm_mt2_500_2 <- data.frame(passage = as.numeric(seq(210,500,10)))
df_lm_mt2_500_2$predicted <- predict(lm_mt2_500, newdata = df_lm_mt2_500_2)
df_lm_mt2_500_2$line_type <- "solid"

df_lm_mt2_500 <- rbind(df_lm_mt2_500_1,df_lm_mt2_500_2)
df_lm_mt2_500 %<>% mutate(line_type = factor(line_type, levels = c("solid", "dashed")))
str(df_lm_mt2_500)

df_lm_mt2_500 <- data.frame(passage = as.numeric(seq(210,500,10)))
df_lm_mt2_500$predicted <- predict(lm_mt2_500, new_data = seq(210,500,10))


fig <- counts_all %>%  ggplot(aes(x=passage, y = mut_count, linetype = group, color = exp_line)) +
        geom_line(linewidth=2) +
        geom_line(data = df_lm_mt4, aes(x = passage, y = predicted), color = "#00c8ff", size = 2)+
        geom_line(data = df_lm_mt2, aes(x = passage, y = predicted), color = "#ad1594c2", size = 2)+
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", linetype = "Dataset", title = paste0(category, " Mutation Accumulation _ Linear Regression"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20),breaks = seq(0,max(counts$mut_count)+20,20)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 40),
        axis.text.x = element_text(size = 30, color = "black", angle = 90),
        axis.text.y = element_text(size = 30, color = "black"),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 30))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_accumulation_regression_whole.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/", category, "_accumulation_regression_whole.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r accumulation per coding and non-coding regions normalized for length}


# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            mutate(effect_simplified2 = ifelse(effect_simplified %in% c("S","N"), "Coding", "Non-Coding")) %>%
            group_by(exp_line, passage, effect_simplified2) %>%
            summarise(count = n()) %>%
            mutate_at(4, as.numeric) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(density = ifelse(effect_simplified2 == "Coding", count*100/(9407-790),count*100/(9626-9076+789-454)))


# visualize using plotly



fig <- counts %>%  ggplot(aes(x=passage, y = density, color = exp_line, linetype = effect_simplified2)) +
        geom_line(linewidth=1) +
        labs(x="\nTransfer", y= "Normalized Mutation Count (%)\n", color = "Virus Lines", linetype = "Region",
        title = paste0("Normalized ",category, " Mutation Accumulation \n (Coding vs Non-Coding)"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$density)+1),breaks = seq(0,max(counts$density)+1,1)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir,category, "_mut_accumulation_coding_vs_noncoding.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/", category, "_mut_accumulation_coding_vs_noncoding.pdf"), height = 14, width = 14)
fig
dev.off()


```

```{r accumulation per syn and non-syn normalized for sites}

# In dn_ds.Rmd 

```
