---
title:  
    "variant freq. dynamics"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("htmlwidgets")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```


```{r read-in variant data}

# determine the server path
if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/1st-man/readin_data.R"))

```


```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/1st-man/plot_custom.R"))


```




```{r set paramters}

# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
} else if (category == "All"){
    min_threshold <- 0.01
    max_threshold <- 1.01
}

```





```{r table of fixed variants}


fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])



variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))


unique(variants_expiii[variants_expiii$mut_info %in% names(fix_count_table_list[[2]])[i],c(2,3,4,6,11,12,16,17,18,19,20)], n = 1)


df <- data.frame()


for (mut in names(setNames(unlist(fix_count_table_list, use.names = FALSE), unlist(lapply(fix_count_table_list, names))))){
    
    lines <- as.vector(table(variants_expiii$exp_line[variants_expiii$mut_info == mut & variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg]))
    occurrence <- sum(lines)
    lines <- ifelse(lines == 0, "❌", "✅")
    
    for (i in 1:nrow(unique(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(2,3,4,6,11,12,16,18,19,20)]))){
        df <- rbind(df, c(as.character(unique(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(14,15)])[i,]), mut, occurrence, lines, as.character(unique(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(2,3,4,6,11,12,16,18,19,20)])[i,])))
    }
    
    
}



colnames(df) <- c("variant_id", "annotation_id", "variant_name", "occurrence", "MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2", names(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(2,3,4,6,11,12,16,18,19,20)]))

df$genomic_pos <- as.numeric(df$genomic_pos)
df <- df[order(df$genomic_pos),]







# Create datatable with caption
table_widget <- datatable(
  df,
  caption = htmltools::tags$caption(
    style = 'caption-side: top; text-align: left; font-weight: bold;',
    "Table 2: Fixed Variants At Transfer 500"
  )
)

# Save as HTML
saveWidget(
  table_widget,
  "/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/fixed_variants.html",
  selfcontained = TRUE
)

# df$loc_in_protein[df$loc_in_protein != ""][!(as.numeric(sapply(str_split(df$loc_in_protein[df$loc_in_protein != ""], pattern = "/"), "[[", 1)) <= as.numeric(sapply(str_split(df$loc_in_protein[df$loc_in_protein != ""], pattern = "/"), "[[", 2)))]

```