---
title:  
    "Fixation dynamics based on maximum fold increase in variant frequency"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("gtools")
library("effsize")


```



```{r read-in variant data}

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}


# load data

source(paste0(wd, "src/analysis/1st-man/readin_data.R"))

```

```{r load visualization settings}
# Visual settings

source(paste0(wd, "src/analysis/1st-man/plot_custom.R"))


```

```{r max-fold-increase processing}


# # record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
# df <- data.frame()


# for (exp_line in exp_line_factor){
#     variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,]
#     fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
#     print(length(fixed_muts))

#     for (i in 1:length(fixed_muts)){
#         print(i)
#         appearance_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0.01]))) #  & variants_expiii_sub$allele_freq >= 0.01
#         fixation_psg <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$allele_freq >= 0.99])))
#         translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == fixed_muts[i]]))
        
#         psgs <- seq(appearance_psg, fixation_psg, by = 10)
#         recordings <- data.frame()
        
#         for (j in 1:(length(psgs)-1)){
#             prev_freq <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == psgs[j] & variants_expiii_sub$allele_freq >= 0.01] #  & variants_expiii_sub$allele_freq >= 0.01
#             current_freq <- variants_expiii_sub$allele_freq[variants_expiii_sub$mut_info == fixed_muts[i] & variants_expiii_sub$passage == psgs[j+1] & variants_expiii_sub$allele_freq >= 0.01] #  & variants_expiii_sub$allele_freq >= 0.01
#             if (length(c(prev_freq,current_freq)) == 2){
#                 recordings <- rbind(recordings, c(psgs[j], psgs[j+1], current_freq/prev_freq))
#             }
#         }
        
#         if (nrow(recordings) != 0){
#             df <- rbind(df, c(exp_line, fixed_muts[i], translational_impact, appearance_psg, fixation_psg, fixation_psg-appearance_psg,as.numeric(recordings[which.max(recordings[,3]),])))
#         } else {
#             df <- rbind(df, c(exp_line, fixed_muts[i], translational_impact, appearance_psg, fixation_psg, fixation_psg-appearance_psg,rep(NA,3)))
#         }
#     }
# }


# # set column names and right data types
# df %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation", "max_psg_lower", "max_psg_upper", "max_fold_change")) %>% 
#         mutate_at(4:6, as.integer) %>%
#         filter(!is.na(max_fold_change)) %>%
#         mutate(max_psg_range = paste(max_psg_lower, max_psg_upper, sep = "_")) %>%
#         mutate(max_psg_range = factor(max_psg_range),
#         exp_line = factor(exp_line, levels = exp_line_factor),
#         effect_simplified = factor(effect_simplified, levels = translational_impacts))



# df %<>% mutate(max_fold_change = as.numeric(max_fold_change))
# df %<>% mutate(max_psg_range = factor(max_psg_range, levels = mixedsort(unique(c(levels(max_psg_range),"370_380", "380_390", "390_400","420_430", "430_440", "440_450", "450_460", "460_470", "470_480", "480_490", "490_500")))))


# max_fold <- df
# head(max_fold)

# # saveRDS(df, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/max_fold_inc.rds")


```

```{r max-fold-increase figure}

max_fold <- readRDS(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/max_fold_inc.rds")

# axis text label data frame
breaks <- seq(20,490,10)

x_axis_labels <- paste0(breaks, "-", breaks+10)
x_axis_labels[seq(2,length(x_axis_labels),2)] <- ""
# summarize max-fold-increase per passage of appearance
max_fold_summary <- max_fold %>% group_by(exp_line, max_psg_lower, max_psg_range) %>%
                    summarize(Mean = mean(max_fold_change, na.rm=TRUE),
                    n = n()) %>%
                    mutate(max_psg_lower = as.numeric(max_psg_lower))

max_fold_summary$max_psg_lower <- max_fold_summary$max_psg_lower + 10

fig <- max_fold_summary %>% 
    ggplot(aes(x = max_psg_lower, y = log2(Mean), color = exp_line)) +
    # facet_wrap(~exp_line) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add regression line without confidence interval
    scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
    scale_x_continuous(limits = c(20,500), breaks = breaks, labels = x_axis_labels) +
    labs(title = "Max. fold inc. over time \n", x = "\n Transfer period", y = "Log2(Max. Fold Inc. in VF) \n",
    color = "Lineage") +
    custom_plot_theme(application = "publication")



# save figure
custom_plot_save(fig, "fixed_max_fold_change_occurrence_trend.pdf", height = 14, width = 14)

```

```{r max-fold-increase figure 2}

max_fold %<>% mutate(host_line = ifelse(exp_line %in% c("MT-2_1", "MT-2_2"), "MT-2", "MT-4")) %>% 
            mutate(host_line = factor(host_line, levels = host_factor))

# axis text label data frame
breaks <- seq(10,490,10)
x_axis_labels <- paste0(breaks, "_", breaks+10)



fig <- max_fold %>% 
    ggplot(aes(x = as.numeric(max_psg_lower), y = log10(max_fold_change), group = host_line, color = host_line, shape = effect_simplified)) +
    # facet_wrap(~exp_line) +
    geom_point(size = 6) +
    geom_smooth(method = "lm", se = FALSE) +  # Add regression line without confidence interval
    scale_color_manual(labels = host_factor, values = c("#ff8000", "#00bbff")) +
    scale_shape_manual(values = c("U", "S", "N")) +
    scale_x_continuous(limits = c(0,490), breaks = breaks, labels = x_axis_labels) +
    labs(title = "Maximum Fold Increase Trend over Time \n", x = "\n Transfer", y = "Log10(Max. Fold Inc.) \n",
    color = "Virus Line") +
    theme_bw() +
    theme(plot.title = element_text(size = 40, face = "bold", hjust = 0.5),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        axis.text.x = element_text(size = 15, color = "black", angle = 90),
        axis.text.y = element_text(size = 15, color = "black"))




```

```{r}

# significant trends over time for exp lines

modell <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$exp_line == "MT-2_1",])
summary(modell)

# significant trend over time for MT-4 lines
model_mt2 <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$host_line == "MT-2",])
model_mt4 <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$host_line == "MT-4",])
summary(model_mt4)

# significant trend over time per line

model_mt21 <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$exp_line == "MT-2_1",])
model_mt22 <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$exp_line == "MT-2_2",])
model_mt41 <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$exp_line == "MT-4_1",])
model_mt42 <- lm(log10(max_fold_change)~as.numeric(max_psg_lower), data = max_fold[max_fold$exp_line == "MT-4_2",])


summary(model_mt42)




# significant higher max fold increase in MT-2 compared to MT-4
mean(max_fold$max_fold_change[max_fold$exp_line %in% c("MT-2_1","MT-2_2")])/mean(max_fold$max_fold_change[max_fold$exp_line %in% c("MT-4_1","MT-4_2")])
wilcox.test(max_fold$max_fold_change[max_fold$exp_line %in% c("MT-2_1","MT-2_2")], max_fold$max_fold_change[max_fold$exp_line %in% c("MT-4_1","MT-4_2")])
cliff.delta(max_fold$max_fold_change[max_fold$exp_line %in% c("MT-2_1","MT-2_2")], max_fold$max_fold_change[max_fold$exp_line %in% c("MT-4_1","MT-4_2")])


```


```{r max-fold-increase per appearance time}

# summarize max-fold-increase per passage of appearance
max_fold_summary <- max_fold %>% group_by(exp_line, appearance) %>%
                    summarize(Mean = mean(max_fold_change, na.rm=TRUE),
                    n = n())


# fit linear models for each group and extract p-values
model_A <- lm(log2(Mean)~appearance, data = max_fold_summary[max_fold_summary$exp_line == exp_line_factor[1], ])
model_B <- lm(log2(Mean)~appearance, data = max_fold_summary[max_fold_summary$exp_line == exp_line_factor[2], ])
model_C <- lm(log2(Mean)~appearance, data = max_fold_summary[max_fold_summary$exp_line == exp_line_factor[3], ])
model_D <- lm(log2(Mean)~appearance, data = max_fold_summary[max_fold_summary$exp_line == exp_line_factor[4], ])


# extract the p-values
p_value_A <- summary(model_A)$coefficients[2, 4]  
p_value_B <- summary(model_B)$coefficients[2, 4]
p_value_C <- summary(model_C)$coefficients[2, 4]  
p_value_D <- summary(model_D)$coefficients[2, 4]

# create a data.frame for annotation
p_value_df <- data.frame(exp_line = exp_line_factor, p_val = c(p_value_A, p_value_B, p_value_C, p_value_D))



fig <- max_fold_summary %>% ggplot(aes(x = appearance, y = log2(Mean), color = exp_line)) +
    facet_wrap(~exp_line)+
    geom_point(aes(size = n)) +
    geom_smooth(method = "lm", se = FALSE) +
    xlim(limits = c(0,500)) +
    geom_text(data = p_value_df, aes(x = Inf, y = Inf, label = paste0("P.value = ", round(p_val, 3))),
    hjust = 1.1, vjust = 2, size = 5, inherit.aes = FALSE) +
    scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
    labs(title = "Maximum Fold Increase Based on Appearance Transfer \n", x = "\n Appearance Transfer", y = "Log2(Average Max. Fold Inc. in VF) \n",
    color = "Virus Line", size = "# Fixed Variants") +
    theme_bw() +
    theme(plot.title = element_text(size = 30, hjust = 0.5),
                axis.title.x = element_text(size = 25),
                axis.title.y = element_text(size = 25),
                axis.text.x = element_text(size = 15, color = "black", angle = 90),
                axis.text.y = element_text(size = 15, color = "black"),
                strip.text = element_text(size = 15))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "fixed_max_fold_change_per_appearance_transfer.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/fixed_max_fold_change_per_appearance_transfer.pdf"), height = 14, width = 14)
fig
dev.off()

```




```{r max-fold increase per relative order}

# df from ## Method 2 in time_to_fixation.Rmd
merged <- merge(t_2_f, max_fold[,c("exp_line", "mut_info", "max_fold_change")], by = c("exp_line", "mut_info"))


df1 <- merged[merged$Occurrence %in% c("Triple", "Quadruple"),]


for (i in 1:nrow(df1)) {
  df1$relative_order[i] <- nrow(df1[df1$exp_line == df1$exp_line[i] & df1$fixation < df1$fixation[i],])
}




df1$line_label <- df1$exp_line  # or paste shape/linetype if different


fig <- df1 %>%
    ggplot(aes(x = relative_order, y = log2(max_fold_change), color = exp_line)) +
    geom_point(aes(), size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(title = "", y = "log2(max. fold inc. in VF)\n", x = "Relative order \n(No. of prior triple/quadruple-occurrence)", color = "Lineage", linetype = "Lineage") +
    scale_color_manual(values = line_col_palette) +
    scale_x_continuous(breaks = seq(0,13, 1))+
    custom_plot_theme(application = "publication") 

# save figure
custom_plot_save(fig, "triple_quadruple_max_fold_inc_vs_relative_order.pdf", height = 14, width = 14)





# Fit a linear model for each experimental line
models <- df1 %>%
  group_by(exp_line) %>%
  do(tidy(lm(log2(max_fold_change) ~ relative_order, data = .)))

# View the p-values
models %>%
  filter(term == "relative_order") %>%
  select(exp_line, estimate, std.error, statistic, p.value)


df2 <- merged[merged$Occurrence %in% c("Single"),]


for (i in 1:nrow(df2)) {
  df2$relative_order[i] <- nrow(df2[df2$exp_line == df2$exp_line[i] & df2$fixation < df2$fixation[i],])
}

fig <- df2 %>%
    ggplot(aes(x = relative_order, y = max_fold_change, color = exp_line)) +
    geom_point(, size = 3) +
    geom_smooth(aes(group = exp_line), method = "lm", se = FALSE) +
    labs(title = "", y = "Max. fold inc. in VF\n", x = "Relative order \n (single-occurrence)", color = "Lineage", linetype = "Lineage") +
    scale_color_manual(values = line_col_palette) +
    scale_linetype_manual(values = c(1,2,3,4)) +
    scale_x_continuous(breaks = seq(0,90, 15))+
    custom_plot_theme(application = "publication") 


# save figure
custom_plot_save(fig, "single_max_fold_inc_vs_relative_order.pdf", height = 14, width = 14)

# Fit a linear model for each experimental line
models <- df2 %>%
  group_by(exp_line) %>%
  do(tidy(lm(max_fold_change ~ relative_order, data = .)))

# View the p-values
models %>%
  filter(term == "relative_order") %>%
  select(exp_line, estimate, std.error, statistic, p.value)



```