---
title:  
    "Mutation Kinetics of EXPIII"
date: 
    "June 18th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
variants_ann_expiii <- variants_ann[variants_ann$exp_line %in% 13:16,]


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# last passage 

end_passage <- 560


# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```

# Accumulation

```{r text numbers}

# set parameters
category <- "Majority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

# get numbers for in-text reporting
variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & allele_freq < max_threshold,passage == end_passage)


a <- nrow(variants_expiii_subset)
b <- length(unique(variants_expiii_subset$mut_info))


```


```{r visualization1: Accumulation plot}


# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)



# visualize 

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation in ", exp))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20),breaks = seq(0,max(counts$mut_count)+20,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


ggplotly(fig)



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_accumulation.pdf"), height = 14, width = 14)
fig
dev.off()

```



```{r visualization1: Unique mutation Accumulation plot}


# prepare data for visualization
variants_expiii_subset <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold)

for (mut in variants_expiii_subset$mut_info){
    variants_expiii_subset$appearance[variants_expiii_subset$mut_info == mut] <- min(as.numeric(as.character(variants_expiii_subset$passage[variants_expiii_subset$mut_info == mut])))
}


# prepare data for visualization
counts <- variants_expiii_subset %>%
            select(exp_line, appearance, mut_info) %>%
            distinct() %>%
            group_by(exp_line, appearance) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(appearance = as.numeric(as.character(appearance))) %>%
            mutate_at(3, as.numeric)




# visualize 

fig <- counts %>%  ggplot(aes(x=appearance, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation in ", exp))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20),breaks = seq(0,max(counts$mut_count)+20,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


ggplotly(fig)



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_appearance.pdf"), height = 14, width = 14)
fig
dev.off()

```


