---
title:  
    "Mutation landscape of EXPIII"
date: 
    "July 1st, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---



```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("RColorBrewer")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
variants_ann_expiii <- variants_ann[variants_ann$exp_line %in% 13:16,]


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# last passage 

end_passage <- 560


# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```





```{r set parameters}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
} else if (category == "All") {
    min_threshold <- 0.05
    max_threshold <- 1.01
}

# functions

`%notin%` <- Negate(`%in%`)


```

```{r first appearance of g>a mutations}


# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 570) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type)) %>%
                            filter(mut_type_sub == "G>A")

nrow(variants_expiii_sub)

# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()

for (exp_line in line_labels){
    variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$exp_line == exp_line,]
    fixed_muts <- unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub2$passage[variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.05])))
        translational_impact <- unique(as.character(variants_expiii_sub2$effect_simplified[variants_expiii_sub2$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance))
    }
}


colnames(df) <- c("exp_line", "mut", "translational_impact", "appearance")
df %<>% mutate(appearance = factor(appearance,levels = seq(10,570, 10)))

table(df$translational_impact)

fig <- ggplot(df, aes(x = appearance, group = exp_line, fill = exp_line)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Density Plot of appearance by exp_line",
    x = "Appearance",
    y = "Density",
    fill = "exp_line"
  ) +
  theme_minimal()


fig

date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "g2a_appearance_density.pdf"), height = 14, width = 14)
fig
dev.off()


```

```{r pie chart}



# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 570) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))

h_line <- "MT2"
color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
# prepare data for visualization
mut_profile_unique <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold & host_line == h_line) %>%
                            select(mut_info, mut_type_sub) %>%
                            distinct() %>%
                            group_by(mut_type_sub) %>%
                            summarise(count = n())



mut_profile_unique$mut_type_sub <- factor(mut_profile_unique$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
mut_profile_unique <- mut_profile_unique[order(mut_profile_unique$count, decreasing = TRUE),]
level_for_later <- as.character(mut_profile_unique$mut_type_sub)


color_pal <- color_pal[match(level_for_later, mut_profile_unique$mut_type_sub)]


m <- list(
    l = 10,
    r = 10,
    b = 200,
    t = 30,
    pad = 20
)

fig <- plot_ly()

fig <- fig %>% add_pie(data = mut_profile_unique, labels = ~mut_type_sub, values = ~count, sort = FALSE, textfont = list(size = 30),
                    marker = list(colors = color_pal)) %>% layout(margin = m, title = paste0("Proportion of Unique ", category, " Mutations in ", h_line))


fig


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
htmlwidgets::saveWidget(fig, file = paste0(fig_dir, "pie_", h_line,"_unique.html"))



mut_profile_unique <- rbind(mut_profile_unique, c("I", 1))
#mut_profile_unique$mut_type_sub <- factor(mut_profile_unique$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))


h_line <- "MT4"
color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
# prepare data for visualization
mut_profile_unique <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold & host_line == h_line) %>%
                            select(mut_info, mut_type_sub) %>%
                            distinct() %>%
                            group_by(mut_type_sub) %>%
                            summarise(count = n())

mut_profile_unique <- rbind(mut_profile_unique, c("I", 1))

mut_profile_unique$mut_type_sub <- factor(mut_profile_unique$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
mut_profile_unique <- mut_profile_unique[order(as.numeric(mut_profile_unique$count), decreasing = TRUE),]


color_pal <- color_pal[match(level_for_later, mut_profile_unique$mut_type_sub)]


m <- list(
    l = 10,
    r = 10,
    b = 200,
    t = 30,
    pad = 20
)

fig <- plot_ly()

fig <- fig %>% add_pie(data = mut_profile_unique, labels = ~mut_type_sub, values = ~count, sort = FALSE, textfont = list(size = 30),
                    marker = list(colors = color_pal)) %>% layout(margin = m, title = paste0("Proportion of Unique ", category, " Mutations in ", h_line))


fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
htmlwidgets::saveWidget(fig, file = paste0(fig_dir, "pie_", h_line,"_unique.html"))


```


```{r g>a overtime per translational category}




# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 150) %>%
                            mutate(mut_cat = case_when(allele_freq >= 0.05 & allele_freq < 0.5 ~ "Minority", allele_freq >= 0.5 & allele_freq < 0.99 ~ "Majority", allele_freq >= 0.99 & allele_freq < 1.01 ~ "Fixed")) %>%
                            filter(mut_cat %in% c("Minority", "Fixed")) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))
                            

variants_expiii_sub$mut_type_sub <- factor(variants_expiii_sub$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
variants_expiii_sub$mut_cat <- factor(variants_expiii_sub$mut_cat, levels = c("Minority", "Majority"))




# prepare data for visualization
mut_profile_unique <- variants_expiii_sub %>%
                            select(mut_info, host_line, mut_type_sub, passage, mut_cat) %>%
                            distinct() %>%
                            group_by(mut_type_sub, host_line, passage, mut_cat) %>%
                            summarise(count = n()) %>%
                            ungroup() %>%
                            group_by(host_line, passage, mut_cat) %>%
                            mutate(per =  100 *count/sum(count)) %>%
                            ungroup() %>%
                            complete(mut_type_sub, passage)

head(mut_profile_unique)
fig <- mut_profile_unique[mut_profile_unique$mut_type_sub == "G>A",] %>% 
                    ggplot(aes(x = passage, y = per, col = mut_cat)) +
                    geom_line(aes(group = mut_cat)) +
                    facet_wrap(~host_line) +
                    labs(title = "Proportion of G>A Mutations Over Time ") +
                    theme_minimal()+ 
                    theme(plot.title = element_text(size = 50, hjust = 0.5),
                        axis.title = element_text(size = 40),
                        axis.text.x = element_blank(),
                        axis.text.y = element_text(size = 30),
                        legend.title = element_text(size=35),
                        legend.text = element_text(size = 25))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "percentage_g_to_a.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r number of unique g2a mutations up to a certain passage}
# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 150) %>%
                            mutate(mut_cat = case_when(allele_freq >= 0.05 & allele_freq < 0.5 ~ "Minority", allele_freq >= 0.5 & allele_freq < 0.99 ~ "Majority", allele_freq >= 0.99 & allele_freq < 1.01 ~ "Fixed")) %>%
                            filter(mut_cat %in% c("Minority", "Fixed")) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))
                            


passages <- seq(10,570, 10)
diff_df <- data.frame()


for (i in 1:56){
    for (exp_line in exp_line_factor){
        unique_count_min <-  length(unique(variants_expiii_sub[variants_expiii_sub$passage <= passages[i] & variants_expiii_sub$exp_line == exp_line & variants_expiii_sub$mut_type_sub == "G>A" & variants_expiii_sub$mut_cat == "Minority","mut_info"]))
        unique_count_fix <-  length(unique(variants_expiii_sub[variants_expiii_sub$passage <= passages[i] & variants_expiii_sub$exp_line == exp_line & variants_expiii_sub$mut_type_sub == "G>A" & variants_expiii_sub$mut_cat == "Fixed","mut_info"]))

        diff_df <- rbind(diff_df, c(passages[i], exp_line, unique_count_min, unique_count_fix))

    }
    
}

colnames(diff_df) <- c("passage", "exp_line", "unique_count_min", "unique_count_fix")

fig <- diff_df %>% ggplot(aes(x = passage, y = unique_count_fix, col = exp_line)) +
                                                                        geom_line(aes(group = exp_line)) +
                                                                        geom_smooth(method = "lm", se = T) +
                                                                        theme_bw()

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "unique_up_until_passage.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r min mutation spectrum, results=TRUE}


passages <- seq(10,570, 10)
diff_df <- data.frame()



for (i in 1:56){
    for (exp_line in exp_line_factor){
        prev_in <- passages[i]
        pres_in <- passages[i+1]

        prev <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == prev_in & variants_expiii$allele_freq >= min_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line")]

        pres <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == pres_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line")]

        addition <- dplyr::setdiff(pres, prev)
        nrow(prev)

        diff_df <- rbind(diff_df, cbind(addition, passage = passages[i+1]))

    }
    
}

diff_df_sub <-  diff_df %>% mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))


counts <- diff_df_sub %>%
            group_by(exp_line, passage, mut_type_sub) %>%
            count() %>%
            dplyr::rename(count=n) %>%
            group_by(exp_line,passage) %>%
            mutate(pct =  100 *count/sum(count)) %>%
            ungroup() %>%
            mutate_at(2:3, as.factor)




color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
counts$mut_type_sub <- factor(counts$mut_type_sub, levels = level_for_later)




fig <- as.data.frame(counts) %>% ggplot(aes(x=passage, y = pct, fill = mut_type_sub)) +
                                geom_bar(position="stack", stat="identity") + 
                                facet_wrap(~exp_line) +
                                labs(x="Passage", y= "Percentage", fill = "Base Substitution", title = "Substitution Spectra of Newly Added Variants\n")+
                                scale_fill_manual(values = color_pal) +
                                theme_bw() +
                                theme(plot.title = element_text(size = 22, hjust = 0.5),
                                axis.title = element_text(size = 18),
                                axis.text.x = element_blank(),
                                axis.text.y = element_text(size = 10),
                                strip.text.x = element_text(size = 25),
                                legend.title = element_text(size=15),
                                legend.text = element_text(size = 10))

fig







# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "mut_spectra_barplot", category,".pdf"), height = 14, width = 14)
fig
dev.off()



```





```{r miscellanous}

counts[counts$mut_type_sub == "G>A" & counts$passage == 40,]


t.test(c(counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-2_2"],counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-2_2"]),c(counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-4_1"],counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-4_2"]))


# compare absolute numbers of newly added G>A mutations compared to the previous passage
str(counts)
counts %<>% 
    mutate(passage = as.numeric(as.character(passage)))
    
fig <- counts[counts$mut_type_sub == "G>A",] %>% ggplot(aes(x = passage, y = pct, col = exp_line)) +
                                                                        geom_line(aes(group = exp_line)) +
                                                                        geom_smooth(method = "lm", se = T) +
                                                                        theme_bw()

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "count_g_to_a.pdf"), height = 14, width = 14)
fig
dev.off()

```

