---
title:  
    "Mutation landscape of EXPIII"
date: 
    "July 1st, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---



```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("RColorBrewer")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))



# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```





```{r set parameters}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
} else if (category == "All") {
    min_threshold <- 0.05
    max_threshold <- 1.01
}

# functions

`%notin%` <- Negate(`%in%`)


```

```{r first appearance of g>a mutations}


# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 570) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))

nrow(variants_expiii_sub)

# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
df <- data.frame()

for (exp_line in line_labels){
    variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$exp_line == exp_line,]
    fixed_muts <- unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05])
    for (mut in fixed_muts){
        appearance <- min(as.numeric(as.vector(variants_expiii_sub2$passage[variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.05])))
        translational_impact <- unique(as.character(variants_expiii_sub2$effect_simplified[variants_expiii_sub2$mut_info == mut]))
        df <- rbind(df, c(exp_line, mut, translational_impact, appearance))
    }
}


colnames(df) <- c("exp_line", "mut", "translational_impact", "appearance")
df %<>% mutate(appearance = factor(appearance,levels = seq(10,570, 10)))

table(df$translational_impact)

fig <- ggplot(df, aes(x = appearance, group = exp_line, fill = exp_line)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Density Plot of appearance by exp_line",
    x = "Appearance",
    y = "Density",
    fill = "exp_line"
  ) +
  theme_minimal()


fig

date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "g2a_appearance_density.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r pca}

# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 500) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type)) %>%
                            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
                            select(exp_line, mut_info, mut_type_sub) %>%
                            distinct()



q <- as.matrix(table(variants_expiii_sub$exp_line, variants_expiii_sub$mut_type_sub))

p <- q/rowSums(q)


pca_result <- prcomp(q, scale = T)

summary(pca_result)

plot(pca_result, type = "l")

biplot(pca_result)
```

```{r pie chart}



# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage < ) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))

host <- "MT2"
color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
# prepare data for visualization
mut_profile_unique <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold & host_line == host) %>%
                            select(mut_info, mut_type_sub) %>%
                            distinct() %>%
                            group_by(mut_type_sub) %>%
                            summarise(count = n())



mut_profile_unique$mut_type_sub <- factor(mut_profile_unique$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
mut_profile_unique <- mut_profile_unique[order(mut_profile_unique$count, decreasing = TRUE),]
level_for_later <- as.character(mut_profile_unique$mut_type_sub)


color_pal <- color_pal[match(level_for_later, mut_profile_unique$mut_type_sub)]


m <- list(
    l = 10,
    r = 10,
    b = 200,
    t = 30,
    pad = 20
)

fig <- plot_ly()
category <- "Minority"

fig <- fig %>% add_pie(data = mut_profile_unique, labels = ~mut_type_sub, values = ~count, sort = FALSE, textfont = list(size = 25),
                    marker = list(colors = color_pal)) %>% layout(margin = m, title = paste0("Proportion of Unique ", category, " Mutations in ", host, "\n"))





# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
htmlwidgets::saveWidget(fig, file = paste0(fig_dir, "pie_", host,"_unique_", category, ".html"))





host <- "MT4"
#color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
# prepare data for visualization
mut_profile_unique <- variants_expiii_sub %>% filter(allele_freq >= min_threshold & allele_freq < max_threshold & host_line == host) %>%
                            select(mut_info, mut_type_sub) %>%
                            distinct() %>%
                            group_by(mut_type_sub) %>%
                            summarise(count = n())

mut_profile_unique <- rbind(mut_profile_unique, c("I", 1))

mut_profile_unique$mut_type_sub <- factor(mut_profile_unique$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
mut_profile_unique <- mut_profile_unique[order(as.numeric(mut_profile_unique$count), decreasing = TRUE),]


color_pal <- color_pal[match(mut_profile_unique$mut_type_sub, level_for_later)]


m <- list(
    l = 10,
    r = 10,
    b = 200,
    t = 30,
    pad = 20
)

fig <- plot_ly()

fig <- fig %>% add_pie(data = mut_profile_unique, labels = ~mut_type_sub, values = ~count, sort = FALSE, textfont = list(size = 25),
                    marker = list(colors = color_pal)) %>% layout(margin = m, title = paste0("Proportion of Unique ", category, " Mutations in ", host))




# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
htmlwidgets::saveWidget(fig, file = paste0(fig_dir, "pie_", host,"_unique_", category, ".html"))


```


```{r g>a overtime per translational category}




# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 150) %>%
                            mutate(mut_cat = case_when(allele_freq >= 0.05 & allele_freq < 0.5 ~ "Minority", allele_freq >= 0.5 & allele_freq < 0.99 ~ "Majority", allele_freq >= 0.99 & allele_freq < 1.01 ~ "Fixed")) %>%
                            filter(mut_cat %in% c("Minority", "Fixed")) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))
                            

variants_expiii_sub$mut_type_sub <- factor(variants_expiii_sub$mut_type_sub, levels = c("A>C", "A>G", "A>T", "C>A", "C>G", "C>T", "G>A", "G>C", "G>T", "T>A", "T>C", "T>G", "D", "I"))
variants_expiii_sub$mut_cat <- factor(variants_expiii_sub$mut_cat, levels = c("Minority", "Majority"))




# prepare data for visualization
mut_profile_unique <- variants_expiii_sub %>%
                            select(mut_info, host_line, mut_type_sub, passage, mut_cat) %>%
                            distinct() %>%
                            group_by(mut_type_sub, host_line, passage, mut_cat) %>%
                            summarise(count = n()) %>%
                            ungroup() %>%
                            group_by(host_line, passage, mut_cat) %>%
                            mutate(per =  100 *count/sum(count)) %>%
                            ungroup() %>%
                            complete(mut_type_sub, passage)

head(mut_profile_unique)
fig <- mut_profile_unique[mut_profile_unique$mut_type_sub == "G>A",] %>% 
                    ggplot(aes(x = passage, y = per, col = mut_cat)) +
                    geom_line(aes(group = mut_cat)) +
                    facet_wrap(~host_line) +
                    labs(title = "Proportion of G>A Mutations Over Time ") +
                    theme_minimal()+ 
                    theme(plot.title = element_text(size = 50, hjust = 0.5),
                        axis.title = element_text(size = 40),
                        axis.text.x = element_blank(),
                        axis.text.y = element_text(size = 30),
                        legend.title = element_text(size=35),
                        legend.text = element_text(size = 25))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "percentage_g_to_a.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r number of unique g2a mutations up to a certain passage}
# add subtype info
variants_expiii_sub <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            #filter(passage == 150) %>%
                            mutate(mut_cat = case_when(allele_freq >= 0.05 & allele_freq < 0.5 ~ "Minority", allele_freq >= 0.5 & allele_freq < 0.99 ~ "Majority", allele_freq >= 0.99 & allele_freq < 1.01 ~ "Fixed")) %>%
                            filter(mut_cat %in% c("Minority", "Fixed")) %>%
                            mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))
                            


passages <- seq(10,570, 10)
diff_df <- data.frame()


for (i in 1:56){
    for (exp_line in exp_line_factor){
        unique_count_min <-  length(unique(variants_expiii_sub[variants_expiii_sub$passage <= passages[i] & variants_expiii_sub$exp_line == exp_line & variants_expiii_sub$mut_type_sub == "G>A" & variants_expiii_sub$mut_cat == "Minority","mut_info"]))
        unique_count_fix <-  length(unique(variants_expiii_sub[variants_expiii_sub$passage <= passages[i] & variants_expiii_sub$exp_line == exp_line & variants_expiii_sub$mut_type_sub == "G>A" & variants_expiii_sub$mut_cat == "Fixed","mut_info"]))

        diff_df <- rbind(diff_df, c(passages[i], exp_line, unique_count_min, unique_count_fix))

    }
    
}

colnames(diff_df) <- c("passage", "exp_line", "unique_count_min", "unique_count_fix")

fig <- diff_df %>% ggplot(aes(x = passage, y = unique_count_fix, col = exp_line)) +
                                                                        geom_line(aes(group = exp_line)) +
                                                                        geom_smooth(method = "lm", se = T) +
                                                                        theme_bw()

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "unique_up_until_passage.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r min mutation spectrum, results=TRUE}


passages <- seq(10,end_psg, 10)
diff_df <- data.frame()



for (i in 1:(end_psg/10-1)){
    for (exp_line in exp_line_factor){
        prev_in <- passages[i]
        pres_in <- passages[i+1]

        prev <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == prev_in & variants_expiii$allele_freq >= min_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line")]

        pres <- variants_expiii[variants_expiii$exp_line == exp_line & variants_expiii$passage == pres_in & variants_expiii$allele_freq >= min_threshold & variants_expiii$allele_freq < max_threshold,c("genomic_pos", "ref_allele", "alt_allele", "mut_type", "exp_line")]

        addition <- dplyr::setdiff(pres, prev)
        nrow(prev)

        diff_df <- rbind(diff_df, cbind(addition, passage = passages[i+1]))

    }
    
}


diff_df_sub <-  diff_df %>% mutate(mut_type_sub = ifelse(mut_type == "P", paste0(ref_allele,">",alt_allele), mut_type))


counts <- diff_df_sub %>%
            group_by(exp_line, passage, mut_type_sub) %>%
            count() %>%
            dplyr::rename(count=n) %>%
            group_by(exp_line,passage) %>%
            mutate(pct =  100 *count/sum(count)) %>%
            ungroup() %>%
            mutate_at(2:3, as.factor)


color_pal <- c(rev(brewer.pal(n=12,"Paired")), "#ea0094", "#ae49bcab")
counts$mut_type_sub <- factor(counts$mut_type_sub, levels = level_for_later)




fig <- as.data.frame(counts) %>% ggplot(aes(x=passage, y = pct, fill = mut_type_sub)) +
                                geom_bar(position="stack", stat="identity") + 
                                facet_wrap(~exp_line) +
                                labs(x="Passage", y= "Percentage", fill = "Base Substitution", title = "Substitution Spectra of Newly Added Variants\n")+
                                scale_fill_manual(values = color_pal) +
                                theme_bw() +
                                theme(plot.title = element_text(size = 22, hjust = 0.5),
                                axis.title = element_text(size = 18),
                                axis.text.x = element_blank(),
                                axis.text.y = element_text(size = 10),
                                strip.text.x = element_text(size = 25),
                                legend.title = element_text(size=15),
                                legend.text = element_text(size = 10))

fig







# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "mut_spectra_barplot_", category,".pdf"), height = 14, width = 14)
fig
dev.off()



```


```{r tests for homogeneity and host effect}




## mixed-effect model
library(lme4)

counts <- diff_df_sub %>%
            group_by(exp_line, passage, mut_type_sub) %>%
            count() %>%
            dplyr::rename(count=n) %>%
            group_by(exp_line,passage) %>%
            mutate(pct =  count/sum(count), total = sum(count)) %>%
            ungroup() %>%
            mutate_at(2:3, as.factor)

head(counts)

counts <- counts %>%
  mutate(Successes = pct * total,
        Failures = total - Successes)


counts %<>% mutate(host = ifelse(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4"),
    exp_line = factor(exp_line, levels = line_labels[c(2,3,4,1)]))



# Chi-Square Test for Homogeneity
# Sample contingency table with counts of mutation types across time points
contingency_table <- table(diff_df_sub$mut_type_sub[diff_df_sub$exp_line == "MT-2_2"], diff_df_sub$passage[diff_df_sub$exp_line == "MT-2_2"])

# Perform the Chi-Square Test
chisq_test <- chisq.test(contingency_table)
print(chisq_test)

head(counts)
str(counts)
counts$exp_line <- as.character(counts$exp_line)
# Fit the multinomial logistic regression
multinom_model <- multinom(mut_type_sub ~ host, weights = count, data = counts)

# Likelihood ratio test to check if 'environment' has a significant effect
# Fit a reduced model (without 'environment')
multinom_model_reduced <- multinom(mut_type_sub ~ 1, weights = count, data = counts)

# Perform the likelihood ratio test
lrt_result <- anova(multinom_model_reduced, multinom_model)
print(lrt_result)


```


```{r}

# Q. Are certain mutation types more likely to be selected for and become majority/fixed in the population?

mut_sub_type_fac <- c("A>C", "A>G","A>T","C>A","C>G","C>T","G>A","G>C","G>T","T>A","T>C","T>G")

length(mut_sub_type_fac)
# count number majority/fixed mutations




min_threshold <- 0.5
max_threshold <- 1.01

mut_sub_count <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            filter(mut_type == "P",
                                allele_freq >= min_threshold & allele_freq <= max_threshold) %>%
                            mutate(mut_type_sub = paste0(ref_allele,">",alt_allele)) %>%
                            mutate(mut_type_sub = factor(mut_type_sub, levels = mut_sub_type_fac)) %>%
                            group_by(passage, exp_line, mut_type_sub, .drop = FALSE) %>%
                            summarize(count = n()) %>%
                            filter(passage == 560)

head(mut_sub_count)



# count number of unique minority


min_threshold <- 0.05
max_threshold <- 0.5

mut_sub_count_min <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            filter(mut_type == "P",
                                allele_freq >= min_threshold & allele_freq <= max_threshold) %>%
                            mutate(mut_type_sub = paste0(ref_allele,">",alt_allele)) %>%
                            mutate(mut_type_sub = factor(mut_type_sub, levels = mut_sub_type_fac)) %>%
                            select(genomic_pos, passage, exp_line, mut_type_sub) %>%
                            distinct() %>%
                            select(exp_line, mut_type_sub) %>%
                            group_by(exp_line, mut_type_sub, .drop = FALSE) %>%
                            summarize(count = n())

str(mut_sub_count_min)

mut_sub_count_min[mut_sub_count_min$exp_line == "MT-2_1",]




for (line in line_labels){
    print(line)
    for (i in mut_sub_type_fac){
        x <- matrix(c(sum(mut_sub_count_min$count[mut_sub_count_min$exp_line == line]), mut_sub_count_min$count[mut_sub_count_min$exp_line == line & mut_sub_count_min$mut_type_sub == i],
                        sum(mut_sub_count$count[mut_sub_count$passage == 560 & mut_sub_count$exp_line == line]), mut_sub_count$count[mut_sub_count$passage == 560 & mut_sub_count$exp_line == line & mut_sub_count$mut_type_sub == i]), nrow = 2, byrow = TRUE)
        pval <- fisher.test(x, alternative = "two.sided")$p.val
        print(ifelse(pval <= 0.05, paste0(i, ": ", pval), ""))
    }

}


# Q. how about for 3 nucleotide context

# define a function to format the context
context_formatter <- function(alt_allele, three_n_context) {
    return(paste0(substr(three_n_context,1,1), "[", substr(three_n_context,2,2), ">", alt_allele, "]", substr(three_n_context,3,3)))
}



reverse_complement <- function(sequences) {

    # Define the complement base pairs
    complement <- c(A = "T", T = "A", C = "G", G = "C")

    # Function to reverse complement a single sequence
    reverse_complement_single <- function(sequence) {
        sequence_split <- unlist(strsplit(sequence, ""))
        complement_sequence <- complement[sequence_split]
        reverse_complement_sequence <- rev(complement_sequence)
        return(paste(reverse_complement_sequence, collapse = ""))
    }

    # Apply the reverse_complement_single function to each sequence in the vector
    return(as.character(sapply(sequences, reverse_complement_single)))
}

context_fac <- c()
for (alt in c("A","C", "G", "T")){
    for (pos1 in c("A","C", "G", "T")){
        for (pos2 in c("C", "T")){
            for (pos3 in c("A","C", "G", "T")){
                if (alt != pos2){
                    context_fac <- append(context_fac,context_formatter(alt, paste0(pos1,pos2,pos3)))
                }
            }
        }
    }
}


# Q. how about for codon usage?



min_threshold <- 0.5
max_threshold <- 1.01

mut_sub_count <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            filter(mut_type == "P",
                                allele_freq >= min_threshold & allele_freq <= max_threshold) %>%
                            mutate(mut_context_96 = ifelse(substr(mut_context, 2, 2) %in% c("C", "T"), context_formatter(alt_allele, mut_context), context_formatter(reverse_complement(alt_allele),reverse_complement(mut_context)))) %>%
                            mutate(mut_context_96 = factor(mut_context_96, levels = context_fac)) %>%
                            group_by(passage, exp_line, mut_context_96, .drop = FALSE) %>%
                            summarize(count = n()) %>%
                            filter(passage == 560)




# count number of unique minority


min_threshold <- 0.05
max_threshold <- 0.5

mut_sub_count_min <-  variants_expiii %>% 
                            mutate(passage = as.numeric(as.character(passage))) %>%
                            filter(mut_type == "P",
                                allele_freq >= min_threshold & allele_freq <= max_threshold) %>%
                            mutate(mut_context_96 = ifelse(substr(mut_context, 2, 2) %in% c("C", "T"), context_formatter(alt_allele, mut_context), context_formatter(reverse_complement(alt_allele),reverse_complement(mut_context)))) %>%
                            mutate(mut_context_96 = factor(mut_context_96, levels = context_fac)) %>%
                            select(genomic_pos, passage, exp_line, mut_context_96) %>%
                            distinct() %>%
                            select(exp_line, mut_context_96) %>%
                            group_by(exp_line, mut_context_96, .drop = FALSE) %>%
                            summarize(count = n())




i <- "C[C>A]C"
line <- "MT-4_1"

sig <- c()
for (line in line_labels){
    print(line)
    for (i in context_fac){
        
        x <- matrix(c(sum(mut_sub_count_min$count[mut_sub_count_min$exp_line == line]), mut_sub_count_min$count[mut_sub_count_min$exp_line == line & mut_sub_count_min$mut_context_96 == i],
                        sum(mut_sub_count$count[mut_sub_count$passage == 560 & mut_sub_count$exp_line == line]), mut_sub_count$count[mut_sub_count$passage == 560 & mut_sub_count$exp_line == line & mut_sub_count$mut_context_96 == i]), nrow = 2, byrow = TRUE)
        
        pval <- fisher.test(x, alternative = "two.sided")$p.val

        if (pval <= 0.05){
            sig <- append(sig,i)
            print(i)
            print(pval)
        }
    }

}

table(sig)




```


```{r}

# Q. how about for codon usage?

# limit to 



head(variants_expiii[variants_expiii$effect_simplified == "S",])

as.numeric(sapply(str_split(variants_expiii$loc_in_cds[variants_expiii$effect_simplified == "S"], pattern = "/"), "[[", 1)) %% 3

# Let's first determine the codons

min_threshold <- 0.5
max_threshold <- 1.01


ss <- variants_expiii %>% 
    filter(mut_type == "P", effect_simplified == "S") %>%
    filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
    filter(passage == end_passage) %>%
    # filter((genomic_pos >= 790 & genomic_pos <= 2084) | (genomic_pos >= 2293 & genomic_pos <= 5041)) %>%
    mutate(pos_in_codon = as.numeric(str_split(loc_in_cds, pattern = "/")[[1]][1]) %% 3) %>%
    mutate(ref_codon = ifelse(pos_in_codon == 0, mut_3_context, NA)) %>%
    mutate(ref_codon = ifelse(pos_in_codon == 1, mut_5_context, ref_codon)) %>%
    mutate(ref_codon = ifelse(pos_in_codon == 2, mut_context, ref_codon)) %>%
    mutate(alt_codon = ifelse(pos_in_codon == 0, paste0(substr(mut_3_context, 1,2), alt_allele), NA)) %>%
    mutate(alt_codon = ifelse(pos_in_codon == 1, paste0(alt_allele, substr(mut_5_context, 2,3)), alt_codon)) %>%
    mutate(alt_codon = ifelse(pos_in_codon == 2, paste0(substr(mut_3_context, 2,2), alt_allele, substr(mut_5_context, 2,2)), alt_codon))






min_threshold <- 0.05
max_threshold <- 0.5


ss2 <- variants_expiii %>% 
    filter(mut_type == "P", effect_simplified == "S") %>%
    filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
    select(genomic_pos, ref_allele, alt_allele, exp_line, loc_in_cds, mut_context, mut_3_context, mut_5_context) %>%
    distinct() %>%
    # filter((genomic_pos >= 790 & genomic_pos <= 2084) | (genomic_pos >= 2293 & genomic_pos <= 5041)) %>%
    mutate(pos_in_codon = as.numeric(str_split(loc_in_cds, pattern = "/")[[1]][1]) %% 3) %>%
    mutate(ref_codon = ifelse(pos_in_codon == 0, mut_3_context, NA)) %>%
    mutate(ref_codon = ifelse(pos_in_codon == 1, mut_5_context, ref_codon)) %>%
    mutate(ref_codon = ifelse(pos_in_codon == 2, mut_context, ref_codon)) %>%
    mutate(alt_codon = ifelse(pos_in_codon == 0, paste0(substr(mut_3_context, 1,2), alt_allele), NA)) %>%
    mutate(alt_codon = ifelse(pos_in_codon == 1, paste0(alt_allele, substr(mut_5_context, 2,3)), alt_codon)) %>%
    mutate(alt_codon = ifelse(pos_in_codon == 2, paste0(substr(mut_3_context, 2,2), alt_allele, substr(mut_5_context, 2,2)), alt_codon))



line <- "MT-4_1"
sss <- ss[ss$exp_line == line,]
sss2 <- ss2[ss2$exp_line == line,]

sss <- ss
sss2 <- ss2
codon <- "TCC>TCT"

codon_usage_odss <- data.frame()

for (codon in names(table(paste(sss2$ref_codon, sss2$alt_codon, sep = ">")))){
    

    a <- sum(table(paste(sss$ref_codon, sss$alt_codon, sep = ">")))
    b <- as.numeric(table(paste(sss$ref_codon, sss$alt_codon, sep = ">"))[codon])
    b <- ifelse(is.na(b), 0, b)

    c <- sum(table(paste(sss2$ref_codon, sss2$alt_codon, sep = ">")))
    d <- as.numeric(table(paste(sss2$ref_codon, sss2$alt_codon, sep = ">"))[codon])

    x <- matrix(c(c,d,a,b), ncol = 2, byrow = T)

    fisher_test_res <- fisher.test(x, alternative = "two.sided")

    codon_usage_odss <- rbind(codon_usage_odss, c(codon, round(as.numeric(fisher_test_res$estimate), digits = 3), round(as.numeric(fisher_test_res$p.val), digits = 3)))
    if (fisher_test_res$p.value <= 0.05){
        print(codon)
        print(fisher_test_res)
    }
}

colnames(codon_usage_odss) <- c("codon", "odds", "p_val")

codon_usage_odss <- codon_usage_odss[order(codon_usage_odss$odds),]

codon_usage_odss$odds <- as.numeric(codon_usage_odss$odds)
codon_usage_odss$p_val <- as.numeric(codon_usage_odss$p_val)
codon_usage_odss$significant <- ifelse(codon_usage_odss$p_val <= 0.05, TRUE, FALSE)

fig <- codon_usage_odss[codon_usage_odss$odds != 0,] %>% ggplot(aes(x = reorder(codon, -odds), y = log2(odds), color = significant)) +
        geom_bar(stat = "identity") +
        geom_text(data = subset(codon_usage_odss, significant == TRUE), aes(label = codon), hjust = -0.5)+
        theme(axis.text.x = element_text(angle = 90))


date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "codon_selection_bias.pdf"), height = 14, width = 14)
fig
dev.off()


```







```{r miscellanous}

counts[counts$mut_type_sub == "G>A" & counts$passage == 40,]


t.test(c(counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-2_2"],counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-2_2"]),c(counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-4_1"],counts$pct[counts$mut_type_sub == "G>A" & counts$exp_line == "MT-4_2"]))


# compare absolute numbers of newly added G>A mutations compared to the previous passage
str(counts)
counts %<>% 
    mutate(passage = as.numeric(as.character(passage)))
    
fig <- counts[counts$mut_type_sub == "G>A",] %>% ggplot(aes(x = passage, y = pct, col = exp_line)) +
                                                                        geom_line(aes(group = exp_line)) +
                                                                        geom_smooth(method = "lm", se = T) +
                                                                        theme_bw()

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "count_g_to_a.pdf"), height = 14, width = 14)
fig
dev.off()

```

