---
title:  
    "Mutation Kinetics of EXPIII"
date: 
    "June 18th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"

# determine what data to be included

exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))



# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```



# Accumulation

```{r text numbers}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

# get numbers for in-text reporting
variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & allele_freq < max_threshold) #& mut_type == "P"


a <- nrow(variants_expiii_subset)
bb <- length(unique(paste0(variants_expiii_subset$exp_line,variants_expiii_subset$mut_info)))
b <- length(unique(variants_expiii_subset$mut_info))
variants_expiii_subset_mt2 <- variants_expiii_subset[variants_expiii_subset$host_line == "MT2",]
variants_expiii_subset_mt4 <- variants_expiii_subset[variants_expiii_subset$host_line == "MT4",]
bb_mt2 <- length(unique(paste0(variants_expiii_subset_mt2$exp_line,variants_expiii_subset_mt2$mut_info)))
bb_mt4 <- length(unique(paste0(variants_expiii_subset_mt4$exp_line,variants_expiii_subset_mt4$mut_info)))
bb_mt2/bb_mt4
b_mt2 <- length(unique(variants_expiii_subset_mt2$mut_info))
b_mt4 <- length(unique(variants_expiii_subset_mt4$mut_info))
b_mt2/b_mt4


c <- length(setdiff(unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT4"]),unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT2"])))
d <- length(setdiff(unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT2"]),unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT4"])))
e <- length(intersect(unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT2"]),unique(variants_expiii_subset$mut_info[variants_expiii_subset$host_line == "MT4"])))


```

```{r}

# plot number of unique positions that have been mutated (minority) 


variants_expiii_subset <- variants_expiii %>%
                                filter(allele_freq >= min_threshold & allele_freq < max_threshold)

# get the number 
bb <- length(unique(variants_expiii_subset$genomic_pos))

# prepare dataset
variants_expiii_subset2 <- variants_expiii_subset
variants_expiii_subset2$exp_line <- "All"

variants_expiii_subset_pooled <- rbind(variants_expiii_subset, variants_expiii_subset2)
variants_expiii_subset_pooled$passage <- as.integer(as.character(variants_expiii_subset_pooled$passage))


counts <- data.frame()
for (psg in seq(10,end_psg,10)){
    d <- variants_expiii_subset_pooled[variants_expiii_subset_pooled$passage <= psg,]
    dd <- d %>% select(genomic_pos, exp_line) %>% distinct() %>% group_by(exp_line) %>% summarise(count = n())
    dd$passage <- psg
    counts <- rbind(counts, dd)
}


fig <- counts %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Position Count\n", color = "Virus Line", title = paste0("Cumulative Number of Uniquely Mutated Positions (", category,")"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$count)+20),breaks = seq(0,max(counts$count)+20,200)) +
        scale_color_manual(labels = c(line_labels, "All"), values = c(line_palette, "black")) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_cumulative_mutated_pos.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r random sampling from pool of possible mutations modelling per host}

counts_sub <- counts[str_detect(counts$exp_line, pattern = "All"),]

counts_sub %<>% group_by(passage) %>%
        summarize(average = mean(count))


# Fit a negative exponential model
model_exp <- nls(average ~ L * (1 - exp(-K * passage)),
                data = counts_sub,
                start = list(L = 5000, K = 0.01),
                control = nls.control(maxiter = 1000))

summary(model_exp)

df <- data.frame(passage = seq(10,2000,10))

df_prediction <- data.frame(passage = seq(10,2000,10))
df_prediction$predicted_mt_2 <- predict(model_exp, newdata = df)
df_prediction$predicted_mt_4 <- predict(model_exp, newdata = df)
df_prediction$predicted_all <- predict(model_exp, newdata = df)
?rep
counts_addon <- data.frame(exp_line = rep(levels(counts$exp_line), each = 150), count = NA, passage = rep(seq(510,2000,10), 5))
counts <- rbind(counts, counts_addon)
View(counts)


fig <- counts %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
        geom_line(linewidth=2) +
        geom_line(data = df_prediction, aes(y = predicted_mt_2), color = "grey", size = 2, linetype = "dashed") +
        geom_line(data = df_prediction, aes(y = predicted_mt_4), color = "grey", size = 2, linetype = "dashed") +
        geom_line(data = df_prediction, aes(y = predicted_all), color = "grey", size = 2, linetype = "dashed") +
        labs(x="\nTransfer", y= "Position Count\n", color = "Virus Line", title = paste0("Modelling of Uniquely Mutated Positions (", category,")"))+
        scale_x_continuous(breaks = seq(0,2000,100)) +
        scale_y_continuous(limits = c(0,max(counts$count+1000, na.rm=T)+20),breaks = seq(0,max(counts$count+1000, na.rm=T)+20,200)) +
        scale_color_manual(labels = c(line_labels, "All"), values = c(line_palette, "black")) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_cumulative_mutated_pos_models.pdf"), height = 14, width = 14)
fig
dev.off()

```

```{r visualization1: Accumulation plot}


# prepare data for visualization
counts <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            group_by(exp_line, passage, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(3, as.numeric)



# visualize 

fig <- counts %>%  ggplot(aes(x=passage, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0(category, " Mutation Accumulation"))+
        scale_x_continuous(breaks = seq(0,570,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+20),breaks = seq(0,max(counts$mut_count)+20,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


ggplotly(fig)



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_accumulation.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r visualization1: cumulative plot of unique mutations}



df <- data.frame()
variants_expiii_subset <- variants_expiii %>% mutate(passage = as.numeric(as.character(passage)))

for (exp_line in exp_line_factor){
    for (passage in seq(10,end_psg, 10)){
        count <- length(unique(variants_expiii_subset$mut_info[variants_expiii_subset$allele_freq >= 0.05 & variants_expiii_subset$passage <= passage & variants_expiii_subset$exp_line == exp_line & variants_expiii_subset$mut_type == "P"]))
        df <- rbind(df, c(exp_line, passage, count))
    }
}

df %<>% set_colnames(c("exp_line", "passage", "count")) %>%
            mutate_at(2:3, as.numeric)

# visualize 

fig <- df %>%  ggplot(aes(x=passage, y = count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0("Number of unique point mutations (",category,")"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(df$count)+20),breaks = seq(0,max(df$count)+20,50)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_unique_recorded.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r visualization1: Unique mutation appearance plot}



# prepare data for visualization
variants_expiii_subset <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold)



for (line in line_labels){
    variants_expiii_subset2 <- variants_expiii_subset[variants_expiii_subset$exp_line == line,]
    for (mut in unique(variants_expiii_subset2$mut_info)){
        variants_expiii_subset$appearance[variants_expiii_subset$mut_info == mut & variants_expiii_subset$exp_line == line] <- min(as.numeric(as.character(variants_expiii_subset2$passage[variants_expiii_subset2$mut_info == mut])))
    }
}

variants_expiii_subset$appearance <- factor(variants_expiii_subset$appearance, levels = seq(10,end_psg,10))

variants_expiii_subset2 <- variants_expiii_subset
variants_expiii_subset2$exp_line <- "All"
variants_expiii_subset <- rbind(variants_expiii_subset, variants_expiii_subset2)

# prepare data for visualization
counts <- variants_expiii_subset %>%
            select(exp_line, appearance, mut_info) %>%
            distinct() %>%
            group_by(exp_line, appearance, .drop = FALSE) %>%
            count() %>%
            dplyr::rename(mut_count = n) %>%
            mutate(host_line = ifelse(exp_line %in% c("MT-2_1","MT-2_2"), "MT2", "MT4")) %>%
            mutate_at(c(1,4), as.factor) %>%
            mutate(appearance = as.numeric(as.character(appearance))) %>%
            mutate_at(3, as.numeric)


# visualize 

low<-findInterval(max(counts$mut_count),c(5,10,20,50,100))
step <- c(5,10,20,50,100)[low - 1]

fig <- counts %>%  ggplot(aes(x=appearance, y = mut_count, color = exp_line)) +
        geom_line(linewidth=2) +
        labs(x="\nTransfer", y= "Mutation Count\n", color = "Virus Line", title = paste0("Appearance of Unique ", category, " Mutations"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$mut_count)+step),breaks = seq(0,max(counts$mut_count)+step,step)) +
        scale_color_manual(labels = c(line_labels, "All"), values = c(line_palette, "black")) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


ggplotly(fig)



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_appearance.pdf"), height = 14, width = 14)
fig
dev.off()

```

```{r visualization1: throughout venn diagram}

# prepare data for visualization
variants_expiii_subset <- variants_expiii %>%
            filter(allele_freq >= min_threshold & allele_freq < max_threshold)

# uniqueness of majority mutations observed throughout the experiment
throughout <- variants_expiii_subset %>%
                select(c(exp_line,mut_info)) %>%
                distinct()


#table(as.numeric(table(par_whole$mut_info)))

# create a named vector from the df
muts <- throughout$mut_info
names(muts) <- throughout$exp_line

# convert named vector to list
muts_list <- lapply(split(muts, names(muts)), unname)


# visualization
fig <- ggvenn(muts_list) +
        labs(title = paste0(category, " Mutations Occurrence Venn Diagram"))+
        theme(plot.title = element_text(size = 20, hjust = 0.5),
        plot.margin = unit(c(1,1,1,1), "cm"))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, category, "_occurrence_venn.pdf"), height = 14, width = 14)
fig
dev.off()

```



```{r}



# prepare data for visualization
counts <- variants_ann_expiii%>% 
              filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
              mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
              mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
              group_by(exp_line, passage, effect_simplified) %>%
              summarise(nr_majority = n()) %>%
              mutate_at(4, as.numeric) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
              mutate_at(c(1,3), as.factor)
              
# visualize using plotly




fig <- counts %>%  ggplot(aes(x=passage, y = nr_majority, color = exp_line, linetype = effect_simplified)) +
        geom_line(linewidth=1) +
        labs(x="\nTransfer", y= "Mutation Count\n",  color = "Virus Lines", linetype = "Translational Impact",
        title = paste0(category, " Mutation Accumulation Based on Translational Effect"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$nr_majority)+10),breaks = seq(0,max(counts$nr_majority)+10,10)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir,category, "_accumulation_translational_impact.pdf"), height = 21, width = 21)
fig
dev.off()

```


```{r}


# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
            mutate(effect_simplified2 = ifelse(effect_simplified %in% c("S","N"), "S/N", "U")) %>%
            group_by(exp_line, passage, effect_simplified2) %>%
            summarise(count = n()) %>%
            mutate_at(4, as.numeric) %>%
            mutate(passage = as.numeric(as.character(passage))) %>%
            mutate_at(c(1,3), as.factor) %>%
            mutate(density = ifelse(effect_simplified2 == "S/N", count*100/(9407-790),count*100/(9626-9076+789-454)))


# visualize using plotly



fig <- counts %>%  ggplot(aes(x=passage, y = density, color = exp_line, linetype = effect_simplified2)) +
        geom_line(linewidth=1) +
        labs(x="\nTransfer", y= "Normalized Mutation Count\n", color = "Virus Lines", linetype = "Translational Impact",
        title = paste0("Normalized ",category, " Mutation Accumulation Based on Translational Effect"))+
        scale_x_continuous(breaks = seq(0,end_psg,50)) +
        scale_y_continuous(limits = c(0,max(counts$density)+1),breaks = seq(0,max(counts$density)+1,1)) +
        scale_color_manual(labels = line_labels, values = line_palette) +
        theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir,category, "_mut_accumulation_translational_impact_u_vs_ns.pdf"), height = 21, width = 21)
fig
dev.off()

```