---
title:  
    "Mutation distribution of EXPIII"
date: 
    "July 1st, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---



```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")

#functions

`%notin%` <- Negate(`%in%`)

```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 


# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")

feature_factor <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "env", "tat2", "rev2", "nef_only", "nef_3UTR", "3UTR", "3R")
feature_start <- c(454,551,635,790,2085,5041,5559,5830,5969,6061,6221,8369,8369,8787,9076,9408,9529)
feature_end <- c(550,634,789,2292,5096,5619,5849,6044,6044,6306,8785,8414,8643,9075,9407,9528,9625)


feature_df <- data.frame(feature = feature_factor,
                            start = feature_start,
                            end = feature_end,
                            length = feature_end - feature_start + 1)

feature_df <- rbind(feature_df, c("tat", sum(feature_df$length[feature_df$feature %in% c("tat1", "tat2")])))
feature_df$length <- as.numeric(feature_df$length)
feature_df <- rbind(feature_df, c("rev", sum(feature_df$length[feature_df$feature %in% c("rev1", "rev2")])))
feature_df$length <- as.numeric(feature_df$length)

feature_df <- feature_df[feature_df$feature %notin% c("tat1", "tat2", "rev1", "rev2"),]

feature_factor_new <- c("5R","5UTR", "5LTRLS", "gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "env", "nef_only", "nef_3UTR", "3UTR", "3R")


# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))




# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```




```{r set parameters}

# set parameters
category <- "Minority"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}



```


```{r number of mutations per genomic feature}


possible_muts <- c(0.22*3, 0.78*3, 1*3)
names(possible_muts) <- c("S", "N", "U")
variants_ann_expiii$feature[variants_ann_expiii$feature == "envelope"] <- "env"
variants_ann_expiii$feature[variants_ann_expiii$genomic_pos >= 9076 & variants_ann_expiii$genomic_pos <= 9407] <- "nef_3UTR"
variants_ann_expiii$feature[variants_ann_expiii$genomic_pos >= 8787 & variants_ann_expiii$genomic_pos <= 9075] <- "nef_only"
# prepare data for visualization
variants_ann_expiii$possible_muts <- possible_muts[as.character(variants_ann_expiii$effect_simplified)]



counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            #filter(passage == end_psg) %>%
            select(exp_line, mut_info, feature, effect_simplified, possible_muts) %>%
            distinct() %>%
            group_by(exp_line, feature, effect_simplified, possible_muts) %>%
            summarise(count = n()) %>%
            mutate_at(c(1,2,3), as.factor) %>%
            left_join(feature_df[,c("feature", "length")], by = join_by(feature == feature)) %>%
            mutate(feature = factor(feature, levels = feature_factor_new)) %>%
            mutate(normalized_count = (count*100)/round(length*possible_muts))

# make the visualization
fig <- ggplot(counts[counts$feature %notin% c("5R", "3R"),]) +
    geom_bar(aes(x = effect_simplified, y = normalized_count, fill = exp_line),
            position = "stack",
            stat = "identity") +
    scale_fill_manual(labels = line_labels, values = line_palette) +
    labs(x = "Genomic Features", y = "Normalized Minority Count (%)", fill = "Virus Line", title = paste0(category, " Mutation Distribution \n"))+
    facet_grid(~ feature, switch = "x") +
    theme_bw()+
    theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, color = "white"),
        panel.spacing = unit(0.2,"cm"))+
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, face="bold"),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=90),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 35))

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "mutation_distribution_", category,".pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/mutation_distribution_", category,".pdf"), height = 14, width = 14)
fig
dev.off()



```

```{r}

head(counts)
library(tibble)

counts %<>% mutate(fef = paste(feature, effect_simplified, sep = "_")) %>%
        ungroup() %>%
        select(exp_line, normalized_count, fef) %>%
        pivot_wider(names_from = fef, values_from = normalized_count) %>%
        column_to_rownames(var = "exp_line")

counts_mx <- as.matrix(counts)

counts_mx[is.na(counts_mx)] <- 0

counts_mx_p <- counts_mx/rowSums(counts_mx)

pca_result <- prcomp(counts_mx_p, scale = T)

summary(pca_result)

plot(pca_result, type = "l")

biplot(pca_result)

```

```{r number of mutations per genomic feature over time}



# prepare data for visualization
counts <- variants_ann_expiii %>% 
            filter(allele_freq >= min_threshold & allele_freq < max_threshold) %>%
            filter(passage %in% seq(100,end_psg,100)) %>%
            group_by(exp_line, passage, feature, effect_simplified) %>%
            summarise(count = n()) %>%
            mutate_at(1:4, as.factor) %>%
            left_join(feature_df, by = join_by(feature == feature)) %>%
            mutate(normalized_count = count*100/length)


# make the visualization
fig <- ggplot(counts) +
    geom_bar(aes(x = effect_simplified, y = normalized_count, fill = exp_line),
        position = "stack",
        stat = "identity") +
    scale_fill_manual(labels = line_labels, values = line_palette) +
    labs(x = "Genomic Features and Passage", y = "Normalized Count", fill = "Line")+
    facet_grid(~ feature + passage, switch = "x") +
    theme_bw()+
    theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, color = "white"),
        panel.spacing = unit(0.2,"cm"))+
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, face="bold"),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=90),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 35))

fig

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "mutation_distribution_overtime_", category,".pdf"), height = 35, width = 35)
fig
dev.off()


```