---
title:  
    "nef deletions in EXPIII"
date: 
    "Oct 31st, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r}

library(RColorBrewer)


```

```{r}


nef_deletions <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/nef_deletions.tsv", sep = "", header = T)



nef_deletions %<>% 
    mutate(length = end - start,
    right_vf = 1 - coverage_after_start/coverage_before_start,
    left_vf = 1 - coverage_before_end/coverage_after_end) %>%
    mutate(consensus_vf = rowMeans(select(.,right_vf, left_vf), na.rm = T),
    deletion_id = paste0(deletion_id, "_", start, ":", end),
    deletion_id = as.factor(deletion_id)) 


del <- levels(nef_deletions$deletion_id)[1]

for (del in levels(nef_deletions$deletion_id)){
    max_record <- max(nef_deletions$passage[nef_deletions$deletion_id == del])
    next_psgs <- seq(max_record,500,10)
    row_to_repeat <- nef_deletions[nef_deletions$deletion_id == del & nef_deletions$passage == max_record,]
    repeated_df <- bind_rows(replicate(length(next_psgs), row_to_repeat, simplify = FALSE))
    repeated_df$passage <- next_psgs
    nef_deletions <- rbind(nef_deletions, repeated_df)
}

nef_deletions$line_type <- "solid"

for (del in levels(nef_deletions$deletion_id)){
    min_record <- min(nef_deletions$passage[nef_deletions$deletion_id == del])
    prev_psgs <- seq(10,min_record,10)
    row_to_repeat <- nef_deletions[nef_deletions$deletion_id == del & nef_deletions$passage == min_record,]
    repeated_df <- bind_rows(replicate(length(prev_psgs), row_to_repeat, simplify = FALSE))
    repeated_df$passage <- prev_psgs
    repeated_df$consensus_vf[1:(length(prev_psgs)-1)] <- 0
    repeated_df$line_type <- "dashed"
    nef_deletions <- rbind(nef_deletions, repeated_df)
}


nef_deletions$line_type <- factor(nef_deletions$line_type, levels = c("solid", "dashed"))


fig <- nef_deletions %>% 
    ggplot(aes(x = passage, y = consensus_vf, color = deletion_id, linetype = line_type)) + 
    labs(x="\nTransfer", y= "Deletion Frequency\n",  color = "Deletion ID") +
    ggtitle(expression("Frequency of " * italic("nef") * " Large Deletions in MT-2_1")) +
    guides(linetype = "none") +
    scale_color_manual(values=brewer.pal(5, "Dark2")) +
    geom_line() +
    theme_bw() +
        theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15))



date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "MT-2_1_nef_deletion.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/MT-2_1_nef_deletion.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r}



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])


variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info))



variants_expiii_subset_mt21 <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts & variants_expiii_subset$exp_line == "MT-2_1",c("exp_line", "passage", "allele_freq", "mut_info")]
colnames(variants_expiii_subset_mt21)[4] <- "variant_info"
variants_expiii_subset_mt21$line_type <- "solid"
variants_expiii_subset_mt21$mut_type <- "Substitutions"
variants_expiii_subset_mt21$mut_type2 <- "Substitutions"

nef_deletions_subset <- nef_deletions[,c("exp_line", "passage", "consensus_vf", "deletion_id", "line_type")]
colnames(nef_deletions_subset)[3] <- "allele_freq"
colnames(nef_deletions_subset)[4] <- "variant_info"
nef_deletions_subset$mut_type <- nef_deletions_subset$variant_info
nef_deletions_subset$mut_type2 <- "LD"
# nef_deletions_subset$passage[nef_deletions_subset$variant_info == "2_9224:9246"] <- nef_deletions_subset$passage[nef_deletions_subset$variant_info == "2_9224:9246"] + 30
# nef_deletions_subset <- nef_deletions_subset[nef_deletions_subset$passage <= 500,]

# colnames(variants_expiii_subset_mt21) == colnames(nef_deletions_subset)

all <- rbind(variants_expiii_subset_mt21, nef_deletions_subset)

all$mut_type2 <- factor(all$mut_type2, levels = c("Substitutions", "LD"))
all$mut_type <- factor(all$mut_type, levels = c("Substitutions", "1_9102:9223", "2_9224:9246", "3_9392:9418", "4_8859:9039", "5_8790:8858"))
all$passage <- as.numeric(as.character(all$passage))

fig <- all %>% ggplot(aes(x = passage, y = allele_freq, group = variant_info, color = mut_type)) +
    geom_line(aes(alpha = mut_type2, linewidth = mut_type2)) +
    facet_wrap(~exp_line, ncol = 1) +
    labs(title = "Variant Frequency Trajectories Overlaid by \n Large Deletion Frequencies \n", y = "Frequency \n", x = "\n Passage", color = "Mutation") +
    scale_x_continuous(breaks = seq(0,500, 50))+
    scale_color_manual(values = c("#67000D",brewer.pal(5, "Dark2"))) +
    scale_alpha_manual(values = c(0.15,1)) +
    scale_linewidth_manual(values = c(1,2))+
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
            axis.title = element_text(size = 45),
            axis.text.x = element_text(size = 20, angle = 90),
            axis.text.y = element_text(size = 30),
            strip.text.x = element_text(size = 35, angle=0),
            legend.title = element_text(size=40),
            legend.text = element_text(size = 35))



date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "MT-2_1_nef_deletion_overlaid_fixed_mutations.pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r later to remove variants occurring in deleted regions}


lis <- names(table(nef_deletions$deletion_id))
for (line in exp_line_factor){
  for (id in lis){
    print(id)
    df_sub <- nef_deletions[nef_deletions$exp_line == line & nef_deletions$deletion_id == id,]
    print(df_sub$passage[which.max(df_sub$consensus_vf)-1])
    nef_deletions$purge_psg[nef_deletions$exp_line == line & nef_deletions$deletion_id == id] <- df_sub$passage[which.max(df_sub$consensus_vf)-1]
  }

}

nef_deletions_distinct <- unique(nef_deletions[,c("exp_line", "start", "end", "purge_psg")])
i <- 1
for (i in 1:nrow(nef_deletions_distinct)){
  variants_expiii %<>% filter(!(exp_line == nef_deletions_distinct$exp_line[i] & passage > nef_deletions_distinct$purge_psg[i] & genomic_pos >= nef_deletions_distinct$start[i] & genomic_pos <= nef_deletions_distinct$end[i]))
}

```