---
title:  
    "Parallel evolution of EXPIII"
date: 
    "June 30th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("reshape2")
library("ggvenn")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("effsize")


```


```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 

# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))




# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```





```{r set parameters}

# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}

```


```{r venn diagram}


end_fixed <- 
        variants_expiii %>%
        filter(allele_freq >= min_threshold, allele_freq < max_threshold, passage == end_psg) %>%
        select(c(exp_line,mut_info)) %>%
        distinct()

nrow(end_fixed)

# percentage of line specific mutations
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 1)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 2)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 3)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))
sum(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))) == 4)/length(rowSums(as.matrix(table(end_fixed$mut_info, end_fixed$exp_line))))


#table(as.numeric(table(par$mut_info)))


# create a named vector from the df
muts <- end_fixed$mut_info
names(muts) <- end_fixed$exp_line

# convert named vector to list
muts_list <- lapply(split(muts, names(muts)), unname)


# visualization
fig <- ggvenn(muts_list) +
        labs(title = paste0(category, " Mutations at Transfer #", end_psg))+
        scale_fill_manual(labels = line_labels, values = line_palette) +
        theme(plot.title = element_text(size = 20, hjust = 0.5),
        plot.margin = unit(c(1,1,1,1), "cm"))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "parallel_venn.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r parallelism simulations}


effect_list <- list(Syn = "S", Non_Syn = "N", Untranslated = "U", All = c("S", "N", "U"))

overall_df <- data.frame()

for (k in 1:4){
    effect <- effect_list[k]
    print(effect)



    # Nr of unique mutations with af >= 0.05
    variants_expiii$passage <- as.integer(as.character(variants_expiii$passage))
    variants_expiii$effect_simplified <- as.character(variants_expiii$effect_simplified)

    # filter for relevant mutations
    variants_expiii_sub <- variants_expiii[variants_expiii$effect_simplified %in% effect[[1]] & variants_expiii$mut_type == "P",]




    df <- data.frame()

    for (line1 in exp_line_factor){
        for (line2 in exp_line_factor){
            exp_all <- data.frame()
            for (base in c("A", "C", "G", "T")){
                variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$ref_allele == base,]
                a <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage <= end_psg]))
                aa <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage <= end_psg]))
                b <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage == end_psg]))
                bb <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage == end_psg]))
                
                c <- length(intersect(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage <= end_psg],variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage <= end_psg]))
                d <- length(intersect(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage == end_psg]),
                unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage == end_psg])))

                i <- 0
                mean(exp_base)
                exp_base <- integer()
                while (i <= 1000){
                    i <- i + 1
                    j <- sample(1:(a+aa-c), size = b+bb, replace = F)
                    k <- sample(1:aa, size = bb, replace = F)
                    exp_base <- c(exp_base,sum(intersect(j,k)<=c))
                }

                exp_all <- rbind(exp_all, exp_base)
            }
            
            exp_shared <- colSums(exp_all)
            obs_all <- length(unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1,line2) & variants_expiii_sub$passage == end_psg]))
            obs_shared <- length(intersect(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage == end_psg],variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage == end_psg]))
            
            # Calculate mean and standard deviation
            mean_data <- mean(exp_shared)
            sd_data <- sd(exp_shared)
            # Calculate the z-score
            z_score <- (obs_shared - mean_data) / sd_data
            # Calculate the p-value
            p_value <- 2 * (1 - pnorm(abs(z_score)))
            df <- rbind(df,c(line1,line2,obs_all,obs_shared,obs_shared/obs_all,mean_data/obs_all,p_value))
        }
    }

    df %<>% set_colnames(c("Var1", "Var2", "total_unique", "shared", "%shared", "expected_%shared", "p.val"))

    #######################
    
    # uniqueness of majority mutations observed at the end of experiment
    end_fixed <- variants_expiii_sub %>%
                            filter(allele_freq >= min_threshold, allele_freq < max_threshold, passage == end_psg) %>%
                            select(c(exp_line,mut_info)) %>%
                            distinct()




    # create a named vector from the df
    muts <- end_fixed$mut_info
    names(muts) <- end_fixed$exp_line

    # convert named vector to list
    muts_list <- lapply(split(muts, names(muts)), unname)


    shared_percent <- c()


    for (i in 1:4){
            dd <- muts_list[[i]]
            for (j in 1:4){
                if (i<=j){
                    shared_percent <- append(shared_percent,100*(sum(dd %in% muts_list[[j]])/(length(muts_list[[i]])+length(muts_list[[j]])-sum(dd %in% muts_list[[j]]))))
                } else {shared_percent <- append(shared_percent,NA)}
            }
            
    }


    shared_mat <- matrix(shared_percent, ncol = 4)
    row.names(shared_mat) <- exp_line_factor
    colnames(shared_mat) <- exp_line_factor

    shared_df <- as.data.frame(shared_mat) %>% 
                            `colnames<-`(names(muts_list)) %>%
                            mutate(line1 = names(muts_list)) %>%
                            mutate(line1 = factor(line1, levels = exp_line_factor)) %>%
                            gather(key = "line2", value = "val", 1:4) %>%
                            mutate(line2 = factor(line2, levels = exp_line_factor)) %>%
                            mutate(val = round(val, 2))



    melted_cormat <- melt(shared_mat, na.rm = TRUE)

    melted_cormat$value <- round(melted_cormat$value, digits = 1)

    # merge simulation data


    melted_cormat <- merge(melted_cormat, df[,c(1,2,6,7)], by = c("Var1", "Var2"))
    melted_cormat <- melted_cormat %>%
        mutate(p.val = as.numeric(p.val)) %>%
        mutate(p_value_category = case_when(
            p.val >= 0.05 ~ "n.s.",
            p.val >= 0.01 & p.val < 0.05 ~ "*",
            p.val >= 0.001 & p.val < 0.01 ~ "**",
            p.val < 0.001 ~ "***"
        ))

    melted_cormat$`expected_%shared` <- round(as.numeric(melted_cormat$`expected_%shared`)*100, digits = 1)
    melted_cormat$`expected_%shared`[melted_cormat$val == 100] <- 100
    melted_cormat$p_value_category[melted_cormat$val == 100] <- ""

    fig <- ggplot(data = as.data.frame(melted_cormat), aes(x=Var1, y=Var2, fill=value)) + 
            geom_tile(color = "white") +
            geom_text(aes(Var1, Var2, label = paste0(value, "(", `expected_%shared`,")\n", p_value_category)), color = "black", size = 13) +
            labs(title = paste0("Fixed ", names(effect)[1], " Mutation Parallelism at Passage #", end_psg)) +
            scale_fill_gradient2(low = "white", high = "red", 
            midpoint = 1, limit = c(0,100), space = "Lab", 
            name="Shared %") +
            theme_minimal()+ 
            theme(plot.title = element_text(size = 40, hjust = 0.5),
                axis.title = element_blank(),
                axis.text.x = element_text(size = 30, angle = 90),
                axis.text.y = element_text(size = 30),
                legend.title = element_text(size=35),
                legend.text = element_text(size = 25)) +
            coord_fixed()



    # save figure
    date <- str_split(Sys.time(), pattern = " ")[[1]][1]
    fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
    ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
    pdf(file = paste0(fig_dir, "parallel_heatmap_", names(effect),".pdf"), height = 14, width = 14)
    print(fig)
    dev.off()
    
    #######################

    obs <- melted_cormat$value[melted_cormat$value != 100]
    mean_obs <- mean(obs)
    se_obs <- sd(obs)/sqrt(length(obs))
    exp <- melted_cormat$`expected_%shared`[melted_cormat$value != 100]
    mean_exp <- mean(exp)
    se_exp <- sd(exp)/sqrt(length(exp))

    test_res <- t.test(obs, exp)


    cohen_d <- cohen.d(obs, exp, paired=TRUE)


    p_val <- test_res$p.value

    overall_df <- rbind(overall_df, c(names(effect), "Observed", mean_obs, se_obs, p_val, cohen_d$estimate))
    overall_df <- rbind(overall_df, c(names(effect), "Simulated", mean_exp, se_exp, p_val, cohen_d$estimate))

}
```




```{r}

colnames(overall_df) <- c("Translation_impact", "group", "mean", "se", "p.val", "cohen_d")


overall_df %<>% mutate_at(1, as.factor)
overall_df$group <- factor(overall_df$group, levels = c("Observed", "Simulated"))
overall_df %<>% mutate_at(3:6, as.numeric)


fig <- ggplot(overall_df, aes(x = Translation_impact, y = mean, fill = group)) +
    geom_col(position = "dodge") +
    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), position = position_dodge(width = 0.9),width = 0.2) +
    labs(title = paste0("Summary of Parallelism at Tranfer #", end_psg), y = "Shared(%)\n", x = "\nTranslational Impact") +
    scale_fill_manual(name = "Group",  # Change the legend title here
        values = c("#038331", "#8fff50"),
        labels = c("Observed", "Simulated"))+
    theme_minimal()+ 
        theme(plot.title = element_text(size = 40, hjust = 0.5),
            axis.title = element_text(size = 30),
            axis.text.x = element_text(size = 20, angle = 90),
            axis.text.y = element_text(size = 20),
            legend.title = element_text(size=35),
            legend.text = element_text(size = 25))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "parallel_summary_barplot.pdf"), height = 14, width = 14)
fig
dev.off()


```




```{r}

k <- 4
line1 <- "MT-2_1"
line2 <- "MT-2_2"
end_psg <- 150

for (k in 4){
    df <- data.frame()
    effect <- effect_list[k]
    print(effect)

    # Nr of unique mutations with af >= 0.05
    variants_expiii$passage <- as.integer(as.character(variants_expiii$passage))
    variants_expiii$effect_simplified <- as.character(variants_expiii$effect_simplified)

    # filter for relevant mutations
    variants_expiii_sub <- variants_expiii[variants_expiii$effect_simplified %in% effect[[1]] & variants_expiii$mut_type == "P",]


    for (end_psg in seq(10,500,10)){
        print(end_psg)

        for (line1 in exp_line_factor){
            for (line2 in exp_line_factor){
                exp_all <- data.frame()
                for (base in c("A", "C", "G", "T")){
                    variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$ref_allele == base,]
                    a <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage <= end_psg]))
                    aa <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage <= end_psg]))
                    b <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage == end_psg]))
                    bb <- length(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage == end_psg]))
                    
                    c <- length(intersect(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage <= end_psg],variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.05 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage <= end_psg]))
                    d <- length(intersect(unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line1) & variants_expiii_sub2$passage == end_psg]),
                    unique(variants_expiii_sub2$mut_info[variants_expiii_sub2$allele_freq >= 0.99 & variants_expiii_sub2$exp_line %in% c(line2) & variants_expiii_sub2$passage == end_psg])))

                    i <- 0
                    
                    exp_base <- integer()
                    while (i <= 1000){
                        i <- i + 1
                        j <- sample(1:a, size = b, replace = F)
                        k <- sample(1:aa, size = bb, replace = F)
                        exp_base <- c(exp_base,sum(intersect(j,k)<=c))
                    }

                    exp_all <- rbind(exp_all, exp_base)
                }
                
                obs_all_vec <- c()
                obs_shared_vec <- c()

                exp_shared <- colSums(exp_all)
                obs_all_vec <- unique(append(obs_all_vec, unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1,line2) & variants_expiii_sub$passage == end_psg])))
                obs_all <- length(obs_all_vec)
                obs_shared_vec <- unique(append(obs_shared_vec, intersect(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line1) & variants_expiii_sub$passage == end_psg],variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99 & variants_expiii_sub$exp_line %in% c(line2) & variants_expiii_sub$passage == end_psg])))
                obs_shared <- length(obs_shared_vec)
                
                
                # Calculate mean and standard deviation
                mean_data <- mean(exp_shared)
                sd_data <- sd(exp_shared)
                # get CI
                result <- t.test(exp_shared, conf.level = 0.95)
                CIs <- as.numeric(result$conf.int)
                # Calculate the z-score
                z_score <- (obs_shared - mean_data) / sd_data
                # Calculate the p-value
                p_value <- 2 * (1 - pnorm(abs(z_score)))
                df <- rbind(df,c(line1,line2,end_psg,obs_all,obs_shared,obs_shared/obs_all,mean_data/obs_all,p_value, CIs[1]/obs_all, CIs[2]/obs_all))
            }
        }

        df %<>% set_colnames(c("Var1", "Var2", "passage", "total_unique", "shared", "pct_shared", "expected_pct_shared", "p.val", "CI_lower", "CI_upper"))
        write.table(df, file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/",names(effect),"_parallelism_temporal_simulation.tsv"), sep = "\t")
    }
}

k <- 4
effect <- effect_list[k]
df <- read.table(file = paste0("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/",names(effect),"_parallelism_temporal_simulation.tsv"), sep = "\t", header = T)

df_long <- df %>% 
    mutate(Pair = paste0(Var1, "vs", Var2)) %>% 
    filter((Pair %in% c("MT-4_1vsMT-4_2", "MT-2_1vsMT-2_2"))) %>%
    pivot_longer(cols = c(pct_shared, expected_pct_shared), names_to = "group", values_to =  "shared_all")

df_long %<>% 
    mutate_at(c(3,7,8,11), as.numeric) %>%
    mutate(shared_all = round(100*shared_all, digits = 2),
    CI_lower = round(100*CI_lower, digits = 2),
    CI_upper = round(100*CI_upper, digits = 2)) %>%
    mutate(group2 = case_when(group == "pct_shared" ~ "Observed", group == "expected_pct_shared" ~ "Expected")) %>%
    select(c(Pair, passage, group2, CI_lower,CI_upper, shared_all, total_unique)) %>%
    mutate_at(c(1), as.factor) %>%
    mutate(group2 = factor(group2, levels = c("Observed", "Expected")))

df_long$group2 <- factor(df_long$group2, levels = c("Observed", "Expected"))

fig <- df_long %>% 
    ggplot(aes(x = passage, y = shared_all, group = interaction(Pair,group2), color = Pair, linetype = group2)) +
    geom_line() +
    # geom_smooth(method = "loess") +
    geom_ribbon(
        data = df_long %>% filter(group2 == "Expected"),  # Only apply CI for the specified group
        aes(ymin = CI_lower, ymax = CI_upper, fill = Pair),
        alpha = 0.2  # Transparency of CI ribbon
    ) +
    labs(title = "Sharedness over Time\n", y = "Shared(%)\n", x = "\nTransfer") +
    scale_linetype_discrete(name = "Group",  # Change the legend title here
                    labels = c("Observed", "Simulated"))+
    theme_minimal()+ 
    theme(plot.title = element_text(size = 55, hjust = 0.5),
            axis.title = element_text(size = 45),
            axis.text.x = element_text(size = 20, face="bold"),
            axis.text.y = element_text(size = 30),
            strip.text.x = element_text(size = 35, angle=90),
            legend.title = element_text(size=40),
            legend.text = element_text(size = 35))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "parallel_over_time.pdf"), height = 14, width = 14)
fig
dev.off()

```