---
title:  
    "Secondary Structure Analyses for EXPIII"
date: 
    "Oct 25th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# load libraries

library(readxl)
library(ggplot2)
library(dplyr)

# define functions

`%notin%` <- Negate(`%in%`)

```

```{r read in structure data}

# read-in shape data

shape <- as.data.frame(read_excel("/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/external/secondary-structure/41592_2014_BFnmeth3029_MOESM232_ESM.xlsx"))

# align coordinates
shape$Nt <- shape$Nt + 454

# prepare the shape data
shape$`1M7 SHAPE MaP`[shape$`1M7 SHAPE MaP` == -999] <- NA


shape$med_55_nt <- NA
for (i in 1:nrow(shape)){
    shape$med_55_nt[i] <- median(shape$`1M7 SHAPE MaP`[max(1,i-27):min(nrow(shape),i+27)], na.rm = T) - median(shape$`1M7 SHAPE MaP`, na.rm = T)
}


plt <- shape %>% ggplot(aes(x = Nt, y = med_55_nt)) +
    labs(title = "SHAPE Levels over Genome", y = "SHAPE score", x = "Position") +
    geom_line() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, face="bold"),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=90),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 35))

# visually inspect the data
plt

date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "shape_levels_over_genome.pdf"), height = 14, width = 14)
plt
dev.off()


# read-in base-pairing probabilities

bp_pr <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/data/external/secondary-structure/41592_2014_BFnmeth3029_MOESM234_ESM.txt", sep = "\t", header = T, skip = 1)

# align coordinates
bp_pr$i <- bp_pr$i+454
bp_pr$j <- bp_pr$j+454

# prepare the base-pairing data
bp_pr$pr <- 10**(-bp_pr$X.log10.Probability.)



for (i in unique(bp_pr$i)){
    df <- bp_pr[bp_pr$i == i,]
    
    bp_pr$shannon[bp_pr$i == i] <- -sum(df$pr*(log10(df$pr)))
}


df <- distinct(bp_pr[,c(1,5)])


shannon_df <- df
shannon_df <- data.frame()
for (i in min(df$i):max(df$i)){
    shannon_df <- rbind(shannon_df, c(i, median(df$shannon[df$i %in% max(1,i-55):min(9173,i+55)], na.rm = T)))
    
}

colnames(shannon_df) <- c("i", "shannon")

plt <- shannon_df %>% ggplot(aes(x = i, y = shannon)) +
    geom_line() +
    scale_x_continuous(breaks = round(seq(min(shannon_df$i), max(shannon_df$i), by = 500),1)) +
    labs(title = "Base Pairing over Genome", y = "Shannon of Base Paring Probabilities", x = "Position") +
    geom_line() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 10, face="bold"),
        axis.text.y = element_text(size = 20),
        strip.text.x = element_text(size = 35, angle=90),
        legend.title = element_text(size=40),
        legend.text = element_text(size = 35))
    

# visually inspect the data
plt

date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "base_paring_shannon_over_genome.pdf"), height = 14, width = 14)
plt
dev.off()


```


```{r read in variant data}


variants_subset <- distinct(variants_expiii[variants_expiii$allele_freq >= 0.05,c("genomic_pos", "mut_info", "exp_line")])

freq_df <- as.data.frame(table(variants_subset$genomic_pos))

colnames(freq_df) <- c("i", "Freq")

freq_df$i <- as.numeric(as.character(freq_df$i))

freq_df_all <- data.frame()

for (i in 1:9627){
    if (i %notin% freq_df$i){
        freq_df_all <- rbind(freq_df_all,c(i,0))
    } else {
        freq_df_all <- rbind(freq_df_all, as.numeric(freq_df[freq_df$i == i,]))
    }
}

colnames(freq_df_all) <- c("i", "freq")
freq_df_all <- freq_df_all[-c(1:454),]



```


```{r}
plot(freq_df_all$freq, shape$med_55_nt)
plot(freq_df_all$freq, shannon_df$shannon)
```

```{r}

# shape data
shape <- shape[,c("Nt", "med_55_nt")]


# shape$med_55_nt <- shape$`1M7 SHAPE MaP`
# shape <- shape[!is.na(shape$med_55_nt),]

shape %<>% select(Nt, med_55_nt) %>% mutate(category_shape = case_when(med_55_nt <= as.numeric(quantile(shape$med_55_nt, probs = c(0.1,0.9))[1]) ~ "low_shape", 
                                        med_55_nt >= as.numeric(quantile(shape$med_55_nt, probs = c(0.1,0.9))[2]) ~ "high_shape")) %>%
            mutate(category_shape = ifelse(is.na(category_shape), "mid", category_shape))



variants_subset <-  variants_expiii %>% filter(host_line == "MT4", allele_freq >= 0.99) %>%
                    select(genomic_pos, mut_info, exp_line) %>%
                    distinct()


cat_count <- table(shape$category)[1:2]
var_count <- table(shape$category[shape$Nt %in% variants_subset$genomic_pos])[1:2]


fisher.test(cbind(cat_count,var_count))


# shannon_df <- df
# bp data
shannon_df %<>% mutate(category_shannon = case_when(shannon <= as.numeric(quantile(shannon_df$shannon, probs = c(0.1,0.9))[1]) ~ "low_shannon", 
                                        shannon >= as.numeric(quantile(shannon_df$shannon, probs = c(0.1,0.9))[2]) ~ "high_shannon")) %>%
            mutate(category_shannon = ifelse(is.na(category_shannon), "mid", category_shannon))

cat_count <- table(shannon_df$category)[1:2]
var_count <- table(shannon_df$category[shannon_df$i %in% variants_subset$genomic_pos])[1:2]

fisher.test(cbind(cat_count,var_count))


```

```{r}

# are there a stronger purifying selection in low bp_shannon regions?

shannon_df_new <- df
shannon_df_new %<>% mutate(category_shannon = case_when(shannon <= as.numeric(quantile(shannon_df_new$shannon, probs = c(0.1,0.9))[1]) ~ "low_shannon", 
                                        shannon >= as.numeric(quantile(shannon_df_new$shannon, probs = c(0.1,0.9))[2]) ~ "high_shannon")) %>%
            mutate(category_shannon = ifelse(is.na(category_shannon), "mid", category_shannon))

variants_subset <-  variants_expiii %>% filter(allele_freq >= 0.01) %>%
                    select(genomic_pos, mut_info, exp_line) %>%
                    distinct()

var_count_min <- table(shannon_df_new$category[shannon_df_new$i %in% variants_subset$genomic_pos])[1:2]


variants_subset <-  variants_expiii %>% filter(allele_freq >= 0.99) %>%
                    select(genomic_pos, mut_info, exp_line) %>%
                    distinct()

var_count_fixed <- table(shannon_df_new$category[shannon_df_new$i %in% variants_subset$genomic_pos])[1:2]

fisher.test(cbind(var_count_min,var_count_fixed))

```




```{r}

# merge shape and base-pairing shannon data


merged_df <- merge(shape, shannon_df, by.x = "Nt", by.y = "i")


variants_subset <-  variants_expiii %>% filter(allele_freq >= 0.05 & host_line == "MT2") %>%
                    select(genomic_pos, mut_info, exp_line) %>%
                    distinct()



cat_count <- table(merged_df$category_shape, merged_df$category_shannon)
var_count <- table(merged_df$category_shape[merged_df$Nt %in% variants_subset$genomic_pos],merged_df$category_shannon[merged_df$Nt %in% variants_subset$genomic_pos])


## compare between double-high and double-low regions
fisher.test(matrix(c(var_count[1,1], var_count[2,2], cat_count[1,1], cat_count[2,2]), ncol = 2, byrow = F))

## compare variant count between double-low region and the rest of genome
mat <- matrix(c(sum(var_count)-var_count[2,2], var_count[2,2], sum(cat_count)-cat_count[2,2], cat_count[2,2]), ncol = 2, byrow = F)
fisher.test(mat)


## regions of double low
merged_df$Nt[merged_df$category_shape == "low_shape" & merged_df$category_shannon == "low_shannon"]

```
