---
title:  
    "Fixation dynamics"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("ggpubr")
library("plotly")
library("RColorBrewer")
library("hrbrthemes")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("magrittr")
library("rstatix")
library("gtools")
library("effsize")
library("purrr")


```


```{r read-in variant data}

if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}


# load data

source(paste0(wd, "src/analysis/1st-man/readin_data.r"))

```

```{r load visualization settings}
# Visual settings

source(paste0(wd, "src/analysis/1st-man/plot_custom.r"))


```


# Accumulation

```{r category thresholds}

# set parameters
category <- "Minority"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```




```{r calculate time to fixation}

# record at what passages the fixed mutations first appeared and reached fixation (continuously) (AF above 0.99)
t_2_f <- data.frame()


for (exp_line in exp_line_factor){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(variants_expiii_sub2$passage[(variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.01)]))))) + 10
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        t_2_f <- rbind(t_2_f, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}


# set column names and right data types
t_2_f %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        mut_info = paste(exp_line, mut_info, sep = "_"),
        host_line = if_else(str_detect(exp_line, pattern = "MT-2"), "MT-2", "MT-4"),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))

```


```{r visualization1: time-to-fixation}
# density of time_to_fixation distributions
fig <- t_2_f %>% ggplot(aes(x = time_to_fixation, color = exp_line)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = exp_line_factor, values = line_col_palette)

fig



# perform pairwise wilcox-test between translation impact groups per exp line

pwc <- t_2_f %>%
    group_by(exp_line) %>%
    pairwise_wilcox_test(
        time_to_fixation ~ effect_simplified,
        p.adjust.method = "none",
        detailed = TRUE
    )


# Visualization: box plots with p-values

low<-findInterval(max(t_2_f$time_to_fixation),c(5,10,20,50,100))
step <- c(5,10,20,50,100)[low - 1]

#Add x position
pwc <- pwc %>% add_xy_position(x = "effect_simplified", step.increase = 1)
# assign new y.positions 
set.seed(1)
pwc$y.position <- sample(seq(500,590,7), replace = F, size = 12)
# make the plot
fig2 <- ggboxplot(t_2_f, x = "effect_simplified", y = "time_to_fixation", color = "exp_line") +
    geom_jitter(aes(color = exp_line), width = 0.2, size = 2, alpha = 0.9) +
    facet_wrap(~exp_line, ncol = 2) +
    labs(x = "Translational Impact", y = "Time to Fixation", color = "Virus Line")+
    scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
    scale_y_continuous(breaks = seq(0,max(t_2_f$time_to_fixation)+step,step), limit = c(0,600)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj", size = 8) +
    custom_plot_theme(application = "publication") +
    theme(axis.text.x = element_text(angle = 0), legend.position = "none")


fig2

# save figure
custom_plot_save(fig2, "time_to_fixation_significance_boxplot_per_line.pdf", height = 14, width = 14)


# # perform pairwise wilcox-test between exp line groups per translation impact
# pwc <- t_2_f %>%
#     group_by(effect_simplified) %>%
#     pairwise_wilcox_test(time_to_fixation ~ exp_line, p.adjust.method = "BH",pool.sd=FALSE, detailed = T)

# #Add x position
# pwc <- pwc %>% add_xy_position(x = "exp_line", step.increase = 1)
# # assign new y.positions 
# pwc$y.position <- sample(seq(500,750,10), replace = F, size = 18)
# # make the plot
# fig3 <- ggboxplot(t_2_f, x = "exp_line", y = "time_to_fixation", color = "exp_line") +
#     facet_wrap(~effect_simplified, ncol = 3) +
#     labs(x = "Virus Line", y = "Time to Fixation", color = "Virus Line")+
#     scale_color_manual(labels = exp_line_factor, values = line_col_palette) +
#     scale_y_continuous(breaks = seq(0,max(t_2_f$time_to_fixation)+step,step)) +
#     stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj") 

# fig3

# perform pairwise wilcox-test between host line groups per translation impact
pwc <- t_2_f %>%
    # filter(mut_info %in% shared) %>%
    # filter(fixation >= 300) %>%
    group_by(effect_simplified) %>%
    pairwise_wilcox_test(time_to_fixation ~ host_line, p.adjust.method = "BH",pool.sd=FALSE, detailed = T)

#Add x position
pwc <- pwc %>% add_xy_position(x = "host_line", step.increase = 1)
# assign new y.positions 
pwc$y.position <- sample(seq(500,650,10), replace = F, size = 3)

# make the plot
fig4 <- ggboxplot(t_2_f, x = "host_line", y = "time_to_fixation", color = "host_line", outliers = FALSE ) +
    geom_jitter(aes(color = host_line), width = 0.2, size = 2, alpha = 0.9) +
    facet_wrap(~effect_simplified, ncol = 3) +
    labs(x = "\n Host", y = "Time to fixation\n", color = "Lineage")+
    scale_color_manual(labels = c("MT-2", "MT-4"), values = c("#ff8b08", "#00bbff")) +
    scale_y_continuous(breaks = seq(0,max(t_2_f$time_to_fixation)+step,step), limit = c(0,600)) +
    stat_pvalue_manual(pwc, hide.ns = TRUE, label = "p.adj", size = 8) +
    custom_plot_theme(application = "publication") +
    theme(legend.position = "none")

fig4


# save figure
custom_plot_save(fig4, "time_to_fixation_per_translation_impact_per_environment.pdf", height = 14, width = 14)

# get inline variables
df %>% group_by(host_line) %>% summarize(Mean = mean(time_to_fixation, na.rm=TRUE), n = n())

wilcox.test(df$time_to_fixation[df$host_line == "MT-2"], df$time_to_fixation[df$host_line == "MT-4"])

```


```{r visualization11: time-to-fixation over time}

# time_to_fixation distributions per function of appearance time

fig <- t_2_f %>% ggplot(aes(x = appearance, y = time_to_fixation, color = exp_line, shape = effect_simplified)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_point() +
                    geom_hline(yintercept = 100) +
                    scale_color_manual(labels = exp_line_factor, values = line_col_palette)

fig

```

```{r distribution of rapidly fixating mutations over time}



t_2_f <- t_2_f %>%
  group_by(exp_line) %>%
  mutate(p10 = quantile(time_to_fixation, 0.10)) %>%
  mutate(p90 = quantile(time_to_fixation, 0.90)) %>%
  ungroup()

labels_with_p10 <- with(t_2_f, setNames(
  paste0(exp_line, "(", round(p10, 1), ")"),
  exp_line
))

t_2_f %<>% mutate(labels = labels_with_p10)


bins <- seq(0,400, 100)

t_2_f_summary <- t_2_f[t_2_f$time_to_fixation < t_2_f$p10,] %>%
        mutate(bin = cut(fixation, breaks = bins, right = FALSE)) %>%
        group_by(exp_line,labels, effect_simplified) %>%
        count(bin, .drop = FALSE)

t_2_f_summary <- t_2_f_summary[!is.na(t_2_f_summary$bin),]



fig <- ggplot(t_2_f_summary, aes(x = effect_simplified, y = n, fill = bin)) +
    facet_wrap(~labels, ncol = 2, strip.position = "top") +
    geom_bar(stat = "identity", position = "dodge") +
    scale_y_continuous(limits = c(0, 8), breaks = seq(0, 12, by = 2)) +
    labs(title = "", x = "\nTranslational impact", y = "Count of rapidly-fixing variants \n", fill = "Fixation period") +
    custom_plot_theme() +
    theme(axis.text.x = element_text(angle = 0))

fig

# save figure
custom_plot_save(fig, "rapidly_fixating_variants_over_time.pdf", height = 14, width = 14)
```




```{r calculate fixation time based on number of recurrence}

## Method 2
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
t_2_f <- data.frame()


for (exp_line in exp_line_factor){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(variants_expiii_sub2$passage[(variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.01)]))))) + 10
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        t_2_f <- rbind(t_2_f, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}


# set column names and right data types
t_2_f %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))


# average time to fixation for fixated mutations based on how many times they are repeated

fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])




t_2_f$Occurrence <- NA
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["1"]])] <- "Single"
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["2"]])] <- "Double"
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["3"]])] <- "Triple"
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["4"]])] <- "Quadruple"
t_2_f <- t_2_f[!is.na(t_2_f$Occurrence),]
t_2_f$Occurrence <- factor(t_2_f$Occurrence, levels = c("Single", "Double", "Triple", "Quadruple"))


comparisons <- list(
  c("Quadruple", "Triple"),
  c("Quadruple", "Double"),
  c("Quadruple", "Single"),
  c("Triple", "Double"),
  c("Triple", "Single"),
  c("Double", "Single")
)


my_col_pal <- c(alpha("grey"), "green", "blue", "red")

```

```{r average time to fixation of neutral sequence simulations}
bottleneck_freq <- 2
sim_data <- readRDS(paste0(wd, "results/tables/misc/neutral-seq-sim/", bottleneck_freq, "_sim_freq_all.rds"))

sim_data$mut_info <- paste0(sim_data$pos, "_", sim_data$base_allele, "_", sim_data$alt_allele)

## Method 2
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
t_2_f_sim <- data.frame()


for (exp_line in exp_line_factor){
    sim_data_sub <- sim_data[sim_data$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(sim_data_sub$mut_info[sim_data_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        sim_data_sub2 <- sim_data_sub[sim_data_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(sim_data_sub$passage[sim_data_sub$mut_info == mut & sim_data_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(sim_data_sub2$passage[(sim_data_sub2$mut_info == mut & sim_data_sub2$allele_freq >= 0.01)]))))) + 10
        t_2_f_sim <- rbind(t_2_f_sim, c(exp_line, mut, appearance, fixation, fixation-appearance))
    }
}


# set column names and right data types
t_2_f_sim %<>% set_colnames(c("exp_line", "mut_info", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(3:5, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor))

median(t_2_f_sim$time_to_fixation)

```

```{r visualization of time to fixation based on number of occurrence}

# Create the plot
fig <- ggplot(t_2_f, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7, outliers = FALSE) +
    geom_jitter(aes(color = Occurrence), width = 0.2, size = 2, alpha = 0.9) +
    geom_hline(yintercept = median(t_2_f_sim$time_to_fixation), linetype = "dashed", color = "black", size = 1) +
    stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj", size = 12) +
    scale_y_continuous(limits = c(0, 800), breaks = seq(0, 500, by = 50)) +
    scale_fill_manual(values = my_col_pal) +
    scale_color_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to fixation\n", title = "") + # Label for the legend
    custom_plot_theme() +
    theme(axis.title.x = element_blank())


# save figure
custom_plot_save(fig, "time-to-fixation-based-on-recurrence.pdf", height = 14, width = 14)

```

####!!!!

```{r}


## Method 2
# record at what passages the fixed mutations first appeared and reached fixation (AF above 0.99)
t_2_f <- data.frame()


for (exp_line in exp_line_factor){
    variants_expiii_sub <- variants_expiii[variants_expiii$exp_line == exp_line,] #& variants_expiii$genomic_pos >= 8787 & variants_expiii$genomic_pos <= 9400
    fixed_muts <- unique(variants_expiii_sub$mut_info[variants_expiii_sub$allele_freq >= 0.99])
    for (mut in fixed_muts){
        variants_expiii_sub2 <- variants_expiii_sub[variants_expiii_sub$mut_info == mut,]
        fixation <- min(as.numeric(as.vector(variants_expiii_sub$passage[variants_expiii_sub$mut_info == mut & variants_expiii_sub$allele_freq >= 0.99])))
        appearance <- max(setdiff(seq(0,fixation,10), as.numeric(as.vector(unique(variants_expiii_sub2$passage[(variants_expiii_sub2$mut_info == mut & variants_expiii_sub2$allele_freq >= 0.01)]))))) + 10
        translational_impact <- unique(as.character(variants_expiii_sub$effect_simplified[variants_expiii_sub$mut_info == mut]))
        t_2_f <- rbind(t_2_f, c(exp_line, mut, translational_impact, appearance, fixation, fixation-appearance))
    }
}


# set column names and right data types
t_2_f %<>% set_colnames(c("exp_line", "mut_info", "effect_simplified", "appearance", "fixation", "time_to_fixation")) %>% 
        mutate_at(4:6, as.integer) %>%
        mutate(exp_line = factor(exp_line, levels = exp_line_factor),
        effect_simplified = factor(effect_simplified, levels = translational_impacts))


# average time to fixation for fixated mutations based on how many times they are repeated

fix_count_table <- table(t_2_f$mut_info)

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])




t_2_f$Occurrence <- NA
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["1"]])] <- "Single"
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["2"]])] <- "Double"
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["3"]])] <- "Triple"
t_2_f$Occurrence[t_2_f$mut_info %in% names(fix_count_table_list[["4"]])] <- "Quadruple"
t_2_f <- t_2_f[!is.na(t_2_f$Occurrence),]
t_2_f$Occurrence <- factor(t_2_f$Occurrence, levels = c("Single", "Double", "Triple", "Quadruple"))



bins <- c(0, 250, 500)

df <- t_2_f %>%
    filter(Occurrence != "Double") %>%
    mutate(labels = case_when(
        Occurrence %in% c("Single") ~ "not_shared",
        Occurrence %in% c("Triple", "Quadruple") ~ "highly_shared"
    )) %>%
    select(exp_line, labels, effect_simplified, fixation) %>%
    mutate(bin = cut(fixation, breaks = bins, right = TRUE, left = FALSE)) %>%
    group_by(exp_line,labels, bin) %>%
    summarise(n = n(), .groups = "drop_last") %>%   # count per bin
    mutate(percentage = n / sum(n) * 100)           # percentage within each group

df2 <- df %>%
    mutate(
    bin = factor(bin, levels = c("(0,250]", "(250,500]")),
    labels = factor(labels, levels = c("highly_shared", "not_shared"))
    )


df2[df2$exp_line == "MT-4_2" & df2$bin == "(0,250]" & df2$labels == "not_shared", "n"] <- 4  
df2[df2$exp_line == "MT-4_2" & df2$bin == "(250,500]" & df2$labels == "not_shared", "n"] <- 19


# Fisher test per exp_line
fisher_results <- df2 %>%
    group_by(exp_line) %>%
    nest() %>%
    mutate(
        # Create 2x2 matrix
        fisher_table = map(data, ~ .x %>%
            select(labels, bin, n) %>%
            pivot_wider(names_from = bin, values_from = n) %>%
        as.data.frame() %>%
        { mat <- .; rownames(mat) <- mat$labels; mat[, -1, drop = FALSE] }  # set rownames, drop label col
        ),
            fisher_test = map(fisher_table, ~ fisher.test(.x)),
        p_value = map_dbl(fisher_test, ~ .x$p.value)) %>%
    select(exp_line, p_value)



fig <- ggplot(df2, aes(x = bin, y = n, fill = labels)) +
    facet_wrap(~exp_line, ncol = 2, strip.position = "top") +
    geom_bar(stat = "identity", position = "dodge") +
    geom_text(aes(label = n),
            position = position_dodge(width = 0.9),
            vjust = -0.2,
            size = 12) +
            # Add Fisher test p-values
    geom_text(data = fisher_results, 
            aes(x = Inf, y = Inf, label = paste("p.val =", round(p_value, 4))),
            inherit.aes = FALSE,
            hjust = 1.7, vjust = 1.5,
            size = 10, 
            color = "black") +
    scale_fill_manual(values = c("purple", "grey")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 10)) +
    labs(title = "", x = "\nFixation period", y = "Count \n", fill = "Sharedness") +
    custom_plot_theme()



# save figure
custom_plot_save(fig, "shared_fixed_fisher.pdf", height = 14, width = 14)



```


```{r regression model of time to fixation for number of occurrence}

# density of time_to_fixation distributions
fig <- df %>% ggplot(aes(x = time_to_fixation, color = exp_line)) +
                    facet_wrap(~exp_line, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = line_labels, values = line_palette)

fig

fig <- df %>% ggplot(aes(x = time_to_fixation, color = Occurrence)) +
                    facet_wrap(~Occurrence, ncol = 2) +
                    geom_density() +
                    scale_color_manual(labels = c("One", "Two", "Three", "Four"), values = c(alpha("grey"), "green", "blue", "red"))

fig



# Shapiro-Wilk test
shapiro.test(df[df$Occurrence == "One",]$time_to_fixation)
shapiro.test(df[df$exp_line == "MT-2_1",]$time_to_fixation)

# pairwise wilcox-test between Occurrence groups

fig <- ggplot(df, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj") +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + # Label for the legend
    theme_minimal() + # Optional: use a minimal theme
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15)) 

fig

# ordinary linear model
# problem 1 - the occurrence variable is not continuous. Can I treat an ordinal categorical variable as continuous?
# problem 2 - each group has a different variance (non-homoscedasticity)

dff <- df
dff %<>% mutate(Occurrence = as.numeric(Occurrence))

# Fit an ordinary linear model
model_lm <- lm(time_to_fixation ~ Occurrence, data = dff)

# Diagnostic plots
par(mfrow = c(2, 2))
plot(model_lm)

# Extract model summary
model_lm_summary <- summary(model_lm)
lm_effects <- model_lm_summary$coefficients

# Create a data frame for the fixed effects
lm_effects_df <- data.frame(
  Term = rownames(lm_effects),
  Estimate = lm_effects[, 1],
  StdError = lm_effects[, 2],
  tValue = lm_effects[, 3],
  pValue = 2 * (1 - pnorm(abs(lm_effects[, 3])))
)

# Prepare the fixed effects text for annotation
lm_effects_text <- paste0(
  "Intercept: ", round(lm_effects_df$Estimate[lm_effects_df$Term == "(Intercept)"], 2), "\n",
  "Occurrence effect: ", round(lm_effects_df$Estimate[lm_effects_df$Term == "Occurrence"], 2), "\n",
  "p-value: ", format.pval(lm_effects_df$pValue[lm_effects_df$Term == "Occurrence"], digits = 3)
)

# Plot with ggplot
fig <- ggplot(df, aes(x = Occurrence, y = time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + 
    theme_minimal() + 
    theme(plot.title = element_text(size = 30, hjust = 0.5),
          axis.title = element_text(size = 25),
          axis.text.x = element_text(size = 20, angle = 90),
          axis.text.y = element_text(size = 20),
          legend.title = element_text(size=20),
          legend.text = element_text(size = 15)) +
    annotate(
        "text", x = 1.5, y = max(dff$time_to_fixation), label = lm_effects_text, 
        size = 6, hjust = -1, color = "orange"
    )

# Add regression line to the plot
fig <- fig +
    geom_smooth(data = dff, aes(x = Occurrence, y = time_to_fixation), method = "lm", se = FALSE, color = "orange")

# Print the final plot
fig



# mixed effect linear model with random effect the exp line
# problem 3 - there is subgrouping in the data that needs to be accounted for, so regard exp_line as a random effect in a mixed effect model




library(lme4)
model_lme <- lmer(time_to_fixation ~ Occurrence + (1|exp_line), data = dff)

par(mfrow = c(2, 2))
plot(model_lme)
model_lme_summary <- summary(model_lme)
fixed_effects <- model_lme_summary$coefficients

fixed_effects_df <- data.frame(
  Term = rownames(fixed_effects),
  Estimate = fixed_effects[, 1],
  StdError = fixed_effects[, 2],
  tValue = fixed_effects[, 3],
  pValue = 2 * (1 - pnorm(abs(fixed_effects[, 3])))
)

fixed_effects_text <- paste0(
  "Intercept: ", round(fixed_effects_df$Estimate[fixed_effects_df$Term == "(Intercept)"], 2), "\n",
  "Occurrence effect: ", round(fixed_effects_df$Estimate[fixed_effects_df$Term == "Occurrence"], 2), "\n",
  "p-value: ", format.pval(fixed_effects_df$pValue[fixed_effects_df$Term == "Occurrence"], digits = 3)
)

fig <- ggplot(df, aes(x = Occurrence, y=time_to_fixation, fill = Occurrence)) + 
    geom_boxplot(color = "black", alpha = 0.7) +
    # stat_compare_means(comparisons = comparisons, method = "wilcox.test", p.adjust.method = "BH", label = "p.adj") +
    scale_fill_manual(values = my_col_pal) +
    labs(fill = "Occurrence", x= "Occurrence", y = "Time to Fixation", title = "Fixation Dynamics Based on Variant Recurrence\n") + # Label for the legend
    theme_minimal() + # Optional: use a minimal theme
    theme(plot.title = element_text(size = 30, hjust = 0.5),
        axis.title = element_text(size = 25),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 20),
        legend.title = element_text(size=20),
        legend.text = element_text(size = 15)) +
    annotate(
        "text", x = 1.5, y = max(df$time_to_fixation), label = fixed_effects_text, 
        size = 6, hjust = -1, color = "orange"
    )

fig <- fig +
    geom_smooth(data = dff, aes(x = Occurrence, y = time_to_fixation), method = "lm", se = FALSE, color = "orange")



```

