---
title:  
    "variant freq. dynamics of EXPIII"
date: 
    "July 15th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```



```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 

# facors

host_factor <- c("MT2", "MT4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```





```{r set paramters}

# set parameters
category <- "Fixed"

if (category == "Sporadic"){
    min_threshold <- 0.01
    max_threshold <- 0.05
} else if (category == "Minority"){
    min_threshold <- 0.05
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
} else if (category == "All"){
    min_threshold <- 0.01
    max_threshold <- 1.01
}

```


```{r variant frequency trajectory of fixed variants, results=TRUE}



variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])

tot_fixed_4lines <- length(fixed_muts)




s <- variants_expiii_subset %>% filter(mut_info_line %in% fixed_muts) %>% select(exp_line, mut_info) %>% distinct()


my_col_pal <- c(rep(c(brewer.pal(9,"Reds"),brewer.pal(9,"PuRd"))[9], length.out = sum(table(s$exp_line)[1:2])),
rep(c(brewer.pal(9,"Blues"),brewer.pal(9,"BuPu"))[9], length.out = sum(table(s$exp_line)[3:4])))


fig <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,] %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = mut_info_line)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    labs(title = "Variant Frequency Trajectories \n", y = "Frequency \n", x = "\n Transfer") +
    scale_color_manual(values = my_col_pal) +
    scale_x_continuous(breaks = seq(0,500, 50))+
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")

fig



# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "frequency_dynamics_",category,"_mutations.pdf"), height = 14, width = 14)
fig
dev.off()

```


```{r variant frequency trajectories colored by sharedness, results=TRUE}


fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])



variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])
variants_expiii_subset <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,]


for (i in 1:nrow(variants_expiii_subset)){
    matching_index <- which(sapply(fix_count_table_list, function(x) variants_expiii_subset$mut_info[i] %in% names(x)))
    if (length(matching_index) == 0) {
        variants_expiii_subset$rep[i] <- 1
    } else {
        variants_expiii_subset$rep[i] <- names(fix_count_table_list)[matching_index]
    }
    
}


my_col_pal <- c(alpha("grey", 0.5), "green", "blue", "red")




fig <- variants_expiii_subset %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = rep)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    labs(title = "Variant Frequency Trajectories \n", y = "Frequency \n", x = "\n Transfer", color = "Occurrence") +
    scale_color_manual(values = my_col_pal) +
    scale_x_continuous(breaks = seq(0,500, 50))+
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0))

fig


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "frequency_dynamics_per_repeated_",category, ".pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/frequency_dynamics_per_repeated_",category, ".pdf"), height = 14, width = 14)
fig
dev.off()


```

```{r new colors}




blues_colors <- c("#A4DDED", "#A3C1AD", "#CCCCFF", "#00CCFF", "#15f4ee", 
"#0071c5", "#5A4FCF", "#004687", "#0000CD", "#191970")

triples <- blues_colors
names(triples) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"])[order(unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"]))]

reds_colors <- brewer.pal(5, "Reds")[3:5]
quad <- reds_colors
names(quad) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "4"])



variants_expiii_subset %<>%
    mutate(mut_info2 = case_when(rep == 1 ~ "Single Occurrence",
                                rep == 2 ~ "Double Occurrence",
                                rep == 3 ~ mut_info,
                                rep == 4 ~ mut_info)) %>%
    mutate(mut_info2 = factor(mut_info2, levels = c("Single Occurrence", "Double Occurrence", names(triples), names(quad))))



custom_colors <- c(
    "Single Occurrence" = alpha("grey", 0.3),
    "Double Occurrence" = alpha("green", 0.6)
)
custom_colors <- c(custom_colors, triples, quad)





fig <- variants_expiii_subset %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = mut_info2)) +
    geom_line(size = 2) +
    facet_wrap(~exp_line, ncol = 2) +
    labs(title = "Variant Frequency Trajectories \n", y = "Frequency \n", x = "\n Transfer", color = "Variant") +
    scale_color_manual(values = custom_colors) +
    scale_x_continuous(breaks = seq(0,500, 50))+
    theme_bw() +
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 50),
        axis.text.x = element_text(size = 40, color = "black", angle = 90),
        axis.text.y = element_text(size = 40, color = "black"),
        strip.text.x = element_text(size = 50, angle=0),
        legend.title = element_text(size=50),
        legend.text = element_text(size = 40))

fig

pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/frequency_dynamics_per_repeated_",category, ".pdf"), height = 21, width = 42)
fig
dev.off()

```

```{r}

variants_expiii_subset2 <- variants_expiii_subset[variants_expiii_subset$exp_line == "MT-2_1",]

variants_expiii_subset2 <- variants_expiii_subset2 %>% filter(passage %in% c(270,310))

head(variants_expiii_subset2)


variants_expiii_subset2_wide <- variants_expiii_subset2 %>%
    select(mut_info, passage, allele_freq) %>%
    pivot_wider(names_from = passage, values_from = allele_freq)

head(variants_expiii_subset2_wide)
variants_expiii_subset2_wide <- variants_expiii_subset2_wide %>%
  filter(!is.na(`270`) & !is.na(`310`))

nrow(variants_expiii_subset2_wide)

df_doubled <- variants_expiii_subset2_wide %>%
  filter(`310` >= 2 * `270`)

nrow(df_doubled)
View(df_doubled)
ss <- variants_expiii$mut_info[variants_expiii$exp_line == "MT-2_1" & variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg]

df_doubled$mut_info[df_doubled$mut_info %in% ss]

table(variants_expiii_subset2$effect_simplified[variants_expiii_subset2$mut_info %in% df_doubled$mut_info[df_doubled$mut_info %in% ss]],
variants_expiii_subset2$mut_info[variants_expiii_subset2$mut_info %in% df_doubled$mut_info[df_doubled$mut_info %in% ss]])

```



```{r table of fixed variants}


fix_count_table <- table(variants_expiii$mut_info[variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg])

fix_count_table_list <- list("4" = fix_count_table[fix_count_table==4],
    "3" = fix_count_table[fix_count_table==3],
    "2" = fix_count_table[fix_count_table==2],
    "1" = fix_count_table[fix_count_table==1])



variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))


unique(variants_expiii[variants_expiii$mut_info %in% names(fix_count_table_list[[2]])[i],c(2,3,4,6,11,12,16,17,18,19,20)], n = 1)


df <- data.frame()


for (mut in names(setNames(unlist(fix_count_table_list, use.names = FALSE), unlist(lapply(fix_count_table_list, names))))){
    
    lines <- as.vector(table(variants_expiii$exp_line[variants_expiii$mut_info == mut & variants_expiii$allele_freq >= 0.99 & variants_expiii$passage == end_psg]))
    occurrence <- sum(lines)
    lines <- ifelse(lines == 0, "❌", "✅")
    
    for (i in 1:nrow(unique(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(2,3,4,6,11,12,16,18,19,20)]))){
        df <- rbind(df, c(as.character(unique(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(14,15)])[i,]), mut, occurrence, lines, as.character(unique(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(2,3,4,6,11,12,16,18,19,20)])[i,])))
    }
    
    
}



colnames(df) <- c("variant_id", "annotation_id", "variant_name", "occurrence", "MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2", names(variants_ann_expiii[variants_ann_expiii$mut_info == mut,c(2,3,4,6,11,12,16,18,19,20)]))

df$genomic_pos <- as.numeric(df$genomic_pos)
df <- df[order(df$genomic_pos),]


View(df)


library(DT)
library(htmlwidgets)




# Create datatable with caption
table_widget <- datatable(
  df,
  caption = htmltools::tags$caption(
    style = 'caption-side: top; text-align: left; font-weight: bold;',
    "Table 2: Fixed Variants At Transfer 500"
  )
)

# Save as HTML
saveWidget(
  table_widget,
  "/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/fixed_variants.html",
  selfcontained = TRUE
)

# df$loc_in_protein[df$loc_in_protein != ""][!(as.numeric(sapply(str_split(df$loc_in_protein[df$loc_in_protein != ""], pattern = "/"), "[[", 1)) <= as.numeric(sapply(str_split(df$loc_in_protein[df$loc_in_protein != ""], pattern = "/"), "[[", 2)))]

```