---
title:  
    "variant freq. trajectories of certain cases of EXPIII"
date: 
    "Feb 3rd, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```



```{r read-in the data}

# determine the server path

if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
variants_ann <- read.table(file = paste0(wd, "results/tables/pipeline-outputs/all_annotated_variants.tsv.gz"), 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# correct for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"


# only keep the EXPIII data
exp <- "EXPIII"
end_psg <- 500

variants_ann_expiii <- variants_ann %>% filter(exp_line %in% 13:16,
        passage <= end_psg) 

# facors

host_factor <- c("MT-2", "MT-4")
exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")

translational_impacts <- c("U", "S", "N")
gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

# format the dataframe
variants_ann_expiii <- variants_ann_expiii %>%
                            mutate(host_line = ifelse(exp_line %in% c("13", "14"), "MT2", "MT4"), # set host cell line info
                            exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2"), # update exp line labels
                            mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% 
                            mutate(effect_simplified = case_when(effect == "synonymous_variant" ~ "S", effect == "untranslated_region" ~ "U")) %>%
                            mutate(effect_simplified = replace_na(effect_simplified, "N")) %>%
                            mutate(passage = as.factor(passage),
                            exp_line = factor(exp_line, levels = exp_line_factor),
                            host_line = factor(host_line, levels = host_factor),
                            effect_simplified = factor(effect_simplified, levels = translational_impacts)) 

# remove duplicate records for the same variants
variants_expiii <- variants_ann_expiii %>% filter(!duplicated(variant_id))


# Visual settings

line_palette <- c("#ff00ff", "#ff2400", "#6600cc", "#0000ff")
breaks_step <- 50
line_labels <- c("MT-2_1", "MT-2_2", "MT-4_1", "MT-4_2")


```

```{r bertels cases}

cases <- c("9412_G_A", "9528_T_G", "618_G_A")
case <- cases[3]

fig <- variants_expiii[variants_expiii$mut_info %in% case,] %>% ggplot(aes(x = passage, y = log10(allele_freq), group = mut_info)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_alpha_manual(values = c(0.1,1)) +
    scale_y_continuous(breaks = c(0, -1, -2, -3), labels = c("1", "0.1", "0.01", "0.001")) +
    labs(title = paste0(case, "\n"), y = "Frequency \n", x = "\n Transfer") +
    # scale_color_manual(values = my_col_pal) +
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")

fig

```



```{r linkage case}

variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])
variants_expiii_subset <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,]


variants_expiii_subset_mt21 <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts & variants_expiii_subset$exp_line == "MT-2_1",]



intersect(variants_expiii_subset_mt21$variant_info[variants_expiii_subset_mt21$passage == 270 & variants_expiii_subset_mt21$allele_freq >= 0.125],
variants_expiii_subset_mt21$variant_info[variants_expiii_subset_mt21$passage == 280 & variants_expiii_subset_mt21$allele_freq <= 0.14 ])


case <- c("972_G_A" , "973_G_A" , "974_G_C")

variants_expiii_subset_mt21$tracking_group <- "No"
variants_expiii_subset_mt21$tracking_group[variants_expiii_subset_mt21$mut_info %in% case] <- "Yes"

variants_expiii_subset_mt21[variants_expiii_subset_mt21$tracking_group == "Yes",]

variants_expiii_subset_mt21 <- variants_expiii_subset_mt21 %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info))



variants_expiii_subset_mt21$passage <- as.numeric(as.character(variants_expiii_subset_mt21$passage))


s <- variants_expiii_subset %>% filter(mut_info_line %in% fixed_muts) %>% select(exp_line, mut_info) %>% distinct()



my_col_pal <- c(rep(c(brewer.pal(9,"Reds"),brewer.pal(9,"PuRd"))[9], length.out = sum(table(s$exp_line)[1:2])),
rep(c(brewer.pal(9,"Blues"),brewer.pal(9,"BuPu"))[9], length.out = sum(table(s$exp_line)[3:4])))
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[1]] <- "#25880b"
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[2]] <- "#0b74a2"
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[3]] <- "#621295"
variants_expiii_subset_mt21$color[is.na(variants_expiii_subset_mt21$color)] <- c(brewer.pal(9,"Reds"),brewer.pal(9,"PuRd"))[9]
color_mapping <- setNames(variants_expiii_subset_mt21$color, variants_expiii_subset_mt21$mut_info)

fig <- variants_expiii_subset_mt21[variants_expiii_subset_mt21$mut_info_line %in% fixed_muts,] %>%
    ggplot(aes(x = passage, y = allele_freq, group = mut_info, color = mut_info, alpha = tracking_group, size = tracking_group)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_alpha_manual(values = c(0.1,1)) +
    scale_size_manual(values = c(1,1.5)) +
    labs(title = "", y = "Frequency \n", x = "\n Transfer") +
    scale_color_manual(values = color_mapping) +
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")


fig <- fig + geom_text_repel(
    data = . %>% filter(tracking_group == "Yes" & passage == 180),
    aes(label = mut_info),
    size = 10,       # Adjust label text size
    color = c("#25880b", "#0b74a2", "#621295") # Optional: set label color
)

fig




# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "frequency_dynamics_linkage_cases.pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/frequency_dynamics_linkage_cases.pdf"), height = 14, width = 14)
fig
dev.off()

```



```{r clonal interference case, results=TRUE}


# 566_G_A  678_G_A 7854_A_G 
case <- c("566_G_A")

variants_expiii$tracking_group <- "No"
variants_expiii$tracking_group[variants_expiii$mut_info %in% case] <- "Yes"

variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))





fig <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,] %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info, color = mut_info_line, alpha = tracking_group)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_alpha_manual(values = c(0.1,1)) +
    labs(title = paste0(case, "\n"), y = "Frequency \n", x = "\n Transfer") +
    scale_color_manual(values = my_col_pal) +
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 20, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")

fig


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "frequency_dynamics_",case, ".pdf"), height = 14, width = 14)
fig
dev.off()
pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/", "frequency_dynamics_",case, ".pdf"), height = 14, width = 14)
fig
dev.off()


```


```{r UTR SHAREd}


case <- c("566_G_A", "678_G_A", "9412_G_A", "9416_T_C", "9439_G_A", "9522_C_T", "9528_T_G")



blues_colors <- c("#A4DDED", "#A3C1AD", "#CCCCFF", "#00CCFF", "#15f4ee", 
"#0071c5", "#5A4FCF", "#004687", "#0000CD", "#191970")

triples <- blues_colors
names(triples) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"])[order(unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"]))]

reds_colors <- brewer.pal(5, "Reds")[3:5]
quad <- reds_colors
names(quad) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "4"])


head(variants_expiii_subset)
variants_expiii_subset2 <- variants_expiii_subset %>%
    filter(mut_info %in% case) %>%
    mutate(mut_info2 = case_when(rep == 1 ~ "Single Occurrence",
                                rep == 2 ~ "Double Occurrence",
                                rep == 3 ~ mut_info,
                                rep == 4 ~ mut_info)) %>%
    mutate(mut_info2 = factor(mut_info2, levels = c("Single Occurrence", "Double Occurrence", names(triples), names(quad))))



custom_colors <- c(triples, quad)





fig <- variants_expiii_subset2 %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = mut_info2)) +
    geom_line(size = 2) +
    facet_wrap(~exp_line, ncol = 2) +
    labs(title = "Variant Frequency Trajectories \n", y = "Frequency \n", x = "\n Transfer", color = "Variant") +
    scale_color_manual(values = custom_colors) +
    scale_x_continuous(breaks = seq(0,500, 50))+
    theme_bw() +
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 50),
        axis.text.x = element_text(size = 40, color = "black", angle = 90),
        axis.text.y = element_text(size = 40, color = "black"),
        strip.text.x = element_text(size = 50, angle=0),
        legend.title = element_text(size=50),
        legend.text = element_text(size = 40))

fig

pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/", "frequency_dynamics_utr_triple_quad.pdf"), height = 21, width = 21)
fig
dev.off()

```