---
title:  
    "variant freq. distributions"
date: 
    "may 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---




```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```



```{r read-in variant data}


if (file.exists("/home/amovas/")){
    print("Remote HPC Connection!")
    wd <- "/home/amovas/data/genome-evo-proj/"
} else {
    print("Local PC Connection!")
    wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/1st-man/readin_data.R"))

```

```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/1st-man/plot_custom.R"))


```



```{r category thresholds}

# set parameters
category <- "Minority"

if (category == "Minority"){
    min_threshold <- 0.01
    max_threshold <- 0.5
} else if (category == "Majority"){
    min_threshold <- 0.5
    max_threshold <- 1.01
} else if (category == "Fixed"){
    min_threshold <- 0.99
    max_threshold <- 1.01
}
```


```{r anime, results=TRUE}


variants_expiii_subset <- variants_expiii %>%   filter(allele_freq >= 0.01) %>%
                                                mutate(passage = as.numeric(as.character(passage)))



gg_fig <- ggplot(variants_expiii_subset, aes(x=allele_freq)) + 
    geom_histogram(aes(y=..count..),      # Histogram with density instead of count on y-axis
                binwidth=.01,
                colour="black", fill="white") +
    geom_density(aes(y = ..count.. * .01), alpha=.3, fill="#FF6666") +
    facet_wrap(~exp_line, ncol = 2) +
    transition_states(passage, transition_length = 1, state_length = 1, wrap = TRUE) + # to create animation 
    labs(title = "Mutation Freq. Distribution \n(Transfer : {closest_state})", x = "Frequency", y = "Count") +
    theme_bw() +
    theme(
    plot.title = element_text(size = 25, hjust = 0.5),
    axis.title = element_text(size = 20),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    strip.text.x = element_text(size = 25),
    legend.title = element_text(size=15),
    legend.text = element_text(size = 10),
    plot.margin = unit(c(1,1,1,1), "cm"))


# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
anim_save(gg_fig, file = paste0(fig_dir, "allele-freq-accumulation3.gif"))

# save for lteeviz
fig_dir <- "/Users/alimos313/Documents/studies/phd/hpc-research/lte-viz/src/misc/www/"

```

