---
title:  
    "variant freq. trajectories of certain cases of EXPIII"
date: 
    "May 26th, 2025"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---


```{r loading libraries, echo=FALSE}

# loading libraries
library("ggplot2")
library("plotly")
library("gganimate")
library("DT")
library("dplyr")
library("tidyr")
library("Biostrings")
library("stringr")
library("purrr")
library("magrittr")
library("hrbrthemes")
library("RColorBrewer")
library("ggrepel")


```


```{r functions and operators}
`%notin%` <- Negate(`%in%`)
```


```{r read-in variant data}

# determine the server path
if (file.exists("/home/amovas/")){
  print("Remote HPC Connection!")
  wd <- "/home/amovas/data/genome-evo-proj/"
} else {
  print("Local PC Connection!")
  wd <- "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/"
}

# load data
source(paste0(wd, "src/analysis/1st-man/readin_data.R"))

```


```{r load visualization settings}

# Visual settings
source(paste0(wd, "src/analysis/1st-man/plot_custom.R"))


```



```{r bertels cases}

cases <- c("9412_G_A", "9528_T_G", "618_G_A")
case <- cases[3]

fig <- variants_expiii[variants_expiii$mut_info %in% case,] %>% ggplot(aes(x = passage, y = log10(allele_freq), group = mut_info)) +
    geom_line() +
    facet_wrap(~exp_line, ncol = 1) +
    scale_alpha_manual(values = c(0.1,1)) +
    scale_y_continuous(breaks = c(0, -1, -2, -3), labels = c("1", "0.1", "0.01", "0.001")) +
    labs(title = paste0(case, "\n"), y = "Frequency \n", x = "\n Transfer") +
    # scale_color_manual(values = my_col_pal) +
    theme_bw() +
    theme(plot.title = element_text(size = 55, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 30, angle = 90),
        axis.text.y = element_text(size = 30),
        strip.text.x = element_text(size = 35, angle=0),
        legend.position="none")

fig

```



```{r linkage case}

variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))



fixed_muts <- unique(variants_expiii_subset$mut_info_line[variants_expiii_subset$allele_freq >= 0.99])
variants_expiii_subset <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,]


variants_expiii_subset_mt21 <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts & variants_expiii_subset$exp_line == "MT-2_1",]



intersect(variants_expiii_subset_mt21$variant_info[variants_expiii_subset_mt21$passage == 270 & variants_expiii_subset_mt21$allele_freq >= 0.125],
variants_expiii_subset_mt21$variant_info[variants_expiii_subset_mt21$passage == 280 & variants_expiii_subset_mt21$allele_freq <= 0.14 ])


case <- c("972_G_A" , "973_G_A" , "974_G_C")

variants_expiii_subset_mt21$tracking_group <- "No"
variants_expiii_subset_mt21$tracking_group[variants_expiii_subset_mt21$mut_info %in% case] <- "Yes"

variants_expiii_subset_mt21[variants_expiii_subset_mt21$tracking_group == "Yes",]

variants_expiii_subset_mt21 <- variants_expiii_subset_mt21 %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info))



variants_expiii_subset_mt21$passage <- as.numeric(as.character(variants_expiii_subset_mt21$passage))


s <- variants_expiii_subset %>% filter(mut_info_line %in% fixed_muts) %>% select(exp_line, mut_info) %>% distinct()




variants_expiii_subset_mt21$color <- line_col_palette[1]
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[1]] <- "#25880b"
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[2]] <- "#0b74a2"
variants_expiii_subset_mt21$color[variants_expiii_subset_mt21$mut_info == case[3]] <- "#621295"

color_mapping <- setNames(variants_expiii_subset_mt21$color, variants_expiii_subset_mt21$mut_info)



fig <- variants_expiii_subset_mt21[variants_expiii_subset_mt21$mut_info_line %in% fixed_muts,] %>%
    ggplot(aes(x = passage, y = allele_freq, group = mut_info, color = mut_info, alpha = tracking_group, size = tracking_group)) +
    geom_line() +
    facet_grid(rows = vars(exp_line), switch = "y") +
    scale_alpha_manual(values = c(0.1,1)) +
    scale_size_manual(values = c(1,1.5)) +
    labs(title = "Linked variants", y = "Frequency \n", x = "\n Transfer") +
    scale_color_manual(values = color_mapping, name = "Variant") +
    theme_bw() +
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 30, color = "black", angle = 90),
        axis.text.y = element_text(size = 30, color = "black"),
        strip.text.y = element_text(size = 35, angle=0),
        legend.position = "none")


fig <- fig + geom_text_repel(
    data = . %>% filter(tracking_group == "Yes" & passage == 180),
    aes(label = mut_info, y = c(0.08, 0.06, 0.17), x = c(330, 330, 180)), # Adjust y position to avoid overlap
    size = 10,       # Adjust label text size
    color = c("#25880b", "#0b74a2", "#621295") # Optional: set label color
)

fig




# save figure
custom_plot_save(fig, "frequency_dynamics_linkage_cases.pdf", height = 14, width = 14)
```



```{r clonal interference case, results=TRUE}


# 566_G_A  678_G_A 7854_A_G 
case <- c("566_G_A")

variants_expiii$tracking_group <- "No"
variants_expiii$tracking_group[variants_expiii$mut_info %in% case] <- "Yes"
variants_expiii$linewidth[variants_expiii$tracking_group == "Yes"] <- 3
variants_expiii$linewidth[variants_expiii$tracking_group == "No"] <- 1
variants_expiii_subset <- variants_expiii %>%
                                mutate(mut_info_line = paste0(exp_line, "_", mut_info),
                                passage = as.numeric(as.character(passage)))

variants_expiii_subset$color_group <- as.character(variants_expiii_subset$exp_line)
variants_expiii_subset$color_group[variants_expiii_subset$mut_info == case[1]] <- "special_case_1"

color_palette <- c(
  "MT-2_1" = unname(line_col_palette[1]),
  "MT-2_2" = unname(line_col_palette[2]),
  "MT-4_1" = unname(line_col_palette[3]),
  "MT-4_2" = unname(line_col_palette[4]),
  "special_case_1" = brewer.pal(5, "Reds")[3]
)



fig <- variants_expiii_subset[variants_expiii_subset$mut_info_line %in% fixed_muts,] %>% 
    ggplot(aes(x = passage, y = allele_freq, group = mut_info, color = color_group, alpha = tracking_group, linewidth = linewidth)) +
    geom_line() +
    facet_grid(rows = vars(exp_line), switch = "y") +
    scale_alpha_manual(values = c(0.1,1)) +
    labs(title = paste0(case, " variant"), y = "Frequency \n", x = "\n Transfer") + #title = paste0(case, "\n")
    scale_color_manual(values = color_palette) +
    scale_linewidth(range = c(1, 3)) +
    theme_bw() +
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 45),
        axis.text.x = element_text(size = 30, color = "black", angle = 90),
        axis.text.y = element_text(size = 30, color = "black"),
        strip.text.y = element_text(size = 35, angle=0),
        legend.position="none")

fig


# save figure
custom_plot_save(fig, paste0("frequency_dynamics_",case, ".pdf"), height = 14, width = 14)

```



####!!!!


```{r UTR SHAREd}


case <- c("566_G_A", "678_G_A", "9412_G_A", "9416_T_C", "9439_G_A", "9522_C_T", "9528_T_G")



blues_colors <- c("#A4DDED", "#A3C1AD", "#CCCCFF", "#00CCFF", "#15f4ee", 
"#0071c5", "#5A4FCF", "#004687", "#0000CD", "#191970")

triples <- blues_colors
names(triples) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"])[order(unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "3"]))]

reds_colors <- brewer.pal(5, "Reds")[3:5]
quad <- reds_colors
names(quad) <- unique(variants_expiii_subset$mut_info[variants_expiii_subset$rep == "4"])


head(variants_expiii_subset)
variants_expiii_subset2 <- variants_expiii_subset %>%
    filter(mut_info %in% case) %>%
    mutate(mut_info2 = case_when(rep == 1 ~ "Single Occurrence",
                                rep == 2 ~ "Double Occurrence",
                                rep == 3 ~ mut_info,
                                rep == 4 ~ mut_info)) %>%
    mutate(mut_info2 = factor(mut_info2, levels = c("Single Occurrence", "Double Occurrence", names(triples), names(quad))))



custom_colors <- c(triples, quad)





fig <- variants_expiii_subset2 %>% ggplot(aes(x = passage, y = allele_freq, group = mut_info_line, color = mut_info2)) +
    geom_line(size = 2) +
    facet_wrap(~exp_line, ncol = 2) +
    labs(title = "Variant Frequency Trajectories \n", y = "Frequency \n", x = "\n Transfer", color = "Variant") +
    scale_color_manual(values = custom_colors) +
    scale_x_continuous(breaks = seq(0,500, 50))+
    theme_bw() +
    theme(plot.title = element_text(size = 50, hjust = 0.5),
        axis.title = element_text(size = 50),
        axis.text.x = element_text(size = 40, color = "black", angle = 90),
        axis.text.y = element_text(size = 40, color = "black"),
        strip.text.x = element_text(size = 50, angle=0),
        legend.title = element_text(size=50),
        legend.text = element_text(size = 40))

fig

pdf(file = paste0("/Users/alimos313/Documents/studies/phd/research/manuscripts/exp-2e-update-manuscript/figures/", "frequency_dynamics_utr_triple_quad.pdf"), height = 21, width = 21)
fig
dev.off()

```