---
title:  
    "Effective population size of EXPIV"
date: 
    "Dec 18th, 2024"
author:  
    "Ali Movasati"  
output:  
    html_document:
        #css: style.css
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
        theme: lumen
        highlight: zenburn
        code_folding: hide
        code_download: true # to make the Rmd source code available
---



```{r loading libraries, echo=FALSE}


# load libraries
library(readxl)
library(stringr)
library(magrittr)
library(ggplot2)
library(dplyr)
library(tidyr)


```


```{r}

# read in the data
variants_ann <- read.table(file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/pipeline-outputs/all_annotated_variants.tsv.gz", 
sep = "\t", stringsAsFactors = FALSE, header = TRUE)


# account for the switched experimental lines
variants_ann$exp_line[variants_ann$exp_line == 15 & variants_ann$passage > 360] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 16 & variants_ann$passage > 360] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "16"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "15"



variants_ann$exp_line[variants_ann$exp_line == 18 & variants_ann$passage > 350] <- "A"
variants_ann$exp_line[variants_ann$exp_line == 19 & variants_ann$passage > 350] <- "B"

variants_ann$exp_line[variants_ann$exp_line == "A"] <- "19"
variants_ann$exp_line[variants_ann$exp_line == "B"] <- "18"


## prepare data

variants_ann %<>% 
                filter(exp_line %in% c(13:14,17:20)) %>%
                filter(coverage >= 500) %>%
                mutate(exp = case_when(exp_line %in% 13:16 ~ "EXPIII", exp_line %in% 17:20 ~ "EXPIV")) %>% # add experiment number info
                mutate(host_line = ifelse(exp_line %in% c("13", "14","17", "18", "19", "20"), "MT2", "MT4")) %>% # add a field containing pos, ref, and alt info of muts
                mutate(mut_info = paste(genomic_pos, ref_allele, alt_allele, sep = "_")) %>% # add host cell line info
                mutate(exp_line = case_when(exp_line==13 ~ "MT-2_1", exp_line==14 ~ "MT-2_2", exp_line==15 ~ "MT-4_1", exp_line==16 ~ "MT-4_2",
                                            exp_line==17 ~ "MT-2_i", exp_line==18 ~ "MT-2_ii", exp_line==19 ~ "MT-2_iii", exp_line==20 ~ "MT-2_iv")) %>%
                mutate(mut_cat = case_when((allele_freq < 0.01) ~ "Unreliable",
                                        (allele_freq >= 0.01 & allele_freq < 0.05) ~ "Sporadic", 
                                        (allele_freq >= 0.05 & allele_freq < 0.5) ~ "Minority",
                                        (allele_freq >= 0.5 & allele_freq < 0.99) ~ "Majority", 
                                        (allele_freq >= 0.99) ~ "Fixated"))

variants <- variants_ann %>% filter(!duplicated(variant_id))



# facors

exp_line_factor <- c("MT-2_1", "MT-2_2", "MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")
mut_cat_factor <- c("Sporadic", "Minority", "Majority", "Fixated")

gene_factor <- c("gag", "pol", "vif", "vpr", "tat", "rev", "vpu", "envelope", "nef")
feature_factor <- c("5utr", "gag", "pol", "vif", "vpr", "tat1", "rev1", "vpu", "envelope", "tat2", "rev2", "nef", "3utr")

line_col_palette <- c("#ff00ff", "#ff2400",  "#66ff66", "#009900", "#00cc99", "#558000")

## data.table option

tbl_opt_list <- list(pageLength = 10, columnDefs = list(list(targets = 1, render = JS(
    "function(data, type, row, meta) {",
    "return type === 'display' && data.length > 10 ?",
    "'<span title=\"' + data + '\">' + data.substr(0, 10) + '...</span>' : data;",
    "}"))))



```

## Effective population size

```{r}

## estimating the effective population size (Variance Effective Size) by this formula: Ne ≈ p(1−p)/Var(Δp)
## if there are more than one generation between the time points: 1/(2*(1-(1-(var(delta_afs)/(af_ave*(1-af_ave))))^(1/20)))

df <- data.frame()


exp_line <- "MT-2_i"
pres_psg <- 260
trans_effect <- "ALL"

# 8787 9408
for (exp_line in exp_line_factor){
    
    print(exp_line)
    
    for (trans_effect in c("U", "S", "N", "ALL")) {
        if (trans_effect == "ALL"){
            variants_sub <- variants[variants$exp_line == exp_line & variants$genomic_pos >= 8787 & variants$genomic_pos <= 9408,]
        } else {
            variants_sub <- variants[variants$exp_line == exp_line & variants$effect_simplified == trans_effect & variants$genomic_pos >= 8787 & variants$genomic_pos <= 9408,]
        }
        if (str_detect(exp_line, pattern = "MT-2")){
            gen_nr <- 20
        } else {
            gen_nr <- 20
        }
        print(gen_nr)
    for (pres_psg in seq(20,570,10)){
        print(pres_psg)
        prev_psg <- pres_psg - 10
        
        pres_muts <- unique(variants_sub$mut_info[variants_sub$passage == pres_psg & variants_sub$allele_freq >= 0.001 & variants_sub$allele_freq <= 0.99])
        prev_muts <- unique(variants_sub$mut_info[variants_sub$passage == prev_psg & variants_sub$allele_freq >= 0.001 & variants_sub$allele_freq <= 0.99])
        union_muts <- union(pres_muts, prev_muts)
        intersect_muts <- intersect(pres_muts, prev_muts)
        # View(variants_sub %>% filter(mut_info %in% intersect_muts & passage %in% c(pres_psg, prev_psg)) %>% select(mut_info, passage, allele_freq))
        delta_afs <- c()
        for (mut in intersect_muts){
            if (mut %in% pres_muts){
                pres_mut_af <- variants_sub$allele_freq[variants_sub$passage == pres_psg & variants_sub$mut_info == mut]
            } else {pre_mut_af <- 0}
            if (mut %in% prev_muts){
                prev_mut_af <- variants_sub$allele_freq[variants_sub$passage == prev_psg & variants_sub$mut_info == mut]
            } else {prev_mut_af <- 0}
            
            delta_af <- pres_mut_af - prev_mut_af
            delta_afs <- append(delta_afs, delta_af)
        }
        
        af_pres <- sum(variants_sub$allele_freq[variants_sub$passage == pres_psg & variants_sub$allele_freq >= 0.01])
        af_prev <- sum(variants_sub$allele_freq[variants_sub$passage == prev_psg & variants_sub$allele_freq >= 0.01])
        af_ave <- af_pres/length(pres_muts)
        
        Ne <- tryCatch({1/(2*(1-(1-(var(delta_afs)/(af_ave*(1-af_ave))))^(1/gen_nr)))}, error = function(e){NA})
        
        df <- rbind(df, c(exp_line, trans_effect, pres_psg, length(union_muts), length(intersect_muts), af_ave, tryCatch({var(delta_afs)}, error = function(e){NA}), Ne))
        }
    }
    
}



df %<>% set_colnames(c("exp_line", "effect_simplified", "psg", "union_count", "intersect_count", "average_allele_freq", "var_freq_change", "Ne")) %>%
        mutate(
            psg = as.numeric(psg),
            var_freq_change = as.numeric(var_freq_change),
            union_count = as.integer(union_count),
            intersect_count = as.integer(intersect_count),
            Ne = as.numeric(Ne))



# save data on disk

# save(df, file = "/Users/alimos313/Documents/studies/phd/hpc-research/genome-evo-proj/results/tables/misc/variance_effective_size_nef.RData")

```


```{r}

head(df[df$exp_line == "MT-2_i" & df$psg == 260,])
# plot Ne
fig <- df[df$effect_simplified == "ALL",] %>% ggplot(aes(x = psg, y = log2(Ne), col = exp_line)) +
        # facet_wrap(~ exp_line) +
        geom_line() +
        scale_y_continuous(breaks = seq(4,15,1),limits = c(4,15))+
        scale_x_continuous(breaks = seq(0,500,50),limits = c(0,500))+
        scale_color_manual(values = line_col_palette) +
        geom_smooth(method = "loess", se = FALSE) +
        labs(x= "\n Transfer", y = "Log2(Ne) \n", title = "Variance Effective Population Size (nef Variants) \n", color = "Virus Line") + # Label for the legend
        theme_minimal() + # Optional: use a minimal theme
        theme(
            plot.title = element_text(size = 30, hjust = 0.5),
            strip.text = element_text(size = 25),
            axis.title = element_text(size = 25),
            axis.text.x = element_text(size = 20, angle = 90),
            axis.text.y = element_text(size = 20),
            legend.title = element_text(size=20),
            legend.text = element_text(size = 15)) 




# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "variance_ne.pdf"), height = 14, width = 14)
fig
dev.off()


# ave Ne per line
head(df)
df %>%
    mutate(host = ifelse(str_detect(exp_line, pattern = "MT-2"), "MT-2", "mt-4")) %>%
    filter(effect_simplified == "ALL" & psg >= 300) %>%
    group_by(host) %>%
    summarise(mean = mean(Ne, na.rm = T), iqr_upper = quantile(Ne, 0.75, na.rm = T), iqr_lower = quantile(Ne, 0.25, na.rm = T), n = n())

4394/634
6.9/4.8
# plot variance in allele freq change
df[df$effect_simplified != "ALL",] %>% ggplot(aes(x = psg, y = log2(var_freq_change), color = effect_simplified)) +
        facet_wrap(~ exp_line) +
        geom_line() +
        geom_smooth(method = "loess", se = FALSE)

# plot proportion of mutation retention
df[df$effect_simplified != "ALL",] %>% ggplot(aes(x = psg, y = intersect_count/union_count, color = effect_simplified)) +
        facet_wrap(~ exp_line) +
        geom_line() +
        geom_smooth(method = "loess", se = FALSE)


df[df$psg == 130 & df$effect_simplified == "S",]



```