```{r}


update_values_df <- function(df, threshold) {
  for (i in seq(20,700,10)) {
    for (exp_line in line_labels){
        if (df$mean_quantity_per_ml_cell_culture_supernatant[df$exp_line == exp_line & df$passage == i] < threshold){
            df$mean_quantity_per_ml_cell_culture_supernatant[df$exp_line == exp_line & df$passage == i] <- 
            mean(c(df$mean_quantity_per_ml_cell_culture_supernatant[df$exp_line == exp_line & df$passage == i - 10], df$mean_quantity_per_ml_cell_culture_supernatant[df$exp_line == exp_line & df$passage == i + 10]), na.rm = TRUE)
        }
    } 
  }
  return(df)
}



```

```{r}

line_col_palette <- c("#66ff66", "#009900", "#00cc99", "#558000")
line_labels <- c("MT-2_i", "MT-2_ii", "MT-2_iii", "MT-2_iv")

data <- read_excel(paste0(wd, "data/titration/SummaryMasterfile_qPCR_Titers.xlsx"), sheet = 1, skip = 1)

# determine what data to be included
end_psg <- 630

data %<>% 
        filter(exp_line %in% 17:20,
        passage <= end_psg) 

# account for the switched experimental lines


data$exp_line[data$exp_line == 18 & data$passage > 350] <- "A"
data$exp_line[data$exp_line == 19 & data$passage > 350] <- "B"

data$exp_line[data$exp_line == "A"] <- "19"
data$exp_line[data$exp_line == "B"] <- "18"


data %<>% mutate(exp_line = case_when(exp_line==17 ~ "MT-2_i", exp_line==18 ~ "MT-2_ii", exp_line==19 ~ "MT-2_iii", exp_line==20 ~ "MT-2_iv")) # update exp line labels


data$passage <- as.numeric(data$passage)
data$exp_line <- factor(data$exp_line, levels = line_labels)


data_cleaned <- data %>% filter(mean_quantity_per_ml_cell_culture_supernatant > 10^5)


# fit linear models for each group and extract p-values
model_A <- lm(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage, data = data_cleaned[data_cleaned$exp_line == line_labels[1], ])
model_B <- lm(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage, data = data_cleaned[data_cleaned$exp_line == line_labels[2], ])
model_C <- lm(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage, data = data_cleaned[data_cleaned$exp_line == line_labels[3], ])
model_D <- lm(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage, data = data_cleaned[data_cleaned$exp_line == line_labels[4], ])


# extract the p-values
p_value_A <- summary(model_A)$coefficients[2, 4]
p_value_B <- summary(model_B)$coefficients[2, 4]
p_value_C <- summary(model_C)$coefficients[2, 4]  
p_value_D <- summary(model_D)$coefficients[2, 4]

# create a data.frame for annotation
p_value_df <- data.frame(exp_line = line_labels, p_val = c(p_value_A, p_value_B, p_value_C, p_value_D))


# make the ggplot object



titration_fig <- data_cleaned %>% ggplot(aes(x = passage, y = log10(mean_quantity_per_ml_cell_culture_supernatant), color = exp_line)) +
                facet_wrap(~exp_line) +
                geom_line() +
                geom_point() +
                geom_smooth(method = "lm", se = FALSE) +
                geom_text(data = p_value_df, aes(x = Inf, y = Inf, label = paste0("P.value = ", round(p_val, 3))),
                hjust = 1.1, vjust = 2, size = 8, inherit.aes = FALSE) +
                labs(title = "qPCR Result \n", x = "\n Transfer", y = "Log10(RNA Copy/ml)\n", color = "Virus Line") +
                #ylim(c(1000000,40000000)) +
                scale_color_manual(values = line_col_palette) +
                theme_bw() +
                theme(plot.title = element_text(size = 30, hjust = 0.5),
                    axis.title = element_text(size = 25),
                    axis.text.x = element_text(size = 20, angle = 90),
                    axis.text.y = element_text(size = 20),
                    legend.title = element_text(size=20),
                    legend.text = element_text(size = 15),
                    strip.text = element_text(size = 25))

# save figure
date <- str_split(Sys.time(), pattern = " ")[[1]][1]
fig_dir <- paste0(wd, "results/figs/publication/expiii/provisional/", date, "/")
ifelse(!dir.exists(file.path(fig_dir)), dir.create(file.path(fig_dir)), FALSE)
pdf(file = paste0(fig_dir, "qpcr_expiv.pdf"), height = 14, width = 14)
titration_fig
dev.off()


```



```{r}

library(lme4)
library(lmerTest)
data$handler <- factor(data$handler)



data_cleaned <- data %>% filter(mean_quantity_per_ml_cell_culture_supernatant > 10^5)


# fit linear models for each group and extract p-values
model_A <- lmer(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage + (1 | handler), data = data_cleaned[data_cleaned$exp_line == line_labels[1], ])
model_B <- lmer(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage + (1 | handler), data = data_cleaned[data_cleaned$exp_line == line_labels[2], ])
model_C <- lmer(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage + (1 | handler), data = data_cleaned[data_cleaned$exp_line == line_labels[3], ])
model_D <- lmer(log10(mean_quantity_per_ml_cell_culture_supernatant) ~ passage + (1 | handler), data = data_cleaned[data_cleaned$exp_line == line_labels[4], ])


# extract the p-values
p_value_A <- summary(model_A)$coefficients[2, 5]
p_value_B <- summary(model_B)$coefficients[2, 5]
p_value_C <- summary(model_C)$coefficients[2, 5]  
p_value_D <- summary(model_D)$coefficients[2, 5]

# create a data.frame for annotation
p_value_df <- data.frame(exp_line = line_labels, p_val = c(p_value_A, p_value_B, p_value_C, p_value_D))


# make the ggplot object



titration_fig <- data_cleaned %>% ggplot(aes(x = passage, y = log10(mean_quantity_per_ml_cell_culture_supernatant), color = handler)) +
                facet_wrap(~exp_line) +
                geom_line() +
                geom_point() +
                geom_smooth(method = "lm", se = FALSE) +
                geom_text(data = p_value_df, aes(x = Inf, y = Inf, label = paste0("P.value = ", round(p_val, 3))),
                hjust = 1.1, vjust = 2, size = 8, inherit.aes = FALSE) +
                labs(title = "qPCR Result \n", x = "\n Transfer", y = "Log10(RNA Copy/ml)\n", color = "Handler") +
                theme_bw() +
                theme(plot.title = element_text(size = 30, hjust = 0.5),
                    axis.title = element_text(size = 25),
                    axis.text.x = element_text(size = 20, angle = 90),
                    axis.text.y = element_text(size = 20),
                    legend.title = element_text(size=20),
                    legend.text = element_text(size = 15),
                    strip.text = element_text(size = 25))


```